# Generated by Django 3.2.15 on 2023-06-07 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0055_alter_product_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("path",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
