# Generated by Django 4.2.25 on 2025-10-07 11:30

from functools import partial

from django.db import migrations

from django_prosemirror.schema import NodeType

from open_inwoner.utils.migration_operations import migrate_to_prosemirror_field

migrate_category_descriptions = partial(
    migrate_to_prosemirror_field,
    app_label="pdc",
    model_name="Category",
    field_name="description",
    allowed_node_types=[NodeType.PARAGRAPH, NodeType.FILER_IMAGE],
    use_singleton=False,
    convert_markdown=True,
    process_images=True,
)


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0068_category_description_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_category_descriptions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
