# Generated by Django 4.2.25 on 2025-10-07 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0072_product_content_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="content_tmp",
        ),
    ]
