# Generated by Django 3.2.15 on 2023-03-08 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAPILog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The hostname part of the url.",
                        max_length=255,
                        verbose_name="Hostname",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The path part of the url.",
                        max_length=255,
                        verbose_name="Path",
                    ),
                ),
                (
                    "params",
                    models.TextField(
                        blank=True,
                        help_text="The parameters (if they exist).",
                        verbose_name="Parameters",
                    ),
                ),
                (
                    "query_params",
                    models.TextField(
                        blank=True,
                        help_text="The query parameters part of the url (if they exist).",
                        verbose_name="Query parameters",
                    ),
                ),
                (
                    "status_code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The status code of the response.",
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="",
                        help_text="The type of request method.",
                        max_length=10,
                    ),
                ),
                (
                    "response_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="This is the response time in ms.",
                        verbose_name="Response in ms",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date when the API call was made.",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who made the request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "External API Log",
                "verbose_name_plural": "External API Logs",
            },
        ),
    ]
