# Generated by Django 4.2.27 on 2025-12-22 12:36

from django.db import migrations, models

import app_data.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MijnAfvalApphookConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="Type")),
                (
                    "namespace",
                    models.CharField(
                        default=None,
                        max_length=100,
                        unique=True,
                        verbose_name="Instance namespace",
                    ),
                ),
                (
                    "app_data",
                    app_data.fields.AppDataField(default="{}", editable=False),
                ),
                (
                    "page_heading",
                    models.CharField(
                        default="Mijn Afval",
                        help_text="The heading of the 'Mijn Afval' page",
                        max_length=200,
                        verbose_name="Page heading",
                    ),
                ),
                (
                    "page_description",
                    models.TextField(
                        blank=True,
                        help_text="The description for the 'Mijn Afval' page",
                        verbose_name="Page description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apphook config",
                "verbose_name_plural": "Apphook configs",
                "abstract": False,
                "unique_together": {("type", "namespace")},
            },
        ),
    ]
