# Generated by Django 4.2.27 on 2025-12-30 13:15

from django.db import migrations


def create_default_config(apps, schema_editor):
    """
    Create a default MijnAfvalApphookConfig instance.

    This ensures that when a CMS page is created with the Mijn Afval apphook,
    there's already a config instance available with default values. Otherwise
    a server restart is required for the CMS integration to work.
    """
    MijnAfvalApphookConfig = apps.get_model("mijn_afval_cms", "MijnAfvalApphookConfig")

    if not MijnAfvalApphookConfig.objects.filter(namespace="mijn_afval").exists():
        MijnAfvalApphookConfig.objects.create(
            namespace="mijn_afval",
            type="open_inwoner.mijn_afval.cms.cms_apps.MijnAfvalApphook",
            page_heading="Mijn Afval",
            page_description="",
        )


def delete_default_config(apps, schema_editor):
    """
    Reverse migration: delete the default config.
    """
    MijnAfvalApphookConfig = apps.get_model("mijn_afval_cms", "MijnAfvalApphookConfig")
    MijnAfvalApphookConfig.objects.filter(namespace="mijn_afval").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("mijn_afval_cms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_config, delete_default_config),
    ]
