ZAKEN_ROOT = "https://zaken.nl/api/v1/"
CATALOGI_ROOT = "https://catalogi.nl/api/v1/"
DOCUMENTEN_ROOT = "https://documenten.nl/api/v1/"
NOTIFICATIONS_ROOT = "https://notifications.nl/api/v1/"
FORMS_ROOT = "https://forms.nl/api/v1/"
