# This docker-compose is used internally in the testsuite to dynamically spin up
# an OpenKlant2 backend, seed it with known data, and record VCR fixtures. Be
# sure to verify any changes here are consistent with 
version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    image: maykinmedia/open-klant:${OPEN_KLANT_IMAGE_TAG:-latest}
    environment: &web-env
      - DJANGO_SETTINGS_MODULE=openklant.conf.docker
      - IS_HTTPS=no
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=db
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - SUBPATH=${SUBPATH:-/}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-f8s@b*ds4t84-q_2#c0j0506@!l2q6r5_pq5e!vm^_9c*#^66b}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DISABLE_2FA=true
    ports:
      # Use a somewhat arbitrary port to avoid clashes
      - 8338:8000
    depends_on:
      - db
      - redis

  redis:
    image: redis
