# Generated by Django 4.2.20 on 2025-06-19 08:58

from django.db import migrations
from django.utils.text import slugify

from cms.api import add_plugin, create_page

from open_inwoner.cms.footer.cms_plugins import CMSFlatPagePlugin


def _get_page_placeholder(page, language, slot):
    # Use real CMS 4 models directly — acceptable since we don't migrate cms schema here.
    # admin_manager bypasses the versioning published-only filter, so draft pages are included.
    from cms.models import PageContent, Placeholder

    page_content = PageContent.admin_manager.filter(
        page_id=page.pk, language=language
    ).get()
    return Placeholder.objects.get_for_obj(page_content).get(slot=slot)


def create_cms_pages(apps, schema_editor):
    FlatPage = apps.get_model("flatpages", "FlatPage")
    User = apps.get_model("accounts", "User")

    language = "nl"
    user = User.objects.filter(is_superuser=True).order_by("pk").first()

    for flatpage in FlatPage.objects.all():
        title = flatpage.title
        slug = flatpage.url.strip("/")
        if not slug:
            slug = slugify(flatpage.title)

        page = create_page(
            title=title,
            template="cms/cms_flatpage_template.html",
            language=language,
            slug=slug,
            in_navigation=True,
            created_by=user,
        )

        placeholder = _get_page_placeholder(page, language, "content")

        add_plugin(
            placeholder=placeholder,
            plugin_type=CMSFlatPagePlugin,
            language=language,
            title=flatpage.title,
            content=flatpage.content,
        )


def _get_page_from_placeholder(placeholder, apps):
    """
    Get a Page from a Placeholder, compatible with both CMS 3.x and 4.x.

    CMS 3.x: Page.objects.filter(placeholders=placeholder).first()
    CMS 4.x: Navigate through Placeholder -> PageContent -> Page
    """
    Page = apps.get_model("cms", "Page")

    try:
        # Try CMS 3.x API first
        return Page.objects.filter(placeholders=placeholder).first()
    except Exception:
        # Fall back to CMS 4.x API
        # In CMS 4.x, placeholders are linked to PageContent via content_type/object_id
        PageContent = apps.get_model("cms", "PageContent")
        from django.contrib.contenttypes.models import ContentType

        page_content_ct = ContentType.objects.get_for_model(PageContent)

        # Check if this placeholder belongs to a PageContent
        if placeholder.content_type == page_content_ct:
            page_content = PageContent.objects.filter(pk=placeholder.source_id).first()
            if page_content:
                return page_content.page

        return None


def link_cms_pages_with_siteconfig(apps, schema_editor):
    SiteConfiguration = apps.get_model("configurations", "SiteConfiguration")
    SiteConfigurationPage = apps.get_model("configurations", "SiteConfigurationPage")

    CMSFlatPageModel = apps.get_model("footer", "CMSFlatPageModel")

    # remove existing pages for clean slate
    SiteConfigurationPage.objects.all().delete()

    site_config = SiteConfiguration.objects.first()

    for order, cms_model in enumerate(CMSFlatPageModel.objects.all()):
        placeholder = cms_model.placeholder
        cms_page = _get_page_from_placeholder(placeholder, apps)

        if cms_page:
            SiteConfigurationPage.objects.create(
                configuration=site_config,
                cms_page=cms_page,
                order=order,
            )


def delete_flatpages(apps, schema_editor):
    FlatPage = apps.get_model("flatpages", "FlatPage")

    FlatPage.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=create_cms_pages,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=link_cms_pages_with_siteconfig,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=delete_flatpages,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
