# Generated by Django 4.2.25 on 2025-10-08 21:13

from functools import partial

from django.db import migrations

from django_prosemirror.schema import NodeType

from open_inwoner.utils.migration_operations import migrate_to_prosemirror_field

migrate_flatpages_content = partial(
    migrate_to_prosemirror_field,
    app_label="footer",
    model_name="CMSFlatPageModel",
    field_name="content",
    allowed_node_types=[NodeType.PARAGRAPH, NodeType.HEADING],
    use_singleton=False,
)


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0003_cmsflatpagemodel_content_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_flatpages_content,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
