# Generated by Django 4.2.25 on 2025-10-08 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0004_cmsflatpagemodel_content_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmsflatpagemodel",
            name="content_tmp",
        ),
    ]
