# Generated by Django 4.2.28 on 2026-03-02 12:43

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0005_cmsflatpagemodel_content_schema_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsflatpagemodel",
            name="content",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                    django_prosemirror.schema.types.NodeType["HEADING"],
                ],
                blank=True,
                default=None,
                help_text="The content of the page",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Content",
            ),
        ),
    ]
