# Generated by Django 3.2.24 on 2024-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userfeed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditemdata",
            name="type",
            field=models.CharField(
                choices=[
                    ("message_simple", "Simple text message"),
                    ("case_status_change", "Case status changed"),
                    ("case_document_added", "Case document added"),
                    ("plan_expiring", "Plan nears deadline"),
                    ("external_task", "External task"),
                ],
                max_length=64,
                verbose_name="Type",
            ),
        ),
    ]
