# Generated by Django 4.2.25 on 2025-11-05 11:47

from django.db import migrations

import structlog

logger = structlog.stdlib.get_logger(__name__)


def remove_external_task_userfeed_items(apps, _):
    FeedItemData = apps.get_model("userfeed", "FeedItemData")

    external_task_feed_items = FeedItemData.objects.filter(type="external_task")

    deleted_count, _ = external_task_feed_items.delete()

    logger.info(
        "Deleted userfeed items for external tasks",
        count=deleted_count,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("userfeed", "0002_alter_feeditemdata_type"),
    ]

    operations = [
        migrations.RunPython(
            code=remove_external_task_userfeed_items,
            reverse_code=migrations.RunPython.noop,
        )
    ]
