# Generated by Django 4.2.25 on 2025-11-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userfeed", "0003_delete_external_task_feeditems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditemdata",
            name="type",
            field=models.CharField(
                choices=[
                    ("message_simple", "Simple text message"),
                    ("case_status_change", "Case status changed"),
                    ("case_document_added", "Case document added"),
                    ("plan_expiring", "Plan nears deadline"),
                ],
                max_length=64,
                verbose_name="Type",
            ),
        ),
    ]
