# Generated by Django 5.2.14 on 2026-06-09 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_migrate_data_from_notifications_api_common"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationProcessingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days to retain notification records in terminal states (SUCCESS, FAILED, SKIPPED). Records older than this will be pruned. Leave empty to keep records indefinitely.",
                        null=True,
                        verbose_name="retention days",
                    ),
                ),
                (
                    "stuck_processing_retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days after which PROCESSING records are considered stuck (worker killed before completion) and will be pruned. Leave empty to never prune stuck records.",
                        null=True,
                        verbose_name="stuck processing retention days",
                    ),
                ),
                (
                    "max_payload_size",
                    models.PositiveIntegerField(
                        default=1048576,
                        help_text="Maximum size in bytes for incoming webhook payloads. Payloads larger than this will be rejected.",
                        verbose_name="maximum payload size",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificatieverwerking configuratie",
            },
        ),
        migrations.CreateModel(
            name="NotificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("kanaal", models.CharField(blank=True, default="", max_length=256)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_processed_at", models.DateTimeField(blank=True, null=True)),
                ("process_started_at", models.DateTimeField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current processing status. PROCESSING status also acts as a lock.",
                        max_length=20,
                    ),
                ),
                ("processing_output", models.TextField(blank=True, default="")),
                ("processing_error", models.TextField(blank=True, default="")),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to="notifications.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificatiebericht",
                "verbose_name_plural": "Notificatieberichten",
            },
        ),
    ]
