# Generated by Django 3.2.12 on 2022-03-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_questionnairestepfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairestep',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Geeft aan dat dit de standaard zelfdiagnose is, slechts een item mag deze waarde hebben..', verbose_name='Standaard zelfdiagnose'),
        ),
    ]
