# Generated by Django 3.2.12 on 2022-03-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_questionnairestep_is_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnairestep",
            options={
                "verbose_name": "Vragenlijststap",
                "verbose_name_plural": "Vragenlijststappen",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairestepfile",
            options={
                "verbose_name": "Vragenlijststap bijlage",
                "verbose_name_plural": "Vragenlijststap bijlagen",
            },
        ),
        migrations.AlterField(
            model_name="questionnairestep",
            name="parent_answer",
            field=models.CharField(
                blank=True,
                help_text="Dit label wordt getoond bij de keuzes van de vorige stap. Dient voor de hoofdvraag leeggelaten te worden.",
                max_length=255,
                verbose_name="Antwoord op de vorige vraag",
            ),
        ),
        migrations.AlterField(
            model_name="questionnairestep",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="URL-vriendelijke naam / Slug"
            ),
        ),
    ]
