# Generated by Django 3.2.12 on 2022-03-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_questionnairestep_is_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnairestep",
            name="is_default",
        ),
    ]
