# Generated by Django 3.2.12 on 2022-03-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_auto_20220328_1042"),
        ("questionnaire", "0006_auto_20220328_1555"),
    ]

    operations = []
