# Generated by Django 3.2.12 on 2022-03-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0007_auto_20220328_1122"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnairestep",
            options={
                "ordering": ("path",),
                "verbose_name": "Vragenlijststap",
                "verbose_name_plural": "Vragenlijststappen",
            },
        ),
    ]
