# Generated by Django 3.2.12 on 2022-03-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0010_merge_20220329_1651"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnairestep",
            options={
                "ordering": ("path",),
                "verbose_name": "Vragenlijststap",
                "verbose_name_plural": "Vragenlijststappen",
            },
        ),
    ]
