# Generated by Django 3.2.13 on 2022-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_alter_questionnairestep_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairestep',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='Code voor intern gebruik'),
            preserve_default=False,
        ),
    ]
