# Generated by Django 3.2.13 on 2022-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20220503_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairestep',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Code voor intern gebruik'),
        ),
    ]
