# Generated by Django 3.2.13 on 2022-05-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0014_alter_questionnairestep_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnairestep",
            name="help_text",
            field=models.CharField(
                blank=True,
                default="Kies het antwoord dat het meest van toepassing is",
                help_text="Beschrijvende tekst bij de vraag.",
                max_length=510,
                verbose_name="Ondersteunende tekst",
            ),
        ),
    ]
