# Generated by Django 3.2.13 on 2022-06-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0039_alter_category_highlighted"),
        ("questionnaire", "0015_alter_questionnairestep_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairestep",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Related category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="pdc.category",
                verbose_name="Thema",
            ),
        ),
        migrations.AddField(
            model_name="questionnairestep",
            name="highlighted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the questionnaire should be highlighted or not.",
                verbose_name="Highlighted",
            ),
        ),
    ]
