# Generated by Django 3.2.13 on 2022-06-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0039_alter_category_highlighted"),
        ("questionnaire", "0016_auto_20220613_1518"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnairestepfile",
            options={
                "verbose_name": "Bijlage vragenlijststap",
                "verbose_name_plural": "Bijlagen vragenlijststap",
            },
        ),
        migrations.AlterField(
            model_name="questionnairestep",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Gerelateerde thema",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="pdc.category",
                verbose_name="Thema",
            ),
        ),
        migrations.AlterField(
            model_name="questionnairestep",
            name="highlighted",
            field=models.BooleanField(
                default=False,
                help_text="Of de thema uitgelicht moet worden op de homepage of niet.",
                verbose_name="Uitgelicht",
            ),
        ),
        migrations.AlterField(
            model_name="questionnairestep",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Deze producten worden weergegeven in deze stap.",
                to="pdc.Product",
                verbose_name="Gerelateerde producten",
            ),
        ),
    ]
