# Generated by Django 3.2.15 on 2022-10-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0017_auto_20220617_0922"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairestep",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Whether the questionnaire-tree should be visible or not, only relevant for the top-level question",
                verbose_name="Gepubliceerd",
            ),
        ),
    ]
