# Generated by Django 3.2.15 on 2022-10-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0018_questionnairestep_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairestep",
            name="redirect_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Indien ingesteld dan wordt de gebruiker na het kiezen van het antwoord doorgestuurd naar een andere vragenlijststap (eventueel in een andere boom",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.questionnairestep",
                verbose_name="Doorsturen naar andere stap (experimenteel)",
            ),
        ),
        migrations.AlterField(
            model_name="questionnairestep",
            name="highlighted",
            field=models.BooleanField(
                default=False,
                help_text="Alleen relevant voor vraag op het hoofdniveau. Indien aangevinkt dan wordt deze vraag getoond op de homepage.",
                verbose_name="Uitgelicht",
            ),
        ),
        migrations.AlterField(
            model_name="questionnairestep",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Alleen relevant voor vraag op het hoofdniveau. Indien uitgevinkt dan kunnen alleen beheerders de vragenlijst zien & doorlopen.",
                verbose_name="Gepubliceerd",
            ),
        ),
    ]
