# Generated by Django 3.2.15 on 2022-11-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0019_auto_20221028_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnairestep",
            name="redirect_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Indien ingesteld dan wordt de gebruiker na het kiezen van het antwoord doorgestuurd naar een andere vragenlijststap (eventueel in een andere boom)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaire.questionnairestep",
                verbose_name="Doorsturen naar andere stap (experimenteel)",
            ),
        ),
    ]
