# Generated by Django 3.2.15 on 2023-05-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0055_alter_product_content"),
        ("questionnaire", "0020_alter_questionnairestep_redirect_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnairestep",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Gerelateerd onderwerp",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="pdc.category",
                verbose_name="Onderwerp",
            ),
        ),
    ]
