# Generated by Django 4.2.24 on 2025-10-01 14:27

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0021_alter_questionnairestep_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnairestep",
            old_name="content",
            new_name="content_tmp",
        ),
        migrations.AddField(
            model_name="questionnairestep",
            name="content",
            field=django_prosemirror.fields.ProsemirrorModelField(
                verbose_name="Uitgebreide informatie",
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
                help_text="Deze inhoud wordt weergegeven in deze stap.",
            ),
        ),
    ]
