# Generated by Django 4.2.24 on 2025-10-01 14:27

from functools import partial

from django.db import migrations

from django_prosemirror.schema import NodeType

from open_inwoner.utils.migration_operations import migrate_to_prosemirror_field

migrate_questionnaire_steps_content = partial(
    migrate_to_prosemirror_field,
    app_label="questionnaire",
    model_name="QuestionnaireStep",
    field_name="content",
    allowed_node_types=[NodeType.PARAGRAPH],
    use_singleton=False,
    convert_markdown=True,
    strip_quotes=True,
)


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0022_questionnairestep_content_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_questionnaire_steps_content,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
