# Generated by Django 4.2.24 on 2025-10-01 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0023_questionnairestep_content_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnairestep",
            name="content_tmp",
        ),
    ]
