# Generated by Django 3.2.15 on 2023-03-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_outgoing_requests", "0002_alter_outgoingrequestslog_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingrequestslog",
            name="req_headers",
            field=models.TextField(
                blank=True,
                help_text="The request headers.",
                null=True,
                verbose_name="Request headers",
            ),
        ),
        migrations.AddField(
            model_name="outgoingrequestslog",
            name="res_headers",
            field=models.TextField(
                blank=True,
                help_text="The response headers.",
                null=True,
                verbose_name="Response headers",
            ),
        ),
    ]
