# Generated by Django 3.2.7 on 2021-12-17 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        help_text="Words which are used by the user in the search box",
                        max_length=250,
                        verbose_name="search query",
                    ),
                ),
                (
                    "search_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The generated url of user's search",
                        max_length=250,
                        verbose_name="search url",
                    ),
                ),
                (
                    "positive",
                    models.BooleanField(
                        help_text="Designates whether the feedback was positive or not",
                        verbose_name="positive",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A remark concerning the feedback (positive or negative) that was given",
                        verbose_name="remark",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date the feedback was saved. This field is automatically set",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "searched_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The logged in user who performed the search",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="searched by",
                    ),
                ),
            ],
        ),
    ]
