# Generated by Django 3.2.12 on 2022-02-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "feedback", "verbose_name_plural": "feedbacks"},
        ),
    ]
