# Generated by Django 3.2.12 on 2022-02-18 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("search", "0002_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedbacks"},
        ),
        migrations.AlterModelOptions(
            name="synonym",
            options={"verbose_name": "Synonym", "verbose_name_plural": "Synonyms"},
        ),
        migrations.AlterField(
            model_name="feedback",
            name="positive",
            field=models.BooleanField(
                help_text="Designates whether the feedback was positive or not",
                verbose_name="Positive",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="remark",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A remark concerning the feedback (positive or negative) that was given",
                verbose_name="Remark",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="search_query",
            field=models.CharField(
                help_text="Words which are used by the user in the search box",
                max_length=250,
                verbose_name="Search query",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="search_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The generated url of user's search",
                max_length=250,
                verbose_name="Search url",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="searched_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The logged in user who performed the search",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Searched by",
            ),
        ),
        migrations.AlterField(
            model_name="synonym",
            name="synonyms",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.TextField(verbose_name="Synonyms"),
                help_text="Words-synonyms concerning the term",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="synonym",
            name="term",
            field=models.CharField(
                help_text="The term", max_length=250, unique=True, verbose_name="Term"
            ),
        ),
    ]
