# Generated by Django 3.2.12 on 2022-03-31 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_auto_20220218_1359"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldBoost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Field name of the Elastic document. For nested fields use '.' ",
                        max_length=200,
                        unique=True,
                        verbose_name="Field",
                    ),
                ),
                (
                    "boost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Boost which multiplies the score for the particular field. The default boost for all fields = 1",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Boost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field boost",
                "verbose_name_plural": "Field boosts",
            },
        ),
    ]
