# Generated by Django 4.2.25 on 2025-10-09 07:08

import django.db.models.deletion
from django.db import migrations, models

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("plugins", "0007_remove_tasksconfig_object_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "body",
                    django_prosemirror.fields.ProsemirrorModelField(
                        allowed_mark_types=[
                            django_prosemirror.schema.types.MarkType["STRONG"],
                            django_prosemirror.schema.types.MarkType["ITALIC"],
                            django_prosemirror.schema.types.MarkType["LINK"],
                            django_prosemirror.schema.types.MarkType["CODE"],
                            django_prosemirror.schema.types.MarkType["UNDERLINE"],
                            django_prosemirror.schema.types.MarkType["STRIKETHROUGH"],
                        ],
                        allowed_node_types=[
                            django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                            django_prosemirror.schema.types.NodeType["BLOCKQUOTE"],
                            django_prosemirror.schema.types.NodeType["HORIZONTAL_RULE"],
                            django_prosemirror.schema.types.NodeType["HEADING"],
                            django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                            django_prosemirror.schema.types.NodeType["CODE_BLOCK"],
                            django_prosemirror.schema.types.NodeType["BULLET_LIST"],
                            django_prosemirror.schema.types.NodeType["ORDERED_LIST"],
                            django_prosemirror.schema.types.NodeType["LIST_ITEM"],
                            django_prosemirror.schema.types.NodeType["TABLE"],
                            django_prosemirror.schema.types.NodeType["TABLE_ROW"],
                            django_prosemirror.schema.types.NodeType["TABLE_CELL"],
                            django_prosemirror.schema.types.NodeType["TABLE_HEADER"],
                            django_prosemirror.schema.types.NodeType["FILER_IMAGE"],
                        ],
                        default=None,
                        help_text="The text content",
                        history=True,
                        tag_to_classes={},
                        verbose_name="Body",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
