# Generated by Django 3.2.15 on 2023-05-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="image_height",
            field=models.PositiveIntegerField(
                blank=True,
                help_text='The image custom height as number in pixels. Example: "720" and not "720px".Leave this field empty if you want the original height of the image to be applied.',
                null=True,
                verbose_name="Custom image height",
            ),
        ),
    ]
