# Generated by Django 3.2.15 on 2023-05-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0002_banner_image_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description to be shown along with the banner.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="name",
            field=models.CharField(default="", max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title to be shown along with the banner.",
                max_length=250,
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
