# Generated by Django 3.2.15 on 2023-05-10 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("banner", "0002_banner_image_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="banner_bannerimage",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the image (this will not be shown on the page)",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='The image custom height as number in pixels. Example: "720" and not "720px".Leave this field empty if you want the original height of the image to be applied.',
                        null=True,
                        verbose_name="Custom image height",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        help_text="Banner image",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="Banner image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="BannerText",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="banner_bannertext",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the text block (this will not be shown on the page)",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="The title of the text block",
                        max_length=250,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the text block",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
