# Generated by Django 4.2.27 on 2025-12-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0008_menu_icons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonextension",
            name="menu_icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person", "User"),
                    ("description", "Products"),
                    ("inbox", "Inbox"),
                    ("inventory_2", "Cases"),
                    ("group", "Collaborate"),
                    ("help_outline", "Help"),
                    ("euro", "Benefits"),
                    ("delete", "Afval"),
                ],
                help_text="Icon in het menu",
                max_length=32,
                verbose_name="Icon",
            ),
        ),
    ]
