# Generated by Django 4.2.25 on 2025-10-15 13:19

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import image_cropping.fields
import localflavor.nl.models
import privates.storages

import open_inwoner.accounts.managers
import open_inwoner.accounts.models
import open_inwoner.utils.validators
from open_inwoner.accounts.choices import LoginTypeChoices
from open_inwoner.utils.hash import generate_email_from_string


# Data migration functions (from 0043_change_digid_email)
def change_bsn_email_to_hash(apps, _):
    User = apps.get_model("accounts", "User")

    for user in User.objects.filter(login_type=LoginTypeChoices.digid).all():
        if user.email == f"user-{user.bsn}@bsn.com":
            user.email = generate_email_from_string(user.bsn)
            user.save()


def change_hash_email_to_bsn(apps, _):
    User = apps.get_model("accounts", "User")

    for user in User.objects.filter(login_type=LoginTypeChoices.digid).all():
        if user.email == generate_email_from_string(user.bsn):
            user.email = f"user-{user.bsn}@bsn.com"
            user.save()


# Note: Most data migrations have been removed from this squashed migration as they
# are only relevant for migrating existing data and not needed for fresh installations.


class Migration(migrations.Migration):
    replaces = [
        ("accounts", "0001_initial"),
        ("accounts", "0002_auto_20211004_1708"),
        ("accounts", "0003_auto_20211008_1100"),
        ("accounts", "0004_auto_20211008_1311"),
        ("accounts", "0003_auto_20211007_1244"),
        ("accounts", "0005_merge_0003_auto_20211007_1244_0004_auto_20211008_1311"),
        ("accounts", "0006_auto_20211013_1415"),
        ("accounts", "0007_contact_uuid"),
        ("accounts", "0008_auto_20211101_1129"),
        ("accounts", "0009_auto_20211101_1137"),
        ("accounts", "0010_auto_20211101_1137"),
        ("accounts", "0005_auto_20211013_1129"),
        ("accounts", "0007_merge_0005_auto_20211013_1129_0006_auto_20211013_1415"),
        ("accounts", "0008_merge_20211020_1415"),
        ("accounts", "0011_merge_20211104_1428"),
        ("accounts", "0012_user_deactivated_on"),
        ("accounts", "0013_alter_user_deactivated_on"),
        ("accounts", "0014_user_is_prepopulated"),
        ("accounts", "0015_auto_20211214_1136"),
        ("accounts", "0016_auto_20211214_1652"),
        ("accounts", "0015_message"),
        ("accounts", "0017_merge_0015_message_0016_auto_20211214_1652"),
        ("accounts", "0017_action_end_date"),
        ("accounts", "0018_merge_20211222_1030"),
        ("accounts", "0019_auto_20211227_1218"),
        ("accounts", "0020_invite"),
        ("accounts", "0021_auto_20220202_0949"),
        ("accounts", "0022_auto_20220202_0949"),
        ("accounts", "0023_auto_20220202_0951"),
        ("accounts", "0021_alter_contact_type"),
        ("accounts", "0024_merge_0021_alter_contact_type_0023_auto_20220202_0951"),
        ("accounts", "0025_migrate_message_seen"),
        ("accounts", "0026_message_sent"),
        ("accounts", "0027_auto_20220214_1440"),
        ("accounts", "0028_auto_20220214_1538"),
        ("accounts", "0029_auto_20220218_1359"),
        ("accounts", "0030_message_file"),
        ("accounts", "0031_message_uuid"),
        ("accounts", "0032_gen_message_uuid"),
        ("accounts", "0033_alter_message_uuid"),
        ("accounts", "0034_alter_message_content"),
        ("accounts", "0035_alter_contact_phonenumber"),
        ("accounts", "0036_alter_user_login_type"),
        ("accounts", "0037_user_contact_type"),
        ("accounts", "0038_auto_20220504_1352"),
        ("accounts", "0039_remove_contact_type"),
        ("accounts", "0040_auto_20220518_1456"),
        ("accounts", "0041_migrate_invite_email"),
        ("accounts", "0042_alter_invite_invitee_email"),
        ("accounts", "0043_change_digid_email"),
        ("accounts", "0044_user_oidc_id"),
        ("accounts", "0045_alter_user_login_type"),
        ("accounts", "0046_alter_user_oidc_id"),
        ("accounts", "0047_action_is_deleted"),
        ("accounts", "0048_auto_20221205_0921"),
        ("accounts", "0049_auto_20221205_0921"),
        ("accounts", "0050_auto_20221205_0924"),
        ("accounts", "0048_alter_action_status"),
        ("accounts", "0051_merge_20221207_0918"),
        ("accounts", "0052_auto_20221213_0758"),
        ("accounts", "0053_user_display_name"),
        ("accounts", "0054_remove_action_goal"),
        ("accounts", "0055_user_image"),
        ("accounts", "0056_auto_20230307_0852"),
        ("accounts", "0057_rename_selected_themes_user_selected_categories"),
        ("accounts", "0058_alter_user_selected_categories"),
        ("accounts", "0059_auto_20230412_1637"),
        ("accounts", "0060_user_infix"),
        ("accounts", "0061_auto_20230612_1428"),
        ("accounts", "0062_alter_user_deactivated_on"),
        ("accounts", "0063_alter_user_phonenumber"),
        ("accounts", "0064_alter_user_email"),
        ("accounts", "0065_user_unique_email_when_not_digid"),
        ("accounts", "0066_remove_user_selected_categories"),
        ("accounts", "0067_auto_20231121_1131"),
        ("accounts", "0068_relax_email_constraint_for_eherkenning"),
        ("accounts", "0069_alter_user_postcode"),
        ("accounts", "0070_auto_20231205_1657"),
        ("accounts", "0071_remove_user_birthday"),
        ("accounts", "0071_delete_appointment"),
        ("accounts", "0072_merge_20240129_1610"),
        ("accounts", "0073_user_selected_categories"),
        ("accounts", "0073_alter_user_user_contacts"),
        ("accounts", "0074_merge_20240228_1544"),
        ("accounts", "0075_user_verified_email"),
        ("accounts", "0076_user_case_notification_channel"),
        ("accounts", "0077_no_roepnaam"),
        ("accounts", "0078_drop_digid_eh_oidc_generics_legacy_tables"),
        ("accounts", "0079_digid_eherkenning_configs"),
        ("accounts", "0080_user_phonenumber_alternative"),
        (
            "accounts",
            "0081_user_check_alternative_phonenumber_differs_from_primary_phonenumber",
        ),
        ("accounts", "0082_user_eherkenning_user_requires_kvk"),
        ("accounts", "0083_user_vestiging_and_more"),
        ("accounts", "0084_user_branch_name"),
        ("accounts", "0085_alter_action_end_date_alter_action_file_and_more"),
    ]

    initial = True

    dependencies = [
        ("pdc", "0055_alter_product_content"),
        ("pdc", "0066_category_access_groups"),
        ("plans", "0011_remove_plan_contacts"),
        ("pdc", "0016_merge_20211206_1627"),
        ("pdc", "0018_alter_product_keywords"),
        ("pdc", "0022_question"),
        (
            "digid_eherkenning_oidc_generics",
            "0009_remove_digidconfig_oidc_exempt_urls_and_more",
        ),
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "bsn",
                    localflavor.nl.models.NLBSNField(
                        blank=True, max_length=12, null=True
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=250)),
                (
                    "housenumber",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("default", "Email en Wachtwoord"),
                            ("digid", "DigiD"),
                        ],
                        default="default",
                        max_length=250,
                    ),
                ),
                (
                    "postcode",
                    localflavor.nl.models.NLZipCodeField(
                        blank=True, max_length=7, null=True
                    ),
                ),
                ("street", models.CharField(blank=True, default="", max_length=250)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", open_inwoner.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="The name of the action",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date the action was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the date when the action was last changed",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The person that created the action.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Used as a reference in the actions api.",
                        null=True,
                        verbose_name="UUID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="The name of the appointment.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        help_text="This is the time that the appointment is at.",
                        verbose_name="Appointment time",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date the appointment was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the date when the appointment was last changed",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The person that created the appointment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Used as a reference in the appointments api.",
                        null=True,
                        verbose_name="UUID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="The first name of the contact person.",
                        max_length=250,
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="The last name of the contact person",
                        max_length=250,
                        verbose_name="Last name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="The email address of the contact person. This field can be left empty.",
                        max_length=254,
                        null=True,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The phonenumber of the contact person. This field can be left empty.",
                        max_length=250,
                        validators=[
                            open_inwoner.utils.validators.validate_phone_number
                        ],
                        verbose_name="Phonenumber",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date the contact was created. This field is automatically set.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the date when the contact was last changed. This field is automatically set.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=1,
                        help_text="This is the person that entered the contact person.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Used as a reference in the contacts api.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="The name of the document",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="This will be the actual document.",
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="",
                        verbose_name="File",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date the document was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the date when the document was last changed",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="This is the user that created the document.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Used as a reference in the documents api.",
                        null=True,
                        verbose_name="UUID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="action",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the actions api.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the appointments api.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the documents api.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rsin",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("default", "Email en Wachtwoord"),
                    ("digid", "DigiD"),
                    ("eherkenning", "eHerkenning"),
                ],
                default="default",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deactivated_on",
            field=models.DateField(
                blank=True,
                help_text="This is the date the user decided to deactivate their account.",
                null=True,
                verbose_name="Deactivated on",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_prepopulated",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if fields have been prepopulated by Haal Central API.",
                verbose_name="prepopulated",
            ),
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-updated_on", "-created_on")},
        ),
        migrations.AddField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Afgerond")],
                default="open",
                help_text="The current status of the action",
                max_length=200,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("contact", "Contactpersoon"),
                    ("begeleider", "Begeleider"),
                    ("organization", "Organisatie"),
                ],
                default="contact",
                help_text="The type of contact",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ("-updated_on", "-created_on")},
        ),
        migrations.AddField(
            model_name="user",
            name="selected_themes",
            field=models.ManyToManyField(
                blank=True, related_name="selected_by", to="pdc.category"
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date the message was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Text content of the message", verbose_name="Content"
                    ),
                ),
                (
                    "seen",
                    models.BooleanField(
                        default=False,
                        help_text="Boolean shows if the message was seem by the receiver",
                        verbose_name="Seen",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="The receiver of the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="THe sender of the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="end_date",
            field=models.DateField(
                help_text="This is the date that the action should be done.",
                null=True,
                verbose_name="Action end date",
            ),
        ),
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ("end_date", "-created_on")},
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user from the contact, who was added based on the contact email.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contact user",
            ),
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(default=False, verbose_name="accepted"),
                ),
                (
                    "key",
                    models.CharField(max_length=64, unique=True, verbose_name="key"),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date the message was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="THe contact the creation of which triggered sending the invite",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invites",
                        to="accounts.contact",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        help_text="User who received the invite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        help_text="User who created the invite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The description of the action",
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="The document that is uploaded to the file",
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="File",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="goal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The goal of the action",
                max_length=250,
                verbose_name="goal",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="is_for",
            field=models.ForeignKey(
                blank=True,
                help_text="The person that needs to do this action.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Is for",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the action belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="plans.plan",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="type",
            field=models.CharField(
                choices=[("incidental", "Incidentieel"), ("recurring", "Terugkerend")],
                default="incidental",
                help_text="The type of action that it is",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="function",
            field=models.CharField(
                default="",
                help_text="The function of the contact within an organization.",
                max_length=200,
                verbose_name="Function",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the document belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_by",
            field=models.ForeignKey(
                help_text="The person that created the action.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="This is the date that the action should be done.",
                null=True,
                verbose_name="Action end date",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("contact", "Contactpersoon"),
                    ("begeleider", "Begeleider"),
                    ("organization", "Organisatie"),
                ],
                default="contact",
                help_text="The type of contact",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sent",
            field=models.BooleanField(
                default=False,
                help_text="Boolean shows if the email was sent to the receiver about this message",
                verbose_name="Sent",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="function",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The function of the contact within an organization.",
                max_length=200,
                verbose_name="Function",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="Birthday"),
        ),
        migrations.AlterField(
            model_name="user",
            name="bsn",
            field=localflavor.nl.models.NLBSNField(
                blank=True, max_length=12, null=True, verbose_name="Bsn"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date joined"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="housenumber",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="House number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_prepopulated",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if fields have been prepopulated by Haal Central API.",
                verbose_name="Prepopulated",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="Staff status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("default", "Email en Wachtwoord"),
                    ("digid", "DigiD"),
                    ("eherkenning", "eHerkenning"),
                ],
                default="default",
                max_length=250,
                verbose_name="Login type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="postcode",
            field=localflavor.nl.models.NLZipCodeField(
                blank=True, max_length=7, null=True, verbose_name="Postcode"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rsin",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Rsin"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="selected_themes",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_by",
                to="pdc.category",
                verbose_name="Selected themes",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Street"
            ),
        ),
        migrations.AlterModelOptions(
            name="action",
            options={
                "ordering": ("end_date", "-created_on"),
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("-updated_on", "-created_on"),
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterModelOptions(
            name="invite",
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="action",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The description of the action",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="goal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The goal of the action",
                max_length=250,
                verbose_name="Goal",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the action belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="plans.plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the document belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="plans.plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="Accepted"),
        ),
        migrations.AlterField(
            model_name="invite",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="The contact the creation of which triggered sending the invite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites",
                to="accounts.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee",
            field=models.ForeignKey(
                help_text="User who received the invite",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Invitee",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="inviter",
            field=models.ForeignKey(
                help_text="User who created the invite",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Inviter",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="key",
            field=models.CharField(max_length=64, unique=True, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                help_text="The receiver of the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Receiver",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="seen",
            field=models.BooleanField(
                default=False,
                help_text="Boolean shows if the message was seen by the receiver",
                verbose_name="Seen",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                help_text="The sender of the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="The file that is attached to the message",
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="File",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Unique identifier", verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Text content of the message",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The phonenumber of the contact person. This field can be left empty.",
                max_length=15,
                validators=[open_inwoner.utils.validators.validate_phone_number],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("default", "E-mail en Wachtwoord"),
                    ("digid", "DigiD"),
                    ("eherkenning", "eHerkenning"),
                ],
                default="default",
                max_length=250,
                verbose_name="Login type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("contact", "Contactpersoon"),
                    ("begeleider", "Begeleider"),
                    ("organization", "Organisatie"),
                ],
                default="contact",
                help_text="The type of contact",
                max_length=200,
                verbose_name="Contact type",
            ),
        ),
        migrations.RemoveField(
            model_name="contact",
            name="type",
        ),
        migrations.AddField(
            model_name="invite",
            name="invitee_email",
            field=models.EmailField(
                help_text="The email used to send the invite",
                max_length=254,
                null=True,
                verbose_name="Invitee email",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                help_text="User who received the invite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Invitee",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee_email",
            field=models.EmailField(
                help_text="The email used to send the invite",
                max_length=254,
                verbose_name="Invitee email",
            ),
        ),
        migrations.RunPython(
            code=change_bsn_email_to_hash,
            reverse_code=change_hash_email_to_bsn,
        ),
        migrations.AlterField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("default", "E-mail en Wachtwoord"),
                    ("digid", "DigiD"),
                    ("eherkenning", "eHerkenning"),
                    ("oidc", "OpenId connect"),
                ],
                default="default",
                max_length=250,
                verbose_name="Login type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="oidc_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This field indicates if a user signed up with OpenId Connect or not.",
                max_length=250,
                verbose_name="OpenId Connect id",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="This indicates a soft-delete where an admin can restore the record.",
                verbose_name="Is soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="invitee_first_name",
            field=models.CharField(
                default="",
                help_text="The first name of the invitee.",
                max_length=250,
                verbose_name="First name",
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="invitee_last_name",
            field=models.CharField(
                default="",
                help_text="The last name of the invitee",
                max_length=250,
                verbose_name="Last name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="contacts_for_approval",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's contacts waiting for approval. This field is used for existing users in the application",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacts for approval",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[open_inwoner.utils.validators.validate_phone_number],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contacts of the specific user",
                related_name="_accounts_user_user_contacts_+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacts",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                help_text="Unique identifier.", null=True, verbose_name="UUID"
            ),
        ),
        migrations.RemoveField(
            model_name="invite",
            name="contact",
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee_first_name",
            field=models.CharField(
                help_text="The first name of the invitee.",
                max_length=250,
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee_last_name",
            field=models.CharField(
                help_text="The last name of the invitee",
                max_length=250,
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.AlterField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("approval", "Accordering"),
                    ("closed", "Afgerond"),
                ],
                default="open",
                help_text="The current status of the action",
                max_length=200,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee_first_name",
            field=models.CharField(
                help_text="The first name of the invitee.",
                max_length=250,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee_last_name",
            field=models.CharField(
                help_text="The last name of the invitee",
                max_length=250,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="Last name",
            ),
        ),
        migrations.RemoveField(
            model_name="action",
            name="goal",
        ),
        migrations.AddField(
            model_name="user",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "150x150",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="cropping",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=image_cropping.fields.ImageCropField(
                blank=True,
                help_text="Image",
                null=True,
                upload_to=open_inwoner.accounts.models.generate_uuid_image_name,
                verbose_name="Image",
            ),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="selected_themes",
            new_name="selected_categories",
        ),
        migrations.AlterField(
            model_name="user",
            name="selected_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_by",
                to="pdc.category",
                verbose_name="Selected categories",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cases_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the user wants to receive notifications for updates concerning cases.",
                verbose_name="Cases notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="messages_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the user wants to receive notifications for new messages.",
                verbose_name="Messages notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="plans_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the user wants to receive notifications for updates concerning plans and actions.",
                verbose_name="Plans notifications",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee_first_name",
            field=models.CharField(
                help_text="The first name of the invitee.",
                max_length=250,
                validators=[open_inwoner.utils.validators.CharFieldValidator()],
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee_last_name",
            field=models.CharField(
                help_text="The last name of the invitee",
                max_length=250,
                validators=[open_inwoner.utils.validators.CharFieldValidator()],
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                validators=[open_inwoner.utils.validators.CharFieldValidator()],
                verbose_name="City",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[open_inwoner.utils.validators.CharFieldValidator()],
                verbose_name="Display name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[open_inwoner.utils.validators.CharFieldValidator()],
                verbose_name="First name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="infix",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[open_inwoner.utils.validators.CharFieldValidator()],
                verbose_name="Infix",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[open_inwoner.utils.validators.CharFieldValidator()],
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                validators=[open_inwoner.utils.validators.CharFieldValidator()],
                verbose_name="Street",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deactivated_on",
            field=models.DateField(
                blank=True,
                help_text="This is the date the user decided to deactivate their account. This field is deprecated since user profiles are now immediately deleted.",
                null=True,
                verbose_name="Deactivated on",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email address"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("login_type", "digid"), _negated=True),
                fields=("email",),
                name="unique_email_when_not_digid",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="selected_categories",
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kvk",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[open_inwoner.utils.validators.validate_kvk],
                verbose_name="KvK number",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_when_not_digid",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("login_type", "digid"), _negated=True),
                    models.Q(("login_type", "eherkenning"), _negated=True),
                ),
                fields=("email",),
                name="unique_email_when_not_digid_or_eherkenning",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="postcode",
            field=localflavor.nl.models.NLZipCodeField(
                blank=True, default="", max_length=7, verbose_name="Postcode"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bsn",
            field=localflavor.nl.models.NLBSNField(
                blank=True, default="", max_length=12, verbose_name="Bsn"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="kvk",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                validators=[open_inwoner.utils.validators.validate_kvk],
                verbose_name="KvK number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rsin",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="Rsin"
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="birthday",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.AddField(
            model_name="user",
            name="selected_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_by",
                to="pdc.category",
                verbose_name="Selected categories",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contacts of the specific user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacts",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Verified email"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="case_notification_channel",
            field=models.CharField(
                choices=[
                    ("digital_and_post", "Digitaal en per brief"),
                    ("digital_only", "Alleen digitaal"),
                ],
                default="digital_and_post",
                verbose_name="Case notifications channel",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="display_name",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS digid_eherkenning_oidc_generics_openidconnectdigidconfig;",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS digid_eherkenning_oidc_generics_openidconnecteherkenningconfig;",
        ),
        migrations.CreateModel(
            name="OpenIDDigiDConfig",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("digid_eherkenning_oidc_generics.digidconfig",),
        ),
        migrations.CreateModel(
            name="OpenIDEHerkenningConfig",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("digid_eherkenning_oidc_generics.eherkenningconfig",),
        ),
        migrations.AddField(
            model_name="user",
            name="phonenumber_alternative",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Alternative phonenumber",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("phonenumber__exact", ""), _negated=True),
                    ("phonenumber_alternative__exact", ""),
                    _connector="OR",
                ),
                name="phonenumber_alt_requires_phonenumber_primary",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("phonenumber", models.F("phonenumber_alternative")),
                        _negated=True,
                    ),
                    ("phonenumber__exact", ""),
                    _connector="OR",
                ),
                name="check_alternative_phonenumber_differs_from_primary_phonenumber",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("kvk__exact", ""), ("login_type", "eherkenning"), _negated=True
                ),
                name="eherkenning_user_requires_kvk",
                violation_error_message="Users with login type `eHerkenning` must have a value set for the kvk nummer",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vestiging",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                validators=[open_inwoner.utils.validators.validate_vestiging],
                verbose_name="Vestigingsnummer",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("login_type", "eherkenning")),
                fields=("kvk", "vestiging"),
                name="eherkenning_user_requires_unique_vestiging_for_a_kvk",
                violation_error_message="A vestigingsnummer must be unique for each kvk nummer",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="branch_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                verbose_name="Company branch name",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="This is the date that the action should be done.",
                null=True,
                verbose_name="Execute before",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="The document that is uploaded to the file",
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="Add a file",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="is_for",
            field=models.ForeignKey(
                blank=True,
                help_text="The person that needs to do this action.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Action for",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the action",
                max_length=250,
                verbose_name="Action title",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Nog te doen"),
                    ("approval", "Mee bezig"),
                    ("closed", "Afgerond"),
                ],
                default="open",
                help_text="The current status of the action",
                max_length=200,
                verbose_name="Status",
            ),
        ),
    ]
