# Generated by Django 3.2.7 on 2021-10-08 09:00

import django.db.models.deletion
from django.db import migrations, models

import privates.storages

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20211004_1708"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="accounts.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="accounts.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="helps",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="accounts.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="accounts.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                validators=[open_inwoner.utils.validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=privates.storages.PrivateMediaFileSystemStorage(), upload_to=""
            ),
        ),
    ]
