# Generated by Django 3.2.7 on 2021-10-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import privates.storages

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20211008_1100"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="helps",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="This is the person that entered the contact person.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="accounts.user",
                verbose_name="Created by",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="action",
            name="created_by",
            field=models.ForeignKey(
                help_text="The person that created the action.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the date the document was created",
                verbose_name="Created on",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the action",
                max_length=250,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="This is the date when the document was last changed",
                verbose_name="Updated on",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                help_text="The person that created the appointment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the date the document was created",
                verbose_name="Created on",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="datetime",
            field=models.DateTimeField(
                help_text="This is the time that the appointment is at.",
                verbose_name="Appointment time",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the appointment.",
                max_length=250,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="This is the date when the document was last changed",
                verbose_name="Updated on",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the date the document was created. This field is automatically set.",
                verbose_name="Created on",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="The email address of the contact person. This field can be left empty.",
                max_length=254,
                null=True,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                help_text="The first name of the contact person.",
                max_length=250,
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                help_text="The last name of the contact person",
                max_length=250,
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The phonenumber of the contact person. This field can be left empty.",
                max_length=250,
                validators=[open_inwoner.utils.validators.validate_phone_number],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="This is the date when the document was last changed. This field is automatically set.",
                verbose_name="Updated on",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the date the document was created",
                verbose_name="Created on",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="This will be te actual document.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the document",
                max_length=250,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                help_text="This is the user that created the document.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="This is the date when the document was last changed",
                verbose_name="Updated on",
            ),
        ),
    ]
