# Generated by Django 3.2.7 on 2021-10-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20211007_1244"),
        ("accounts", "0004_auto_20211008_1311"),
    ]

    operations = []
