# Generated by Django 3.2.7 on 2021-10-18 10:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20211013_1415"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="guid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="GUID"
            ),
        ),
    ]
