# Generated by Django 3.2.7 on 2021-10-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20211013_1129"),
        ("accounts", "0006_auto_20211013_1415"),
    ]

    operations = []
