# Generated by Django 3.2.7 on 2021-10-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_contact_uuid"),
        ("accounts", "0007_merge_0005_auto_20211013_1129_0006_auto_20211013_1415"),
    ]

    operations = []
