# Generated by Django 3.2.7 on 2021-11-01 10:29

import uuid

from django.db import migrations, models

import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_contact_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the actions api.",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the appointments api.",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the documents api.",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the date the action was created",
                verbose_name="Created on",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="This is the date when the action was last changed",
                verbose_name="Updated on",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the date the appointment was created",
                verbose_name="Created on",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="This is the date when the appointment was last changed",
                verbose_name="Updated on",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the date the contact was created. This field is automatically set.",
                verbose_name="Created on",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="This is the date when the contact was last changed. This field is automatically set.",
                verbose_name="Updated on",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="This will be the actual document.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="File",
            ),
        ),
    ]
