# Generated by Django 3.2.7 on 2021-10-18 11:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_contact_guid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="guid",
        ),
        migrations.AddField(
            model_name="contact",
            name="reference",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="reference"
            ),
        ),
    ]
