# Generated by Django 3.2.7 on 2021-11-01 10:37

import uuid

from django.db import migrations


def gen_uuid_action(apps, schema_editor):
    MyModel = apps.get_model("accounts", "Action")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


def gen_uuid_appointment(apps, schema_editor):
    MyModel = apps.get_model("accounts", "Appointment")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


def gen_uuid_document(apps, schema_editor):
    MyModel = apps.get_model("accounts", "Document")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20211101_1129"),
    ]

    operations = [
        migrations.RunPython(gen_uuid_action, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            gen_uuid_appointment, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(gen_uuid_document, reverse_code=migrations.RunPython.noop),
    ]
