# Generated by Django 3.2.7 on 2021-11-01 10:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auto_20211101_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the actions api.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the appointments api.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used as a reference in the documents api.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
