# Generated by Django 3.2.7 on 2021-11-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20211020_1415"),
        ("accounts", "0010_auto_20211101_1137"),
    ]

    operations = []
