# Generated by Django 3.2.7 on 2021-11-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_merge_20211104_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_on",
            field=models.DateField(
                blank=True,
                help_text="This is the date the user decides to deactivate account.",
                null=True,
                verbose_name="Deactivated on",
            ),
        ),
    ]
