# Generated by Django 3.2.7 on 2021-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_deactivated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deactivated_on",
            field=models.DateField(
                blank=True,
                help_text="This is the date the user decided to deactivate their account.",
                null=True,
                verbose_name="Deactivated on",
            ),
        ),
    ]
