# Generated by Django 3.2.7 on 2021-12-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_is_prepopulated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-updated_on", "-created_on")},
        ),
        migrations.AddField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Afgerond")],
                default="open",
                help_text="The current status of the action",
                max_length=200,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("contact", "Contactpersoon"),
                    ("begeleider", "Begeleider"),
                    ("organization", "Orgnaisatie"),
                ],
                default="contact",
                help_text="The type of contact",
                max_length=200,
                verbose_name="Type",
            ),
        ),
    ]
