# Generated by Django 3.2.7 on 2021-12-16 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_is_prepopulated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the date the message was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Text content of the message", verbose_name="Content"
                    ),
                ),
                (
                    "seen",
                    models.BooleanField(
                        default=False,
                        help_text="Boolean shows if the message was seem by the receiver",
                        verbose_name="Seen",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="The receiver of the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="THe sender of the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
