# Generated by Django 3.2.7 on 2021-12-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_message"),
        ("accounts", "0016_auto_20211214_1652"),
    ]

    operations = []
