# Generated by Django 3.2.7 on 2021-12-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20211214_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="end_date",
            field=models.DateField(
                help_text="This is the date that the action should be done.",
                null=True,
                verbose_name="Action end date",
            ),
        ),
    ]
