# Generated by Django 3.2.7 on 2021-12-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_action_end_date"),
        ("accounts", "0017_merge_0015_message_0016_auto_20211214_1652"),
    ]

    operations = []
