# Generated by Django 3.2.7 on 2021-12-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0018_alter_product_keywords"),
        ("accounts", "0018_merge_20211222_1030"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ("end_date", "-created_on")},
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user from the contact, who was added based on the contact email.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contact user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="selected_themes",
            field=models.ManyToManyField(
                blank=True, related_name="selected_by", to="pdc.Category"
            ),
        ),
    ]
