# Generated by Django 3.2.7 on 2022-01-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_merge_20211222_1030"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ("end_date", "-created_on")},
        ),
    ]
