# Generated by Django 3.2.7 on 2022-01-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_action_options"),
        ("plans", "0001_initial"),
        ("pdc", "0019_product_uniforme_productnaam"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="plan",
            field=models.ForeignKey(
                help_text="The plan that the action belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("contact", "Contactpersoon"),
                    ("begeleider", "Begeleider"),
                    ("organization", "Organisatie"),
                ],
                default="contact",
                help_text="The type of contact",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="selected_themes",
            field=models.ManyToManyField(
                blank=True, related_name="selected_by", to="pdc.Category"
            ),
        ),
    ]
