# Generated by Django 3.2.7 on 2022-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_auto_20220110_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="function",
            field=models.CharField(default="", max_length=200, verbose_name="Function"),
        ),
    ]
