# Generated by Django 3.2.7 on 2022-02-02 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
        ("accounts", "0021_auto_20220202_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the action belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="plans.plan",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="type",
            field=models.CharField(
                choices=[("incidental", "Incidentieel"), ("recurring", "Terugkerend")],
                default="incidental",
                help_text="The type of action that it is",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="function",
            field=models.CharField(
                default="",
                help_text="The function of the contact within an organization.",
                max_length=200,
                verbose_name="Function",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the document belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_by",
            field=models.ForeignKey(
                help_text="The person that created the action.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="This is the date that the action should be done.",
                null=True,
                verbose_name="Action end date",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("contact", "Contactpersoon"),
                    ("begeleider", "Begeleider"),
                    ("organization", "Organisatie"),
                ],
                default="contact",
                help_text="The type of contact",
                max_length=200,
                verbose_name="Type",
            ),
        ),
    ]
