# Generated by Django 3.2.7 on 2022-01-12 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0011_planfile_created_at"),
        ("accounts", "0021_contact_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="file",
            field=models.FileField(
                help_text="The document that is uploaded to the file",
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="File",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="is_for",
            field=models.ForeignKey(
                help_text="The person that needs to do this action.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="type",
            field=models.CharField(
                choices=[("incidental", "Incidentieel"), ("recurring", "Terugkerend")],
                default="incidental",
                help_text="The type of action that it is",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_by",
            field=models.ForeignKey(
                help_text="The person that created the action.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the action belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="plans.plan",
            ),
        ),
    ]
