# Generated by Django 3.2.7 on 2022-01-12 16:04

from django.db import migrations


def creator_is_for(apps, schemas):
    Action = apps.get_model("accounts.Action")

    for action in Action.objects.all():
        action.is_for = action.created_by
        action.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_auto_20220112_1704"),
    ]

    operations = [migrations.RunPython(creator_is_for)]
