# Generated by Django 3.2.7 on 2022-01-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0011_planfile_created_at"),
        ("accounts", "0023_auto_20220112_1704"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the document belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="plans.plan",
            ),
        ),
    ]
