# Generated by Django 3.2.7 on 2022-02-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_contact_type"),
        ("accounts", "0023_auto_20220202_0951"),
    ]

    operations = []
