# Generated by Django 3.2.7 on 2022-01-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_document_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="description",
            field=models.TextField(
                default="",
                help_text="The description of the action",
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="goal",
            field=models.CharField(
                default="",
                help_text="The goal of the action",
                max_length=250,
                verbose_name="goal",
            ),
        ),
    ]
