# Generated by Django 3.2.7 on 2022-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_migrate_message_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sent",
            field=models.BooleanField(
                default=False,
                help_text="Boolean shows if the email was sent to the receiver about this message",
                verbose_name="Sent",
            ),
        ),
    ]
