# Generated by Django 3.2.7 on 2022-01-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_invite"),
        ("accounts", "0025_auto_20220117_1710"),
    ]

    operations = []
