# Generated by Django 3.2.12 on 2022-02-14 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_auto_20220214_1543"),
        ("accounts", "0027_auto_20220214_1440"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("-updated_on", "-created_on"),
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "document", "verbose_name_plural": "documents"},
        ),
        migrations.AlterField(
            model_name="action",
            name="goal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The goal of the action",
                max_length=250,
                verbose_name="Goal",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the action belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="plans.plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the document belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="plans.plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="Accepted"),
        ),
        migrations.AlterField(
            model_name="invite",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="The contact the creation of which triggered sending the invite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites",
                to="accounts.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee",
            field=models.ForeignKey(
                help_text="User who received the invite",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Invitee",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="inviter",
            field=models.ForeignKey(
                help_text="User who created the invite",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Inviter",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="key",
            field=models.CharField(max_length=64, unique=True, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                help_text="The receiver of the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Receiver",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="seen",
            field=models.BooleanField(
                default=False,
                help_text="Boolean shows if the message was seen by the receiver",
                verbose_name="Seen",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                help_text="The sender of the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
    ]
