# Generated by Django 3.2.12 on 2022-02-18 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_auto_20220214_1440"),
        ("accounts", "0028_auto_20220214_1538"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={
                "ordering": ("end_date", "-created_on"),
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("-updated_on", "-created_on"),
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterModelOptions(
            name="invite",
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="action",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The description of the action",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="goal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The goal of the action",
                max_length=250,
                verbose_name="Goal",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the action belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="plans.plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan that the document belongs to. This can be left empty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="plans.plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="Accepted"),
        ),
        migrations.AlterField(
            model_name="invite",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="The contact the creation of which triggered sending the invite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites",
                to="accounts.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee",
            field=models.ForeignKey(
                help_text="User who received the invite",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Invitee",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="inviter",
            field=models.ForeignKey(
                help_text="User who created the invite",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Inviter",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="key",
            field=models.CharField(max_length=64, unique=True, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                help_text="The receiver of the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Receiver",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="seen",
            field=models.BooleanField(
                default=False,
                help_text="Boolean shows if the message was seen by the receiver",
                verbose_name="Seen",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                help_text="The sender of the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
    ]
