# Generated by Django 3.2.12 on 2022-03-07 15:33

from django.db import migrations, models
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_auto_20220218_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="The file that is attached to the message",
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="File",
            ),
        ),
    ]
