# Generated by Django 3.2.7 on 2021-11-01 10:37

import uuid

from django.db import migrations


def gen_uuid_message(apps, schema_editor):
    Message = apps.get_model("accounts", "Message")
    for row in Message.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_message_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid_message, reverse_code=migrations.RunPython.noop),
    ]
