# Generated by Django 3.2.12 on 2022-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_alter_message_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Text content of the message",
                verbose_name="Content",
            ),
        ),
    ]
