# Generated by Django 3.2.12 on 2022-03-25 12:08

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_alter_message_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The phonenumber of the contact person. This field can be left empty.",
                max_length=15,
                validators=[open_inwoner.utils.validators.validate_phone_number],
                verbose_name="Phonenumber",
            ),
        ),
    ]
