# Generated by Django 3.2.12 on 2022-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_alter_contact_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("default", "E-mail en Wachtwoord"),
                    ("digid", "DigiD"),
                    ("eherkenning", "eHerkenning"),
                ],
                default="default",
                max_length=250,
                verbose_name="Login type",
            ),
        ),
    ]
