# Generated by Django 3.2.12 on 2022-05-04 11:52

from django.db import migrations


def copy_contact_type_from_contacts_to_user(apps, schema_editor):
    Contact = apps.get_model("accounts", "Contact")
    for contact in Contact.objects.exclude(contact_user__isnull=True):
        user = contact.contact_user
        user.contact_type = contact.type
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_user_contact_type"),
    ]

    operations = [
        migrations.RunPython(
            copy_contact_type_from_contacts_to_user,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
