# Generated by Django 3.2.12 on 2022-05-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_auto_20220504_1352"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="type",
        ),
    ]
