# Generated by Django 3.2.13 on 2022-05-18 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_remove_contact_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="invitee_email",
            field=models.EmailField(
                help_text="The email used to send the invite",
                max_length=254,
                null=True,
                verbose_name="Invitee email",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                help_text="User who received the invite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Invitee",
            ),
        ),
    ]
