# Generated by Django 3.2.13 on 2022-06-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_change_digid_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oidc_id",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
