# Generated by Django 3.2.15 on 2022-11-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_alter_user_oidc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                verbose_name="Is soft-deleted",
                help_text="This indicates a soft-delete where an admin can restore the record.",
            ),
        ),
    ]
