# Generated by Django 3.2.15 on 2022-12-05 08:21

from django.conf import settings
from django.db import migrations, models
import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_action_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="invitee_first_name",
            field=models.CharField(
                default="",
                help_text="The first name of the invitee.",
                max_length=250,
                verbose_name="First name",
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="invitee_last_name",
            field=models.CharField(
                default="",
                help_text="The last name of the invitee",
                max_length=250,
                verbose_name="Last name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="contacts_for_approval",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's contacts waiting for approval. This field is used for existing users in the application",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacts for approval",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[open_inwoner.utils.validators.validate_phone_number],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contacts of the specific user",
                related_name="_accounts_user_user_contacts_+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacts",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                help_text="Unique identifier.", null=True, verbose_name="UUID"
            ),
        ),
    ]
