# Generated by Django 3.2.15 on 2022-11-25 09:42

import uuid

from django.db import migrations


def gen_user_uuid(apps, schema_editor):
    MyModel = apps.get_model("accounts", "User")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


def populate_user_contacts(apps, schema_editor):
    MyModel = apps.get_model("accounts", "Contact")
    for contact in MyModel.objects.exclude(contact_user__isnull=True):
        creator = contact.created_by
        contact_user = contact.contact_user
        creator.user_contacts.add(contact_user)


def populate_invite_names(apps, schema_editor):
    MyModel = apps.get_model("accounts", "Invite")
    for invite in MyModel.objects.filter(accepted=True):
        invite.invitee_first_name = invite.invitee.first_name
        invite.invitee_last_name = invite.invitee.last_name
        invite.save()


def populate_plan_contacts(apps, schema_editor):
    MyModel = apps.get_model("plans", "Plan")
    for plan in MyModel.objects.all():
        for contact in plan.contacts.exclude(contact_user__isnull=True):
            plan.plan_contacts.add(contact.contact_user)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_auto_20221125_1042"),
        ("plans", "0009_plan_plan_contacts"),
    ]

    operations = [
        migrations.RunPython(gen_user_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            populate_user_contacts, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_invite_names, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_plan_contacts, reverse_code=migrations.RunPython.noop
        ),
    ]
