# Generated by Django 3.2.15 on 2022-11-24 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20221124_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invitee_first_name',
            field=models.CharField(help_text='The first name of the invitee.', max_length=250, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invitee_last_name',
            field=models.CharField(help_text='The last name of the invitee', max_length=250, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique identifier.', unique=True, verbose_name='UUID'),
        ),
    ]
