# Generated by Django 3.2.15 on 2022-12-05 08:21

import uuid

from django.db import migrations


def gen_user_uuid(apps, schema_editor):
    MyModel = apps.get_model("accounts", "User")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


def populate_user_contacts(apps, schema_editor):
    MyModel = apps.get_model("accounts", "Contact")
    for contact in MyModel.objects.exclude(contact_user__isnull=True):
        if contact.created_by != contact.contact_user:
            creator = contact.created_by
            contact_user = contact.contact_user
            creator.user_contacts.add(contact_user)


def populate_invite_names(apps, schema_editor):
    MyModel = apps.get_model("accounts", "Invite")
    for invite in MyModel.objects.filter(invitee__isnull=False):
        invite.invitee_first_name = invite.invitee.first_name
        invite.invitee_last_name = invite.invitee.last_name
        invite.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_auto_20221205_0921"),
    ]

    operations = [
        migrations.RunPython(gen_user_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            populate_user_contacts, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_invite_names, reverse_code=migrations.RunPython.noop
        ),
    ]
