# Generated by Django 3.2.15 on 2022-12-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_action_is_deleted"),
        ("accounts", "0049_auto_20221130_1614"),
    ]

    operations = []
