# Generated by Django 3.2.15 on 2022-12-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_alter_action_status"),
        ("accounts", "0050_auto_20221205_0924"),
    ]

    operations = []
