# Generated by Django 3.2.15 on 2022-12-13 06:58

from django.db import migrations, models
import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_merge_20221207_0918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="invitee_first_name",
            field=models.CharField(
                help_text="The first name of the invitee.",
                max_length=250,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invitee_last_name",
            field=models.CharField(
                help_text="The last name of the invitee",
                max_length=250,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="Last name",
            ),
        ),
    ]
