# Generated by Django 3.2.15 on 2023-01-17 14:21

from django.db import migrations, models
import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_auto_20221213_0758"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="Display name",
            ),
        ),
    ]
