# Generated by Django 3.2.15 on 2023-02-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_user_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="goal",
        ),
    ]
