# Generated by Django 3.2.15 on 2023-02-24 10:49

from django.db import migrations, models
import open_inwoner.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_user_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the begeleider",
                null=True,
                upload_to=open_inwoner.accounts.models.generate_uuid_photo_name,
                verbose_name="Begeleider photo",
            ),
        ),
    ]
