# Generated by Django 3.2.15 on 2023-03-07 07:52

from django.db import migrations
import image_cropping.fields
import open_inwoner.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "150x150",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=True,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=image_cropping.fields.ImageCropField(
                blank=True,
                help_text="Image",
                null=True,
                upload_to=open_inwoner.accounts.models.generate_uuid_image_name,
                verbose_name="Image",
            ),
        ),
    ]
