# Generated by Django 3.2.15 on 2023-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_auto_20230307_0852"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cases_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the user wants to receive notifications for updates concerning cases.",
                verbose_name="Cases notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="messages_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the user wants to receive notifications for new messages.",
                verbose_name="Messages notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="plans_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the user wants to receive notifications for updates concerning plans and actions.",
                verbose_name="Plans notifications",
            ),
        ),
    ]
