# Generated by Django 3.2.15 on 2023-04-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdc', '0055_alter_product_content'),
        ('accounts', '0057_rename_selected_themes_user_selected_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, related_name='selected_by', to='pdc.Category', verbose_name='Selected categories'),
        ),
    ]
