# Generated by Django 3.2.15 on 2023-05-23 12:26

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0059_auto_20230412_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="infix",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[open_inwoner.utils.validators.validate_charfield_entry],
                verbose_name="Infix",
            ),
        ),
    ]
