# Generated by Django 3.2.15 on 2023-06-26 07:52

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_alter_user_deactivated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Phonenumber",
            ),
        ),
    ]
