# Generated by Django 3.2.20 on 2023-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_user_unique_email_when_not_digid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="selected_categories",
        ),
    ]
