# Generated by Django 3.2.20 on 2023-11-21 10:31

from django.db import migrations, models
import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0066_remove_user_selected_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Company name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kvk",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[open_inwoner.utils.validators.validate_kvk],
                verbose_name="KvK number",
            ),
        ),
    ]
