# Generated by Django 3.2.20 on 2023-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0067_auto_20231121_1131"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_when_not_digid",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("login_type", "digid"), _negated=True),
                    models.Q(("login_type", "eherkenning"), _negated=True),
                ),
                fields=("email",),
                name="unique_email_when_not_digid_or_eherkenning",
            ),
        ),
    ]
