# Generated by Django 3.2.20 on 2023-12-05 15:57

from django.db import migrations, models
import localflavor.nl.models
import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0069_alter_user_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bsn",
            field=localflavor.nl.models.NLBSNField(
                blank=True, default="", max_length=12, verbose_name="Bsn"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Company name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="kvk",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                validators=[open_inwoner.utils.validators.validate_kvk],
                verbose_name="KvK number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rsin",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="Rsin"
            ),
        ),
    ]
