# Generated by Django 3.2.23 on 2024-01-19 09:24

from django.db import migrations
from open_inwoner.utils.hash import generate_email_from_string
from ..choices import LoginTypeChoices


def change_kvk_email_to_hash(apps, _):
    User = apps.get_model("accounts", "User")

    for user in User.objects.filter(login_type=LoginTypeChoices.eherkenning).all():
        if user.email == f"user-{user.kvk}@localhost":
            user.email = generate_email_from_string(user.kvk)
            user.save()


def change_hash_email_to_kvk(apps, _):
    User = apps.get_model("accounts", "User")

    for user in User.objects.filter(login_type=LoginTypeChoices.eherkenning).all():
        if user.email == generate_email_from_string(user.kvk):
            user.email = f"user-{user.kvk}@localhost"
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_auto_20231205_1657"),
    ]

    operations = [
        migrations.RunPython(change_kvk_email_to_hash, change_hash_email_to_kvk)
    ]
