# Generated by Django 3.2.23 on 2024-01-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_auto_20231205_1657"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
