# Generated by Django 3.2.23 on 2024-01-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_auto_20231205_1657"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birthday",
        ),
    ]
