# Generated by Django 3.2.23 on 2024-01-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0071_delete_appointment"),
        ("accounts", "0071_remove_user_birthday"),
    ]

    operations = []
