# Generated by Django 4.2.10 on 2024-02-13 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0072_merge_20240129_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contacts of the specific user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacts",
            ),
        ),
    ]
