# Generated by Django 4.2.10 on 2024-02-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0073_alter_user_user_contacts"),
        ("accounts", "0073_user_selected_categories"),
    ]

    operations = []
