# Generated by Django 4.2.11 on 2024-03-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0074_merge_20240228_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Verified email"
            ),
        ),
    ]
