# Generated by Django 4.2.11 on 2024-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0075_user_verified_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="case_notification_channel",
            field=models.CharField(
                choices=[
                    ("digital_and_post", "Digitaal en per brief"),
                    ("digital_only", "Alleen digitaal"),
                ],
                default="digital_and_post",
                verbose_name="Case notifications channel",
            ),
        ),
    ]
