# Generated by Django 4.2.15 on 2024-08-22 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0076_user_case_notification_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="display_name",
        ),
    ]
