# Generated by Django 4.2.16 on 2024-09-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0077_no_roepnaam"),
        ("accounts", "0077_openiddigidconfig_openideherkenningconfig"),
    ]

    operations = []
