# Generated by Django 4.2.16 on 2025-02-13 11:57

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0079_digid_eherkenning_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phonenumber_alternative",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Alternative phonenumber",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("phonenumber__exact", ""), _negated=True),
                    ("phonenumber_alternative__exact", ""),
                    _connector="OR",
                ),
                name="phonenumber_alt_requires_phonenumber_primary",
            ),
        ),
    ]
