# Generated by Django 4.2.18 on 2025-03-11 15:35

from django.db import migrations, models
from django.db.models import F


def dedupe_phone_numbers(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    for user in User.objects.filter(phonenumber=F("phonenumber_alternative")):
        user.phonenumber_alternative = ""
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0080_user_phonenumber_alternative"),
    ]

    operations = [
        migrations.RunPython(
            code=dedupe_phone_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("phonenumber", models.F("phonenumber_alternative")),
                        _negated=True,
                    ),
                    ("phonenumber__exact", ""),
                    _connector="OR",
                ),
                name="check_alternative_phonenumber_differs_from_primary_phonenumber",
            ),
        ),
    ]
