# Generated by Django 4.2.18 on 2025-03-05 11:56

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0080_user_phonenumber_alternative"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vestiging",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                validators=[open_inwoner.utils.validators.validate_vestiging],
                verbose_name="Vestigingsnummer",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("kvk__exact", ""), _negated=True),
                    ("vestiging__exact", ""),
                    _connector="OR",
                ),
                name="vestiging_requires_kvk",
            ),
        ),
    ]
