# Generated by Django 4.2.20 on 2025-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0081_user_check_alternative_phonenumber_differs_from_primary_phonenumber",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("kvk__exact", ""), ("login_type", "eherkenning"), _negated=True
                ),
                name="eherkenning_user_requires_kvk",
                violation_error_message="Users with login type `eHerkenning` must have a value set for the kvk nummer",
            ),
        ),
    ]
