# Generated by Django 4.2.20 on 2025-03-17 15:48

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0082_user_eherkenning_user_requires_kvk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vestiging",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                validators=[open_inwoner.utils.validators.validate_vestiging],
                verbose_name="Vestigingsnummer",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("login_type", "eherkenning")),
                fields=("kvk", "vestiging"),
                name="eherkenning_user_requires_unique_vestiging_for_a_kvk",
                violation_error_message="A vestigingsnummer must be unique for each kvk nummer",
            ),
        ),
    ]
