# Generated by Django 4.2.20 on 2025-04-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0083_user_vestiging_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                verbose_name="Company branch name",
            ),
        ),
    ]
