# Generated by Django 4.2.16 on 2025-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0083_user_vestiging_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Nog te doen"),
                    ("approval", "Mee bezig"),
                    ("closed", "Afgerond"),
                ],
                default="open",
                help_text="The current status of the action",
                max_length=200,
                verbose_name="Status",
            ),
        ),
    ]
