# Generated by Django 4.2.18 on 2025-04-24 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0084_user_branch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="This is the date that the action should be done.",
                null=True,
                verbose_name="Execute before",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="The document that is uploaded to the file",
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="Add a file",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="is_for",
            field=models.ForeignKey(
                blank=True,
                help_text="The person that needs to do this action.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Action for",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name of the action",
                max_length=250,
                verbose_name="Action title",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Nog te doen"),
                    ("approval", "Mee bezig"),
                    ("closed", "Afgerond"),
                ],
                default="open",
                help_text="The current status of the action",
                max_length=200,
                verbose_name="Status",
            ),
        ),
    ]
