# Generated by Django 4.2.20 on 2025-06-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("accounts", "0086_user_last_login_delta_squashed_0088_alter_user_prev_login"),
        ("accounts", "0089_alter_user_prev_login"),
    ]

    dependencies = [
        ("accounts", "0085_alter_action_end_date_alter_action_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="previous_login",
            field=models.DateTimeField(
                blank=True,
                help_text="The previous login time for the user, which will be shown upon login when `last_login` has been updated to the current timestamp.",
                null=True,
                verbose_name="Previous login",
            ),
        ),
    ]
