# Generated by Django 4.2.22 on 2025-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0086_user_last_login_delta_squashed_0088_alter_user_prev_login_squashed_0089_alter_user_prev_login",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="check_alternative_phonenumber_differs_from_primary_phonenumber",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("phonenumber", models.F("phonenumber_alternative")),
                        _negated=True,
                    ),
                    ("phonenumber__exact", ""),
                    _connector="OR",
                ),
                name="check_alternative_phonenumber_differs_from_primary_phonenumber",
                violation_error_message="Primary and secondary phone numbers cannot be the same",
            ),
        ),
    ]
