# Generated by Django 4.2.25 on 2025-10-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0090_remove_user_check_alternative_phonenumber_differs_from_primary_phonenumber_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="phonenumber_alt_requires_phonenumber_primary",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("phonenumber__exact", ""), _negated=True),
                    ("phonenumber_alternative__exact", ""),
                    _connector="OR",
                ),
                name="phonenumber_alt_requires_phonenumber_primary",
                violation_error_message="A primary phone number is required for setting an alternative phone number",
            ),
        ),
    ]
