# Generated by Django 4.2.26 on 2025-11-11 08:21

from django.db import migrations, models

import django_jsonform.models.fields
import mozilla_django_oidc_db.fields
import mozilla_django_oidc_db.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0091_remove_user_phonenumber_alt_requires_phonenumber_primary_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenIDEIDASConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether OpenID Connect for authentication/authorization is enabled",
                        verbose_name="enable",
                    ),
                ),
                (
                    "oidc_rp_client_id",
                    models.CharField(
                        help_text="OpenID Connect client ID provided by the OIDC Provider",
                        max_length=1000,
                        verbose_name="OpenID Connect client ID",
                    ),
                ),
                (
                    "oidc_rp_client_secret",
                    models.CharField(
                        help_text="OpenID Connect secret provided by the OIDC Provider",
                        max_length=1000,
                        verbose_name="OpenID Connect secret",
                    ),
                ),
                (
                    "oidc_rp_sign_algo",
                    models.CharField(
                        default="HS256",
                        help_text="Algorithm the Identity Provider uses to sign ID tokens",
                        max_length=50,
                        verbose_name="OpenID sign algorithm",
                    ),
                ),
                (
                    "oidc_rp_scopes_list",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="OpenID Connect scope"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.models.get_default_scopes,
                        help_text="OpenID Connect scopes that are requested during login",
                        size=None,
                        verbose_name="OpenID Connect scopes",
                    ),
                ),
                (
                    "oidc_op_discovery_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="URL of your OpenID Connect provider discovery endpoint ending with a slash (`.well-known/...` will be added automatically). If this is provided, the remaining endpoints can be omitted, as they will be derived from this endpoint.",
                        max_length=1000,
                        verbose_name="Discovery endpoint",
                    ),
                ),
                (
                    "oidc_op_jwks_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="URL of your OpenID Connect provider JSON Web Key Set endpoint. Required if `RS256` is used as signing algorithm.",
                        max_length=1000,
                        verbose_name="JSON Web Key Set endpoint",
                    ),
                ),
                (
                    "oidc_op_authorization_endpoint",
                    models.URLField(
                        help_text="URL of your OpenID Connect provider authorization endpoint",
                        max_length=1000,
                        verbose_name="Authorization endpoint",
                    ),
                ),
                (
                    "oidc_op_token_endpoint",
                    models.URLField(
                        help_text="URL of your OpenID Connect provider token endpoint",
                        max_length=1000,
                        verbose_name="Token endpoint",
                    ),
                ),
                (
                    "oidc_token_use_basic_auth",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, the client ID and secret are sent in the HTTP Basic auth header when obtaining the access token. Otherwise, they are sent in the request body.",
                        verbose_name="Use Basic auth for token endpoint",
                    ),
                ),
                (
                    "oidc_op_user_endpoint",
                    models.URLField(
                        help_text="URL of your OpenID Connect provider userinfo endpoint",
                        max_length=1000,
                        verbose_name="User endpoint",
                    ),
                ),
                (
                    "oidc_rp_idp_sign_key",
                    models.CharField(
                        blank=True,
                        help_text="Key the Identity Provider uses to sign ID tokens in the case of an RSA sign algorithm. Should be the signing key in PEM or DER format.",
                        max_length=1000,
                        verbose_name="Sign key",
                    ),
                ),
                (
                    "oidc_op_logout_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="URL of your OpenID Connect provider logout endpoint",
                        max_length=1000,
                        verbose_name="Logout endpoint",
                    ),
                ),
                (
                    "oidc_use_nonce",
                    models.BooleanField(
                        default=True,
                        help_text="Controls whether the OpenID Connect client uses nonce verification",
                        verbose_name="Use nonce",
                    ),
                ),
                (
                    "oidc_nonce_size",
                    models.PositiveIntegerField(
                        default=32,
                        help_text="Sets the length of the random string used for OpenID Connect nonce verification",
                        verbose_name="Nonce size",
                    ),
                ),
                (
                    "oidc_state_size",
                    models.PositiveIntegerField(
                        default=32,
                        help_text="Sets the length of the random string used for OpenID Connect state verification",
                        verbose_name="State size",
                    ),
                ),
                (
                    "oidc_keycloak_idp_hint",
                    models.CharField(
                        blank=True,
                        help_text="Specific for Keycloak: parameter that indicates which identity provider should be used (therefore skipping the Keycloak login screen).",
                        max_length=1000,
                        verbose_name="Keycloak Identity Provider hint",
                    ),
                ),
                (
                    "userinfo_claims_source",
                    models.CharField(
                        choices=[
                            ("userinfo_endpoint", "Userinfo endpoint"),
                            ("id_token", "ID token"),
                        ],
                        default="userinfo_endpoint",
                        help_text="Indicates the source from which the user information claims should be extracted.",
                        max_length=100,
                        verbose_name="user information claims extracted from",
                    ),
                ),
                (
                    "default_loa",
                    models.CharField(
                        blank=True,
                        choices=[],
                        help_text="Fallback level of assurance, in case no claim value could be extracted.",
                        max_length=100,
                        verbose_name="default LOA",
                    ),
                ),
                (
                    "loa_value_mapping",
                    django_jsonform.models.fields.JSONField(
                        blank=True,
                        default=list,
                        help_text="Level of assurance claim value mappings. Useful if the values in the LOA claim are proprietary, so you can translate them into their standardized identifiers.",
                        verbose_name="loa mapping",
                    ),
                ),
                (
                    "pseudo_identifier_claim",
                    mozilla_django_oidc_db.fields.ClaimField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="claim path segment"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.fields.ClaimFieldDefault(
                            "person_pseudo_identifier"
                        ),
                        help_text="Claim path for PseudoID - unique pseudonymous identifier for natural persons. Use this to identify users across authentication sessions when BSN is not available. Source: eHerkenning/eIDAS urn:etoegang:1.12:EntityConcernedID:PseudoID",
                        size=None,
                        verbose_name="Pseudo identifier claim",
                    ),
                ),
                (
                    "natural_person_bsn_identifier_claim",
                    mozilla_django_oidc_db.fields.ClaimField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="claim path segment"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.fields.ClaimFieldDefault(
                            "person_bsn_identifier"
                        ),
                        help_text="Claim path for BSN (Burgerservicenummer) - National Identification Number. Source: eHerkenning/eIDAS urn:etoegang:1.12:EntityConcernedID:BSN",
                        size=None,
                        verbose_name="BSN identifier claim",
                    ),
                ),
                (
                    "natural_person_first_name_claim",
                    mozilla_django_oidc_db.fields.ClaimField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="claim path segment"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.fields.ClaimFieldDefault(
                            "first_name"
                        ),
                        help_text="Claim path for first/given name of natural person. Source: eHerkenning/eIDAS",
                        size=None,
                        verbose_name="First name claim",
                    ),
                ),
                (
                    "natural_person_family_name_claim",
                    mozilla_django_oidc_db.fields.ClaimField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="claim path segment"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.fields.ClaimFieldDefault(
                            "family_name"
                        ),
                        help_text="Claim path for family name/surname of natural person. Source: eHerkenning/eIDAS",
                        size=None,
                        verbose_name="Family name claim",
                    ),
                ),
                (
                    "natural_person_date_of_birth_claim",
                    mozilla_django_oidc_db.fields.ClaimField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="claim path segment"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.fields.ClaimFieldDefault(
                            "birthdate"
                        ),
                        help_text="Claim path for date of birth in format YYYY-MM-DD. Source: eHerkenning/eIDAS",
                        size=None,
                        verbose_name="Date of birth claim",
                    ),
                ),
                (
                    "legal_entity_identifier_claim",
                    mozilla_django_oidc_db.fields.ClaimField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="claim path segment"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.fields.ClaimFieldDefault(
                            "company_identifier"
                        ),
                        help_text="Claim path for legal entity identifier - additional identifier for legal entities. Source: urn:etoegang:1.11:EntityConcernedID:eIDASLegalIdentifier",
                        size=None,
                        verbose_name="Legal entity identifier claim",
                    ),
                ),
                (
                    "company_name_claim",
                    mozilla_django_oidc_db.fields.ClaimField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="claim path segment"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.fields.ClaimFieldDefault(
                            "company_name"
                        ),
                        help_text="Claim path for company/organization legal name. Source: eIDAS urn:etoegang:1.12:EntityConcernedID:LegalName",
                        size=None,
                        verbose_name="Company name claim",
                    ),
                ),
                (
                    "loa_claim",
                    mozilla_django_oidc_db.fields.ClaimField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="claim path segment"
                        ),
                        blank=True,
                        default=mozilla_django_oidc_db.fields.ClaimFieldDefault("acr"),
                        help_text="Claim path for Level of Assurance (LoA) value. Indicates the authentication strength/security level. Source: eIDAS",
                        size=None,
                        verbose_name="Level of Assurance (LoA) claim",
                    ),
                ),
            ],
            options={
                "verbose_name": "eIDAS OIDC configuration",
            },
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_when_not_digid_or_eherkenning",
        ),
        migrations.AddField(
            model_name="user",
            name="eidas_company_id",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="EIDAS Company ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="eidas_pseudo_id",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="EIDAS Pseudo ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("default", "E-mail en Wachtwoord"),
                    ("digid", "DigiD"),
                    ("eherkenning", "eHerkenning"),
                    ("oidc", "OpenId connect"),
                    ("eidas_person_bsn", "EIDAS person with BSN"),
                    ("eidas_person_pseudo_id", "EIDAS person with Pseudo ID"),
                    ("eidas_company", "EIDAS company with Company ID"),
                ],
                default="default",
                max_length=250,
                verbose_name="Login type",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("login_type", "default")),
                fields=("email",),
                name="unique_email_for_regular_users",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("eidas_pseudo_id__exact", ""),
                    (
                        "login_type__in",
                        ["eidas_person_bsn", "eidas_person_pseudo_id", "eidas_company"],
                    ),
                    _negated=True,
                ),
                name="eidas_user_requires_pseudo_id",
                violation_error_message="Users with eIDAS login types must have a value set for the eIDAS pseudo identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("login_type", "eidas_person_bsn"),
                    ("login_type", "eidas_person_pseudo_id"),
                    ("login_type", "eidas_company"),
                    _connector="OR",
                ),
                fields=("eidas_pseudo_id",),
                name="eidas_pseudo_id_unique_for_eidas_login_types",
                violation_error_message="The eIDAS pseudo identifier must be unique across all eIDAS login types",
            ),
        ),
    ]
