# Generated by Django 5.2.14 on 2026-06-15 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0092_openideidasconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "E-mailadres"), ("phone", "Telefoonnummer")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("value", models.CharField(max_length=254, verbose_name="Value")),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("default", "E-mail en Wachtwoord"),
                            ("digid", "DigiD"),
                            ("eherkenning", "eHerkenning"),
                            ("oidc", "OpenId connect"),
                            ("eidas_person_bsn", "EIDAS person with BSN"),
                            ("eidas_person_pseudo_id", "EIDAS person with Pseudo ID"),
                            ("eidas_company", "EIDAS company with Company ID"),
                        ],
                        max_length=50,
                        verbose_name="Login type",
                    ),
                ),
                (
                    "is_standard_for_type",
                    models.BooleanField(
                        default=False, verbose_name="Is standard for type"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital address",
                "verbose_name_plural": "Digital addresses",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.digitaladdress",
                verbose_name="Preferred digital address",
            ),
        ),
        migrations.AddConstraint(
            model_name="digitaladdress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("login_type", "default"), ("type", "email")),
                fields=("value",),
                name="unique_email_digital_address_for_regular_users",
            ),
        ),
        migrations.AddConstraint(
            model_name="digitaladdress",
            constraint=models.UniqueConstraint(
                fields=("user", "type", "value"),
                name="unique_digital_address_per_user_type_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="digitaladdress",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_standard_for_type=True),
                fields=("user", "type"),
                name="unique_standard_digital_address_per_user_type",
            ),
        ),
    ]
