# Generated by Django 5.2.14 on 2026-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0092_openideidasconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="infix",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Infix"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Last name"
            ),
        ),
    ]
