# Generated by Django 5.2.14 on 2026-06-11 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0094_backfill_digitaladdress_from_user_flat_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="check_alternative_phonenumber_differs_from_primary_phonenumber",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="phonenumber_alt_requires_phonenumber_primary",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phonenumber_alternative",
        ),
    ]
