# Generated by Django 5.2.14 on 2026-07-02 09:53
from django.db import migrations

from digid_eherkenning.oidc.migrations_operations import (
    MoveDigiDDataOperation,
    MoveEHerkenningDataOperation,
)

# Hardcoded rather than imported from open_inwoner.accounts.oidc_plugins.constants:
# migrations must be frozen in time and not depend on app code that may change.
OIDC_DIGID_IDENTIFIER = "oidc-digid"
OIDC_EH_IDENTIFIER = "oidc-eherkenning"
OIDC_EIDAS_IDENTIFIER = "oidc-eidas"


def _migrate_eidas_forward(apps, schema_editor):
    """
    Move the OpenIDEIDASConfig singleton into an OIDCClient + OIDCProvider.

    Mirrors digid_eherkenning.oidc.migrations_operations.migrate_config_forward,
    but for our own eIDAS config model and its claim-field names.
    """
    OpenIDEIDASConfig = apps.get_model("accounts", "OpenIDEIDASConfig")
    OIDCClient = apps.get_model("mozilla_django_oidc_db", "OIDCClient")
    OIDCProvider = apps.get_model("mozilla_django_oidc_db", "OIDCProvider")

    old_config = OpenIDEIDASConfig.objects.first()
    if old_config is None:
        return

    provider, _ = OIDCProvider.objects.get_or_create(
        identifier=f"{OIDC_EIDAS_IDENTIFIER}-provider",
        defaults={
            "oidc_op_discovery_endpoint": old_config.oidc_op_discovery_endpoint,
            "oidc_op_jwks_endpoint": old_config.oidc_op_jwks_endpoint,
            "oidc_op_authorization_endpoint": old_config.oidc_op_authorization_endpoint,
            "oidc_op_token_endpoint": old_config.oidc_op_token_endpoint,
            "oidc_op_user_endpoint": old_config.oidc_op_user_endpoint,
            "oidc_op_logout_endpoint": old_config.oidc_op_logout_endpoint,
            "oidc_token_use_basic_auth": old_config.oidc_token_use_basic_auth,
            "oidc_use_nonce": old_config.oidc_use_nonce,
            "oidc_nonce_size": old_config.oidc_nonce_size,
            "oidc_state_size": old_config.oidc_state_size,
        },
    )
    OIDCClient.objects.update_or_create(
        identifier=OIDC_EIDAS_IDENTIFIER,
        defaults={
            "enabled": old_config.enabled,
            "oidc_provider": provider,
            "oidc_rp_client_id": old_config.oidc_rp_client_id,
            "oidc_rp_client_secret": old_config.oidc_rp_client_secret,
            "oidc_rp_sign_algo": old_config.oidc_rp_sign_algo,
            "oidc_rp_scopes_list": old_config.oidc_rp_scopes_list,
            "oidc_rp_idp_sign_key": old_config.oidc_rp_idp_sign_key,
            "oidc_keycloak_idp_hint": old_config.oidc_keycloak_idp_hint,
            "userinfo_claims_source": old_config.userinfo_claims_source,
            "options": {
                "loa_settings": {
                    "claim_path": old_config.loa_claim,
                    "default": old_config.default_loa,
                    "value_mapping": old_config.loa_value_mapping,
                },
                "identity_settings": {
                    "legal_subject_pseudo_identifier_claim_path": old_config.pseudo_identifier_claim,
                    "legal_subject_bsn_identifier_claim_path": old_config.natural_person_bsn_identifier_claim,
                    "legal_subject_first_name_claim_path": old_config.natural_person_first_name_claim,
                    "legal_subject_family_name_claim_path": old_config.natural_person_family_name_claim,
                    "legal_subject_date_of_birth_claim_path": old_config.natural_person_date_of_birth_claim,
                    "legal_entity_identifier_claim_path": old_config.legal_entity_identifier_claim,
                    "company_name_claim_path": old_config.company_name_claim,
                },
            },
        },
    )


def _migrate_eidas_backward(apps, schema_editor):
    """
    Recreate the OpenIDEIDASConfig singleton from the OIDCClient + OIDCProvider.

    Runs after the DeleteModel is reversed (which recreates the table).
    """
    OpenIDEIDASConfig = apps.get_model("accounts", "OpenIDEIDASConfig")
    OIDCClient = apps.get_model("mozilla_django_oidc_db", "OIDCClient")

    client = (
        OIDCClient.objects.select_related("oidc_provider")
        .filter(identifier=OIDC_EIDAS_IDENTIFIER)
        .first()
    )
    if client is None or client.oidc_provider is None:
        return

    options = client.options or {}
    loa_settings = options.get("loa_settings", {})
    identity_settings = options.get("identity_settings", {})
    provider = client.oidc_provider

    OpenIDEIDASConfig.objects.create(
        enabled=client.enabled,
        # Provider settings
        oidc_op_discovery_endpoint=provider.oidc_op_discovery_endpoint,
        oidc_op_jwks_endpoint=provider.oidc_op_jwks_endpoint,
        oidc_op_authorization_endpoint=provider.oidc_op_authorization_endpoint,
        oidc_op_token_endpoint=provider.oidc_op_token_endpoint,
        oidc_op_user_endpoint=provider.oidc_op_user_endpoint,
        oidc_op_logout_endpoint=provider.oidc_op_logout_endpoint,
        oidc_token_use_basic_auth=provider.oidc_token_use_basic_auth,
        oidc_use_nonce=provider.oidc_use_nonce,
        oidc_nonce_size=provider.oidc_nonce_size,
        oidc_state_size=provider.oidc_state_size,
        # Client settings
        oidc_rp_client_id=client.oidc_rp_client_id,
        oidc_rp_client_secret=client.oidc_rp_client_secret,
        oidc_rp_sign_algo=client.oidc_rp_sign_algo,
        oidc_rp_scopes_list=client.oidc_rp_scopes_list,
        oidc_rp_idp_sign_key=client.oidc_rp_idp_sign_key,
        oidc_keycloak_idp_hint=client.oidc_keycloak_idp_hint,
        userinfo_claims_source=client.userinfo_claims_source,
        # Options -> claim fields
        loa_claim=loa_settings.get("claim_path", []),
        default_loa=loa_settings.get("default", ""),
        loa_value_mapping=loa_settings.get("value_mapping", []),
        pseudo_identifier_claim=identity_settings.get(
            "legal_subject_pseudo_identifier_claim_path", []
        ),
        natural_person_bsn_identifier_claim=identity_settings.get(
            "legal_subject_bsn_identifier_claim_path", []
        ),
        natural_person_first_name_claim=identity_settings.get(
            "legal_subject_first_name_claim_path", []
        ),
        natural_person_family_name_claim=identity_settings.get(
            "legal_subject_family_name_claim_path", []
        ),
        natural_person_date_of_birth_claim=identity_settings.get(
            "legal_subject_date_of_birth_claim_path", []
        ),
        legal_entity_identifier_claim=identity_settings.get(
            "legal_entity_identifier_claim_path", []
        ),
        company_name_claim=identity_settings.get("company_name_claim_path", []),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0097_digitaladdress_ordering"),
        # OIDCClient / OIDCProvider tables must exist before we can move data into them.
        ("mozilla_django_oidc_db", "0006_oidcprovider_oidcclient"),
        # The old DigiDConfig / EHerkenningConfig models (and their fields) must still
        # be present so the move operations can read them.
        (
            "digid_eherkenning_oidc_generics",
            "0009_remove_digidconfig_oidc_exempt_urls_and_more",
        ),
    ]

    # Our proxy models (OpenIDDigiDConfig / OpenIDEHerkenningConfig) inherit from the
    # digid_eherkenning models that migration 0010 deletes. We must delete our proxies
    # (and move the data) BEFORE 0010 runs, otherwise the proxy bases can no longer be
    # resolved when rendering migration state (InvalidBasesError).
    run_before = [
        (
            "digid_eherkenning_oidc_generics",
            "0010_delete_digidconfig_delete_digidmachtigenconfig_and_more",
        ),
    ]

    operations = [
        # Move existing config data into the new generic OIDCClient/OIDCProvider models.
        MoveDigiDDataOperation(identifier=OIDC_DIGID_IDENTIFIER),
        MoveEHerkenningDataOperation(identifier=OIDC_EH_IDENTIFIER),
        migrations.RunPython(_migrate_eidas_forward, _migrate_eidas_backward),
        # Now the data is preserved, drop the old config models.
        migrations.DeleteModel(
            name="OpenIDEIDASConfig",
        ),
        migrations.DeleteModel(
            name="OpenIDDigiDConfig",
        ),
        migrations.DeleteModel(
            name="OpenIDEHerkenningConfig",
        ),
    ]
