# Generated by Django 5.2.14 on 2026-07-07 10:56

from django.db import migrations

import privates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0098_delete_openideidasconfig_delete_openiddigidconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="file",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="The document that is uploaded to the file",
                null=True,
                upload_to="",
                verbose_name="Add a file",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=privates.fields.PrivateMediaFileField(
                upload_to="", verbose_name="File"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="The file that is attached to the message",
                null=True,
                upload_to="",
                verbose_name="File",
            ),
        ),
    ]
