# Generated by Django 4.2.18 on 2025-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TravelDocumentsConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Travel documents configuration",
            },
        ),
    ]
