# Generated by Django 4.2.18 on 2025-03-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traveldocumentsconfig",
            name="test",
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="id_card_appointment_url",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="id_card_info_url",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="id_card_online_inquiry_url",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="id_card_report_missing_url",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="national_passport_appointment_url",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="national_passport_info_url",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="national_passport_online_inquiry_url",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="national_passport_report_missing_url",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
