# Generated by Django 4.2.18 on 2025-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_documents", "0002_remove_traveldocumentsconfig_test_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_appointment_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Appointment url"
            ),
        ),
    ]
