# Generated by Django 4.2.18 on 2025-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "travel_documents",
            "0004_alter_traveldocumentsconfig_id_card_appointment_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="business_passport_appointment_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Appointment URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="business_passport_info_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="More information URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="business_passport_online_inquiry_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Online inquiry URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="business_passport_report_missing_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Report missing URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="second_business_passport_appointment_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Appointment URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="second_business_passport_info_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="More information URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="second_business_passport_online_inquiry_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Online inquiry URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="second_business_passport_report_missing_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Report missing URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="second_passport_appointment_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Appointment URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="second_passport_info_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="More information URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="second_passport_online_inquiry_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Online inquiry URL"
            ),
        ),
        migrations.AddField(
            model_name="traveldocumentsconfig",
            name="second_passport_report_missing_url",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Report missing URL"
            ),
        ),
    ]
