# Generated by Django 4.2.18 on 2025-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "travel_documents",
            "0005_traveldocumentsconfig_business_passport_appointment_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_appointment_url",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Appointment URL"
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_info_url",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="More information URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_online_inquiry_url",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Online inquiry URL"
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_report_missing_url",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Report missing URL"
            ),
        ),
    ]
