# Generated by Django 4.2.18 on 2025-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "travel_documents",
            "0008_alter_traveldocumentsconfig_national_passport_appointment_url",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="business_passport_appointment_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can request an appointment for this document.",
                max_length=250,
                null=True,
                verbose_name="Appointment URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="business_passport_info_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can see more information about this document.",
                max_length=250,
                null=True,
                verbose_name="More information URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="business_passport_online_inquiry_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can make a new online inquiry for this document.",
                max_length=250,
                null=True,
                verbose_name="Online inquiry URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="business_passport_report_missing_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can report this document as missing.",
                max_length=250,
                null=True,
                verbose_name="Report missing URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="id_card_appointment_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can request an appointment for this document.",
                max_length=250,
                null=True,
                verbose_name="Appointment URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="id_card_info_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can see more information about this document.",
                max_length=250,
                null=True,
                verbose_name="More information URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="id_card_online_inquiry_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can make a new online inquiry for this document.",
                max_length=250,
                null=True,
                verbose_name="Online inquiry URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="id_card_report_missing_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can report this document as missing.",
                max_length=250,
                null=True,
                verbose_name="Report missing URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_appointment_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can request an appointment for this document.",
                max_length=250,
                null=True,
                verbose_name="Appointment URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_info_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can see more information about this document.",
                max_length=250,
                null=True,
                verbose_name="More information URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_online_inquiry_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can make a new online inquiry for this document.",
                max_length=250,
                null=True,
                verbose_name="Online inquiry URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="national_passport_report_missing_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can report this document as missing.",
                max_length=250,
                null=True,
                verbose_name="Report missing URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="second_business_passport_appointment_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can request an appointment for this document.",
                max_length=250,
                null=True,
                verbose_name="Appointment URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="second_business_passport_info_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can see more information about this document.",
                max_length=250,
                null=True,
                verbose_name="More information URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="second_business_passport_online_inquiry_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can make a new online inquiry for this document.",
                max_length=250,
                null=True,
                verbose_name="Online inquiry URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="second_business_passport_report_missing_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can report this document as missing.",
                max_length=250,
                null=True,
                verbose_name="Report missing URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="second_passport_appointment_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can request an appointment for this document.",
                max_length=250,
                null=True,
                verbose_name="Appointment URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="second_passport_info_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can see more information about this document.",
                max_length=250,
                null=True,
                verbose_name="More information URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="second_passport_online_inquiry_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can make a new online inquiry for this document.",
                max_length=250,
                null=True,
                verbose_name="Online inquiry URL",
            ),
        ),
        migrations.AlterField(
            model_name="traveldocumentsconfig",
            name="second_passport_report_missing_url",
            field=models.CharField(
                blank=True,
                help_text="Links to a page where the user can report this document as missing.",
                max_length=250,
                null=True,
                verbose_name="Report missing URL",
            ),
        ),
    ]
