# Generated by Django 3.2.15 on 2023-06-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simple_certmanager", "0002_alter_certificate_private_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoapService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable label to identify services",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the service to connect to.",
                        verbose_name="URL",
                    ),
                ),
                (
                    "client_certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The SSL certificate file used for client identification. If left empty, mutual TLS is disabled.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soap_services_client",
                        to="simple_certmanager.certificate",
                    ),
                ),
                (
                    "server_certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The SSL/TLS certificate of the server",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soap_services_server",
                        to="simple_certmanager.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "SOAP service",
                "verbose_name_plural": "SOAP services",
            },
        ),
    ]
