# Generated by Django 3.2.15 on 2023-08-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soapservice",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Base URL of the service to connect to.",
                verbose_name="URL",
            ),
        ),
    ]
