# Generated by Django 5.2.11 on 2026-02-08 23:47
# Squashed migration for configurations app - combines 0001 through 0096

import functools

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ckeditor.fields
import colorfield.fields
import django_jsonform.models.fields
import django_prosemirror.fields
import django_prosemirror.schema.types
import filer.fields.image

import open_inwoner.configurations.models
import open_inwoner.configurations.validators
import open_inwoner.utils.fields
import open_inwoner.utils.files
import open_inwoner.utils.migration_operations
import open_inwoner.utils.validators


# Data migration functions (inlined from original migrations)
def copy_setting_from_openzaak_config(apps, _):
    """Copy eHerkenning setting from OpenZaakConfig (0075)."""
    OpenZaakConfig = apps.get_model("openzaak", "OpenZaakConfig")
    SiteConfiguration = apps.get_model("configurations", "SiteConfiguration")

    try:
        openzaak_config = OpenZaakConfig.objects.get()
    except OpenZaakConfig.DoesNotExist:
        return

    try:
        site_config = SiteConfiguration.objects.get()
    except SiteConfiguration.DoesNotExist:
        return

    if hasattr(openzaak_config, "enable_eherkenning_for_eenmanszaak"):
        site_config.enable_eherkenning_for_eenmanszaak = (
            openzaak_config.enable_eherkenning_for_eenmanszaak
        )
        site_config.save(update_fields=["enable_eherkenning_for_eenmanszaak"])


def create_partial_admin_edit_permissions(apps, _):
    """Create custom permissions for partial admin editing (0085)."""
    SiteConfiguration = apps.get_model("configurations", "SiteConfiguration")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    siteconfig_ct = ContentType.objects.get_for_model(SiteConfiguration)

    for codename, name in (
        ("siteconfig_fieldset_color", "Can edit colors"),
        ("siteconfig_fieldset_images", "Can edit images"),
        ("siteconfig_fieldset_warning_banner", "Can edit warning banner"),
        ("siteconfig_fieldset_page_texts", "Can edit page texts"),
        ("siteconfig_fieldset_help_texts", "Can edit help texts"),
    ):
        Permission.objects.get_or_create(
            codename=codename,
            content_type=siteconfig_ct,
            defaults={"name": name},
        )


def delete_partial_admin_edit_permissions(apps, _):
    """Delete custom permissions (reverse of 0085)."""
    Permission = apps.get_model("auth", "Permission")

    for codename in (
        "siteconfig_fieldset_color",
        "siteconfig_fieldset_images",
        "siteconfig_fieldset_warning_banner",
        "siteconfig_fieldset_page_texts",
        "siteconfig_fieldset_help_texts",
    ):
        Permission.objects.filter(codename=codename).delete()


class Migration(migrations.Migration):
    replaces = [
        ("configurations", "0001_initial"),
        ("configurations", "0002_siteconfiguration_hero_image_login"),
        ("configurations", "0003_auto_20211210_1254"),
        ("configurations", "0002_auto_20211215_1410"),
        (
            "configurations",
            "0004_merge_0002_auto_20211215_1410_0003_auto_20211210_1254",
        ),
        ("configurations", "0005_auto_20220110_1042"),
        ("configurations", "0006_auto_20220117_1626"),
        ("configurations", "0007_auto_20220202_1835"),
        ("configurations", "0007_auto_20220202_1307"),
        (
            "configurations",
            "0008_merge_0007_auto_20220202_1307_0007_auto_20220202_1835",
        ),
        ("configurations", "0009_siteconfiguration_show_cases"),
        ("configurations", "0009_auto_20220218_1359"),
        ("configurations", "0010_merge_20220228_1623"),
        ("configurations", "0009_auto_20220215_1428"),
        ("configurations", "0011_merge_20220302_1245"),
        (
            "configurations",
            "0010_merge_0009_auto_20220215_1428_0009_auto_20220218_1359",
        ),
        ("configurations", "0012_merge_20220303_1128"),
        ("configurations", "0012_merge_20220302_1815"),
        ("configurations", "0013_merge_20220311_1841"),
        ("configurations", "0013_merge_20220309_1710"),
        ("configurations", "0014_merge_20220314_1716"),
        ("configurations", "0015_siteconfiguration_show_product_finder"),
        ("configurations", "0016_alter_siteconfigurationpage_options"),
        ("configurations", "0017_auto_20220330_1436"),
        ("configurations", "0018_auto_20220629_1504"),
        ("configurations", "0019_auto_20220704_1002"),
        ("configurations", "0020_siteconfiguration_login_show"),
        ("configurations", "0021_siteconfiguration_more_titles"),
        ("configurations", "0022_siteconfiguration_more_text"),
        (
            "configurations",
            "0023_rename_home_questionnaire_subtitle_siteconfiguration_home_questionnaire_intro",
        ),
        ("configurations", "0024_alter_siteconfiguration_home_questionnaire_intro"),
        (
            "configurations",
            "0025_rename_select_questionnaire_subtitle_siteconfiguration_select_questionnaire_intro",
        ),
        ("configurations", "0026_alter_siteconfiguration_select_questionnaire_intro"),
        ("configurations", "0027_siteconfiguration_show_plans"),
        ("configurations", "0028_siteconfiguration_show_actions"),
        ("configurations", "0029_auto_20221221_1636"),
        ("configurations", "0030_auto_20230120_1331"),
        ("configurations", "0031_siteconfiguration_siteimprove_id"),
        ("configurations", "0032_siteconfiguration_favicon"),
        ("configurations", "0033_alter_siteconfiguration_favicon"),
        ("configurations", "0034_siteconfiguration_footer_visiting_phonenumber"),
        ("configurations", "0035_alter_siteconfiguration_footer_visiting_phonenumber"),
        ("configurations", "0034_siteconfiguration_plans_banner"),
        ("configurations", "0036_merge_20230303_1004"),
        ("configurations", "0037_auto_20230403_1301"),
        ("configurations", "0038_auto_20230404_1745"),
        ("configurations", "0039_alter_siteconfiguration_hero_image_login"),
        ("configurations", "0040_auto_20230503_1417"),
        ("configurations", "0041_siteconfiguration_redirect_to"),
        ("configurations", "0042_siteconfiguration_login_2fa_sms"),
        ("configurations", "0043_siteconfiguration_allow_messages_file_sharing"),
        ("configurations", "0044_siteconfiguration_openid_display"),
        ("configurations", "0045_alter_siteconfiguration_footer_visiting_phonenumber"),
        ("configurations", "0046_siteconfiguration_cookie_consent"),
        (
            "configurations",
            "0047_siteconfiguration_hide_categories_from_anonymous_users",
        ),
        ("configurations", "0048_auto_20230816_1255"),
        ("configurations", "0049_siteconfiguration_extra_css"),
        ("configurations", "0050_siteconfig_warning_banner"),
        ("configurations", "0049_auto_20230821_1523"),
        ("configurations", "0051_merge_20230907_1800"),
        ("configurations", "0052_siteconfiguration_search_filters"),
        ("configurations", "0052_siteconfiguration_registration_text"),
        ("configurations", "0053_merge_20230928_1457"),
        ("configurations", "0054_siteconfiguration_display_social"),
        ("configurations", "0055_siteconfiguration_eherkenning_enabled"),
        ("configurations", "0056_alter_siteconfiguration_eherkenning_enabled"),
        ("configurations", "0057_siteconfiguration_theme_stylesheet"),
        ("configurations", "0058_siteconfiguration_recipients_email_digest"),
        ("configurations", "0058_customfontset"),
        ("configurations", "0059_merge_20240129_1645"),
        ("configurations", "0060_auto_20240208_1426"),
        ("configurations", "0059_siteconfiguration_email_logo"),
        ("configurations", "0061_merge_20240214_1308"),
        ("configurations", "0059_alter_siteconfigurationpage_options"),
        ("configurations", "0062_merge_20240215_1501"),
        ("configurations", "0062_merge_20240214_1644"),
        ("configurations", "0063_merge_20240216_1622"),
        ("configurations", "0064_auto_20240304_1200"),
        ("configurations", "0065_siteconfiguration_kcm_survey_link_text_and_more"),
        ("configurations", "0065_siteconfiguration_email_verification_required"),
        ("configurations", "0066_merge_20240405_1100"),
        ("configurations", "0067_alter_siteconfiguration_warning_banner_text"),
        ("configurations", "0068_siteconfiguration_contactmoment_contact_form"),
        ("configurations", "0068_change_siteconfiguration_notifications"),
        ("configurations", "0069_merge_20240724_0945"),
        ("configurations", "0070_siteconfiguration_enable_notification_channels"),
        ("configurations", "0071_correct_siteconfiguration"),
        (
            "configurations",
            "0072_alter_siteconfiguration_notifications_actions_enabled_and_more",
        ),
        (
            "configurations",
            "0073_alter_siteconfiguration_notifications_actions_enabled",
        ),
        ("configurations", "0074_alter_siteconfiguration_accent_color_and_more"),
        ("configurations", "0075_siteconfiguration_enable_eherkenning_for_eenmanszaak"),
        ("configurations", "0076_siteconfiguration_enable_crawler_indexing"),
        ("configurations", "0077_config_rich_editor_login_page"),
        ("configurations", "0078_siteconfiguration_security_txt_redirect_target"),
        ("configurations", "0079_search_zero_results_text"),
        ("configurations", "0080_siteconfiguration_include_cms_pages_in_search_index"),
        ("configurations", "0081_alter_siteconfigurationpage_options_and_more"),
        ("configurations", "0082_alter_siteconfigurationpage_cms_page"),
        ("configurations", "0083_custom_javascript"),
        ("configurations", "0084_siteconfiguration_email_verification_message"),
        ("configurations", "0085_create_partial_admin_edit_permissions"),
        ("configurations", "0086_siteconfiguration_warning_banner_text_schema_1"),
        ("configurations", "0087_siteconfiguration_warning_banner_text_data"),
        ("configurations", "0088_siteconfiguration_warning_banner_text_schema_2"),
        ("configurations", "0089_siteconfiguration_login_text_schema_1"),
        ("configurations", "0090_siteconfiguration_login_text_data"),
        ("configurations", "0091_siteconfiguration_login_text_schema_2"),
        ("configurations", "0092_siteconfiguration_search_zero_results_text_schema_1"),
        ("configurations", "0093_siteconfiguration_search_zero_results_text_data"),
        ("configurations", "0094_siteconfiguration_search_zero_results_text_schema_2"),
        ("configurations", "0095_alter_siteconfiguration_login_text_and_more"),
        ("configurations", "0096_siteconfiguration_search_enabled"),
    ]

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("filer", "__first__"),
        ("flatpages", "0001_initial"),
        ("openzaak", "0063_alter_openzaakconfig_show_cases_without_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the municipality", max_length=255
                    ),
                ),
                (
                    "primary_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The primary color of the municipality's site",
                        max_length=18,
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The secondary color of the municipality's site",
                        max_length=18,
                    ),
                ),
                (
                    "accent_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The accent color of the municipality's site",
                        max_length=18,
                        verbose_name="Accent color",
                    ),
                ),
                (
                    "logo",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        help_text="Logo of the municipality",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_logo",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "hero_image_login",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        help_text="Hero image on the login page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hero_image_login",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "login_allow_registration",
                    models.BooleanField(
                        default=False,
                        help_text="Wanneer deze optie uit staat is het enkel toegestaan om met DigiD in te loggen. Zet deze instelling aan om ook het inloggen met gebruikersnaam/wachtwoord en het aanmelden zonder DigiD toe te staan.",
                        verbose_name="Sta lokale registratie toe",
                    ),
                ),
                (
                    "login_text",
                    models.TextField(
                        blank=True,
                        help_text="Deze tekst wordt getoond op de login pagina.",
                        verbose_name="Login tekst",
                    ),
                ),
                (
                    "accent_font_color",
                    models.CharField(
                        choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                        default="#4B4B4B",
                        help_text="The font color for when the background is the accent color",
                        max_length=50,
                        verbose_name="Accent font color",
                    ),
                ),
                (
                    "primary_font_color",
                    models.CharField(
                        choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                        default="#FFFFFF",
                        help_text="The font color for when the background is the primary color",
                        max_length=50,
                    ),
                ),
                (
                    "secondary_font_color",
                    models.CharField(
                        choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                        default="#FFFFFF",
                        help_text="The font color for when the background is the secondary color",
                        max_length=50,
                    ),
                ),
                (
                    "footer_mailing_intro",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Mailing intro text on the footer section.",
                        verbose_name="Mailing details",
                    ),
                ),
                (
                    "footer_mailing_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mailing title on the footer section.",
                        max_length=255,
                        verbose_name="Footer mailing title",
                    ),
                ),
                (
                    "footer_visiting_intro",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Visiting intro text on the footer section.",
                        verbose_name="Visiting details",
                    ),
                ),
                (
                    "footer_visiting_map",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Visiting address in google maps on the footer section.",
                        max_length=255,
                        verbose_name="Footer visiting map",
                    ),
                ),
                (
                    "footer_visiting_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Visiting title on the footer section.",
                        max_length=255,
                        verbose_name="Footer visiting title",
                    ),
                ),
                (
                    "home_map_intro",
                    models.TextField(
                        blank=True,
                        help_text="Map's intro text on the home page.",
                        verbose_name="Home map intro",
                    ),
                ),
                (
                    "home_map_title",
                    models.CharField(
                        default="In de buurt",
                        help_text="Map's title on the home page.",
                        max_length=255,
                        verbose_name="Home map title",
                    ),
                ),
                (
                    "home_theme_intro",
                    models.TextField(
                        blank=True,
                        help_text="Theme's intro text on the home page.",
                        verbose_name="Home theme's intro",
                    ),
                ),
                (
                    "home_theme_title",
                    models.CharField(
                        default="Thema's",
                        help_text="Theme's title on the home page.",
                        max_length=255,
                        verbose_name="Home theme's title",
                    ),
                ),
                (
                    "home_welcome_intro",
                    models.TextField(
                        blank=True,
                        help_text="Welcome intro text on the home page.",
                        verbose_name="Home welcome intro",
                    ),
                ),
                (
                    "home_welcome_title",
                    models.CharField(
                        default="Welcome",
                        help_text="Welcome title on the home page.",
                        max_length=255,
                        verbose_name="Home welcome title",
                    ),
                ),
                (
                    "theme_intro",
                    models.TextField(
                        blank=True,
                        help_text="Theme's intro text on the theme's page.",
                        verbose_name="Theme's intro",
                    ),
                ),
                (
                    "theme_title",
                    models.CharField(
                        default="Thema's",
                        help_text="Theme's title on the theme's page.",
                        max_length=255,
                        verbose_name="Theme's title",
                    ),
                ),
                (
                    "account_help_text",
                    models.TextField(
                        blank=True,
                        default="Op dit scherm ziet u uw persoonlijke profielgegevens en gerelateerde gegevens.",
                        help_text="The help text for the profile page.",
                        verbose_name="Account help",
                    ),
                ),
                (
                    "home_help_text",
                    models.TextField(
                        blank=True,
                        default="Welkom! Op dit scherm vindt u een overzicht van de verschillende thema's en producten & diensten.",
                        help_text="The help text for the home page.",
                        verbose_name="Home help",
                    ),
                ),
                (
                    "product_help_text",
                    models.TextField(
                        blank=True,
                        default="Op dit scherm kunt u de details vinden over het gekozen product of dienst. Afhankelijk van het product kunt u deze direct aanvragen of meer informatie opvragen.",
                        help_text="The help text for the product page.",
                        verbose_name="Product help",
                    ),
                ),
                (
                    "search_help_text",
                    models.TextField(
                        blank=True,
                        default="Op dit scherm kunt u zoeken naar de producten en diensten.",
                        help_text="The help text for the search page.",
                        verbose_name="Search help",
                    ),
                ),
                (
                    "theme_help_text",
                    models.TextField(
                        blank=True,
                        default="Op dit scherm vindt u de verschillende thema's waarvoor wij producten en diensten aanbieden.",
                        help_text="The help text for the theme page.",
                        verbose_name="Theme help",
                    ),
                ),
                (
                    "email_new_message",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send email about each new message the user receives",
                        verbose_name="Send email about a new message",
                    ),
                ),
                (
                    "show_cases",
                    models.BooleanField(
                        default=False,
                        help_text="By default the cases are not shown. If the OpenZaak integration is configured this needs to be set to True.",
                        verbose_name="Show cases",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
        migrations.CreateModel(
            name="SiteConfigurationPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_configurations",
                        to="configurations.siteconfiguration",
                    ),
                ),
                (
                    "flatpage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_flatpages",
                        to="flatpages.flatpage",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="flatpages",
            field=models.ManyToManyField(
                related_name="configurations",
                through="configurations.SiteConfigurationPage",
                to="flatpages.flatpage",
                verbose_name="Flatpages",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image_login",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Deprecated. CMS banner plugin should be used instead.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hero_image_login",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Hero image login",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Logo of the municipality",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_logo",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="name",
            field=models.CharField(
                help_text="The name of the municipality",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="primary_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="The primary color of the municipality's site",
                max_length=18,
                verbose_name="Primary color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="primary_font_color",
            field=models.CharField(
                choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                default="#FFFFFF",
                help_text="The font color for when the background is the primary color",
                max_length=50,
                verbose_name="Primary font color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="secondary_color",
            field=colorfield.fields.ColorField(
                default="#0000FF",
                help_text="The secondary color of the municipality's site",
                max_length=18,
                verbose_name="Secondary color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="secondary_font_color",
            field=models.CharField(
                choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                default="#FFFFFF",
                help_text="The font color for when the background is the secondary color",
                max_length=50,
                verbose_name="Secondary font color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfigurationpage",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_configurations",
                to="configurations.siteconfiguration",
                verbose_name="Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfigurationpage",
            name="flatpage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_flatpages",
                to="flatpages.flatpage",
                verbose_name="Flatpage",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="ga_code",
            field=models.CharField(
                blank=True,
                help_text="Typically looks like 'G-XXXXX'. Supplying this installs Google Analytics.",
                max_length=50,
                verbose_name="Google Analytics code",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="gtm_code",
            field=models.CharField(
                blank=True,
                help_text="Typically looks like 'GTM-XXXX'. Supplying this installs Google Tag Manager.",
                max_length=50,
                verbose_name="Google Tag Manager code",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="matomo_site_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The 'idsite' of the website you're tracking in Matomo.",
                null=True,
                verbose_name="Matomo site ID",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="matomo_url",
            field=models.CharField(
                blank=True,
                help_text="The base URL of your Matomo server, e.g. 'matomo.example.com'.",
                max_length=255,
                verbose_name="Matomo server URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="plan_help_text",
            field=models.TextField(
                blank=True,
                default="Met het onderdeel Samenwerken kunt u samen met uw contactpersonen of begeleider van de gemeente aan de slag om met een samenwerkingsplan uw persoonlijke situatie te verbeteren. Door samen aan uw doelen te werken en acties te omschrijven kunnen we elkaar helpen.",
                help_text="The help text for the plan page.",
                verbose_name="Plan help",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="questionnaire_help_text",
            field=models.TextField(
                blank=True,
                default="Het onderdeel Zelfdiagnose stelt u in staat om met het beantwoorden van enkele vragen een advies te krijgen van de gemeente, met concrete vervolgstappen en producten en diensten. U kunt tevens uw antwoorden en het advies bewaren om met een begeleider van de gemeente te bespreken.",
                help_text="The help text for the questionnaire page.",
                verbose_name="Questionnaire help",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="openid_connect_login_text",
            field=models.CharField(
                default="Login with Azure AD",
                help_text="The text that should display when OpenId connect is set as a login method",
                max_length=250,
                verbose_name="Openid Connect login text",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="openid_connect_logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Logo that can be used for the OpenId connect login method",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oidc_logo",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Openid Connect Logo",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="login_show",
            field=models.BooleanField(
                default=True,
                help_text="Wanneer deze optie uit staat dan kan nog wel worden ingelogd via /accounts/login/ , echter het inloggen is verborgen",
                verbose_name="Toon inlogknop rechts bovenin",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_questionnaire_title",
            field=models.CharField(
                default="Waar bent u naar op zoek?",
                help_text="Questionnaire title on the home page.",
                max_length=255,
                verbose_name="Home page questionaire title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="select_questionnaire_title",
            field=models.CharField(
                default="Keuze zelfdiagnose?",
                help_text="Questionaire selector title on the theme and profile pages.",
                max_length=255,
                verbose_name="Questionaire selector widget title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_product_finder_intro",
            field=models.TextField(
                blank=True,
                default="Met een paar simpele vragen ziet u welke producten passen bij uw situatie",
                help_text="Product finder's intro text on the home page.",
                verbose_name="Home product finder intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_product_finder_title",
            field=models.CharField(
                default="Productzoeker",
                help_text="Product finder's title on the home page.",
                max_length=255,
                verbose_name="Product finder title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="plans_edit_message",
            field=models.CharField(
                default="Hier kunt u uw doel aanpassen",
                help_text="The message when a user edits a goal.",
                max_length=255,
                verbose_name="Edit goal message",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="plans_no_plans_message",
            field=models.CharField(
                default="U heeft nog geen plan gemaakt.",
                help_text="The message in the plans listing when user has no plans.",
                max_length=255,
                verbose_name="No plans message",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_questionnaire_intro",
            field=models.TextField(
                blank=True,
                default="Test met een paar simpele vragen of u recht heeft op een product",
                help_text="Questionnaire intro text on the home page.",
                verbose_name="Home page questionaire intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="plans_intro",
            field=models.TextField(
                blank=True,
                default="Hier werkt u aan uw doelen. Dit doet u samen met uw contactpersoon bij de gemeente. ",
                help_text="The sub-title for the plan page.",
                verbose_name="Plan pages intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="select_questionnaire_intro",
            field=models.TextField(
                blank=True,
                default="Kies hieronder één van de volgende vragenlijsten om de zelfdiagnose te starten.",
                help_text="Questionaire selector intro on the theme and profile pages.",
                verbose_name="Questionaire selector widget intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Footer logo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="footer_logo",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Footer logo",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_logo_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The title - help text of the footer logo.",
                max_length=255,
                verbose_name="Footer logo title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_logo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="The external link for the footer logo.",
                verbose_name="Footer logo link",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="siteimprove_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SiteImprove ID - this can be found in the snippet example, which should contain a URL like '//siteimproveanalytics.com/js/siteanalyze_xxxxx.js'. The xxxxx part is the ID.",
                max_length=10,
                verbose_name="SiteImprove ID",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="favicon",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Image to use as favicon",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favicon",
                to=settings.FILER_IMAGE_MODEL,
                validators=[
                    open_inwoner.utils.validators.FilerExactImageSizeValidator(32, 32)
                ],
                verbose_name="Favicon image (32x32, .png)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="home_help_text",
            field=models.TextField(
                blank=True,
                default="Welkom! Op dit scherm vindt u een overzicht van de verschillende onderwerpen en producten & diensten.",
                help_text="The help text for the home page.",
                verbose_name="Home help",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="home_theme_intro",
            field=models.TextField(
                blank=True,
                help_text="Category's intro text on the home page.",
                verbose_name="Home theme's intro",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="home_theme_title",
            field=models.CharField(
                default="Onderwerpen",
                help_text="Category's title on the home page.",
                max_length=255,
                verbose_name="Home theme's title",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="theme_help_text",
            field=models.TextField(
                blank=True,
                default="Op dit scherm vindt u de verschillende onderwerpen waarvoor wij producten en diensten aanbieden.",
                help_text="The help text for the theme page.",
                verbose_name="Category help",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="theme_intro",
            field=models.TextField(
                blank=True,
                help_text="Category's intro text on the theme's page.",
                verbose_name="Category's intro",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="theme_title",
            field=models.CharField(
                default="Onderwerpen",
                help_text="Category's title on the theme's page.",
                max_length=255,
                verbose_name="Category's title",
            ),
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="show_cases",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="redirect_to",
            field=models.CharField(
                blank=True,
                help_text="Provide a url or a path where the user should be redirected to from the anonymous page. Path example: '/accounts/login/', Url example: 'https://www.example.com'",
                max_length=255,
                null=True,
                verbose_name="Redirect anonymous user to",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="login_2fa_sms",
            field=models.BooleanField(
                default=False,
                help_text="Whether we want the users to be able to log in with 2FA authentication by using an SMS workflow.",
                verbose_name="Login with 2FA-with-SMS",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="allow_messages_file_sharing",
            field=models.BooleanField(
                default=True,
                help_text="Whether file sharing via the messages is allowed or not",
                verbose_name="Allow messages file sharing",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="openid_display",
            field=models.CharField(
                choices=[("admin", "Admin"), ("regular", "Regular user")],
                default="admin",
                help_text="Only selected groups will see the option to login via OpenId.",
                max_length=24,
                validators=[
                    open_inwoner.configurations.validators.validate_oidc_config
                ],
                verbose_name="Show option to login via OpenId",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="cookie_info_text",
            field=models.CharField(
                blank=True,
                default="Wij gebruiken cookies om onze website en dienstverlening te verbeteren.",
                help_text="The text that displays inside the cookie banner. Supplying this makes the cookie banner visible.",
                max_length=255,
                verbose_name="Cookie info text",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="cookie_link_text",
            field=models.CharField(
                blank=True,
                default="Lees meer over ons cookiebeleid.",
                help_text="The text that is displayed as the link to the cookie policy.",
                max_length=255,
                verbose_name="Cookie link text",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="cookie_link_url",
            field=models.CharField(
                blank=True,
                default="/pages/privacyverklaring/",
                help_text="The link to the cookie policy page.",
                max_length=255,
                verbose_name="Privacy page link",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hide_categories_from_anonymous_users",
            field=models.BooleanField(
                default=False,
                help_text="If checked, categories will be hidden from users who are not logged in.",
                verbose_name="Hide categories from anonymous users",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hide_search_from_anonymous_users",
            field=models.BooleanField(
                default=False,
                help_text="If checked, only authenticated users will be able to search the page.",
                verbose_name="Hide search from anonymous users",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="extra_css",
            field=open_inwoner.utils.fields.CSSField(
                blank=True,
                help_text="Additional CSS added to the page. Note only a (safe) subset of CSS properties is supported.",
                verbose_name="Extra CSS",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="warning_banner_background_color",
            field=colorfield.fields.ColorField(
                default="#FFDBAD",
                help_text="The background color for the warning banner",
                max_length=18,
                verbose_name="Warning banner background",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="warning_banner_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the warning banner should be displayed",
                verbose_name="Show warning banner",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="warning_banner_font_color",
            field=colorfield.fields.ColorField(
                default="#000000",
                help_text="The font color for the warning banner",
                max_length=18,
                verbose_name="Warning banner font",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="warning_banner_text",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Text will be displayed on the warning banner",
                verbose_name="Warning banner text",
            ),
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_mailing_intro",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_mailing_title",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_visiting_intro",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_visiting_map",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_visiting_title",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_filter_categories",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show category-checkboxes in order to filter the search result.",
                verbose_name="Add category filter for search results",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_filter_organizations",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show organization-checkboxes in order to filter the search result.",
                verbose_name="Add organization filter for search results",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_filter_tags",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show tag-checkboxes in order to filter the search result.",
                verbose_name="Add tag filter for search results",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="registration_text",
            field=models.TextField(
                blank=True,
                help_text="Deze tekst wordt getoond op de registratie pagina.",
                verbose_name="Registratie tekst",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="display_social",
            field=models.BooleanField(
                default=True,
                help_text="Enable sharing of products on social media (Facebook, LinkedIn...)",
                verbose_name="Display social media buttons",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="eherkenning_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether users can log in with eHerkenning or not. By default, the SAML integration will be used for this, in order to use the OpenID Connect integration, navigate to `OpenID Connect configuration for eHerkenning` and enable it.",
                verbose_name="eHerkenning authentication enabled",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="theme_stylesheet",
            field=models.FileField(
                blank=True,
                help_text="Additional CSS file added to the page.",
                null=True,
                upload_to="themes/",
                validators=[django.core.validators.FileExtensionValidator(["css"])],
                verbose_name="Theme stylesheet",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="recipients_email_digest",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                help_text="The email addresses that should receive a daily report of items requiring attention.",
                size=None,
                verbose_name="recipients email digest",
            ),
        ),
        migrations.CreateModel(
            name="CustomFontSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading_font",
                    open_inwoner.configurations.models.CustomFontField(
                        blank=True,
                        help_text="Upload heading font. TTF font types only.",
                        null=True,
                        storage=open_inwoner.utils.files.OverwriteStorage(),
                        upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_heading,
                        validators=[
                            django.core.validators.FileExtensionValidator(["ttf"])
                        ],
                        verbose_name="Heading font",
                    ),
                ),
                (
                    "site_configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fonts",
                        to="configurations.siteconfiguration",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "body_font_bold",
                    open_inwoner.configurations.models.CustomFontField(
                        blank=True,
                        help_text="Upload bold text body font. TTF font types only.",
                        null=True,
                        storage=open_inwoner.utils.files.OverwriteStorage(),
                        upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_body_bold,
                        validators=[
                            django.core.validators.FileExtensionValidator(["ttf"])
                        ],
                        verbose_name="Body font bold",
                    ),
                ),
                (
                    "body_font_bold_italic",
                    open_inwoner.configurations.models.CustomFontField(
                        blank=True,
                        help_text="Upload bold italic text body font. TTF font types only.",
                        null=True,
                        storage=open_inwoner.utils.files.OverwriteStorage(),
                        upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_body_bold_italic,
                        validators=[
                            django.core.validators.FileExtensionValidator(["ttf"])
                        ],
                        verbose_name="Body font bold italic",
                    ),
                ),
                (
                    "body_font_italic",
                    open_inwoner.configurations.models.CustomFontField(
                        blank=True,
                        help_text="Upload italic text body font. TTF font types only.",
                        null=True,
                        storage=open_inwoner.utils.files.OverwriteStorage(),
                        upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_body_italic,
                        validators=[
                            django.core.validators.FileExtensionValidator(["ttf"])
                        ],
                        verbose_name="Body font italic",
                    ),
                ),
                (
                    "body_font_regular",
                    open_inwoner.configurations.models.CustomFontField(
                        blank=True,
                        help_text="Upload regular text body font. TTF font types only.",
                        null=True,
                        storage=open_inwoner.utils.files.OverwriteStorage(),
                        upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_body,
                        validators=[
                            django.core.validators.FileExtensionValidator(["ttf"])
                        ],
                        verbose_name="Body font regular",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Image to use as logo in email.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logo",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Email logo (.png or .jpg)",
            ),
        ),
        migrations.AlterModelOptions(
            name="siteconfigurationpage",
            options={
                "ordering": ("order",),
                "verbose_name": "Flatpage in the footer",
                "verbose_name_plural": "Flatpages in the footer",
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_page",
            field=models.URLField(
                blank=True,
                help_text="URL of the public contact page of the organization",
                verbose_name="URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_phonenumber",
            field=models.CharField(
                blank=True,
                help_text="The public contact phone number of the organization",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kcm_survey_link_text",
            field=models.CharField(
                blank=True,
                help_text="The text that is displayed on the customer satisfaction survey link",
                max_length=255,
                verbose_name="KCM survey link text",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kcm_survey_link_url",
            field=models.URLField(
                blank=True,
                help_text="The external link for the customer satisfaction survey.",
                verbose_name="KCM survey URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_verification_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether to require users to verify their email address",
                verbose_name="Email verification required",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contactmoment_contact_form_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Display contact form on the questions list page so that users can create new questions",
                verbose_name="Contactmoment contact form",
            ),
        ),
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="email_new_message",
            new_name="notifications_messages_enabled",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="enable_notification_channel_choice",
            field=models.BooleanField(
                default=False,
                help_text="Give users the option to choose how they want to receive notifications (digital and post or digital only)",
                verbose_name="Enable choice of notification channel",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="notifications_cases_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable notifications for cases (if enabled, individual users can still opt out of notifications about case updates, though not of notifications that indicate that an action concerning some case is required)",
                verbose_name="User notifications for cases",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="notifications_messages_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable notifications for messages (if enabled, individual users can still opt out; messages will only be sent if the user also opts in)",
                verbose_name="User notifications for messages",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="notifications_plans_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable notifications for plans (if enabled, individual users can still opt out)",
                verbose_name="User notifications for expiring plans",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="notifications_actions_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable notifications for expiring actions concerning plans (if enabled, individual users can still opt out by disabling notifications for plans)",
                verbose_name="User notifications for expiring actions",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="accent_color",
            field=colorfield.fields.ColorField(
                default="#FF0000",
                help_text="The accent color of the municipality's site",
                max_length=18,
                verbose_name="Accent color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="flatpages",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="configurations",
                through="configurations.SiteConfigurationPage",
                to="flatpages.flatpage",
                verbose_name="Flatpages",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="enable_eherkenning_for_eenmanszaak",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, eenmanszaken may authenticate using eHerkenning and subsequently their kvk nummer will be used to interface with the zaken and klanten backends. If not, an eenmanszaak will be forced to use DigiD, and the user's BSN will be used instead.",
                verbose_name="Allow eenmanszaken to authenticate using eHerkenning",
            ),
        ),
        migrations.RunPython(
            code=copy_setting_from_openzaak_config,
            reverse_code=migrations.RunPython.noop,
            elidable=True,  # Only needed for upgrades, not fresh installs
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="enable_crawler_indexing",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, search engines can index the site",
                verbose_name="Enable indexing by search engines",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="login_text",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Deze tekst wordt getoond op de login pagina.",
                verbose_name="Login tekst",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="security_txt_redirect_target",
            field=models.URLField(
                default="https://www.ncsc.nl/.well-known/security.txt",
                help_text="Link to which ./well-known/security.txt will redirect to",
                verbose_name="Redirect security.txt to",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_zero_results_text",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Text to display for when there are no search results.",
                verbose_name="Text for zero search results",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="include_cms_pages_in_search_index",
            field=models.BooleanField(
                default=False,
                help_text="If checked, CMS pages will be added to the search index and included in search results. Note the change will not take effect until the search index has been refreshed.",
                verbose_name="Make CMS Pages searchable",
            ),
        ),
        migrations.AlterModelOptions(
            name="siteconfigurationpage",
            options={
                "ordering": ("order",),
                "verbose_name": "CMS page in the footer",
                "verbose_name_plural": "CMS pages in the footer",
            },
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="flatpages",
        ),
        migrations.RemoveField(
            model_name="siteconfigurationpage",
            name="flatpage",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="cms_pages",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="configurations",
                through="configurations.SiteConfigurationPage",
                to="cms.page",
                verbose_name="CMS pages",
            ),
        ),
        migrations.AddField(
            model_name="siteconfigurationpage",
            name="cms_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_cms_pages",
                to="cms.page",
                verbose_name="Footer CMS Page",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="custom_javascript",
            field=models.FileField(
                blank=True,
                help_text="Upload a custom JavaScript file (.js) that will be loaded on every page.",
                null=True,
                upload_to="custom_scripts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["js"]
                    ),
                    open_inwoner.configurations.validators.validate_javascript_file,
                ],
                verbose_name="Custom JavaScript",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="custom_javascript_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Let op: Custom JavaScript kan de beveiliging en prestaties van de applicatie negatief beïnvloeden. Door het aanvinken van deze optie bevestig ik dat ik de mogelijke risico’s begrijp en – indien nodig – dit heb afgestemd met de security-afdeling voordat ik deze inlaad. Het aanvinken van deze optie is noodzakelijk om de Javascript daadwerkelijk te tonen.",
                verbose_name="I confirm I understand the risks of adding custom Javascript",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_verification_message",
            field=models.TextField(
                blank=True,
                default="Er is een e-mail verstuurd naar {email}. Klik op de link in de mail om uw e-mailadres te bevestigen. Heeft u geen e-mail ontvangen? Verstuur deze dan nog een keer via onderstaande knop.",
                help_text="The message for the user that they need to verify their email. Use the placeholder {email} to insert the user's email.",
                verbose_name="Email verification message",
            ),
        ),
        migrations.RunPython(
            code=create_partial_admin_edit_permissions,
            reverse_code=delete_partial_admin_edit_permissions,
            # NOT elidable - permissions are needed for fresh installs too
        ),
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="warning_banner_text",
            new_name="warning_banner_text_tmp",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="warning_banner_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
            ),
        ),
        migrations.RunPython(
            code=functools.partial(
                open_inwoner.utils.migration_operations.migrate_to_prosemirror_field,
                *(),
                **{
                    "allowed_node_types": [
                        django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                    ],
                    "app_label": "configurations",
                    "field_name": "warning_banner_text",
                    "model_name": "SiteConfiguration",
                    "use_singleton": True,
                },
            ),
            reverse_code=migrations.RunPython.noop,
            elidable=True,  # Only needed for upgrades, not fresh installs
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="warning_banner_text_tmp",
        ),
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="login_text",
            new_name="login_text_tmp",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="login_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
            ),
        ),
        migrations.RunPython(
            code=functools.partial(
                open_inwoner.utils.migration_operations.migrate_to_prosemirror_field,
                *(),
                **{
                    "allowed_node_types": [
                        django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                    ],
                    "app_label": "configurations",
                    "field_name": "login_text",
                    "model_name": "SiteConfiguration",
                    "use_singleton": True,
                },
            ),
            reverse_code=migrations.RunPython.noop,
            elidable=True,  # Only needed for upgrades, not fresh installs
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="login_text_tmp",
        ),
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="search_zero_results_text",
            new_name="search_zero_results_text_tmp",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_zero_results_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
            ),
        ),
        migrations.RunPython(
            code=functools.partial(
                open_inwoner.utils.migration_operations.migrate_to_prosemirror_field,
                *(),
                **{
                    "allowed_node_types": [
                        django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                    ],
                    "app_label": "configurations",
                    "field_name": "search_zero_results_text",
                    "model_name": "SiteConfiguration",
                    "use_singleton": True,
                },
            ),
            reverse_code=migrations.RunPython.noop,
            elidable=True,  # Only needed for upgrades, not fresh installs
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="search_zero_results_text_tmp",
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="login_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                help_text="Deze tekst wordt getoond op de login pagina.",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Login tekst",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="search_zero_results_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                help_text="Text will be displayed on the warning banner",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Text for zero search results",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="warning_banner_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Warning banner text",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether search functionality is enabled.",
                verbose_name="Enable Search",
            ),
        ),
    ]
