# Generated by Django 3.2.7 on 2021-11-23 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import colorfield.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the municipality", max_length=255
                    ),
                ),
                (
                    "primary_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The primary color of the municipality's site",
                        max_length=18,
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The secondary color of the municipality's site",
                        max_length=18,
                    ),
                ),
                (
                    "accent_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="The accent color of the municipality's site",
                        max_length=18,
                    ),
                ),
                (
                    "logo",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        help_text="Logo of the municipality",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_logo",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
