# Generated by Django 3.2.7 on 2021-12-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="accent_font_color",
            field=models.CharField(
                choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                default="#4B4B4B",
                help_text="The font color for when the background is the accent color",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="primary_font_color",
            field=models.CharField(
                choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                default="#FFFFFF",
                help_text="The font color for when the background is the primary color",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="secondary_font_color",
            field=models.CharField(
                choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                default="#FFFFFF",
                help_text="The font color for when the background is the secondary color",
                max_length=50,
            ),
        ),
    ]
