# Generated by Django 3.2.7 on 2021-12-08 13:25

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image_login',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Hero image on the login page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_image_login', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
