# Generated by Django 3.2.7 on 2021-12-08 13:15

from django.db import migrations

import colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="font_color",
            field=colorfield.fields.ColorField(
                choices=[("#FFFFFF", "white"), ("#000000", "black")],
                default="#FFFFFF",
                max_length=18,
            ),
        ),
    ]
