# Generated by Django 3.2.7 on 2021-12-09 10:15

from django.db import migrations

import colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0002_siteconfiguration_font_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="font_color",
            field=colorfield.fields.ColorField(
                choices=[("#FFFFFF", "white"), ("#000000", "black")],
                default="#FFFFFF",
                help_text="The font color for primary, secondary and accent color changes",
                max_length=18,
            ),
        ),
    ]
