# Generated by Django 3.2.7 on 2022-01-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flatpages", "0001_initial"),
        (
            "configurations",
            "0004_merge_0002_auto_20211215_1410_0003_auto_20211210_1254",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_mailing_intro",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Mailing intro text on the home page.",
                verbose_name="Mailing details",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_mailing_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mailing title on the home page.",
                max_length=255,
                verbose_name="Home mailing title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_map_intro",
            field=models.TextField(
                blank=True,
                help_text="Map's intro text on the home page.",
                verbose_name="Home map intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_map_title",
            field=models.CharField(
                default="In de buurt",
                help_text="Map's title on the home page.",
                max_length=255,
                verbose_name="Home map title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_theme_intro",
            field=models.TextField(
                blank=True,
                help_text="Theme's intro text on the home page.",
                verbose_name="Home theme's intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_theme_title",
            field=models.CharField(
                default="Thema's",
                help_text="Theme's title on the home page.",
                max_length=255,
                verbose_name="Home theme's title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_visiting_intro",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Visiting intro text on the home page.",
                verbose_name="Visiting details",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_visiting_map",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Visiting address in google maps on the home page.",
                max_length=255,
                verbose_name="Home visiting map",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_visiting_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Visiting title on the home page.",
                max_length=255,
                verbose_name="Home visiting title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_welcome_intro",
            field=models.TextField(
                blank=True,
                help_text="Welcome intro text on the home page.",
                verbose_name="Home welcome intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_welcome_title",
            field=models.CharField(
                default="Welcom",
                help_text="Welcome title on the home page.",
                max_length=255,
                verbose_name="Home welcome title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="theme_intro",
            field=models.TextField(
                blank=True,
                help_text="Theme's intro text on the theme's page.",
                verbose_name="Theme's intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="theme_title",
            field=models.CharField(
                default="Thema's",
                help_text="Theme's title on the theme's page.",
                max_length=255,
                verbose_name="Theme's title",
            ),
        ),
        migrations.CreateModel(
            name="SiteConfigurationPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configurations.siteconfiguration",
                    ),
                ),
                (
                    "flatpage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flatpages.flatpage",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="flatpages",
            field=models.ManyToManyField(
                related_name="configurations",
                through="configurations.SiteConfigurationPage",
                to="flatpages.FlatPage",
            ),
        ),
    ]
