# Generated by Django 3.2.7 on 2022-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configurations",
            "0004_merge_0002_auto_20211215_1410_0003_auto_20211210_1254",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="account_help_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for the profile page.",
                verbose_name="Account help",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_help_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for the home page.",
                verbose_name="Home help",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="product_help_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for the product page.",
                verbose_name="Product help",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_help_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for the search page.",
                verbose_name="Search help",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="theme_help_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for the theme page.",
                verbose_name="Theme help",
            ),
        ),
    ]
