# Generated by Django 3.2.7 on 2022-01-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0005_auto_20220110_1042"),
        ("configurations", "0005_auto_20220113_1110"),
    ]

    operations = []
