# Generated by Django 3.2.7 on 2022-02-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0006_auto_20220117_1626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="home_welcome_title",
            field=models.CharField(
                default="Welcome",
                help_text="Welcome title on the home page.",
                max_length=255,
                verbose_name="Home welcome title",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="login_allow_registration",
            field=models.BooleanField(
                default=False,
                help_text="Wanneer deze optie uit staat is het enkel toegestaan om met DigiD in te loggen. Zet deze instelling aan om ook het inloggen met gebruikersnaam/wachtwoord en het aanmelden zonder DigiD toe te staan.",
                verbose_name="Sta lokale registratie toe",
            ),
        ),
    ]
