# Generated by Django 3.2.7 on 2022-02-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0007_auto_20220202_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="show_cases",
            field=models.BooleanField(
                default=False,
                help_text="By default the cases are not shown. If the OpenZaak integration is configured this can be set to True.",
                verbose_name="Show cases",
            ),
        ),
    ]
