# Generated by Django 3.2.7 on 2022-02-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0007_auto_20220202_1307"),
        ("configurations", "0007_auto_20220202_1835"),
    ]

    operations = []
