# Generated by Django 3.2.12 on 2022-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configurations",
            "0008_merge_0007_auto_20220202_1307_0007_auto_20220202_1835",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="ga_code",
            field=models.CharField(
                blank=True,
                help_text="Typically looks like 'G-XXXXX'. Supplying this installs Google Analytics.",
                max_length=50,
                verbose_name="Google Analytics code",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="gtm_code",
            field=models.CharField(
                blank=True,
                help_text="Typically looks like 'GTM-XXXX'. Supplying this installs Google Tag Manager.",
                max_length=50,
                verbose_name="Google Tag Manager code",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="matomo_site_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The 'idsite' of the website you're tracking in Matomo.",
                null=True,
                verbose_name="Matomo site ID",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="matomo_url",
            field=models.CharField(
                blank=True,
                help_text="The base URL of your Matomo server, e.g. 'matomo.example.com'.",
                max_length=255,
                verbose_name="Matomo server URL",
            ),
        ),
    ]
