# Generated by Django 3.2.12 on 2022-02-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_merge_0007_auto_20220202_1307_0007_auto_20220202_1835'),
        ('configurations', '0008_siteconfiguration_show_cases'),
    ]

    operations = [
    ]
