# Generated by Django 3.2.12 on 2022-02-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0009_auto_20220218_1359"),
        ("configurations", "0009_siteconfiguration_show_cases"),
    ]

    operations = []
