# Generated by Django 3.2.12 on 2022-03-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0009_auto_20220215_1428"),
        ("configurations", "0009_auto_20220218_1359"),
    ]

    operations = []
