# Generated by Django 3.2.12 on 2022-03-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_merge_0009_auto_20220215_1428_0009_auto_20220218_1359'),
        ('configurations', '0011_merge_20220302_1245'),
    ]

    operations = [
    ]
