# Generated by Django 3.2.12 on 2022-03-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0012_merge_20220302_1815"),
        ("configurations", "0012_merge_20220303_1128"),
    ]

    operations = []
