# Generated by Django 3.2.12 on 2022-03-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0013_merge_20220309_1710"),
        ("configurations", "0013_merge_20220311_1841"),
    ]

    operations = []
