# Generated by Django 3.2.12 on 2022-03-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0014_merge_20220314_1716"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="show_product_finder",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Als dit is aangevinkt en er zijn product condities gemaakt, dan wordt op de homepagina de productzoeker weergegeven.",
                verbose_name="Laat productzoeker zien op de homepagina.",
            ),
        ),
    ]
