# Generated by Django 3.2.12 on 2022-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0016_alter_siteconfigurationpage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="plan_help_text",
            field=models.TextField(
                blank=True,
                default="Met het onderdeel Samenwerken kunt u samen met uw contactpersonen of begeleider van de gemeente aan de slag om met een samenwerkingsplan uw persoonlijke situatie te verbeteren. Door samen aan uw doelen te werken en acties te omschrijven kunnen we elkaar helpen.",
                help_text="The help text for the plan page.",
                verbose_name="Plan help",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="questionnaire_help_text",
            field=models.TextField(
                blank=True,
                default="Het onderdeel Zelfdiagnose stelt u in staat om met het beantwoorden van enkele vragen een advies te krijgen van de gemeente, met concrete vervolgstappen en producten en diensten. U kunt tevens uw antwoorden en het advies bewaren om met een begeleider van de gemeente te bespreken.",
                help_text="The help text for the questionnaire page.",
                verbose_name="Questionnaire help",
            ),
        ),
    ]
