# Generated by Django 3.2.13 on 2022-06-29 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('configurations', '0017_auto_20220330_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='openid_connect_login_text',
            field=models.CharField(default='Login with Azure AD', help_text='The text that should display when Openid connect is set as a login method', max_length=250, verbose_name='Openid Connect login text'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='openid_connect_logo',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Logo that can be used for the openid commect login method', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oidc_logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Openid Connect Logo'),
        ),
    ]
