# Generated by Django 3.2.13 on 2022-07-04 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("configurations", "0018_auto_20220629_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="openid_connect_login_text",
            field=models.CharField(
                default="Login with Azure AD",
                help_text="The text that should display when OpenId connect is set as a login method",
                max_length=250,
                verbose_name="Openid Connect login text",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="openid_connect_logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Logo that can be used for the OpenId connect login method",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oidc_logo",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Openid Connect Logo",
            ),
        ),
    ]
