# Generated by Django 3.2.15 on 2022-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0020_siteconfiguration_login_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_questionnaire_subtitle",
            field=models.CharField(
                default="Test met een paar simpele vragen of u recht heeft op een product",
                help_text="Questionnaire sub-title on the home page.",
                max_length=255,
                verbose_name="Home page questionaire sub-title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_questionnaire_title",
            field=models.CharField(
                default="Waar bent u naar op zoek?",
                help_text="Questionnaire title on the home page.",
                max_length=255,
                verbose_name="Home page questionaire title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="select_questionnaire_subtitle",
            field=models.CharField(
                default="Kies hieronder één van de volgende vragenlijsten om de zelfdiagnose te starten.",
                help_text="Questionaire selector sub-title on the theme and profile pages.",
                max_length=255,
                verbose_name="Questionaire selector widget sub-title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="select_questionnaire_title",
            field=models.CharField(
                default="Keuze zelfdiagnose?",
                help_text="Questionaire selector title on the theme and profile pages.",
                max_length=255,
                verbose_name="Questionaire selector widget title",
            ),
        ),
    ]
