# Generated by Django 3.2.15 on 2022-11-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0021_siteconfiguration_more_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_product_finder_intro",
            field=models.TextField(
                blank=True,
                default="Met een paar simpele vragen ziet u welke producten passen bij uw situatie",
                help_text="Product finder's intro text on the home page.",
                verbose_name="Home product finder intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_product_finder_title",
            field=models.CharField(
                default="Productzoeker",
                help_text="Product finder's title on the home page.",
                max_length=255,
                verbose_name="Product finder title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="plans_edit_message",
            field=models.CharField(
                default="Hier kunt u uw doel aanpassen",
                help_text="The message when a user edits a goal.",
                max_length=255,
                verbose_name="Edit goal message",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="plans_intro",
            field=models.TextField(
                default="Hier werkt u aan uw doelen. Dit doet u samen met uw contactpersoon bij de gemeente. ",
                help_text="The sub-title for the plan page.",
                verbose_name="Plan pages intro",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="plans_no_plans_message",
            field=models.CharField(
                default="U heeft nog geen plan gemaakt.",
                help_text="The message in the plans listing when user has no plans.",
                max_length=255,
                verbose_name="No plans message",
            ),
        ),
    ]
