# Generated by Django 3.2.15 on 2022-11-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0022_siteconfiguration_more_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="home_questionnaire_subtitle",
            new_name="home_questionnaire_intro",
        ),
    ]
