# Generated by Django 3.2.15 on 2022-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configurations",
            "0023_rename_home_questionnaire_subtitle_siteconfiguration_home_questionnaire_intro",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="home_questionnaire_intro",
            field=models.TextField(
                default="Test met een paar simpele vragen of u recht heeft op een product",
                help_text="Questionnaire intro text on the home page.",
                verbose_name="Home page questionaire intro",
            ),
        ),
    ]
