# Generated by Django 3.2.15 on 2022-11-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0024_alter_siteconfiguration_home_questionnaire_intro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="select_questionnaire_subtitle",
            new_name="select_questionnaire_intro",
        ),
    ]
