# Generated by Django 3.2.15 on 2022-11-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configurations",
            "0025_rename_select_questionnaire_subtitle_siteconfiguration_select_questionnaire_intro",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="select_questionnaire_intro",
            field=models.TextField(
                default="Kies hieronder één van de volgende vragenlijsten om de zelfdiagnose te starten.",
                help_text="Questionaire selector intro on the theme and profile pages.",
                verbose_name="Questionaire selector widget intro",
            ),
        ),
    ]
