# Generated by Django 3.2.15 on 2022-12-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0026_alter_siteconfiguration_select_questionnaire_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="show_plans",
            field=models.BooleanField(
                default=True,
                help_text="Als dit is aangevinkt, dan wordt op de homepagina en het gebruikers profiel de samenwerken feature weergegeven.",
                verbose_name="Laat samenwerken zien op de homepage en menu",
            ),
        ),
    ]
