# Generated by Django 3.2.15 on 2022-12-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0027_siteconfiguration_show_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="show_actions",
            field=models.BooleanField(
                default=True,
                help_text="Als dit is aangevinkt, dan worded op de gebruikers profiel pagina de acties weergegeven.",
                verbose_name="Laat acties zien op de profiel pagina",
            ),
        ),
    ]
