# Generated by Django 3.2.15 on 2023-01-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("configurations", "0029_auto_20221221_1636"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Footer logo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="footer_logo",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Footer logo",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_logo_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The title - help text of the footer logo.",
                max_length=255,
                verbose_name="Footer logo title",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_logo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="The external link for the footer logo.",
                verbose_name="Footer logo link",
            ),
        ),
    ]
