# Generated by Django 3.2.15 on 2023-02-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0030_auto_20230120_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="siteimprove_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SiteImprove ID - this can be found in the snippet example, which should contain a URL like '//siteimproveanalytics.com/js/siteanalyze_xxxxx.js'. The xxxxx part is the ID.",
                max_length=10,
                verbose_name="SiteImprove ID",
            ),
        ),
    ]
