# Generated by Django 3.2.15 on 2023-02-07 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import filer.fields.image

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("configurations", "0031_siteconfiguration_siteimprove_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="favicon",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Image to use as favicon",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favicon",
                to=settings.FILER_IMAGE_MODEL,
                validators=[
                    open_inwoner.utils.validators.FilerExactImageSizeValidator(32, 32)
                ],
                verbose_name="Favicon image (32x32)",
            ),
        ),
    ]
