# Generated by Django 3.2.15 on 2023-03-01 07:45

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("configurations", "0033_alter_siteconfiguration_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="plans_banner",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Banner of the plans",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_banner",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Plans banner",
            ),
        ),
    ]
