# Generated by Django 3.2.15 on 2023-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0033_alter_siteconfiguration_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_visiting_phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Visiting phonenumber on the footer section.",
                max_length=255,
                verbose_name="Footer visiting phonenumber",
            ),
        ),
    ]
