# Generated by Django 3.2.15 on 2023-02-24 16:58

from django.db import migrations, models
import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0034_siteconfiguration_footer_visiting_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="footer_visiting_phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Visiting phonenumber on the footer section.",
                max_length=15,
                validators=[open_inwoner.utils.validators.validate_phone_number],
                verbose_name="Footer visiting phonenumber",
            ),
        ),
    ]
