# Generated by Django 3.2.15 on 2023-03-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0034_siteconfiguration_plans_banner"),
        ("configurations", "0035_alter_siteconfiguration_footer_visiting_phonenumber"),
    ]

    operations = []
