# Generated by Django 3.2.15 on 2023-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0036_merge_20230303_1004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="home_help_text",
            field=models.TextField(
                blank=True,
                default="Welkom! Op dit scherm vindt u een overzicht van de verschillende onderwerpen en producten & diensten.",
                help_text="The help text for the home page.",
                verbose_name="Home help",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="home_theme_title",
            field=models.CharField(
                default="Onderwerpen",
                help_text="Theme's title on the home page.",
                max_length=255,
                verbose_name="Home theme's title",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="theme_help_text",
            field=models.TextField(
                blank=True,
                default="Op dit scherm vindt u de verschillende onderwerpen waarvoor wij producten en diensten aanbieden.",
                help_text="The help text for the theme page.",
                verbose_name="Theme help",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="theme_title",
            field=models.CharField(
                default="Onderwerpen",
                help_text="Theme's title on the theme's page.",
                max_length=255,
                verbose_name="Theme's title",
            ),
        ),
    ]
