# Generated by Django 3.2.15 on 2023-04-20 13:11

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("configurations", "0038_auto_20230404_1745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image_login",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Deprecated. CMS banner plugin should be used instead.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hero_image_login",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Hero image login",
            ),
        ),
    ]
