# Generated by Django 3.2.15 on 2023-05-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0039_alter_siteconfiguration_hero_image_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="plans_banner",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="show_actions",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="show_cases",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="show_plans",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="show_product_finder",
        ),
    ]
