# Generated by Django 3.2.15 on 2023-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0040_auto_20230503_1417"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="redirect_to",
            field=models.CharField(
                blank=True,
                help_text="Provide a url or a path where the user should be redirected to from the anonymous page. Path example: '/accounts/login/', Url example: 'https://www.example.com'",
                max_length=255,
                null=True,
                verbose_name="Redirect anonymous user to",
            ),
        ),
    ]
