# Generated by Django 3.2.15 on 2023-05-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0041_siteconfiguration_redirect_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="login_2fa_sms",
            field=models.BooleanField(
                default=False,
                help_text="Whether we want the users to be able to log in with 2FA authentication by using an SMS workflow.",
                verbose_name="Login with 2FA-with-SMS",
            ),
        ),
    ]
