# Generated by Django 3.2.15 on 2023-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0042_siteconfiguration_login_2fa_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="allow_messages_file_sharing",
            field=models.BooleanField(
                default=True,
                help_text="Whether file sharing via the messages is allowed or not",
                verbose_name="Allow messages file sharing",
            ),
        ),
    ]
