# Generated by Django 3.2.15 on 2023-06-20 07:32

from django.db import migrations, models
import open_inwoner.configurations.validators


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0043_siteconfiguration_allow_messages_file_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="openid_display",
            field=models.CharField(
                choices=[("admin", "Admin"), ("regular", "Regular user")],
                default="admin",
                help_text="Only selected groups will see the option to login via OpenId.",
                max_length=24,
                validators=[
                    open_inwoner.configurations.validators.validate_oidc_config
                ],
                verbose_name="Show option to login via OpenId",
            ),
        ),
    ]
