# Generated by Django 3.2.15 on 2023-06-27 10:33

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0044_siteconfiguration_openid_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="footer_visiting_phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Visiting phonenumber on the footer section.",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Footer visiting phonenumber",
            ),
        ),
    ]
