# Generated by Django 3.2.15 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0046_siteconfiguration_cookie_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="hide_categories_from_anonymous_users",
            field=models.BooleanField(
                default=False,
                help_text="If checked, categories will be hidden from users who are not logged in.",
                verbose_name="Hide categories from anonymous users",
            ),
        ),
    ]
