# Generated by Django 3.2.20 on 2023-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configurations",
            "0047_siteconfiguration_hide_categories_from_anonymous_users",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="hide_search_from_anonymous_users",
            field=models.BooleanField(
                default=False,
                help_text="If checked, only authenticated users will be able to search the page.",
                verbose_name="Hide search from anonymous users",
            ),
        ),
    ]
