# Generated by Django 3.2.20 on 2023-08-21 14:01

from django.db import migrations

import open_inwoner.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0048_auto_20230816_1255"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="extra_css",
            field=open_inwoner.utils.fields.CSSField(
                blank=True,
                help_text="Additional CSS added to the page",
                verbose_name="Extra CSS",
            ),
        ),
    ]
