# Generated by Django 3.2.20 on 2023-08-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0048_auto_20230816_1255"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_mailing_intro",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_mailing_title",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_visiting_intro",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_visiting_map",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_visiting_phonenumber",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_visiting_title",
        ),
    ]
