# Generated by Django 3.2.20 on 2023-09-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0049_auto_20230821_1523"),
        ("configurations", "0050_siteconfig_warning_banner"),
    ]

    operations = []
