# Generated by Django 3.2.20 on 2023-09-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0051_merge_20230907_1800"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_filter_categories",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show category-checkboxes in order to filter the search result.",
                verbose_name="Add category filter for search results",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_filter_organizations",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show organization-checkboxes in order to filter the search result.",
                verbose_name="Add organization filter for search results",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_filter_tags",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show tag-checkboxes in order to filter the search result.",
                verbose_name="Add tag filter for search results",
            ),
        ),
    ]
