# Generated by Django 3.2.20 on 2023-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0051_merge_20230907_1800"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="registration_text",
            field=models.TextField(
                blank=True,
                help_text="Deze tekst wordt getoond op de registratie pagina.",
                verbose_name="Registratie tekst",
            ),
        ),
    ]
