# Generated by Django 3.2.20 on 2023-09-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0052_siteconfiguration_registration_text"),
        ("configurations", "0052_siteconfiguration_search_filters"),
    ]

    operations = []
