# Generated by Django 3.2.20 on 2023-10-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0053_merge_20230928_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="display_social",
            field=models.BooleanField(
                default=True,
                help_text="Enable sharing of products on social media (Facebook, LinkedIn...)",
                verbose_name="Display social media buttons",
            ),
        ),
    ]
