# Generated by Django 3.2.20 on 2023-11-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0054_siteconfiguration_display_social"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="eherkenning_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether users can log in with eHerkenning or not.",
                verbose_name="eHerkenning authentication enabled",
            ),
        ),
    ]
