# Generated by Django 3.2.20 on 2023-12-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0055_siteconfiguration_eherkenning_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="eherkenning_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether users can log in with eHerkenning or not. By default, the SAML integration will be used for this, in order to use the OpenID Connect integration, navigate to `OpenID Connect configuration for eHerkenning` and enable it.",
                verbose_name="eHerkenning authentication enabled",
            ),
        ),
    ]
