# Generated by Django 3.2.23 on 2024-02-13 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("configurations", "0058_siteconfiguration_recipients_email_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Image to use as logo in email.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logo",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Email logo (.png or .jpg)",
            ),
        ),
    ]
