# Generated by Django 3.2.23 on 2024-02-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0058_siteconfiguration_recipients_email_digest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteconfigurationpage",
            options={
                "ordering": ("order",),
                "verbose_name": "Flatpage in the footer",
                "verbose_name_plural": "Flatpages in the footer",
            },
        ),
    ]
