# Generated by Django 3.2.23 on 2024-01-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0058_customfontset"),
        ("configurations", "0058_siteconfiguration_recipients_email_digest"),
    ]

    operations = []
