# Generated by Django 3.2.23 on 2024-02-08 13:26

import django.core.validators
from django.db import migrations
import open_inwoner.configurations.models
import open_inwoner.utils.files


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0059_merge_20240129_1645"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customfontset",
            name="text_body_font",
        ),
        migrations.AddField(
            model_name="customfontset",
            name="body_font_bold",
            field=open_inwoner.configurations.models.CustomFontField(
                blank=True,
                help_text="Upload bold text body font. TTF font types only.",
                null=True,
                storage=open_inwoner.utils.files.OverwriteStorage(),
                upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_body_bold,
                validators=[django.core.validators.FileExtensionValidator(["ttf"])],
                verbose_name="Body font bold",
            ),
        ),
        migrations.AddField(
            model_name="customfontset",
            name="body_font_bold_italic",
            field=open_inwoner.configurations.models.CustomFontField(
                blank=True,
                help_text="Upload bold italic text body font. TTF font types only.",
                null=True,
                storage=open_inwoner.utils.files.OverwriteStorage(),
                upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_body_bold_italic,
                validators=[django.core.validators.FileExtensionValidator(["ttf"])],
                verbose_name="Body font bold italic",
            ),
        ),
        migrations.AddField(
            model_name="customfontset",
            name="body_font_italic",
            field=open_inwoner.configurations.models.CustomFontField(
                blank=True,
                help_text="Upload italic text body font. TTF font types only.",
                null=True,
                storage=open_inwoner.utils.files.OverwriteStorage(),
                upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_body_italic,
                validators=[django.core.validators.FileExtensionValidator(["ttf"])],
                verbose_name="Body font italic",
            ),
        ),
        migrations.AddField(
            model_name="customfontset",
            name="body_font_regular",
            field=open_inwoner.configurations.models.CustomFontField(
                blank=True,
                help_text="Upload regular text body font. TTF font types only.",
                null=True,
                storage=open_inwoner.utils.files.OverwriteStorage(),
                upload_to=open_inwoner.configurations.models.CustomFontSet.update_filename_body,
                validators=[django.core.validators.FileExtensionValidator(["ttf"])],
                verbose_name="Body font regular",
            ),
        ),
    ]
