# Generated by Django 3.2.23 on 2024-02-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0059_siteconfiguration_email_logo"),
        ("configurations", "0060_auto_20240208_1426"),
    ]

    operations = []
