# Generated by Django 3.2.23 on 2024-02-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0059_alter_siteconfigurationpage_options"),
        ("configurations", "0061_merge_20240214_1308"),
    ]

    operations = []
