# Generated by Django 4.2.10 on 2024-02-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0059_alter_siteconfigurationpage_options"),
        ("configurations", "0061_merge_20240214_1308"),
    ]

    operations = []
