# Generated by Django 4.2.10 on 2024-02-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0062_merge_20240214_1644"),
        ("configurations", "0062_merge_20240215_1501"),
    ]

    operations = []
