# Generated by Django 3.2.24 on 2024-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0063_siteconfiguration_contact_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_page",
            field=models.URLField(
                blank=True,
                help_text="URL of the public contact page of the organization",
                verbose_name="URL",
            ),
        ),
    ]
