# Generated by Django 3.2.24 on 2024-03-04 11:00

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0063_merge_20240216_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_page",
            field=models.URLField(
                blank=True,
                help_text="URL of the public contact page of the organization",
                verbose_name="URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_phonenumber",
            field=models.CharField(
                blank=True,
                help_text="The public contact phone number of the organization",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Phonenumber",
            ),
        ),
    ]
