# Generated by Django 4.2.11 on 2024-04-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0064_auto_20240304_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="kcm_survey_link_text",
            field=models.CharField(
                blank=True,
                help_text="The text that is displayed on the customer satisfaction survey link",
                max_length=255,
                verbose_name="KCM survey link text",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kcm_survey_link_url",
            field=models.URLField(
                blank=True,
                help_text="The external link for the customer satisfaction survey.",
                verbose_name="KCM survey URL",
            ),
        ),
    ]
