# Generated by Django 4.2.11 on 2024-04-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0065_siteconfiguration_email_verification_required"),
        ("configurations", "0065_siteconfiguration_kcm_survey_link_text_and_more"),
    ]

    operations = []
