# Generated by Django 4.2.11 on 2024-07-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0067_alter_siteconfiguration_warning_banner_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="contactmoment_contact_form_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Display contact form on the questions list page so that users can create new questions",
                verbose_name="Contactmoment contact form",
            ),
        ),
    ]
