# Generated by Django 4.2.11 on 2024-07-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0067_alter_siteconfiguration_warning_banner_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="warning_banner_text",
            field=models.TextField(
                blank=True,
                help_text="Text will be displayed on the warning banner",
                verbose_name="Warning banner text",
            ),
        ),
    ]
