# Generated by Django 4.2.11 on 2024-07-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0068_change_siteconfiguration_notifications"),
        ("configurations", "0068_siteconfiguration_contactmoment_contact_form"),
    ]

    operations = []
