# Generated by Django 4.2.15 on 2024-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0070_siteconfiguration_enable_notification_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="notifications_cases_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Notify users of updates to cases or if an action is required (if set, individual users can still opt out)",
                verbose_name="User notifications for cases",
            ),
        ),
    ]
