# Generated by Django 4.2.15 on 2024-08-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configurations",
            "0072_alter_siteconfiguration_notifications_actions_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="notifications_actions_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable notifications for expiring actions concerning plans (if enabled, individual users can still opt out by disabling notifications for plans)",
                verbose_name="User notifications for expiring actions",
            ),
        ),
    ]
