# Generated by Django 4.2.15 on 2024-08-29 09:57

from django.db import migrations, models

import colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("flatpages", "0001_initial"),
        (
            "configurations",
            "0073_alter_siteconfiguration_notifications_actions_enabled",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="accent_color",
            field=colorfield.fields.ColorField(
                default="#FF0000",
                help_text="The accent color of the municipality's site",
                max_length=18,
                verbose_name="Accent color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="flatpages",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="configurations",
                through="configurations.SiteConfigurationPage",
                to="flatpages.flatpage",
                verbose_name="Flatpages",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="secondary_color",
            field=colorfield.fields.ColorField(
                default="#0000FF",
                help_text="The secondary color of the municipality's site",
                max_length=18,
                verbose_name="Secondary color",
            ),
        ),
    ]
