# Generated by Django 4.2.18 on 2025-02-04 09:07

import logging

from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.db import migrations, models

logger = logging.getLogger(__name__)


def copy_setting_from_openzaak_config(apps, _):
    OpenZaakConfig = apps.get_model("openzaak", "OpenZaakConfig")
    SiteConfiguration = apps.get_model("configurations", "SiteConfiguration")

    try:
        # Should be a singletos
        openzaak_config = OpenZaakConfig.objects.get()
        site_config = SiteConfiguration.objects.get()
    except ObjectDoesNotExist:
        pass  # Nothing to migrate
    except MultipleObjectsReturned:
        logger.warning(
            "Unable to migrate `enable_eherkenning_for_eenmanszaak` flag from "
            "OpenZaakConfig, found multiple OpenZaakConfig/SiteConfiguration objects"
        )
    else:
        site_config.enable_eherkenning_for_eenmanszaak = (
            openzaak_config.enable_eherkenning_for_eenmanszaak
        )
        site_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0074_alter_siteconfiguration_accent_color_and_more"),
        ("openzaak", "0063_alter_openzaakconfig_show_cases_without_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="enable_eherkenning_for_eenmanszaak",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, eenmanszaken may authenticate using eHerkenning and subsequently their kvk nummer will be used to interface with the zaken and klanten backends. If not, an eenmanszaak will be forced to use DigiD, and the user's BSN will be used instead.",
                verbose_name="Allow eenmanszaken to authenticate using eHerkenning",
            ),
        ),
        migrations.RunPython(
            copy_setting_from_openzaak_config, reverse_code=migrations.RunPython.noop
        ),
    ]
