# Generated by Django 4.2.16 on 2025-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0075_siteconfiguration_enable_eherkenning_for_eenmanszaak"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="enable_crawler_indexing",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, search engines can index the site",
                verbose_name="Enable indexing by search engines",
            ),
        ),
    ]
