# Generated by Django 4.2.16 on 2025-04-03 15:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0076_siteconfiguration_enable_crawler_indexing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="login_text",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Deze tekst wordt getoond op de login pagina.",
                verbose_name="Login tekst",
            ),
        ),
    ]
