# Generated by Django 4.2.20 on 2025-04-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0077_config_rich_editor_login_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="security_txt_redirect_target",
            field=models.URLField(
                default="https://www.ncsc.nl/.well-known/security.txt",
                help_text="Link to which ./well-known/security.txt will redirect to",
                verbose_name="Redirect security.txt to",
            ),
        ),
    ]
