# Generated by Django 4.2.20 on 2025-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0079_search_zero_results_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="include_cms_pages_in_search_index",
            field=models.BooleanField(
                default=False,
                help_text="If checked, CMS pages will be added to the search index and included in search results. Note the change will not take effect until the search index has been refreshed.",
                verbose_name="Make CMS Pages searchable",
            ),
        ),
    ]
