# Generated by Django 4.2.20 on 2025-06-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("configurations", "0080_siteconfiguration_include_cms_pages_in_search_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteconfigurationpage",
            options={
                "ordering": ("order",),
                "verbose_name": "CMS page in the footer",
                "verbose_name_plural": "CMS pages in the footer",
            },
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="flatpages",
        ),
        migrations.RemoveField(
            model_name="siteconfigurationpage",
            name="flatpage",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="cms_pages",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="configurations",
                through="configurations.SiteConfigurationPage",
                to="cms.page",
                verbose_name="CMS pages",
            ),
        ),
        migrations.AddField(
            model_name="siteconfigurationpage",
            name="cms_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_footer_pages",
                to="cms.page",
                verbose_name="Footer CMS Page",
            ),
        ),
    ]
