# Generated by Django 4.2.20 on 2025-06-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("configurations", "0081_alter_siteconfigurationpage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfigurationpage",
            name="cms_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_cms_pages",
                to="cms.page",
                verbose_name="Footer CMS Page",
            ),
        ),
    ]
