# Generated by Django 4.2.24 on 2025-09-11 08:10

import django.core.validators
from django.db import migrations, models

import open_inwoner.configurations.validators


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0082_alter_siteconfigurationpage_cms_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="custom_javascript",
            field=models.FileField(
                blank=True,
                help_text="Upload a custom JavaScript file (.js) that will be loaded on every page.",
                null=True,
                upload_to="custom_scripts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["js"]
                    ),
                    open_inwoner.configurations.validators.validate_javascript_file,
                ],
                verbose_name="Custom JavaScript",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="custom_javascript_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Let op: Custom JavaScript kan de beveiliging en prestaties van de applicatie negatief beïnvloeden. Door het aanvinken van deze optie bevestig ik dat ik de mogelijke risico’s begrijp en – indien nodig – dit heb afgestemd met de security-afdeling voordat ik deze inlaad. Het aanvinken van deze optie is noodzakelijk om de Javascript daadwerkelijk te tonen.",
                verbose_name="I confirm I understand the risks of adding custom Javascript",
            ),
        ),
    ]
