# Generated by Django 4.2.24 on 2025-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0083_custom_javascript"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineLogConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "automatically_prune_logs",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automatic pruning of old timeline log entries",
                        verbose_name="Automatically prune timeline logs",
                    ),
                ),
                (
                    "keep_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Number of days to keep timeline log entries before pruning",
                        verbose_name="Keep logs for days",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
