# Generated by Django 4.2.22 on 2025-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0083_custom_javascript"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_verification_message",
            field=models.TextField(
                blank=True,
                default="Er is een e-mail verstuurd naar {email}. Klik op de link in de mail om uw e-mailadres te bevestigen. Heeft u geen e-mail ontvangen? Verstuur deze dan nog een keer via onderstaande knop.",
                help_text="The message for the user that they need to verify their email. Use the placeholder {email} to insert the user's email.",
                verbose_name="Email verification message",
            ),
        ),
    ]
