# Generated by Django 4.2.22 on 2025-09-10 12:45

from django.db import migrations

import structlog

logger = structlog.stdlib.get_logger(__name__)


def create_partial_admin_edit_permissions(apps, _):
    SiteConfiguration = apps.get_model("configurations", "SiteConfiguration")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    siteconfig_ct = ContentType.objects.get_for_model(SiteConfiguration)

    for codename, name in (
        ("siteconfig_fieldset_color", "Can edit colors"),
        ("siteconfig_fieldset_images", "Can edit images"),
        ("siteconfig_fieldset_warning_banner", "Can edit warning banner"),
        ("siteconfig_fieldset_page_texts", "Can edit page texts"),
        ("siteconfig_fieldset_help_texts", "Can edit help texts"),
    ):
        Permission.objects.create(
            codename=codename,
            name=name,
            content_type=siteconfig_ct,
        )


def delete_partial_admin_edit_permissions(apps, _):
    Permission = apps.get_model("auth", "Permission")

    for codename in (
        "siteconfig_fieldset_color",
        "siteconfig_fieldset_images",
        "siteconfig_fieldset_warning_banner",
        "siteconfig_fieldset_page_texts",
        "siteconfig_fieldset_help_texts",
    ):
        deleted_count, _ = Permission.objects.filter(codename=codename).delete()
        if deleted_count:
            logger.info(
                "Deleted Permission objects for SiteConfiguration",
                siteconfig_part=codename,
                deleted_count=deleted_count,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0084_siteconfiguration_email_verification_message"),
    ]

    operations = [
        migrations.RunPython(
            code=create_partial_admin_edit_permissions,
            reverse_code=delete_partial_admin_edit_permissions,
        )
    ]
