# Generated by Django 4.2.24 on 2025-09-24 15:03

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0085_create_partial_admin_edit_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="warning_banner_text",
            new_name="warning_banner_text_tmp",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="warning_banner_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
            ),
        ),
    ]
