# Generated by Django 4.2.24 on 2025-09-24 15:03

from functools import partial

from django.db import migrations

from django_prosemirror.schema import NodeType

from open_inwoner.utils.migration_operations import migrate_to_prosemirror_field

migrate_login_text = partial(
    migrate_to_prosemirror_field,
    app_label="configurations",
    model_name="SiteConfiguration",
    field_name="login_text",
    allowed_node_types=[NodeType.PARAGRAPH],
    use_singleton=True,
)


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0089_siteconfiguration_login_text_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_login_text,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
