# Generated by Django 4.2.24 on 2025-09-24 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0090_siteconfiguration_login_text_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="login_text_tmp",
        ),
    ]
