# Generated by Django 4.2.25 on 2025-10-14 15:56

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0094_siteconfiguration_search_zero_results_text_schema_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="login_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                help_text="Deze tekst wordt getoond op de login pagina.",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Login tekst",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="search_zero_results_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                help_text="Text will be displayed on the warning banner",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Text for zero search results",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="warning_banner_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Warning banner text",
            ),
        ),
    ]
