# Generated by Django 4.2.25 on 2025-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0095_alter_siteconfiguration_login_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="search_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether search functionality is enabled.",
                verbose_name="Enable Search",
            ),
        ),
    ]
