# Generated by Django 4.2.30 on 2026-04-23 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0097_alter_siteconfiguration_login_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="clamav_host",
            field=models.CharField(
                blank=True,
                default="clamav",
                help_text="Hostname or IP address of the ClamAV daemon.",
                max_length=255,
                verbose_name="ClamAV host",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="clamav_port",
            field=models.PositiveIntegerField(
                default=3310,
                help_text="TCP port of the ClamAV daemon (default: 3310).",
                validators=[django.core.validators.MaxValueValidator(65535)],
                verbose_name="ClamAV port",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="clamav_timeout",
            field=models.FloatField(
                default=30.0,
                help_text="Connection timeout in seconds for the ClamAV daemon.",
                verbose_name="ClamAV timeout",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="enable_virus_scan",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, uploaded files are scanned for viruses using ClamAV. Requires a ClamAV service reachable at the configured host and port.",
                verbose_name="Enable virus scan",
            ),
        ),
    ]
