# Generated by Django 5.2.16 on 2026-08-19 10:07

from django.db import migrations, models

import open_inwoner.configurations.validators


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0099_alter_siteconfiguration_search_zero_results_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="redirect_to",
            field=models.CharField(
                blank=True,
                help_text="Provide a url or a path where the user should be redirected to from the anonymous page. Path example: '/accounts/login/', Url example: 'https://www.example.com'",
                max_length=255,
                null=True,
                validators=[
                    open_inwoner.configurations.validators.validate_redirect_to
                ],
                verbose_name="Redirect anonymous user to",
            ),
        ),
    ]
