# Generated by Django 5.2.16 on 2026-08-19 16:00

from django.db import migrations, models

import colorfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0100_alter_siteconfiguration_redirect_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="primary_color",
            field=colorfield.fields.ColorField(
                default="#154273",
                help_text="The primary color of the municipality's site",
                max_length=18,
                verbose_name="Primary color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="secondary_color",
            field=colorfield.fields.ColorField(
                default="#C2410C",
                help_text="The secondary color of the municipality's site",
                max_length=18,
                verbose_name="Secondary color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="accent_color",
            field=colorfield.fields.ColorField(
                default="#76D2B6",
                help_text="The accent color of the municipality's site",
                max_length=18,
                verbose_name="Accent color",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="secondary_font_color",
            field=models.CharField(
                choices=[("#FFFFFF", "light"), ("#4B4B4B", "dark")],
                default="#FFFFFF",
                help_text="The font color for when the background is the secondary color",
                max_length=50,
                verbose_name="Secondary font color",
            ),
        ),
    ]
