version: '3.4'

services:
  keycloak:
    image: keycloak/keycloak:24.0.1-0
    environment:
      - KEYCLOAK_ADMIN=demo
      - KEYCLOAK_ADMIN_PASSWORD=demo
    command: start-dev --import-realm
    volumes:
      - ./keycloak/fixtures/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8080:8080
    networks:
      open-inwoner-dev:
        aliases:
          - keycloak.open-inwoner.local

networks:
  open-inwoner-dev:
    name: open-inwoner-dev
