# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  openklant-db:
    image: postgis/postgis:12-2.5
    environment:
      - POSTGRES_USER=${DB_USER:-open_klant}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-open_klant}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      openklant-dev:
        aliases:
          - openklant.local

  openklant-redis:
    image: redis
    networks:
      openklant-dev:
        aliases:
          - openklant.local

  openklant-web:
    image: maykinmedia/open-klant:0.5-pre
    environment:
      - DJANGO_SETTINGS_MODULE=openklant.conf.docker
      - SECRET_KEY=${SECRET_KEY:-a8s@b*ds4t84-q_2#c0j0506@!l2q6r5_pq5e!vm^_9c*#^66b}
      - DB_HOST=openklant-db
      - DB_USER=${DB_USER:-open_klant}
      - DB_PASSWORD=${DB_PASSWORD:-open_klant}
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=openklant-redis:6379/0
      - CACHE_AXES=openklant-redis:6379/0
      - NOTIFICATIONS_DISABLED=1
      - UWSGI_PORT=8001
    ports:
      - 8001:8001
    depends_on:
      - openklant-db
      - openklant-redis

    networks:
      openklant-dev:
        aliases:
          - openklant.local

networks:
  openklant-dev:
    name: openklant-dev

volumes:
  db_data:
