# Generated by Django 3.2.20 on 2023-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kvkconfig",
            name="api_root",
            field=models.URLField(
                help_text="The root of the API (e.g. https://api.kvk.nl/api/v1)",
                max_length=128,
                verbose_name="API root",
            ),
        ),
    ]
