# Generated by Django 3.2.23 on 2024-02-12 08:12

from django.db import migrations


def strip_version_number(apps, _):
    KvKConfig = apps.get_model("kvk.KvKConfig")

    config = KvKConfig.objects.first()
    if not config:
        return

    config.api_root = str(config.api_root).strip("v1/")
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0002_alter_kvkconfig_api_root"),
    ]

    operations = [
        migrations.RunPython(
            code=strip_version_number, reverse_code=migrations.RunPython.noop
        ),
    ]
