# Generated by Django 3.2.23 on 2024-02-19 08:26

from django.db import migrations, models
import open_inwoner.kvk.validators


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0003_api_root"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kvkconfig",
            name="api_root",
            field=models.URLField(
                help_text="The root of the API without version number and endpoint (e.g. https://api.kvk.nl/api/ or https://api.kvk.nl/test/api).",
                max_length=128,
                validators=[open_inwoner.kvk.validators.validate_api_root],
                verbose_name="API root",
            ),
        ),
    ]
