---

- hosts: cindy
  vars_files:
    - vars/base.yml
    - vars/staging-secrets.yml
    - vars/staging.yml
    - vars/packages.yml
  become: yes
  vars:
    # Certbot
    certbot_admin_email: support@maykinmedia.nl
    certbot_create_if_missing: true
    # Unused due to certbot_auto_renew=False but it's used by certbot_hooks task.
    certbot_create_standalone_stop_services: ['nginx']
    # Debian 9 (at least) has its own renewal via systemd timers.
    # See: https://github.com/geerlingguy/ansible-role-certbot/issues/90
    certbot_auto_renew: false
    certbot_certs:
      - domains:
        - groningen.openinwoner.nl
      - domains:
        - leeuwarden.openinwoner.nl
      - domains:
        - zwolle.openinwoner.nl
      - domains:
        - mijn-acceptatie.enschede.nl
      - domains:
        - deventer.openinwoner.nl
      - domains:
        - zaanstad.openinwoner.nl

  tasks:
  - include: maykin-deployment/ansible/tasks/startdeploy.yml
  - block:
    - include: maykin-deployment/ansible/tasks/create_maykin_user.yml
    - include: maykin-deployment/ansible/tasks/staff_pub_keys.yml
    - include: maykin-deployment/ansible/tasks/setup.yml
    - include: maykin-deployment/ansible/tasks/hostname.yml
    - include: maykin-deployment/ansible/tasks/exim4.yml
    - include: maykin-deployment/ansible/tasks/firewall.yml
    - include: maykin-deployment/ansible/tasks/zabbix-agent.yml
    - include: maykin-deployment/ansible/tasks/logrotate.yml
    - include: maykin-deployment/ansible/tasks/elasticsearch-7.yml
    - include: maykin-deployment/ansible/tasks/postgresql-11-postgis-2.5.yml
    - include: maykin-deployment/ansible/tasks/npm.yml
    - include: tasks/db-all-sites.yml
    - include: tasks/django-project.yml
    - include: tasks/migrate-all-sites.yml
    - include: tasks/env-all-sites.yml
    # Uncomment the next 3 lines (certbot) to use Let's Encrypt.
    # Run the below once on your local machine
    # - include: maykin-deployment/ansible/tasks/ansible-galaxy.yml
    - include_role:
       name: geerlingguy.certbot
    - include: maykin-deployment/ansible/tasks/nginx-per-target.yml
    - include: maykin-deployment/ansible/tasks/cronjobs.yml
    - include: maykin-deployment/ansible/tasks/rsnapshot.yml
    - include: maykin-deployment/ansible/tasks/set-maintenance-mode.yml
    - include: maykin-deployment/ansible/tasks/supervisor-per-group.yml
    - include: maykin-deployment/ansible/tasks/unset-maintenance-mode.yml
    - include: maykin-deployment/ansible/tasks/stopdeploy.yml
    rescue:
    - include: maykin-deployment/ansible/tasks/errordeploy.yml

  handlers:
  - include: maykin-deployment/ansible/handlers/main.yml
