ZAKEN_ROOT = "https://zaken.nl/api/v1/"
CATALOGI_ROOT = "https://catalogi.nl/api/v1/"
DOCUMENTEN_ROOT = "https://documenten.nl/api/v1/"
NOTIFICATIONS_ROOT = "https://notifications.nl/api/v1/"
FORMS_ROOT = "https://forms.nl/api/v1/"

ANOTHER_ZAKEN_ROOT = "https://andere-zaken.nl/api/v1/"
ANOTHER_CATALOGI_ROOT = "https://andere-catalogi.nl/api/v1/"
ANOTHER_DOCUMENTEN_ROOT = "https://andere-documenten.nl/api/v1/"
ANOTHER_NOTIFICATIONS_ROOT = "https://andere-notifications.nl/api/v1/"
ANOTHER_FORMS_ROOT = "https://andere-forms.nl/api/v1/"
