# Generated by Django 3.2.20 on 2023-11-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simple_certmanager", "0002_alter_certificate_private_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KvKConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_root",
                    models.URLField(
                        blank=True,
                        help_text="The root of the API (e.g. https://api.kvk.nl/api/v1)",
                        max_length=128,
                        verbose_name="API root",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="The API key to connect to the KvK API.",
                        max_length=255,
                        verbose_name="API key",
                    ),
                ),
                (
                    "client_certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The SSL certificate file used for client identification. ",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kvk_service_client",
                        to="simple_certmanager.certificate",
                    ),
                ),
                (
                    "server_certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The SSL/TLS certificate of the server.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kvk_service_server",
                        to="simple_certmanager.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "KvK configuration",
            },
        ),
    ]
