# Generated by Django 4.2.20 on 2025-06-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("open_product", "0001_initial"),
        ("open_product", "0002_rename_openproductconfigmodel_openproductconfig"),
        ("open_product", "0003_alter_openproductconfig_options"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenProductConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_urls",
                    models.JSONField(
                        default=dict,
                        help_text="URL configurations for product type actions",
                        verbose_name="Action URLs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Product Configuration",
            },
        ),
    ]
