# Generated by Django 3.2.7 on 2021-12-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0013_oas_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="HaalCentraalConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Haal Centraal API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haal Centraal configuration",
            },
        ),
    ]
