# Generated by Django 4.2.30 on 2026-04-09 16:09

import django.db.models.deletion
from django.db import migrations, models

import open_inwoner.haalcentraal.validators


class Migration(migrations.Migration):
    replaces = [
        ("haalcentraal", "0001_initial"),
        ("haalcentraal", "0002_auto_20230206_1511"),
        ("haalcentraal", "0003_haalcentraalconfig_api_verwerking_and_more"),
        ("haalcentraal", "0004_haalcentraalconfig_api_afnemer_oin"),
        ("haalcentraal", "0005_haalcentraalconfig_x_request_afnemerscode_and_more"),
        ("haalcentraal", "0006_haalcentraalconfig_x_request_user"),
    ]

    initial = True

    dependencies = [
        ("zgw_consumers", "0025_service_jwt_valid_for"),
        ("zgw_consumers", "0013_oas_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="HaalCentraalConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        help_text="Fill in the appropriate headers for the chosen API service below.",
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Haal Centraal API",
                    ),
                ),
                (
                    "api_doelbinding",
                    models.CharField(
                        blank=True,
                        help_text="Value of the 'x-doelbinding' header for Haalcentraal BRP API requests.",
                        max_length=64,
                        verbose_name="API 'doelbinding' header",
                    ),
                ),
                (
                    "api_origin_oin",
                    models.CharField(
                        blank=True,
                        help_text="Value of the 'x-origin-oin' header for Haalcentraal BRP API requests.",
                        max_length=64,
                        verbose_name="API 'OIN' header",
                    ),
                ),
                (
                    "api_verwerking",
                    models.CharField(
                        blank=True,
                        help_text="Value of the 'x-verwerking' header for Haalcentraal BRP API requests",
                        max_length=242,
                        validators=[
                            open_inwoner.haalcentraal.validators.validate_verwerking_header
                        ],
                        verbose_name="API 'verwerking' header",
                    ),
                ),
                (
                    "api_afnemer_oin",
                    models.CharField(
                        blank=True,
                        help_text="Value of the 'x-afnemer-oin' header for Haalcentraal BRP API requests.",
                        max_length=64,
                        verbose_name="API 'OIN' afnemer header",
                    ),
                ),
                (
                    "x_request_afnemerscode",
                    models.CharField(
                        blank=True,
                        help_text="Value of the 'x-request-afnemerscode' header",
                        max_length=64,
                        verbose_name="API 'afnemerscode' header",
                    ),
                ),
                (
                    "x_request_application",
                    models.CharField(
                        blank=True,
                        help_text="Value of the 'x-request-application' header",
                        max_length=64,
                        verbose_name="API 'application' header",
                    ),
                ),
                (
                    "x_request_organization",
                    models.CharField(
                        blank=True,
                        help_text="Value of the 'x-request-organization' header",
                        max_length=64,
                        verbose_name="API 'organization' header",
                    ),
                ),
                (
                    "x_request_user",
                    models.CharField(
                        blank=True,
                        help_text="Value of the 'x-request-user' header",
                        max_length=64,
                        verbose_name="API 'user' header",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haal Centraal configuration",
            },
        ),
    ]
