# Generated by Django 4.2.20 on 2025-07-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0025_service_jwt_valid_for"),
        ("haalcentraal", "0004_haalcentraalconfig_api_afnemer_oin"),
    ]

    operations = [
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="x_request_afnemerscode",
            field=models.CharField(
                blank=True,
                help_text="Value of the 'x-request-afnemerscode' header",
                max_length=64,
                verbose_name="API 'afnemerscode' header",
            ),
        ),
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="x_request_application",
            field=models.CharField(
                blank=True,
                help_text="Value of the 'x-request-application' header",
                max_length=64,
                verbose_name="API 'application' header",
            ),
        ),
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="x_request_organization",
            field=models.CharField(
                blank=True,
                help_text="Value of the 'x-request-organization' header",
                max_length=64,
                verbose_name="API 'organization' header",
            ),
        ),
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="x_request_user",
            field=models.CharField(
                blank=True,
                help_text="Value of the 'x-request-usre' header",
                max_length=64,
                verbose_name="API 'user' header",
            ),
        ),
        migrations.AlterField(
            model_name="haalcentraalconfig",
            name="service",
            field=models.OneToOneField(
                help_text="Fill in the appropriate headers for the chosen API service below.",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Haal Centraal API",
            ),
        ),
    ]
