# Generated by Django 4.2.18 on 2025-03-17 14:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("haalcentraal", "0004_haalcentraalconfig_api_afnemer_oin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReisDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reisdocumentnummer",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z0-9]{9}$")
                        ]
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator("^[a-zA-Z0-9 \\.]+$")
                        ]
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9À-ž '\\,\\(\\)\\.\\-]{1,200}$"
                            )
                        ]
                    ),
                ),
                ("endDateValid_date", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
