# Generated by Django 4.2.21 on 2025-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haalcentraal", "0005_haalcentraalconfig_x_request_afnemerscode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haalcentraalconfig",
            name="x_request_user",
            field=models.CharField(
                blank=True,
                help_text="Value of the 'x-request-user' header",
                max_length=64,
                verbose_name="API 'user' header",
            ),
        ),
    ]
