# Generated by Django 4.2.30 on 2026-04-09 16:10

from django.db import migrations, models


def migrate_brp_version(apps, schema_editor):
    from django.conf import settings

    HaalCentraalConfig = apps.get_model("haalcentraal", "HaalCentraalConfig")
    config, _ = HaalCentraalConfig.objects.get_or_create(pk=1)
    brp_version = getattr(settings, "BRP_VERSION", "2.0")
    config.brp_version = brp_version if brp_version in ("1.3", "2.0", "2.1") else "2.0"
    config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("haalcentraal", "0001_squashed_0006_haalcentraalconfig_x_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="brp_version",
            field=models.CharField(
                choices=[("1.3", "BRP 1.3"), ("2.0", "BRP 2.0"), ("2.1", "BRP 2.1")],
                default="2.0",
                max_length=3,
                verbose_name="BRP version",
            ),
        ),
        migrations.RunPython(migrate_brp_version, migrations.RunPython.noop),
    ]
