# Generated by Django 4.2.30 on 2026-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haalcentraal", "0008_replace_header_fields_with_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haalcentraalconfig",
            name="brp_version",
            field=models.CharField(
                choices=[
                    ("1.3", "BRP 1.3"),
                    ("2.0", "BRP 2.0"),
                    ("2.1", "BRP 2.1"),
                    ("2.2", "BRP 2.2"),
                    ("2.3", "BRP 2.3"),
                    ("2.4", "BRP 2.4"),
                    ("2.5", "BRP 2.5"),
                    ("2.6", "BRP 2.6"),
                    ("2.7", "BRP 2.7"),
                ],
                default="2.0",
                help_text="Version of the Haal Centraal BRP API to use. See https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/redoc for the API specification.",
                max_length=3,
                verbose_name="BRP version",
            ),
        ),
    ]
