# Generated by Django 4.2.20 on 2025-06-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("product_list", "0001_initial"),
        ("product_list", "0002_productlist_theme"),
        ("product_list", "0003_alter_productlist_theme"),
        ("product_list", "0004_alter_productlist_theme"),
        ("product_list", "0005_alter_productlist_theme"),
        ("product_list", "0006_alter_productlist_theme"),
        ("product_list", "0007_alter_productlist_theme"),
        ("product_list", "0008_alter_productlist_theme"),
        ("product_list", "0009_alter_productlist_description_and_more"),
        ("product_list", "0010_producttypeactionconfig"),
        ("product_list", "0011_delete_producttypeactionconfig"),
    ]

    initial = True

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductList",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of this product list.", verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of this product list.",
                        verbose_name="Description",
                    ),
                ),
                ("theme", models.CharField(verbose_name="Theme")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
