# Generated by Django 4.2.22 on 2025-06-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_list", "0001_squashed_0011_delete_producttypeactionconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlist",
            name="theme",
            field=models.CharField(
                help_text="What theme of Open Products the list will render.",
                verbose_name="Theme",
            ),
        ),
    ]
