# Generated by Django 4.2.22 on 2025-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_list", "0012_alter_productlist_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlist",
            name="description",
            field=models.CharField(
                help_text="Description of the product list.", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="productlist",
            name="title",
            field=models.CharField(
                help_text="Title of the product list.", verbose_name="Title"
            ),
        ),
    ]
