# Generated by Django 3.2.7 on 2021-11-29 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Synonym",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="The term",
                        max_length=250,
                        unique=True,
                        verbose_name="term",
                    ),
                ),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(verbose_name="synonyms"),
                        help_text="Words-synonyms concerning the term",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "synonym",
                "verbose_name_plural": "synonyms",
            },
        ),
    ]
