# Generated by Django 3.2.7 on 2021-11-29 15:12

from django.db import migrations, models

import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("synonyms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synonym",
            name="synonyms",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.TextField(verbose_name="synonyms"),
                help_text="Words-synonyms concerning the term",
                size=None,
            ),
        ),
    ]
