# Generated by Django 3.2.15 on 2023-04-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenKlantConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contactmomenten_service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "cmc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Contactmomenten API",
                    ),
                ),
                (
                    "klanten_service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "kc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Klanten API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Klant configuration",
            },
        ),
    ]
