# Generated by Django 3.2.15 on 2023-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0005_auto_20230621_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactformsubject",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
    ]
