# Generated by Django 3.2.20 on 2023-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0006_alter_contactformsubject_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactformsubject",
            name="subject_code",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="e-Suite 'onderwerp' code"
            ),
        ),
    ]
