# Generated by Django 3.2.23 on 2023-12-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0007_contactformsubject_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="openklantconfig",
            name="use_rsin_for_innNnpId_query_parameter",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, resources from the Klanten and Contactmomenten APIs for eHerkenning users are fetched using the company RSIN (Open Klant). If not enabled, these resources are fetched using the KvK number.",
                verbose_name="Fetch resources from Klanten and Contactmomenten APIs for users authenticated with eHerkenning using RSIN",
            ),
        ),
    ]
