# Generated by Django 4.2.10 on 2024-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0009_klantcontactmomentanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="openklantconfig",
            name="register_channel",
            field=models.CharField(
                blank=True,
                default="contactformulier",
                help_text="The channel through which contactmomenten are created",
                max_length=50,
                verbose_name="Contactmoment kanaal",
            ),
        ),
    ]
