# Generated by Django 4.2.11 on 2024-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0010_openklantconfig_register_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openklantconfig",
            name="use_rsin_for_innNnpId_query_parameter",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, resources from the Klanten and Contactmomenten APIs for eHerkenning users are fetched using the company RSIN (Open Klant). If not enabled, these resources are fetched using the KvK number.",
                verbose_name="Fetch resources from Klanten and Contactmomenten APIs for users authenticated with eHerkenning using RSIN",
            ),
        ),
    ]
