# Generated by Django 4.2.10 on 2024-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0010_openklantconfig_register_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="openklantconfig",
            name="api_sends_email_confirmation",
            field=models.BooleanField(
                default=False,
                help_text="If enabled the external API will send a confirmation email.If not enabled the 'contactform_confirmation' email template will be sent",
                verbose_name="API stuurt bevestiging",
            ),
        ),
    ]
