# Generated by Django 4.2.11 on 2024-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "openklant",
            "0011_alter_openklantconfig_use_rsin_for_innnnpid_query_parameter",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="openklantconfig",
            name="send_email_confirmation",
            field=models.BooleanField(
                default=False,
                help_text="If enabled the 'contactform_confirmation' email template will be sent. If disabled the external API will send a confirmation email.",
                verbose_name="Stuur contactformulier e-mailbevestiging",
            ),
        ),
    ]
