# Generated by Django 4.2.15 on 2024-09-06 10:04

from django.db import migrations, models

import django_jsonform.models.fields

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0012_openklantconfig_send_email_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="openklantconfig",
            name="exclude_contactmoment_kanalen",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    help_text="Contactmomenten registered via one of these channels will not be displayed to users.",
                    max_length=100,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                validators=[
                    open_inwoner.utils.validators.validate_array_contents_non_empty
                ],
            ),
        ),
    ]
