# Generated by Django 4.2.16 on 2024-11-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0014_contactformconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactformconfig",
            name="title",
            field=models.TextField(
                blank=True, help_text="Title of the contact form.", verbose_name="Title"
            ),
        ),
    ]
