# Generated by Django 4.2.16 on 2024-12-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0014_contactformconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="KlantenInteractiesConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuratie Klanten Interacties",
            },
        ),
        migrations.AlterModelOptions(
            name="openklantconfig",
            options={"verbose_name": "Esuite configuration"},
        ),
        migrations.CreateModel(
            name="OpenKlant2Config2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_root", models.URLField(verbose_name="API root url")),
                ("api_token", models.CharField(verbose_name="API key token")),
                (
                    "mijn_vragen_kanaal",
                    models.CharField(verbose_name="Mijn vragen kanaal"),
                ),
                (
                    "mijn_vragen_organisatie_naam",
                    models.CharField(verbose_name="Mijn vragen organisatie naam"),
                ),
                (
                    "mijn_vragen_actor",
                    models.CharField(verbose_name="Mijn vragen actor"),
                ),
                (
                    "interne_taak_gevraagde_handeling",
                    models.CharField(verbose_name="Interne taak gevraagde handeling"),
                ),
                (
                    "interne_taak_toelichting",
                    models.CharField(verbose_name="Interne taak toelichting"),
                ),
                (
                    "config",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openklant.klanteninteractiesconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Klant configuration",
            },
        ),
        migrations.AddField(
            model_name="openklantconfig",
            name="config",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="openklant.klanteninteractiesconfig",
            ),
        ),
        migrations.AlterField(
            model_name="contactformsubject",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="openklant.klanteninteractiesconfig",
            ),
        ),
    ]
