# Generated by Django 4.2.16 on 2024-12-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
        ("openklant", "0014_contactformconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenKlant2Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mijn_vragen_kanaal",
                    models.CharField(
                        blank=True, default="", verbose_name="Mijn vragen kanaal"
                    ),
                ),
                (
                    "mijn_vragen_organisatie_naam",
                    models.CharField(
                        blank=True,
                        default="",
                        verbose_name="Mijn vragen organisatie naam",
                    ),
                ),
                (
                    "mijn_vragen_actor",
                    models.CharField(
                        blank=True, default="", verbose_name="Mijn vragen actor"
                    ),
                ),
                (
                    "interne_taak_gevraagde_handeling",
                    models.CharField(
                        blank=True,
                        default="",
                        verbose_name="Interne taak gevraagde handeling",
                    ),
                ),
                (
                    "interne_taak_toelichting",
                    models.CharField(
                        blank=True, default="", verbose_name="Interne taak toelichting"
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Klanten API",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenKlant2 configuration",
            },
        ),
    ]
