# Generated by Django 4.2.16 on 2025-01-08 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
        ("openklant", "0016_klantensysteemconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openklant2config",
            name="service",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Klanten API",
            ),
        ),
    ]
