# Generated by Django 4.2.16 on 2025-01-16 14:41

from django.db import migrations, models
import open_inwoner.openklant.models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0018_rename_openklantconfig_esuiteklantconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klantensysteemconfig",
            name="primary_backend",
            field=models.CharField(
                choices=[("esuite", "ESUITE"), ("openklant2", "OPENKLANT2")],
                help_text="Choose the primary backend for retrieving klanten data. Changes to klanten data will be saved to both backends (if configured).",
                max_length=10,
                validators=[open_inwoner.openklant.models.validate_primary_backend],
                verbose_name="Primary backend",
            ),
        ),
    ]
