# Generated by Django 4.2.16 on 2025-01-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0019_alter_klantensysteemconfig_primary_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openklant2config",
            name="interne_taak_gevraagde_handeling",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Beschrijving van de gevraagde handeling voor de interne taak die ontstaat als resultaat van een vraag",
                verbose_name="Interne taak gevraagde handeling",
            ),
        ),
        migrations.AlterField(
            model_name="openklant2config",
            name="interne_taak_toelichting",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Toelichting bij de gevraagde handeling voor de interne taak die ontstaat als resultaat van een vraag",
                verbose_name="Interne taak toelichting",
            ),
        ),
        migrations.AlterField(
            model_name="openklant2config",
            name="mijn_vragen_actor",
            field=models.CharField(
                blank=True,
                default="",
                help_text="De UUID van een bestaande Actor in de de configureerde API waaraan nieuwe vragen worden toegewezen",
                verbose_name="Mijn vragen actor",
            ),
        ),
        migrations.AlterField(
            model_name="openklant2config",
            name="mijn_vragen_kanaal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Het kanaal waaronder nieuwe vragen als Klantcontact object zullen worden aangemaakt",
                verbose_name="Mijn vragen kanaal",
            ),
        ),
    ]
