# Generated by Django 4.2.16 on 2025-01-14 13:42

from django.db import migrations


def migrate_registration_defaults(apps, _):
    ESuiteKlantConfig = apps.get_model("openklant", "ESuiteKlantConfig")
    KlantenSysteemConfig = apps.get_model("openklant", "KlantenSysteemConfig")

    es_config = ESuiteKlantConfig.objects.first()
    klanten_config = KlantenSysteemConfig.objects.first()

    if es_config and klanten_config:
        klanten_config.register_contact_via_api = es_config.register_contact_moment
        klanten_config.register_contact_email = es_config.register_email
        klanten_config.send_email_confirmation = es_config.send_email_confirmation
        klanten_config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0021_klantensysteemconfig_register_contact_email_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_registration_defaults,
            reverse_code=migrations.RunPython.noop,
        )
    ]
