# Generated by Django 4.2.18 on 2025-01-29 09:03

from django.db import migrations, models

import open_inwoner.openklant.models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0023_remove_esuiteklantconfig_register_contact_moment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klantensysteemconfig",
            name="primary_backend",
            field=models.CharField(
                choices=[("esuite", "ESUITE"), ("openklant2", "OPENKLANT2")],
                help_text="Choose the primary backend for retrieving klanten data. Changes to klanten data will be saved to both backends (if configured).",
                max_length=10,
                validators=[open_inwoner.openklant.models.validate_backend_choice],
                verbose_name="Primary backend",
            ),
        ),
    ]
