# Generated by Django 4.2.18 on 2025-02-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "openklant",
            "0024_rename_subject_code_contactformsubject_esuite_subject_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="esuiteklantconfig",
            name="send_klantcontact_confirmation_email",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, a confirmation email will be sent upon registering a klantcontact.",
                verbose_name="Send confirmation email for registration of klantcontact",
            ),
        ),
    ]
