# Generated by Django 4.2.18 on 2025-01-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0024_alter_klantensysteemconfig_primary_backend"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactformsubject",
            old_name="subject_code",
            new_name="esuite_subject_code",
        ),
        migrations.RemoveField(
            model_name="contactformsubject",
            name="config",
        ),
        migrations.AddField(
            model_name="contactformsubject",
            name="esuite_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="openklant.esuiteklantconfig",
            ),
        ),
        migrations.AlterField(
            model_name="contactformsubject",
            name="esuite_subject_code",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="e-Suite 'onderwerp' code",
            ),
        ),
        migrations.AddField(
            model_name="contactformsubject",
            name="openklant_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="openklant.openklant2config",
            ),
        ),
    ]
