# Generated by Django 4.2.18 on 2025-03-04 13:08

from django.db import migrations
from django.db.models import Q


def set_default_for_klant_config(apps, _):
    ContactFormSubject = apps.get_model("openklant", "ContactFormSubject")
    ESuiteKlantConfig = apps.get_model("openklant", "ESuiteKlantConfig")
    OpenKlant2Config = apps.get_model("openklant", "OpenKlant2Config")

    for contact_form_subject in ContactFormSubject.objects.filter(
        Q(esuite_config__isnull=True) | Q(openklant_config__isnull=True)
    ):
        contact_form_subject.esuite_config = (
            contact_form_subject.esuite_config or ESuiteKlantConfig.objects.first()
        )
        contact_form_subject.openklant_config = (
            contact_form_subject.esuite_config or OpenKlant2Config.objects.first()
        )
        contact_form_subject.save()


def delete_default_for_klant_config(apps, _):
    ContactFormSubject = apps.get_model("openklant", "ContactFormSubject")

    for contact_form_subject in ContactFormSubject.objects.filter(
        Q(esuite_config__isnull=False) | Q(openklant_config__isnull=False)
    ):
        contact_form_subject.esuite_config = None
        contact_form_subject.openklant_config = None
        contact_form_subject.save()


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0025_esuiteklantconfig_send_klantcontact_confirmation_email"),
    ]

    operations = [
        migrations.RunPython(
            code=set_default_for_klant_config,
            reverse_code=delete_default_for_klant_config,
        )
    ]
