# Generated by Django 4.2.20 on 2025-04-23 08:21

from django.db import migrations, models

import open_inwoner.openklant.models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0026_contactform_subject_config_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klantensysteemconfig",
            name="primary_backend",
            field=models.CharField(
                blank=True,
                choices=[("esuite", "ESUITE"), ("openklant2", "OPENKLANT2")],
                help_text="Choose the primary backend for retrieving klanten data. Changes to klanten data will be saved to both backends (if configured).",
                max_length=10,
                validators=[open_inwoner.openklant.models.validate_backend_choice],
                verbose_name="Primary backend",
            ),
        ),
    ]
