# Generated by Django 4.2.22 on 2025-08-26 13:34

from django.db import migrations, models


def copy_contactform_description(apps, _):
    ContactFormConfig = apps.get_model("openklant", "ContactFormConfig")

    for config in ContactFormConfig.objects.all():
        old_description = config.description

        config.description_authenticated_user = old_description
        config.description_anonymous_user = old_description
        config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0027_alter_klantensysteemconfig_primary_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactformconfig",
            name="description_anonymous_user",
            field=models.TextField(
                blank=True,
                help_text="Description of the contact form for anonymous/non-authenticated users",
                verbose_name="Description anonymous users",
            ),
        ),
        migrations.AddField(
            model_name="contactformconfig",
            name="description_authenticated_user",
            field=models.TextField(
                blank=True,
                help_text="Description of the contact form for authenticated users",
                verbose_name="Description authenticated users",
            ),
        ),
        migrations.RunPython(
            code=copy_contactform_description,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="contactformconfig",
            name="description",
        ),
    ]
