# Generated by Django 4.2.25 on 2025-10-06 16:15

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0028_change_contactformconfig_descriptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactformconfig",
            name="description_anonymous_user",
        ),
        migrations.AddField(
            model_name="contactformconfig",
            name="description_anonymous_user",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                help_text="Description of the contact form for anonymous/non-authenticated users",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Description anonymous users",
            ),
        ),
        migrations.RemoveField(
            model_name="contactformconfig",
            name="description_authenticated_user",
        ),
        migrations.AddField(
            model_name="contactformconfig",
            name="description_authenticated_user",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                help_text="Description of the contact form for authenticated users",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Description authenticated users",
            ),
        ),
    ]
