# Generated by Django 4.2.25 on 2025-10-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0025_service_jwt_valid_for"),
        ("openklant", "0029_contactformconfig_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openklant2config",
            name="service",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Klanten API",
            ),
        ),
    ]
