# Generated by Django 4.2.28 on 2026-03-02 12:43

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0030_alter_openklant2config_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactformconfig",
            name="description_anonymous_user",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                blank=True,
                default=None,
                help_text="Description of the contact form for anonymous/non-authenticated users",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Description anonymous users",
            ),
        ),
        migrations.AlterField(
            model_name="contactformconfig",
            name="description_authenticated_user",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                blank=True,
                default=None,
                help_text="Description of the contact form for authenticated users",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Description authenticated users",
            ),
        ),
    ]
