# Generated by Django 5.2.14 on 2026-06-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0095_remove_phonenumber_alternative"),
        (
            "openklant",
            "0031_alter_contactformconfig_description_anonymous_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitaalAdresKlant2Mapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ok2_uuid", models.UUIDField(verbose_name="OpenKlant2 UUID")),
                (
                    "digital_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openklant2_mapping",
                        to="accounts.digitaladdress",
                        verbose_name="Digital address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digitaal adres OpenKlant2 mapping",
                "verbose_name_plural": "Digitaal adres OpenKlant2 mappings",
            },
        ),
    ]
