# Generated by Django 5.2.14 on 2026-06-15 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0094_add_digitaladdress_and_preferred_address"),
        (
            "openklant",
            "0031_alter_contactformconfig_description_anonymous_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitaalAdresOpenKlantMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ok_uuid", models.UUIDField(verbose_name="OpenKlant UUID")),
                (
                    "digital_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openklant_mapping",
                        to="accounts.digitaladdress",
                        verbose_name="Digital address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digitaal adres OpenKlant mapping",
                "verbose_name_plural": "Digitaal adres OpenKlant mappings",
            },
        ),
    ]
