# Generated by Django 5.2.16 on 2026-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0032_digitaaladresopenklantmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="esuiteklantconfig",
            name="contactmoment_fetch_timeout",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Total time budget in seconds for retrieving contactmomenten for the 'Mijn vragen' pages. Contactmomenten still outstanding when the budget runs out are reported as missing rather than delaying the page further. Set slightly below the overall HTTP response timeout of the server.",
                verbose_name="Contactmoment fetch timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="esuiteklantconfig",
            name="contactmoment_num_workers",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Maximum number of worker threads used to retrieve contactmomenten in parallel for the 'Mijn vragen' pages. Leave empty to use the default.",
                null=True,
                verbose_name="Contactmoment worker threads",
            ),
        ),
    ]
