# Generated by Django 5.2.16 on 2026-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0033_esuiteklantconfig_contactmoment_fetch_timeout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="esuiteklantconfig",
            name="contactmoment_cache_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                default=300,
                help_text="How long (in seconds) a resolved contactmoment is cached. Since a contactmoment can gain an answer after it was first cached, this is how long an answer can take to appear after it was actually given. Leave empty to disable caching.",
                null=True,
                verbose_name="Contactmoment cache timeout (seconds)",
            ),
        ),
    ]
