# Generated by Django 5.2.16 on 2026-07-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0034_esuiteklantconfig_contactmoment_cache_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="openklant2config",
            name="partij_cache_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                default=300,
                help_text="How long (in seconds) the partij belonging to a user is remembered. Every klantinteracties page starts by resolving this, so caching it saves a request per page view. Only the identifier is cached, not the partij data itself. Leave empty to disable caching.",
                null=True,
                verbose_name="Partij cache timeout (seconds)",
            ),
        ),
    ]
