# Generated by Django 5.2.16 on 2026-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0035_openklant2config_partij_cache_timeout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esuiteklantconfig",
            name="contactmoment_cache_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                default=300,
                help_text="How long (in seconds) contactmoment data is cached: both a klant's list of klantcontactmomenten and each resolved contactmoment. Since a contactmoment can gain an answer after it was first cached, this is how long an answer can take to appear after it was actually given. A question asked through this site always appears immediately regardless. Leave empty to disable caching.",
                null=True,
                verbose_name="Contactmoment cache timeout (seconds)",
            ),
        ),
    ]
