# Generated by Django 5.2.16 on 2026-08-11 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0036_alter_esuiteklantconfig_contactmoment_cache_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="esuiteklantconfig",
            name="contactmoment_max_requests",
            field=models.PositiveIntegerField(
                default=5,
                help_text="How many further pages of a klant's klantcontactmomenten are retrieved after the first one, so that a klant with a long history has a bounded worst case. A klant with more klantcontactmomenten than fit in these pages sees only the most recent ones. Raising this raises the cost of every 'Mijn vragen' page view and of the cache warm-up on login.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Contactmoment pagination requests",
            ),
        ),
    ]
