# Generated by Django 5.2.16 on 2026-08-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0037_esuiteklantconfig_contactmoment_max_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openklant2config",
            name="mijn_vragen_kanaal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Het kanaal waaronder nieuwe vragen als Klantcontact object zullen worden aangemaakt. Dit kanaal wordt alleen gebruikt bij het aanmaken van vragen: het ophalen van vragen en reacties is niet beperkt tot dit kanaal.",
                verbose_name="Mijn vragen kanaal",
            ),
        ),
    ]
