# Generated by Django 5.2.16 on 2026-08-26 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0038_alter_openklant2config_mijn_vragen_kanaal"),
    ]

    operations = [
        migrations.AddField(
            model_name="openklant2config",
            name="vragen_cache_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                default=300,
                help_text="How long a user's questions and reactions are remembered, so that not every page view has to look them up again. A reaction registered elsewhere can take this long to show up; anything done through this site appears immediately. Leave empty to disable caching.",
                null=True,
                verbose_name="Vragen cache timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="openklant2config",
            name="vragen_fetch_timeout",
            field=models.PositiveIntegerField(
                default=15,
                help_text="How long looking up reactions for the 'Mijn vragen' pages may take in total. Whatever is not found within this time is left out, and the user is told the overview is incomplete and offered a retry, rather than kept waiting. Keep this below the time limit of the web server.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Vragen fetch timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="openklant2config",
            name="vragen_num_workers",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="How many reactions are looked up at the same time while building the 'Mijn vragen' pages. A higher number makes those pages faster but asks more of the Klanten API at once. Leave empty to use the default.",
                null=True,
                verbose_name="Vragen worker threads",
            ),
        ),
    ]
