# Generated by Django 5.2.16 on 2026-08-31 13:16

from django.db import migrations, models

from open_inwoner.utils.url import uuid_from_url

# Rows are updated in batches so that a large table does not turn one statement into
# a long lock.
_BATCH_SIZE = 1000


def carry_over_seen_answers(apps, schema_editor):
    """Record which answer a user has seen, where that can still be worked out.

    eSuite holds one answer per contactmoment, so for its rows `contactmoment_url`
    identifies the answer that was seen and the flag translates exactly. A Klanten API
    row's url is the question's klantcontact rather than the answer's, so the uuid
    taken from it can never match an answer and those rows behave as unseen: which
    answer was read is not recorded anywhere, and cannot be recovered. That shows the
    citizen one more "new answer" badge for a question answered recently, which is
    preferable to claiming they have read an answer we cannot identify.
    """
    KlantContactMomentAnswer = apps.get_model("openklant", "KlantContactMomentAnswer")

    batch = []
    for row in (
        KlantContactMomentAnswer.objects.filter(
            is_seen=True, last_seen_answer_uuid__isnull=True
        )
        .only("id", "contactmoment_url")
        .iterator(chunk_size=_BATCH_SIZE)
    ):
        if not (seen_uuid := uuid_from_url(row.contactmoment_url)):
            continue

        row.last_seen_answer_uuid = seen_uuid
        batch.append(row)

        if len(batch) >= _BATCH_SIZE:
            KlantContactMomentAnswer.objects.bulk_update(
                batch, ["last_seen_answer_uuid"]
            )
            batch = []

    if batch:
        KlantContactMomentAnswer.objects.bulk_update(batch, ["last_seen_answer_uuid"])


def restore_seen_flag(apps, schema_editor):
    """Reverse of the above: flag everyone known to have seen an answer.

    Which answer that was is precisely what a boolean cannot hold, so going back
    keeps that a user has read something and loses what it was.
    """
    KlantContactMomentAnswer = apps.get_model("openklant", "KlantContactMomentAnswer")
    KlantContactMomentAnswer.objects.filter(last_seen_answer_uuid__isnull=False).update(
        is_seen=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("openklant", "0039_openklant2config_vragen_cache_timeout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="klantcontactmomentanswer",
            name="last_seen_answer_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="The most recent answer the user has seen. A question can collect several answers over time, so recording which one was seen is what makes a later answer show as new. Empty until the user opens a question that has one.",
                null=True,
                verbose_name="Last seen answer",
            ),
        ),
        migrations.RunPython(carry_over_seen_answers, restore_seen_flag),
        # Dropped only after the carry-over above has read it.
        migrations.RemoveField(
            model_name="klantcontactmomentanswer",
            name="is_seen",
        ),
    ]
