---

user_name: maykin
group_name: staff
project_name: open-inwoner
project_root: "/srv/sites/{{ project_name }}-{{ target }}"
project_src_dir: "open-inwoner"
celery_worker_path: "open-inwoner"
django_settings_module: "{{ project_src_dir }}.conf.{{ target }}"

django_secret_key: "wvi=esi+d^4x*#=72*u=sr2hm0!n%y39numxcbevx)%u-#v%l7"

pub_key_users:
  - alex
  - joeri
  - jorik
  - sven
  - sjoerd

project_repo: git@github.com:maykinmedia/open-inwoner.git
branch: develop

nginx_access_log_file: "{{ project_root }}/log/nginx/access.log"
nginx_error_log_file: "{{ project_root }}/log/nginx/error.log"
nginx_static_dir: "{{ project_root }}/static/"
nginx_media_dir: "{{ project_root }}/media/"
extra_path: ""  # If the root project can return a 404

nginx_basicauth_user: maykin
nginx_basicauth_password: nogniet

# Needed for creating superuser when deployed as Docker container.
# docker: true
# container_name: "{{ openzaak_replicas.0.name }}"

django_superuser_username: maykin
django_superuser_email: support@maykinmedia.nl

sentry_slug: "{{ project_name }} - {{ target }}"

uptimerobot_monitor_friendly_name: "{{ project_name }} - {{ target }}"
uptimerobot_monitor_url: "https://{{ nginx_server_name }}"
