# Generated by Django 4.2.10 on 2024-03-08 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("laposta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_id",
                    models.CharField(
                        help_text="Unique ID of the list in the API",
                        max_length=50,
                        verbose_name="List ID",
                    ),
                ),
                (
                    "member_id",
                    models.CharField(
                        help_text="Unique ID of the member for this list in the API",
                        max_length=50,
                        verbose_name="Member ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "unique_together": {("list_id", "member_id")},
            },
        ),
    ]
