# Generated by Django 4.2.10 on 2024-03-11 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laposta", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="lapostaconfig",
            name="limit_list_selection_to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="If configured, users will only be able to choose from this selection of lists to subscribe to",
                size=None,
                verbose_name="Limit list selection to",
            ),
        ),
    ]
