# Generated by Django 4.2.11 on 2024-04-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laposta", "0003_lapostaconfig_limit_list_selection_to"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
