# Generated by Django 3.2.15 on 2023-04-24 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonExtension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requires_auth",
                    models.BooleanField(
                        default=False,
                        help_text="Deze pagina vereist een account",
                        verbose_name="Requires authentication",
                    ),
                ),
                (
                    "requires_auth_bsn",
                    models.BooleanField(
                        default=False,
                        help_text="Deze pagina vereist een account met een Digid BSN",
                        verbose_name="Requires BSN authentication",
                    ),
                ),
                (
                    "extended_object",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.page",
                    ),
                ),
                (
                    "public_extension",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_extension",
                        to="extensions.commonextension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
