# Generated by Django 3.2.15 on 2023-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extensions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonextension",
            name="menu_indicator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plan_new_contacts", "Plans > new contacts"),
                    ("inbox_new_messages", "Inbox > new messages"),
                ],
                help_text="Toon een counter naast het label",
                max_length=32,
                verbose_name="Indicator",
            ),
        ),
    ]
