# Generated by Django 3.2.20 on 2023-11-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extensions", "0005_alter_commonextension_menu_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commonextension",
            old_name="requires_auth_bsn",
            new_name="requires_auth_bsn_or_kvk",
        ),
    ]
