# Generated by Django 3.2.15 on 2023-08-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extensions", "0005_alter_commonextension_menu_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonextension",
            name="help_text",
            field=models.TextField(
                blank=True, help_text="Help text for the page", verbose_name="Help text"
            ),
        ),
    ]
