# Generated by Django 3.2.20 on 2023-11-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extensions",
            "0006_rename_requires_auth_bsn_commonextension_requires_auth_bsn_or_kvk",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonextension",
            name="requires_auth_bsn_or_kvk",
            field=models.BooleanField(
                default=False,
                help_text="Deze pagina vereist een account met een Digid BSN of eHerkenning KvK",
                verbose_name="Requires DigiD/eHerkenning authentication",
            ),
        ),
    ]
