# Generated by Django 3.2.15 on 2023-11-11 10:00

from django.db import migrations, models
from django.db.models import Q

from cms.models import Page


def set_help_texts(apps, schema_editor):
    PageModel = apps.get_model("cms", "Page")

    # pages = PageModel.objects.filter(
    #     Q(publisher_is_draft=False) and Q(commonextension__isnull=False)
    # )

    for page in Page.objects.all():
        page.commonextension.help_text = "hello world"
        setattr(page.commonextension, "help_text", "hello world")
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("extensions", "0006_commonextension_help_text"),
    ]

    operations = [
        migrations.RunPython(set_help_texts, reverse_code=migrations.RunPython.noop)
    ]
