# Generated by Django 4.2.21 on 2025-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0007_alter_commonextension_requires_auth_bsn_or_kvk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonextension",
            name="menu_icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person", "User"),
                    ("description", "Products"),
                    ("inbox", "Inbox"),
                    ("inventory_2", "Cases"),
                    ("group", "Collaborate"),
                    ("help", "Help"),
                    ("euro", "Benefits"),
                ],
                help_text="Icon in het menu",
                max_length=32,
                verbose_name="Icon",
            ),
        ),
    ]
