# Generated by Django 4.2.21 on 2025-07-28 14:43

from django.db import migrations, models


def map_icon_values(apps, schema_editor):
    CommonExtension = apps.get_model("extensions", "CommonExtension")

    # Euro_outline is an invalid name, note that help_outline is valid
    CommonExtension.objects.filter(menu_icon="euro_outline").update(menu_icon="euro")


def reverse_map_icon_values(apps, schema_editor):
    CommonExtension = apps.get_model("extensions", "CommonExtension")

    # Revert to the initial mapping
    CommonExtension.objects.filter(menu_icon="euro").update(menu_icon="euro_outline")


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0007_alter_commonextension_requires_auth_bsn_or_kvk"),
    ]

    operations = [
        # Note that the ORM itself does not validate the TextChoices, we can (re)map
        # prior to the field being altered
        migrations.RunPython(
            map_icon_values,
            reverse_map_icon_values,
        ),
        migrations.AlterField(
            model_name="commonextension",
            name="menu_icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person", "User"),
                    ("description", "Products"),
                    ("inbox", "Inbox"),
                    ("inventory_2", "Cases"),
                    ("group", "Collaborate"),
                    ("help_outline", "Help"),
                    ("euro", "Benefits"),
                ],
                help_text="Icon in het menu",
                max_length=32,
                verbose_name="Icon",
            ),
        ),
    ]
