# Generated by Django 3.2.15 on 2023-06-27 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("soap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSDConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gemeentecode",
                    models.CharField(
                        blank=True,
                        help_text="Municipality code to register zaken",
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Expected a numerical value.", regex="^[0-9]+$"
                            )
                        ],
                        verbose_name="Municipality code",
                    ),
                ),
                (
                    "bedrijfs_naam",
                    models.CharField(
                        blank=True,
                        help_text="Name of the supplier",
                        max_length=32,
                        validators=[open_inwoner.utils.validators.CharFieldValidator()],
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "applicatie_naam",
                    models.CharField(
                        blank=True,
                        help_text="Name of the application",
                        max_length=32,
                        validators=[open_inwoner.utils.validators.CharFieldValidator()],
                        verbose_name="Application Name",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="soap.soapservice",
                        verbose_name="SOAP Service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
