# Generated by Django 3.2.15 on 2023-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_available_from",
            field=models.CharField(
                default="29-01",
                help_text="Day and month from when the report for the preceding year is available for download",
                max_length=5,
                verbose_name="Yearly report available from (dd-mm)",
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_comments",
            field=models.TextField(
                blank=True,
                help_text="Help text for the columns in the Jaaropgave PDF",
                verbose_name="PDF help text",
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_delta",
            field=models.SmallIntegerField(
                default=3, verbose_name="Show reports for the last # years"
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_display_text",
            field=models.TextField(
                blank=True,
                help_text="The text displayed as overview of the 'Jaaropgave' tab",
                max_length=704,
                verbose_name="Display text",
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable download"),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="maandspecificatie_available_from",
            field=models.SmallIntegerField(
                default=25,
                help_text="Day of the month from when the report for the preceding month is available for download",
                verbose_name="Report available from the # day of the month",
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="maandspecificatie_delta",
            field=models.SmallIntegerField(
                default=12, verbose_name="Show reports for the last # months"
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="maandspecificatie_display_text",
            field=models.TextField(
                blank=True,
                help_text="The text displayed as overview of the 'Maandspecificatie' tab",
                max_length=704,
                verbose_name="Display text",
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="maandspecificatie_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable download"),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="mijn_uitkeringen_text",
            field=models.TextField(
                blank=True,
                help_text="The text displayed as overview of the 'Mijn Uikeringen' section.",
                max_length=704,
                verbose_name="Overview text",
            ),
        ),
    ]
