# Generated by Django 3.2.15 on 2023-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_available_from",
            field=models.CharField(
                default="29-01",
                help_text="Month from when the report for the preceding year is available for download",
                max_length=5,
                verbose_name="Yearly report available from (dd-mm)",
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Enable download of yearly reports"
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_range",
            field=models.SmallIntegerField(
                default=3, verbose_name="Show yearly reports for the last # years"
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="maandspecificatie_available_from",
            field=models.SmallIntegerField(
                default=25,
                help_text="Day of the month from when the report for the preceding month is available for download",
                verbose_name="Monthly report available from the # day of the month",
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="maandspecificatie_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Enable download of monthly reports"
            ),
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="maandspecificatie_range",
            field=models.SmallIntegerField(
                default=12, verbose_name="Show yearly reports for the last # months"
            ),
        ),
    ]
