# Generated by Django 3.2.15 on 2023-07-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssd", "0002_auto_20230722_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_comments",
            field=models.TextField(
                blank=True,
                help_text="Help text for the columns in the Jaaropgave PDF",
                verbose_name="Jaaropgave help text",
            ),
        ),
    ]
