# Generated by Django 3.2.15 on 2023-07-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssd", "0002_auto_20230722_1545"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssdconfig",
            name="jaaropgave_available_from",
        ),
        migrations.RemoveField(
            model_name="ssdconfig",
            name="jaaropgave_enabled",
        ),
        migrations.RemoveField(
            model_name="ssdconfig",
            name="jaaropgave_range",
        ),
        migrations.RemoveField(
            model_name="ssdconfig",
            name="maandspecificatie_available_from",
        ),
        migrations.RemoveField(
            model_name="ssdconfig",
            name="maandspecificatie_enabled",
        ),
        migrations.RemoveField(
            model_name="ssdconfig",
            name="maandspecificatie_range",
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="mijn_uitkeringen_text",
            field=models.TextField(
                blank=True,
                help_text="The text displayed as overview of the 'Mijn Uikeringen' section.",
                max_length=704,
                verbose_name="Overview text",
            ),
        ),
        migrations.CreateModel(
            name="MaandspecificatieConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maandspecificatie_enabled",
                    models.BooleanField(default=True, verbose_name="Enable download"),
                ),
                (
                    "maandspecificatie_delta",
                    models.SmallIntegerField(
                        default=12, verbose_name="Show reports for the last # months"
                    ),
                ),
                (
                    "maandspecificatie_available_from",
                    models.SmallIntegerField(
                        default=25,
                        help_text="Day of the month from when the report for the preceding month is available for download",
                        verbose_name="Report available from the # day of the month",
                    ),
                ),
                (
                    "display_text",
                    models.TextField(
                        blank=True,
                        help_text="The text displayed as overview of the 'Maandspecificatie' tab",
                        max_length=704,
                        verbose_name="Display text",
                    ),
                ),
                (
                    "client_config",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maandspecificatie",
                        to="ssd.ssdconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JaaropgaveConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jaaropgave_enabled",
                    models.BooleanField(default=True, verbose_name="Enable download"),
                ),
                (
                    "jaaropgave_delta",
                    models.SmallIntegerField(
                        default=3, verbose_name="Show reports for the last # years"
                    ),
                ),
                (
                    "jaaropgave_available_from",
                    models.CharField(
                        default="29-01",
                        help_text="Day and month from when the report for the preceding year is available for download",
                        max_length=5,
                        verbose_name="Yearly report available from (dd-mm)",
                    ),
                ),
                (
                    "display_text",
                    models.TextField(
                        blank=True,
                        help_text="The text displayed as overview of the 'Jaaropgave' tab",
                        max_length=704,
                        verbose_name="Display text",
                    ),
                ),
                (
                    "jaaropgave_comments",
                    models.TextField(
                        blank=True,
                        help_text="Help text for the columns in the Jaaropgave PDF",
                        verbose_name="PDF help text",
                    ),
                ),
                (
                    "client_config",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jaaropgave",
                        to="ssd.ssdconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
