# Generated by Django 3.2.15 on 2023-07-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ssd", "0003_auto_20230726_1517"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jaaropgaveconfig",
            old_name="display_text",
            new_name="mijn_uitkeringen_text",
        ),
    ]
