# Generated by Django 3.2.15 on 2023-07-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ssd", "0004_rename_display_text_jaaropgaveconfig_mijn_uitkeringen_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jaaropgaveconfig",
            old_name="mijn_uitkeringen_text",
            new_name="display_text",
        ),
    ]
