# Generated by Django 4.2.11 on 2024-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssd", "0005_fix_translations_typo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ssdconfig",
            old_name="jaaropgave_comments",
            new_name="jaaropgave_pdf_comments",
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="maandspecificatie_pdf_comments",
            field=models.TextField(
                blank=True,
                help_text="Optional comments to be included in the maandspecificatie PDF. Markdown formatting is supported.",
                verbose_name="PDF help text",
            ),
        ),
    ]
