# Generated by Django 4.2.24 on 2025-10-01 08:48

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        (
            "ssd",
            "0006_rename_jaaropgave_comments_ssdconfig_jaaropgave_pdf_comments_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ssdconfig",
            old_name="jaaropgave_display_text",
            new_name="jaaropgave_display_text_tmp",
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_display_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                verbose_name="Display text",
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
                help_text="The text displayed as overview of the 'Jaaropgave' tab",
            ),
        ),
    ]
