# Generated by Django 4.2.24 on 2025-10-01 08:48

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("ssd", "0009_ssdconfig_jaaropgave_display_text_schema_2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ssdconfig",
            old_name="jaaropgave_pdf_comments",
            new_name="jaaropgave_pdf_comments_tmp",
        ),
        migrations.AddField(
            model_name="ssdconfig",
            name="jaaropgave_pdf_comments",
            field=django_prosemirror.fields.ProsemirrorModelField(
                verbose_name="PDF help text",
                help_text="Optional comments to be included in the jaaropgave PDF. Markdown formatting is supported.",
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                allowed_mark_types=[],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
            ),
        ),
    ]
