# Generated by Django 4.2.24 on 2025-10-01 08:48

import logging  # noqa: TID251 - keep for old migrations
from functools import partial

from django.db import migrations

import markdown
from django_prosemirror.config import ProsemirrorConfig
from django_prosemirror.schema import MarkType, NodeType
from django_prosemirror.serde import html_to_doc

logger = logging.getLogger(__name__)


def migrate_ssd_field(apps, schema_editor, field_name, convert_markdown=False):
    SSDConfig = apps.get_model("ssd", "SSDConfig")

    row = SSDConfig.objects.values("pk", f"{field_name}_tmp").first()

    if not row:
        return

    content = row[f"{field_name}_tmp"]

    if not content or not content.strip():
        return

    config = ProsemirrorConfig(
        allowed_node_types=[NodeType.PARAGRAPH],
        allowed_mark_types=[
            MarkType.STRONG,
            MarkType.ITALIC,
            MarkType.LINK,
            MarkType.UNDERLINE,
        ],
    )

    if convert_markdown:
        content = markdown.markdown(content, extensions=["extra"])

    content = content.strip('"')

    if not content.startswith("<p>"):
        content = f"<p>{content}</p>"

    try:
        doc = html_to_doc(content, schema=config.schema)
    except (IndexError, ValueError):
        logger.exception("Warning: Could not convert description for ssd_config")
        return

    SSDConfig.objects.filter(pk=row["pk"]).update(**{field_name: doc})


migrate_maandspecificatie_display_text = partial(
    migrate_ssd_field,
    field_name="maandspecificatie_display_text",
    convert_markdown=True,
)


class Migration(migrations.Migration):
    dependencies = [
        ("ssd", "0013_ssdconfig_maandspecificatie_display_text_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_maandspecificatie_display_text,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
