# Generated by Django 4.2.24 on 2025-10-01 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssd", "0017_ssdconfig_maandspecificatie_pdf_comments_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssdconfig",
            name="maandspecificatie_pdf_comments_tmp",
        ),
    ]
