# Generated by Django 4.2.28 on 2026-03-02 12:43

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("ssd", "0018_ssdconfig_maandspecificatie_pdf_comments_schema_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssdconfig",
            name="jaaropgave_display_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                blank=True,
                default=None,
                help_text="The text displayed as overview of the 'Jaaropgave' tab",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Display text",
            ),
        ),
        migrations.AlterField(
            model_name="ssdconfig",
            name="jaaropgave_pdf_comments",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                blank=True,
                default=None,
                help_text="Optional comments to be included in the jaaropgave PDF. Markdown formatting is supported.",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="PDF help text",
            ),
        ),
        migrations.AlterField(
            model_name="ssdconfig",
            name="maandspecificatie_display_text",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                blank=True,
                default=None,
                help_text="The text displayed as overview of the 'Maandspecificatie' tab",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Display text",
            ),
        ),
        migrations.AlterField(
            model_name="ssdconfig",
            name="maandspecificatie_pdf_comments",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                blank=True,
                default=None,
                help_text="Optional comments to be included in the maandspecificatie PDF. Markdown formatting is supported.",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="PDF help text",
            ),
        ),
    ]
