# Generated by Django 5.2.17 on 2026-09-21 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssd", "0019_alter_ssdconfig_jaaropgave_display_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ssdconfig",
            options={"verbose_name": "Mijn uitkeringen"},
        ),
    ]
