# Generated by Django 5.2.17 on 2026-09-23 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssd", "0020_alter_ssdconfig_options"),
        ("ssd", "0020_sanitize_prosemirror_link_hrefs"),
    ]

    operations = []
