# Generated by Django 3.2.15 on 2023-06-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0018_zaaktypeconfig_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypeconfig",
            name="contact_moments_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Enable sending questions via OpenKlant API"
            ),
        ),
    ]
