# Generated by Django 3.2.15 on 2023-06-23 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0019_zaaktypeconfig_contact_moments_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zaaktypeconfig",
            old_name="contact_moments_enabled",
            new_name="contact_form_enabled",
        ),
    ]
