# Generated by Django 4.2.18 on 2025-01-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0062_zgwapigroupconfig_klant_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openzaakconfig",
            name="show_cases_without_status",
            field=models.BooleanField(
                default=False,
                help_text="By default cases are only shown if they have a status set.",
                verbose_name="Show cases without status",
            ),
        ),
    ]
