# Generated by Django 4.2.16 on 2025-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0064_remove_openzaakconfig_enable_eherkenning_for_eenmanszaak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openzaakconfig",
            name="title_text",
            field=models.TextField(
                default="Hier vindt u een overzicht van al uw lopende en afgeronde zaken.",
                help_text="The title/introductory text shown on the list view of 'Mijn zaken'.",
                verbose_name="Title text",
            ),
        ),
    ]
