# Generated by Django 4.2.16 on 2025-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0065_alter_openzaakconfig_title_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openzaakconfig",
            name="derive_zaak_titel_from",
            field=models.CharField(
                choices=[
                    (
                        "zaak_omschrijving",
                        "The description of the case (`zaak.omschrijving`)",
                    ),
                    (
                        "zaaktype_omschrijving",
                        "The description of the case's type (`zaaktype.omschrijving`)",
                    ),
                    (
                        "zaaktype_onderwerp",
                        "The subject of the case's type (`zaaktype.onderwerp`)",
                    ),
                ],
                default="zaaktype_omschrijving",
                help_text="Which field from the underlying zaaksysteem to use to display the title  for a zaak (e.g. on the Mijn Zaken page).",
                verbose_name="Derive the case title from",
            ),
        ),
    ]
