# Generated by Django 4.2.25 on 2025-10-06 10:32

import logging  # noqa: TID251 - keep for old migrations

from django.db import migrations

import markdown
from django_prosemirror.config import ProsemirrorConfig
from django_prosemirror.schema import MarkType, NodeType
from django_prosemirror.serde import html_to_doc

logger = logging.getLogger(__name__)


def migrate_statustype_descriptions(apps, _):
    ZaakTypeStatusTypeConfig = apps.get_model("openzaak", "ZaakTypeStatusTypeConfig")

    statustype_configs = ZaakTypeStatusTypeConfig.objects.all()

    config = ProsemirrorConfig(
        allowed_node_types=[NodeType.PARAGRAPH],
        allowed_mark_types=[
            MarkType.STRONG,
            MarkType.ITALIC,
            MarkType.LINK,
            MarkType.UNDERLINE,
        ],
    )

    for statustype_config in statustype_configs:
        content = statustype_config.description_tmp

        if not content or not content.strip():
            statustype_config.description = None
            statustype_config.save()
            continue

        content = content.strip('"')

        content = markdown.markdown(content, extensions=["extra"])

        if not content.startswith("<p>"):
            content = f"<p>{content}</p>"

        try:
            doc = html_to_doc(content, schema=config.schema)
            statustype_config.description = doc
        except (IndexError, ValueError):
            logger.exception(
                "Warning: Could not convert description for statustype_config: %s",
                statustype_config,
            )
            statustype_config.description = None

        statustype_config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0070_zaaktypestatustypeconfig_description_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_statustype_descriptions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
