# Generated by Django 4.2.26 on 2025-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0075_zaaktypestatustypeconfig_doc_upload_description_schema_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="fetch_rollen_with_betrokkene_type",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, zaken roles are filtered using the type of betrokkene ('natuurlijk persoon', 'niet-natuurlijk persoon', 'vestiging').",
                verbose_name="Filter zaken roles by betrokkene type",
            ),
        ),
    ]
