# Generated by Django 4.2.27 on 2026-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0076_zgwapigroupconfig_fetch_rollen_with_betrokkene_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogusconfig",
            name="found_in_api",
            field=models.BooleanField(
                default=True,
                help_text="Whether this object is (still) present in the backend API. This field is for diagnostic purposes only. If an object is not found in the API, this may be due to a transient issue and might be solved on a subsequent syncing operation.",
                verbose_name="Found in API",
            ),
        ),
        migrations.AddField(
            model_name="zaaktypeconfig",
            name="found_in_api",
            field=models.BooleanField(
                default=True,
                help_text="Whether this object is (still) present in the backend API. This field is for diagnostic purposes only. If an object is not found in the API, this may be due to a transient issue and might be solved on a subsequent syncing operation.",
                verbose_name="Found in API",
            ),
        ),
        migrations.AddField(
            model_name="zaaktypeinformatieobjecttypeconfig",
            name="found_in_api",
            field=models.BooleanField(
                default=True,
                help_text="Whether this object is (still) present in the backend API. This field is for diagnostic purposes only. If an object is not found in the API, this may be due to a transient issue and might be solved on a subsequent syncing operation.",
                verbose_name="Found in API",
            ),
        ),
        migrations.AddField(
            model_name="zaaktyperesultaattypeconfig",
            name="found_in_api",
            field=models.BooleanField(
                default=True,
                help_text="Whether this object is (still) present in the backend API. This field is for diagnostic purposes only. If an object is not found in the API, this may be due to a transient issue and might be solved on a subsequent syncing operation.",
                verbose_name="Found in API",
            ),
        ),
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="found_in_api",
            field=models.BooleanField(
                default=True,
                help_text="Whether this object is (still) present in the backend API. This field is for diagnostic purposes only. If an object is not found in the API, this may be due to a transient issue and might be solved on a subsequent syncing operation.",
                verbose_name="Found in API",
            ),
        ),
    ]
