# Generated by Django 4.2.11 on 2024-07-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning_oidc_generics_legacy", "0001_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectdigidconfig",
            name="oidc_token_use_basic_auth",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the client ID and secret are sent in the HTTP Basic auth header when obtaining the access token. Otherwise, they are sent in the request body.",
                verbose_name="Use Basic auth for token endpoint",
            ),
        ),
        migrations.AddField(
            model_name="openidconnecteherkenningconfig",
            name="oidc_token_use_basic_auth",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the client ID and secret are sent in the HTTP Basic auth header when obtaining the access token. Otherwise, they are sent in the request body.",
                verbose_name="Use Basic auth for token endpoint",
            ),
        ),
    ]
