# Generated by Django 3.2.23 on 2024-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning_oidc_generics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectdigidconfig",
            name="error_message_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping that maps error messages returned by the identity provider to human readable error messages that are shown to the user",
                max_length=1000,
                verbose_name="Error message mapping",
            ),
        ),
        migrations.AddField(
            model_name="openidconnecteherkenningconfig",
            name="error_message_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping that maps error messages returned by the identity provider to human readable error messages that are shown to the user",
                max_length=1000,
                verbose_name="Error message mapping",
            ),
        ),
    ]
