# Generated by Django 4.2.10 on 2024-03-11 16:12

from django.db import migrations, models

import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning_oidc_generics_legacy", "0002_auto_20240109_1055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openidconnectdigidconfig",
            name="oidc_exempt_urls",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(max_length=1000, verbose_name="Exempt URL"),
                blank=True,
                default=list,
                help_text="This is a list of absolute url paths, regular expressions for url paths, or Django view names. This plus the mozilla-django-oidc urls are exempted from the session renewal by the SessionRefresh middleware.",
                size=None,
                verbose_name="URLs exempt from session renewal",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnecteherkenningconfig",
            name="oidc_exempt_urls",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(max_length=1000, verbose_name="Exempt URL"),
                blank=True,
                default=list,
                help_text="This is a list of absolute url paths, regular expressions for url paths, or Django view names. This plus the mozilla-django-oidc urls are exempted from the session renewal by the SessionRefresh middleware.",
                size=None,
                verbose_name="URLs exempt from session renewal",
            ),
        ),
    ]
