# Generated by Django 4.2.11 on 2024-07-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "digid_eherkenning_oidc_generics_legacy",
            "0003_alter_openidconnectdigidconfig_oidc_exempt_urls_and_more",
        ),
    ]

    # models have the wrong db_table associated
    query1 = """
        ALTER TABLE "digid_eherkenning_oidc_generics_openidconnectdigidconfig"
        RENAME TO "digid_eherkenning_oidc_generics_legacy_openidconnectdigidconfig";
    """

    query2 = """
        ALTER TABLE "digid_eherkenning_oidc_generics_openidconnecteherkenningconfig"
        RENAME TO "digid_eherkenning_oidc_generics_legacy_openidconnecteherkenningconfig";
    """

    operations = [migrations.RunSQL(query1), migrations.RunSQL(query2)]
