# Generated by Django 4.2.11 on 2024-07-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "digid_eherkenning_oidc_generics_legacy",
            "0003_alter_openidconnectdigidconfig_oidc_exempt_urls_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="openidconnectdigidconfig",
            table="digid_eherkenning_oidc_generics_openidconnectdigidconfig",
        ),
        migrations.AlterModelTable(
            name="openidconnecteherkenningconfig",
            table="digid_eherkenning_oidc_generics_openidconnecteherkenningconfig",
        ),
    ]
