# Generated by Django 3.2.7 on 2022-02-02 08:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0021_auto_20220202_0949"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "title",
                    models.CharField(help_text="The title of the plan", max_length=250),
                ),
                (
                    "goal",
                    models.TextField(
                        help_text="The goal for the plan. So that you and the contact knows what the goal is."
                    ),
                ),
                (
                    "end_date",
                    models.DateField(help_text="When the plan should be archived."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contacts",
                    models.ManyToManyField(
                        help_text="The contact that will help you with this plan.",
                        related_name="plans",
                        to="accounts.Contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
