# Generated by Django 3.2.7 on 2022-01-10 13:24

import django.db.models.deletion
from django.db import migrations, models

import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filer", "0012_file_mime_type"),
        ("accounts", "0019_alter_action_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="The title of the plan", max_length=250),
                ),
                (
                    "intro",
                    models.TextField(
                        help_text="The introduction text for the plan. So that you and the contact know a little more about the plan."
                    ),
                ),
                (
                    "end_date",
                    models.DateField(help_text="When the plan should be archived."),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        help_text="The contact that will help you with this plan.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.contact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanFiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    filer.fields.file.FilerFileField(
                        help_text="The file that should be connected to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filer.file",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="To which plan the file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("explaination", models.TextField(help_text="")),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="The plan what the goal is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
            ],
        ),
    ]
