# Generated by Django 3.2.7 on 2022-01-10 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_auto_20220110_1529"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now,
                help_text="Slug of the plan",
                max_length=100,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goal",
            name="explaination",
            field=models.TextField(help_text=""),
        ),
    ]
