# Generated by Django 3.2.7 on 2022-02-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_auto_20220214_1538"),
        ("plans", "0002_auto_20220214_1440"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "goal",
                    models.TextField(
                        help_text="The goal for the plan. So that you and the contact knows what the goal is.",
                        verbose_name="goal",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="plan",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contact that will help you with this plan.",
                related_name="plans",
                to="accounts.Contact",
                verbose_name="contacts",
            ),
        ),
        migrations.CreateModel(
            name="ActionTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="The name of the action",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The description of the action",
                        verbose_name="description",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The goal of the action",
                        max_length=250,
                        verbose_name="goal",
                    ),
                ),
                (
                    "end_in_days",
                    models.PositiveIntegerField(
                        help_text="End date is set X days in the future",
                        verbose_name="Ends in x days",
                    ),
                ),
                (
                    "plan_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plantemplate",
                    ),
                ),
            ],
        ),
    ]
