# Generated by Django 3.2.7 on 2022-02-21 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_auto_20220221_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontemplate",
            name="type",
            field=models.CharField(
                choices=[("incidental", "Incidentieel"), ("recurring", "Terugkerend")],
                default="incidental",
                help_text="The type of action that it is",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="actiontemplate",
            name="plan_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actiontemplates",
                to="plans.plantemplate",
            ),
        ),
    ]
