# Generated by Django 3.2.7 on 2022-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_auto_20220110_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="explaination",
            field=models.TextField(help_text=""),
        ),
    ]
