# Generated by Django 3.2.12 on 2022-03-02 09:28

import django.db.models.deletion
from django.db import migrations, models

import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ("filer", "0012_file_mime_type"),
        ("accounts", "0029_auto_20220218_1359"),
        ("plans", "0005_merge_0003_auto_20220218_1359_0004_auto_20220221_1734"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantemplate",
            name="file",
            field=filer.fields.file.FilerFileField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="filer.file",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contact that will help you with this plan.",
                related_name="plans",
                to="accounts.Contact",
                verbose_name="Contacts",
            ),
        ),
    ]
