# Generated by Django 3.2.12 on 2022-03-04 15:19

import django.db.models.deletion
from django.db import migrations, models

import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ("filer", "0012_file_mime_type"),
        ("plans", "0006_auto_20220302_1028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontemplate",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The description that will be applied to the action if this template in chosen.",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="actiontemplate",
            name="end_in_days",
            field=models.PositiveIntegerField(
                help_text="End date is set X days in the future if this template is chosen",
                verbose_name="Ends in x days",
            ),
        ),
        migrations.AlterField(
            model_name="actiontemplate",
            name="goal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The goal that will be applied to the action if this template in chosen.",
                max_length=250,
                verbose_name="goal",
            ),
        ),
        migrations.AlterField(
            model_name="actiontemplate",
            name="name",
            field=models.CharField(
                default="",
                help_text="The name that will be applied to the action if this template in chosen.",
                max_length=250,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="actiontemplate",
            name="plan_template",
            field=models.ForeignKey(
                help_text="The plan template the action belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actiontemplates",
                to="plans.plantemplate",
                verbose_name="Plan template",
            ),
        ),
        migrations.AlterField(
            model_name="actiontemplate",
            name="type",
            field=models.CharField(
                choices=[("incidental", "Incidentieel"), ("recurring", "Terugkerend")],
                default="incidental",
                help_text="The type of action that will be applied to the action if this template in chosen.",
                max_length=200,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="plantemplate",
            name="file",
            field=filer.fields.file.FilerFileField(
                blank=True,
                help_text="The initial file of the plan. This could be a template for the final product.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="filer.file",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="plantemplate",
            name="name",
            field=models.CharField(
                help_text="The name of the plan template. Will not be copied over to the plan.",
                max_length=250,
                verbose_name="Name",
            ),
        ),
    ]
