# Generated by Django 3.2.7 on 2022-01-12 10:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_auto_20220112_1059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="explaination",
            field=models.TextField(help_text=""),
        ),
        migrations.AlterField(
            model_name="plan",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
