# Generated by Django 3.2.7 on 2022-01-12 10:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0007_auto_20220112_1104"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="intro",
        ),
        migrations.AddField(
            model_name="plan",
            name="goal",
            field=models.TextField(
                default="",
                help_text="The goal for the plan. So that you and the contact knows what the goal is.",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Goal",
        ),
    ]
