# Generated by Django 3.2.7 on 2022-01-12 10:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0008_auto_20220112_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
