# Generated by Django 3.2.15 on 2022-11-30 15:11

from django.db import migrations


def populate_plan_contacts(apps, schema_editor):
    MyModel = apps.get_model("plans", "Plan")
    for plan in MyModel.objects.all():
        for contact in plan.contacts.exclude(contact_user__isnull=True):
            plan.plan_contacts.add(contact.contact_user)


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0009_plan_plan_contacts"),
    ]

    operations = [
        migrations.RunPython(
            populate_plan_contacts, reverse_code=migrations.RunPython.noop
        )
    ]
