# Generated by Django 3.2.15 on 2022-11-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0009_plan_plan_contacts"),
        ("accounts", "0048_auto_20221128_1527"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="contacts",
        ),
    ]
