# Generated by Django 3.2.7 on 2022-01-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_contact_function"),
        ("plans", "0009_alter_plan_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="contact",
        ),
        migrations.AddField(
            model_name="plan",
            name="contacts",
            field=models.ManyToManyField(
                help_text="The contact that will help you with this plan.",
                related_name="plans",
                to="accounts.Contact",
            ),
        ),
    ]
