# Generated by Django 3.2.15 on 2022-11-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0010_auto_20221130_1611"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="contacts",
        ),
    ]
