# Generated by Django 3.2.15 on 2022-12-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0010_auto_20221205_0921"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="contacts",
        ),
    ]
