# Generated by Django 3.2.7 on 2022-01-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0011_planfile_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlanFile",
        ),
    ]
