# Generated by Django 3.2.15 on 2023-02-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_user_image"),
        ("plans", "0012_remove_actiontemplate_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The description of the plan.",
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="plantemplate",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The description of the plan.",
                verbose_name="description",
            ),
        ),
    ]
