# Generated by Django 3.2.15 on 2023-03-06 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_user_image"),
        ("plans", "0013_auto_20230223_1115"),
    ]

    # https://docs.djangoproject.com/en/3.2/howto/writing-migrations/#changing-a-manytomanyfield-to-use-a-through-model

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE plans_plan_plan_contacts RENAME TO plans_plancontact",
                    reverse_sql="ALTER TABLE plans_plancontact RENAME TO plans_plan_plan_contacts",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="PlanContact",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Contact",
                            ),
                        ),
                        (
                            "plan",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="plans.plan",
                                verbose_name="Plan",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="plan",
                    name="plan_contacts",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="The contact that will help you with this plan.",
                        related_name="plans",
                        through="plans.PlanContact",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contacts",
                    ),
                ),
            ],
        ),
    ]
