# Generated by Django 4.2.16 on 2025-03-17 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plans", "0016_alter_plancontact_notify_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="How do you intend to achieve this goal?",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="end_date",
            field=models.DateField(
                help_text="When the plan should be archived.",
                verbose_name="Expected end date",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="goal",
            field=models.TextField(
                help_text="What do you wish to achieve through this plan?",
                verbose_name="Goal",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Who will you be working with on this plan?",
                related_name="plans",
                through="plans.PlanContact",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contacts",
            ),
        ),
    ]
