# Generated by Django 4.2.16 on 2025-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0017_alter_create_template_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantemplate",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The description of the plan: how do you intend to achieve this goal?",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="plantemplate",
            name="goal",
            field=models.TextField(
                help_text="What do you wish to achieve through this plan?",
                verbose_name="goal",
            ),
        ),
    ]
