# Generated by Django 4.2.21 on 2025-05-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0018_enhanced_plan_text_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Here you can add a note, and supplement it with new consecutive notes by clicking 'Save'.",
            ),
        ),
    ]
