# Generated by Django 4.2.21 on 2025-05-15 12:49

from django.db import migrations

import ckeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0018_enhanced_plan_text_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="note",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Here you can add a note, and supplement it with new consecutive notes by clicking 'Save'.",
            ),
        ),
    ]
