# Generated by Django 4.2.22 on 2025-06-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0066_category_access_groups"),
        ("plans", "0019_add_plan_note_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantemplate",
            name="related_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to",
                to="pdc.category",
                verbose_name="Related categories",
            ),
        ),
    ]
