from ..utils import config

SETUP_CONFIGURATION_STEPS = [
    "open_inwoner.configurations.bootstrap.zgw.ZakenAPIConfigurationStep",
    "open_inwoner.configurations.bootstrap.zgw.CatalogiAPIConfigurationStep",
    "open_inwoner.configurations.bootstrap.zgw.DocumentenAPIConfigurationStep",
    "open_inwoner.configurations.bootstrap.zgw.FormulierenAPIConfigurationStep",
    "open_inwoner.configurations.bootstrap.zgw.ZGWAPIsConfigurationStep",
    "open_inwoner.configurations.bootstrap.kic.KlantenAPIConfigurationStep",
    "open_inwoner.configurations.bootstrap.kic.ContactmomentenAPIConfigurationStep",
    "open_inwoner.configurations.bootstrap.kic.KICAPIsConfigurationStep",
]
OIP_ORGANIZATION = config("OIP_ORGANIZATION", "")

# ZGW configuration variables
ZGW_CONFIG_ENABLE = config("ZGW_CONFIG_ENABLE", default=True)
ZGW_CONFIG_ZAKEN_API_ROOT = config("ZGW_CONFIG_ZAKEN_API_ROOT", "")
if ZGW_CONFIG_ZAKEN_API_ROOT and not ZGW_CONFIG_ZAKEN_API_ROOT.endswith("/"):
    ZGW_CONFIG_ZAKEN_API_ROOT = f"{ZGW_CONFIG_ZAKEN_API_ROOT.strip()}/"
ZGW_CONFIG_ZAKEN_OAS_URL = ZGW_CONFIG_ZAKEN_API_ROOT  # this is still required by the form, but not actually used
ZGW_CONFIG_ZAKEN_API_CLIENT_ID = config("ZGW_CONFIG_ZAKEN_API_CLIENT_ID", "")
ZGW_CONFIG_ZAKEN_API_SECRET = config("ZGW_CONFIG_ZAKEN_API_SECRET", "")
ZGW_CONFIG_CATALOGI_API_ROOT = config("ZGW_CONFIG_CATALOGI_API_ROOT", "")
if ZGW_CONFIG_CATALOGI_API_ROOT and not ZGW_CONFIG_CATALOGI_API_ROOT.endswith("/"):
    ZGW_CONFIG_CATALOGI_API_ROOT = f"{ZGW_CONFIG_CATALOGI_API_ROOT.strip()}/"
ZGW_CONFIG_CATALOGI_OAS_URL = ZGW_CONFIG_CATALOGI_API_ROOT  # this is still required by the form, but not actually used
ZGW_CONFIG_CATALOGI_API_CLIENT_ID = config("ZGW_CONFIG_CATALOGI_API_CLIENT_ID", "")
ZGW_CONFIG_CATALOGI_API_SECRET = config("ZGW_CONFIG_CATALOGI_API_SECRET", "")
ZGW_CONFIG_DOCUMENTEN_API_ROOT = config("ZGW_CONFIG_DOCUMENTEN_API_ROOT", "")
if ZGW_CONFIG_DOCUMENTEN_API_ROOT and not ZGW_CONFIG_DOCUMENTEN_API_ROOT.endswith("/"):
    ZGW_CONFIG_DOCUMENTEN_API_ROOT = f"{ZGW_CONFIG_DOCUMENTEN_API_ROOT.strip()}/"
ZGW_CONFIG_DOCUMENTEN_OAS_URL = ZGW_CONFIG_DOCUMENTEN_API_ROOT  # this is still required by the form, but not actually used
ZGW_CONFIG_DOCUMENTEN_API_CLIENT_ID = config("ZGW_CONFIG_DOCUMENTEN_API_CLIENT_ID", "")
ZGW_CONFIG_DOCUMENTEN_API_SECRET = config("ZGW_CONFIG_DOCUMENTEN_API_SECRET", "")
ZGW_CONFIG_FORMULIEREN_API_ROOT = config("ZGW_CONFIG_FORMULIEREN_API_ROOT", "")
if ZGW_CONFIG_FORMULIEREN_API_ROOT and not ZGW_CONFIG_FORMULIEREN_API_ROOT.endswith(
    "/"
):
    ZGW_CONFIG_FORMULIEREN_API_ROOT = f"{ZGW_CONFIG_FORMULIEREN_API_ROOT.strip()}/"
ZGW_CONFIG_FORMULIEREN_OAS_URL = ZGW_CONFIG_FORMULIEREN_API_ROOT  # this is still required by the form, but not actually used
ZGW_CONFIG_FORMULIEREN_API_CLIENT_ID = config(
    "ZGW_CONFIG_FORMULIEREN_API_CLIENT_ID", ""
)
ZGW_CONFIG_FORMULIEREN_API_SECRET = config("ZGW_CONFIG_FORMULIEREN_API_SECRET", "")
# ZGW config options
ZGW_CONFIG_ZAAK_MAX_CONFIDENTIALITY = config(
    "ZGW_CONFIG_ZAAK_MAX_CONFIDENTIALITY", None
)
ZGW_CONFIG_DOCUMENT_MAX_CONFIDENTIALITY = config(
    "ZGW_CONFIG_DOCUMENT_MAX_CONFIDENTIALITY", None
)
ZGW_CONFIG_ACTION_REQUIRED_DEADLINE_DAYS = config("ACTION_REQUIRED_DEADLINE_DAYS", None)
ZGW_CONFIG_ALLOWED_FILE_EXTENSIONS = config("ZGW_CONFIG_ALLOWED_FILE_EXTENSIONS", None)
ZGW_CONFIG_MIJN_AANVRAGEN_TITLE_TEXT = config(
    "ZGW_CONFIG_MIJN_AANVRAGEN_TITLE_TEXT", None
)
ZGW_CONFIG_ENABLE_CATEGORIES_FILTERING_WITH_ZAKEN = config(
    "ZGW_CONFIG_ENABLE_CATEGORIES_FILTERING_WITH_ZAKEN", None
)
ZGW_CONFIG_SKIP_NOTIFICATION_STATUSTYPE_INFORMEREN = config(
    "ZGW_CONFIG_SKIP_NOTIFICATION_STATUSTYPE_INFORMEREN", None
)
ZGW_CONFIG_REFORMAT_ESUITE_ZAAK_IDENTIFICATIE = config(
    "ZGW_CONFIG_REFORMAT_ESUITE_ZAAK_IDENTIFICATIE", None
)
ZGW_CONFIG_FETCH_EHERKENNING_ZAKEN_WITH_RSIN = config(
    "ZGW_CONFIG_FETCH_EHERKENNING_ZAKEN_WITH_RSIN", None
)

# KIC configuration variables
KIC_CONFIG_ENABLE = config("KIC_CONFIG_ENABLE", default=True)
KIC_CONFIG_KLANTEN_API_ROOT = config("KIC_CONFIG_KLANTEN_API_ROOT", "")
if KIC_CONFIG_KLANTEN_API_ROOT and not KIC_CONFIG_KLANTEN_API_ROOT.endswith("/"):
    KIC_CONFIG_KLANTEN_API_ROOT = f"{KIC_CONFIG_KLANTEN_API_ROOT.strip()}/"
KIC_CONFIG_KLANTEN_OAS_URL = KIC_CONFIG_KLANTEN_API_ROOT  # this is still required by the form, but not actually used
KIC_CONFIG_KLANTEN_API_CLIENT_ID = config("KIC_CONFIG_KLANTEN_API_CLIENT_ID", "")
KIC_CONFIG_KLANTEN_API_SECRET = config("KIC_CONFIG_KLANTEN_API_SECRET", "")
KIC_CONFIG_CONTACTMOMENTEN_API_ROOT = config("KIC_CONFIG_CONTACTMOMENTEN_API_ROOT", "")
if (
    KIC_CONFIG_CONTACTMOMENTEN_API_ROOT
    and not KIC_CONFIG_CONTACTMOMENTEN_API_ROOT.endswith("/")
):
    KIC_CONFIG_CONTACTMOMENTEN_API_ROOT = (
        f"{KIC_CONFIG_CONTACTMOMENTEN_API_ROOT.strip()}/"
    )
KIC_CONFIG_CONTACTMOMENTEN_OAS_URL = KIC_CONFIG_CONTACTMOMENTEN_API_ROOT  # this is still required by the form, but not actually used
KIC_CONFIG_CONTACTMOMENTEN_API_CLIENT_ID = config(
    "KIC_CONFIG_CONTACTMOMENTEN_API_CLIENT_ID", ""
)
KIC_CONFIG_CONTACTMOMENTEN_API_SECRET = config(
    "KIC_CONFIG_CONTACTMOMENTEN_API_SECRET", ""
)
KIC_CONFIG_REGISTER_EMAIL = config("KIC_CONFIG_REGISTER_EMAIL", None)
KIC_CONFIG_REGISTER_CONTACT_MOMENT = config("KIC_CONFIG_REGISTER_CONTACT_MOMENT", None)
KIC_CONFIG_REGISTER_BRONORGANISATIE_RSIN = config(
    "KIC_CONFIG_REGISTER_BRONORGANISATIE_RSIN", None
)
KIC_CONFIG_REGISTER_CHANNEL = config("KIC_CONFIG_REGISTER_CHANNEL", None)
KIC_CONFIG_REGISTER_TYPE = config("KIC_CONFIG_REGISTER_TYPE", None)
KIC_CONFIG_REGISTER_EMPLOYEE_ID = config("KIC_CONFIG_REGISTER_EMPLOYEE_ID", None)
KIC_CONFIG_USE_RSIN_FOR_INNNNPID_QUERY_PARAMETER = config(
    "KIC_CONFIG_USE_RSIN_FOR_INNNNPID_QUERY_PARAMETER", None
)
