from maykin_common.config import config

SETUP_CONFIGURATION_STEPS = [
    "mozilla_django_oidc_db.setup_configuration.steps.AdminOIDCConfigurationStep",
    "zgw_consumers.contrib.setup_configuration.steps.ServiceConfigurationStep",
    "open_inwoner.configurations.bootstrap.zgw.OpenZaakConfigurationStep",
    "open_inwoner.configurations.bootstrap.openklant.KlantenSysteemConfigurationStep",
    "open_inwoner.configurations.bootstrap.default_users.UserConfigurationStep",
    "django_setup_configuration.contrib.sites.steps.SitesConfigurationStep",
]
OIP_ORGANIZATION = config("OIP_ORGANIZATION", default="")

# ZGW configuration variables
ZGW_CONFIG_ENABLE = config("ZGW_CONFIG_ENABLE", default=False)
ZGW_SERVER_CERTIFICATE_LABEL = config("ZGW_SERVER_CERTIFICATE_LABEL", default="")
ZGW_SERVER_CERTIFICATE_TYPE = config("ZGW_SERVER_CERTIFICATE_TYPE", default="")
ZGW_SERVER_CERTIFICATE_PUBLIC_CERTIFICATE = (
    "ZGW_SERVER_CERTIFICATE_PUBLIC_CERTIFICATE",
    None,
)
ZGW_ZAAK_SERVICE_API_ROOT = config("ZGW_ZAAK_SERVICE_API_ROOT", default="")
if ZGW_ZAAK_SERVICE_API_ROOT and not ZGW_ZAAK_SERVICE_API_ROOT.endswith("/"):
    ZGW_ZAAK_SERVICE_API_ROOT = f"{ZGW_ZAAK_SERVICE_API_ROOT.strip()}/"
ZGW_ZAKEN_OAS_URL = ZGW_ZAAK_SERVICE_API_ROOT  # this is still required by the form, but not actually used
ZGW_ZAAK_SERVICE_API_CLIENT_ID = config("ZGW_ZAAK_SERVICE_API_CLIENT_ID", default="")
ZGW_ZAAK_SERVICE_API_SECRET = config("ZGW_ZAAK_SERVICE_API_SECRET", default="")
ZGW_CATALOGI_SERVICE_API_ROOT = config("ZGW_CATALOGI_SERVICE_API_ROOT", default="")
if ZGW_CATALOGI_SERVICE_API_ROOT and not ZGW_CATALOGI_SERVICE_API_ROOT.endswith("/"):
    ZGW_CATALOGI_SERVICE_API_ROOT = f"{ZGW_CATALOGI_SERVICE_API_ROOT.strip()}/"
ZGW_CATALOGI_OAS_URL = ZGW_CATALOGI_SERVICE_API_ROOT  # this is still required by the form, but not actually used
ZGW_CATALOGI_SERVICE_API_CLIENT_ID = config(
    "ZGW_CATALOGI_SERVICE_API_CLIENT_ID", default=""
)
ZGW_CATALOGI_SERVICE_API_SECRET = config("ZGW_CATALOGI_SERVICE_API_SECRET", default="")
ZGW_DOCUMENTEN_SERVICE_API_ROOT = config("ZGW_DOCUMENTEN_SERVICE_API_ROOT", default="")
if ZGW_DOCUMENTEN_SERVICE_API_ROOT and not ZGW_DOCUMENTEN_SERVICE_API_ROOT.endswith(
    "/"
):
    ZGW_DOCUMENTEN_SERVICE_API_ROOT = f"{ZGW_DOCUMENTEN_SERVICE_API_ROOT.strip()}/"
ZGW_DOCUMENTEN_OAS_URL = ZGW_DOCUMENTEN_SERVICE_API_ROOT  # this is still required by the form, but not actually used
ZGW_DOCUMENTEN_SERVICE_API_CLIENT_ID = config(
    "ZGW_DOCUMENTEN_SERVICE_API_CLIENT_ID", default=""
)
ZGW_DOCUMENTEN_SERVICE_API_SECRET = config(
    "ZGW_DOCUMENTEN_SERVICE_API_SECRET", default=""
)
ZGW_FORM_SERVICE_API_ROOT = config("ZGW_FORM_SERVICE_API_ROOT", default="")
if ZGW_FORM_SERVICE_API_ROOT and not ZGW_FORM_SERVICE_API_ROOT.endswith("/"):
    ZGW_FORM_SERVICE_API_ROOT = f"{ZGW_FORM_SERVICE_API_ROOT.strip()}/"
ZGW_FORMULIEREN_OAS_URL = ZGW_FORM_SERVICE_API_ROOT  # this is still required by the form, but not actually used
ZGW_FORM_SERVICE_API_CLIENT_ID = config("ZGW_FORM_SERVICE_API_CLIENT_ID", default="")
ZGW_FORM_SERVICE_API_SECRET = config("ZGW_FORM_SERVICE_API_SECRET", default="")
# ZGW config options
ZGW_ZAAK_MAX_CONFIDENTIALITY = config("ZGW_ZAAK_MAX_CONFIDENTIALITY", default=None)
ZGW_DOCUMENT_MAX_CONFIDENTIALITY = config(
    "ZGW_DOCUMENT_MAX_CONFIDENTIALITY", default=None
)
ZGW_ACTION_REQUIRED_DEADLINE_DAYS = config(
    "ACTION_REQUIRED_DEADLINE_DAYS", default=None
)
ZGW_ALLOWED_FILE_EXTENSIONS = config("ZGW_ALLOWED_FILE_EXTENSIONS", default=None)
ZGW_MIJN_AANVRAGEN_TITLE_TEXT = config("ZGW_MIJN_AANVRAGEN_TITLE_TEXT", default=None)
ZGW_ENABLE_CATEGORIES_FILTERING_WITH_ZAKEN = config(
    "ZGW_ENABLE_CATEGORIES_FILTERING_WITH_ZAKEN", default=None
)
ZGW_SKIP_NOTIFICATION_STATUSTYPE_INFORMEREN = config(
    "ZGW_SKIP_NOTIFICATION_STATUSTYPE_INFORMEREN", default=None
)
ZGW_REFORMAT_ESUITE_ZAAK_IDENTIFICATIE = config(
    "ZGW_REFORMAT_ESUITE_ZAAK_IDENTIFICATIE", default=None
)
ZGW_FETCH_EHERKENNING_ZAKEN_WITH_RSIN = config(
    "ZGW_FETCH_EHERKENNING_ZAKEN_WITH_RSIN", default=None
)

# KIC configuration variables
KIC_CONFIG_ENABLE = config("KIC_CONFIG_ENABLE", default=False)
KIC_SERVER_CERTIFICATE_LABEL = config("KIC_SERVER_CERTIFICATE_LABEL", default="")
KIC_SERVER_CERTIFICATE_TYPE = config("KIC_SERVER_CERTIFICATE_TYPE", default="")
KIC_SERVER_CERTIFICATE_PUBLIC_CERTIFICATE = config(
    "KIC_SERVER_CERTIFICATE_PUBLIC_CERTIFICATE",
    default=None,
)
KIC_KLANTEN_SERVICE_API_ROOT = config("KIC_KLANTEN_SERVICE_API_ROOT", default="")
if KIC_KLANTEN_SERVICE_API_ROOT and not KIC_KLANTEN_SERVICE_API_ROOT.endswith("/"):
    KIC_KLANTEN_SERVICE_API_ROOT = f"{KIC_KLANTEN_SERVICE_API_ROOT.strip()}/"
KIC_KLANTEN_OAS_URL = KIC_KLANTEN_SERVICE_API_ROOT  # this is still required by the form, but not actually used
KIC_KLANTEN_SERVICE_API_CLIENT_ID = config(
    "KIC_KLANTEN_SERVICE_API_CLIENT_ID", default=""
)
KIC_KLANTEN_SERVICE_API_SECRET = config("KIC_KLANTEN_SERVICE_API_SECRET", default="")
KIC_CONTACTMOMENTEN_SERVICE_API_ROOT = config(
    "KIC_CONTACTMOMENTEN_SERVICE_API_ROOT", default=""
)
if (
    KIC_CONTACTMOMENTEN_SERVICE_API_ROOT
    and not KIC_CONTACTMOMENTEN_SERVICE_API_ROOT.endswith("/")
):
    KIC_CONTACTMOMENTEN_SERVICE_API_ROOT = (
        f"{KIC_CONTACTMOMENTEN_SERVICE_API_ROOT.strip()}/"
    )
KIC_CONTACTMOMENTEN_OAS_URL = KIC_CONTACTMOMENTEN_SERVICE_API_ROOT  # this is still required by the form, but not actually used
KIC_CONTACTMOMENTEN_SERVICE_API_CLIENT_ID = config(
    "KIC_CONTACTMOMENTEN_SERVICE_API_CLIENT_ID", default=""
)
KIC_CONTACTMOMENTEN_SERVICE_API_SECRET = config(
    "KIC_CONTACTMOMENTEN_SERVICE_API_SECRET", default=""
)
KIC_REGISTER_EMAIL = config("KIC_REGISTER_EMAIL", default=None)
KIC_REGISTER_CONTACT_MOMENT = config("KIC_REGISTER_CONTACT_MOMENT", default=None)
KIC_REGISTER_BRONORGANISATIE_RSIN = config(
    "KIC_REGISTER_BRONORGANISATIE_RSIN", default=None
)
KIC_REGISTER_CHANNEL = config("KIC_REGISTER_CHANNEL", default=None)
KIC_REGISTER_TYPE = config("KIC_REGISTER_TYPE", default=None)
KIC_REGISTER_EMPLOYEE_ID = config("KIC_REGISTER_EMPLOYEE_ID", default=None)
KIC_USE_RSIN_FOR_INNNNPID_QUERY_PARAMETER = config(
    "KIC_USE_RSIN_FOR_INNNNPID_QUERY_PARAMETER", default=None
)


#
# SiteConfiguration variables
#
SITE_CONFIG_ENABLE = config("SITE_CONFIG_ENABLE", default=False)
SITE_NAME = config("SITE_NAME", default=None)
SITE_PRIMARY_COLOR = config("SITE_PRIMARY_COLOR", default=None)
SITE_SECONDARY_COLOR = config("SITE_SECONDARY_COLOR", default=None)
SITE_ACCENT_COLOR = config("SITE_ACCENT_COLOR", default=None)
SITE_PRIMARY_FONT_COLOR = config("SITE_PRIMARY_FONT_COLOR", default=None)
SITE_SECONDARY_FONT_COLOR = config("SITE_SECONDARY_FONT_COLOR", default=None)
SITE_ACCENT_FONT_COLOR = config("SITE_ACCENT_FONT_COLOR", default=None)
SITE_WARNING_BANNER_ENABLED = config("SITE_WARNING_BANNER_ENABLED", default=None)
SITE_WARNING_BANNER_TEXT = config("SITE_WARNING_BANNER_TEXT", default=None)
SITE_WARNING_BANNER_BACKGROUND_COLOR = config(
    "SITE_WARNING_BANNER_BACKGROUND_COLOR", default=None
)
SITE_CONTACTMOMENT_CONTACT_FORM_ENABLED = config(
    "SITE_CONTACTMOMENT_CONTACT_FORM_ENABLED", default=None
)
SITE_WARNING_BANNER_FONT_COLOR = config("SITE_WARNING_BANNER_FONT_COLOR", default=None)
SITE_HERO_IMAGE_LOGIN = config("SITE_HERO_IMAGE_LOGIN", default=None)
SITE_LOGIN_SHOW = config("SITE_LOGIN_SHOW", default=None)
SITE_LOGIN_ALLOW_REGISTRATION = config("SITE_LOGIN_ALLOW_REGISTRATION", default=None)
SITE_LOGIN_2FA_SMS = config("SITE_LOGIN_2FA_SMS", default=None)
SITE_LOGIN_TEXT = config("SITE_LOGIN_TEXT", default=None)
SITE_REGISTRATION_TEXT = config("SITE_REGISTRATION_TEXT", default=None)
SITE_HOME_WELCOME_TITLE = config("SITE_HOME_WELCOME_TITLE", default=None)
SITE_HOME_WELCOME_INTRO = config("SITE_HOME_WELCOME_INTRO", default=None)
SITE_HOME_THEME_TITLE = config("SITE_HOME_THEME_TITLE", default=None)
SITE_HOME_THEME_INTRO = config("SITE_HOME_THEME_INTRO", default=None)
SITE_THEME_TITLE = config("SITE_THEME_TITLE", default=None)
SITE_THEME_INTRO = config("SITE_THEME_INTRO", default=None)
SITE_HOME_MAP_TITLE = config("SITE_HOME_MAP_TITLE", default=None)
SITE_HOME_MAP_INTRO = config("SITE_HOME_MAP_INTRO", default=None)
SITE_HOME_QUESTIONNAIRE_TITLE = config("SITE_HOME_QUESTIONNAIRE_TITLE", default=None)
SITE_HOME_QUESTIONNAIRE_INTRO = config("SITE_HOME_QUESTIONNAIRE_INTRO", default=None)
SITE_HOME_PRODUCT_FINDER_TITLE = config("SITE_HOME_PRODUCT_FINDER_TITLE", default=None)
SITE_HOME_PRODUCT_FINDER_INTRO = config("SITE_HOME_PRODUCT_FINDER_INTRO", default=None)
SITE_SEARCH_ZERO_RESULTS_TEXT = config("SEARCH_ZERO_RESULTS_TEXT", default=None)
SITE_SELECT_QUESTIONNAIRE_TITLE = config(
    "SITE_SELECT_QUESTIONNAIRE_TITLE", default=None
)
SITE_SELECT_QUESTIONNAIRE_INTRO = config(
    "SITE_SELECT_QUESTIONNAIRE_INTRO", default=None
)
SITE_PLANS_INTRO = config("SITE_PLANS_INTRO", default=None)
SITE_PLANS_NO_PLANS_MESSAGE = config("SITE_PLANS_NO_PLANS_MESSAGE", default=None)
SITE_PLANS_EDIT_MESSAGE = config("SITE_PLANS_EDIT_MESSAGE", default=None)
SITE_FOOTER_LOGO_TITLE = config("SITE_FOOTER_LOGO_TITLE", default=None)
SITE_FOOTER_LOGO_URL = config("SITE_FOOTER_LOGO_URL", default=None)
SITE_HOME_HELP_TEXT = config("SITE_HOME_HELP_TEXT", default=None)
SITE_THEME_HELP_TEXT = config("SITE_THEME_HELP_TEXT", default=None)
SITE_PRODUCT_HELP_TEXT = config("SITE_PRODUCT_HELP_TEXT", default=None)
SITE_SEARCH_HELP_TEXT = config("SITE_SEARCH_HELP_TEXT", default=None)
SITE_ACCOUNT_HELP_TEXT = config("SITE_ACCOUNT_HELP_TEXT", default=None)
SITE_QUESTIONNAIRE_HELP_TEXT = config("SITE_QUESTIONNAIRE_HELP_TEXT", default=None)
SITE_PLAN_HELP_TEXT = config("SITE_PLAN_HELP_TEXT", default=None)
SITE_SEARCH_FILTER_CATEGORIES = config("SITE_SEARCH_FILTER_CATEGORIES", default=None)
SITE_SEARCH_FILTER_TAGS = config("SITE_SEARCH_FILTER_TAGS", default=None)
SITE_SEARCH_FILTER_ORGANIZATIONS = config(
    "SITE_SEARCH_FILTER_ORGANIZATIONS", default=None
)
SITE_NOTIFICATIONS_ACTIONS_ENABLED = config(
    "SITE_NOTIFICATIONS_ACTIONS_ENABLED", default=None
)
SITE_NOTIFICATIONS_CASES_ENABLED = config(
    "SITE_NOTIFICATIONS_CASES_ENABLED", default=None
)
SITE_NOTIFICATIONS_PLANS_ENABLED = config(
    "SITE_NOTIFICATIONS_PLANS_ENABLED", default=None
)
SITE_NOTIFICATIONS_MESSAGES_ENABLED = config(
    "SITE_NOTIFICATIONS_MESSAGES_ENABLED", default=None
)
SITE_RECIPIENTS_EMAIL_DIGEST = config("SITE_RECIPIENTS_EMAIL_DIGEST", default=None)
SITE_CONTACT_PHONENUMBER = config("SITE_CONTACT_PHONENUMBER", default=None)
SITE_CONTACT_PAGE = config("SITE_CONTACT_PAGE", default=None)
SITE_GTM_CODE = config("SITE_GTM_CODE", default=None)
SITE_GA_CODE = config("SITE_GA_CODE", default=None)
SITE_MATOMO_URL = config("SITE_MATOMO_URL", default=None)
SITE_MATOMO_SITE_ID = config("SITE_MATOMO_SITE_ID", default=None)
SITE_SITEIMPROVE_ID = config("SITE_SITEIMPROVE_ID", default=None)
SITE_COOKIE_INFO_TEXT = config("SITE_COOKIE_INFO_TEXT", default=None)
SITE_COOKIE_LINK_TEXT = config("SITE_COOKIE_LINK_TEXT", default=None)
SITE_COOKIE_LINK_URL = config("SITE_COOKIE_LINK_URL", default=None)
SITE_KCM_SURVEY_LINK_TEXT = config("SITE_KCM_SURVEY_LINK_TEXT", default=None)
SITE_KCM_SURVEY_LINK_URL = config("SITE_KCM_SURVEY_LINK_URL", default=None)
SITE_OPENID_CONNECT_LOGIN_TEXT = config("SITE_OPENID_CONNECT_LOGIN_TEXT", default=None)
SITE_OPENID_DISPLAY = config("SITE_OPENID_DISPLAY", default=None)
SITE_REDIRECT_TO = config("SITE_REDIRECT_TO", default=None)
SITE_ALLOW_MESSAGES_FILE_SHARING = config(
    "SITE_ALLOW_MESSAGES_FILE_SHARING", default=None
)
SITE_HIDE_CATEGORIES_FROM_ANONYMOUS_USERS = config(
    "SITE_HIDE_CATEGORIES_FROM_ANONYMOUS_USERS", default=None
)
SITE_HIDE_SEARCH_FROM_ANONYMOUS_USERS = config(
    "SITE_HIDE_SEARCH_FROM_ANONYMOUS_USERS", default=None
)
SITE_DISPLAY_SOCIAL = config("SITE_DISPLAY_SOCIAL", default=None)
SITE_THEME_STYLESHEET = config("SITE_THEME_STYLESHEET", default=None)
SITE_EHERKENNING_ENABLED = config("SITE_EHERKENNING_ENABLED", default=None)


# Authentication configuration variables
# NOTE variables are namespaced with `DIGID_OIDC`, but some model field names also have `oidc_...` in them
DIGID_OIDC_CONFIG_ENABLE = config("DIGID_OIDC_CONFIG_ENABLE", default=False)
DIGID_OIDC_BSN_CLAIM = config("DIGID_OIDC_BSN_CLAIM", default=None)
DIGID_OIDC_OIDC_RP_CLIENT_ID = config("DIGID_OIDC_OIDC_RP_CLIENT_ID", default=None)
DIGID_OIDC_OIDC_RP_CLIENT_SECRET = config(
    "DIGID_OIDC_OIDC_RP_CLIENT_SECRET", default=None
)
DIGID_OIDC_OIDC_RP_SIGN_ALGO = config("DIGID_OIDC_OIDC_RP_SIGN_ALGO", default=None)
DIGID_OIDC_OIDC_RP_SCOPES_LIST = config("DIGID_OIDC_OIDC_RP_SCOPES_LIST", default=None)
DIGID_OIDC_OIDC_OP_DISCOVERY_ENDPOINT = config(
    "DIGID_OIDC_OIDC_OP_DISCOVERY_ENDPOINT", default=None
)
DIGID_OIDC_OIDC_OP_JWKS_ENDPOINT = config(
    "DIGID_OIDC_OIDC_OP_JWKS_ENDPOINT", default=None
)
DIGID_OIDC_OIDC_OP_AUTHORIZATION_ENDPOINT = config(
    "DIGID_OIDC_OIDC_OP_AUTHORIZATION_ENDPOINT", default=None
)
DIGID_OIDC_OIDC_OP_TOKEN_ENDPOINT = config(
    "DIGID_OIDC_OIDC_OP_TOKEN_ENDPOINT", default=None
)
DIGID_OIDC_OIDC_OP_USER_ENDPOINT = config(
    "DIGID_OIDC_OIDC_OP_USER_ENDPOINT", default=None
)
DIGID_OIDC_OIDC_RP_IDP_SIGN_KEY = config(
    "DIGID_OIDC_OIDC_RP_IDP_SIGN_KEY", default=None
)
DIGID_OIDC_USERINFO_CLAIMS_SOURCE = config(
    "DIGID_OIDC_USERINFO_CLAIMS_SOURCE", default=None
)
DIGID_OIDC_OIDC_OP_LOGOUT_ENDPOINT = config(
    "DIGID_OIDC_OIDC_OP_LOGOUT_ENDPOINT", default=None
)
DIGID_OIDC_OIDC_KEYCLOAK_IDP_HINT = config(
    "DIGID_OIDC_OIDC_KEYCLOAK_IDP_HINT", default=None
)
DIGID_OIDC_OIDC_USE_NONCE = config("DIGID_OIDC_OIDC_USE_NONCE", default=None)
DIGID_OIDC_OIDC_NONCE_SIZE = config("DIGID_OIDC_OIDC_NONCE_SIZE", default=None)
DIGID_OIDC_OIDC_STATE_SIZE = config("DIGID_OIDC_OIDC_STATE_SIZE", default=None)

# NOTE variables are namespaced with `EHERKENNING_OIDC`, but some model field names also have `oidc_...` in them
EHERKENNING_OIDC_CONFIG_ENABLE = config("EHERKENNING_OIDC_CONFIG_ENABLE", default=False)
EHERKENNING_OIDC_LEGAL_SUBJECT_CLAIM = config(
    "EHERKENNING_OIDC_LEGAL_SUBJECT_CLAIM", default=None
)
EHERKENNING_OIDC_OIDC_RP_CLIENT_ID = config(
    "EHERKENNING_OIDC_OIDC_RP_CLIENT_ID", default=None
)
EHERKENNING_OIDC_OIDC_RP_CLIENT_SECRET = config(
    "EHERKENNING_OIDC_OIDC_RP_CLIENT_SECRET", default=None
)
EHERKENNING_OIDC_OIDC_RP_SIGN_ALGO = config(
    "EHERKENNING_OIDC_OIDC_RP_SIGN_ALGO", default=None
)
EHERKENNING_OIDC_OIDC_RP_SCOPES_LIST = config(
    "EHERKENNING_OIDC_OIDC_RP_SCOPES_LIST", default=None
)
EHERKENNING_OIDC_OIDC_OP_DISCOVERY_ENDPOINT = config(
    "EHERKENNING_OIDC_OIDC_OP_DISCOVERY_ENDPOINT", default=None
)
EHERKENNING_OIDC_OIDC_OP_JWKS_ENDPOINT = config(
    "EHERKENNING_OIDC_OIDC_OP_JWKS_ENDPOINT", default=None
)
EHERKENNING_OIDC_OIDC_OP_AUTHORIZATION_ENDPOINT = config(
    "EHERKENNING_OIDC_OIDC_OP_AUTHORIZATION_ENDPOINT", default=None
)
EHERKENNING_OIDC_OIDC_OP_TOKEN_ENDPOINT = config(
    "EHERKENNING_OIDC_OIDC_OP_TOKEN_ENDPOINT", default=None
)
EHERKENNING_OIDC_OIDC_OP_USER_ENDPOINT = config(
    "EHERKENNING_OIDC_OIDC_OP_USER_ENDPOINT", default=None
)
EHERKENNING_OIDC_OIDC_RP_IDP_SIGN_KEY = config(
    "EHERKENNING_OIDC_OIDC_RP_IDP_SIGN_KEY", default=None
)
EHERKENNING_OIDC_USERINFO_CLAIMS_SOURCE = config(
    "EHERKENNING_OIDC_USERINFO_CLAIMS_SOURCE", default=None
)
EHERKENNING_OIDC_OIDC_OP_LOGOUT_ENDPOINT = config(
    "EHERKENNING_OIDC_OIDC_OP_LOGOUT_ENDPOINT", default=None
)
EHERKENNING_OIDC_OIDC_KEYCLOAK_IDP_HINT = config(
    "EHERKENNING_OIDC_OIDC_KEYCLOAK_IDP_HINT", default=None
)
EHERKENNING_OIDC_OIDC_USE_NONCE = config(
    "EHERKENNING_OIDC_OIDC_USE_NONCE", default=None
)
EHERKENNING_OIDC_OIDC_NONCE_SIZE = config(
    "EHERKENNING_OIDC_OIDC_NONCE_SIZE", default=None
)
EHERKENNING_OIDC_OIDC_STATE_SIZE = config(
    "EHERKENNING_OIDC_OIDC_STATE_SIZE", default=None
)

# NOTE variables are namespaced with `ADMIN_OIDC`, but some model field names also have `oidc_...` in them
ADMIN_OIDC_CONFIG_ENABLE = config("ADMIN_OIDC_CONFIG_ENABLE", default=False)
ADMIN_OIDC_OIDC_RP_CLIENT_ID = config("ADMIN_OIDC_OIDC_RP_CLIENT_ID", default=None)
ADMIN_OIDC_OIDC_RP_CLIENT_SECRET = config(
    "ADMIN_OIDC_OIDC_RP_CLIENT_SECRET", default=None
)
ADMIN_OIDC_OIDC_RP_SCOPES_LIST = config("ADMIN_OIDC_OIDC_RP_SCOPES_LIST", default=None)
ADMIN_OIDC_OIDC_RP_SIGN_ALGO = config("ADMIN_OIDC_OIDC_RP_SIGN_ALGO", default=None)
ADMIN_OIDC_OIDC_RP_IDP_SIGN_KEY = config(
    "ADMIN_OIDC_OIDC_RP_IDP_SIGN_KEY", default=None
)
ADMIN_OIDC_OIDC_OP_DISCOVERY_ENDPOINT = config(
    "ADMIN_OIDC_OIDC_OP_DISCOVERY_ENDPOINT", default=None
)
ADMIN_OIDC_OIDC_OP_JWKS_ENDPOINT = config(
    "ADMIN_OIDC_OIDC_OP_JWKS_ENDPOINT", default=None
)
ADMIN_OIDC_OIDC_OP_AUTHORIZATION_ENDPOINT = config(
    "ADMIN_OIDC_OIDC_OP_AUTHORIZATION_ENDPOINT", default=None
)
ADMIN_OIDC_OIDC_OP_TOKEN_ENDPOINT = config(
    "ADMIN_OIDC_OIDC_OP_TOKEN_ENDPOINT", default=None
)
ADMIN_OIDC_OIDC_OP_USER_ENDPOINT = config(
    "ADMIN_OIDC_OIDC_OP_USER_ENDPOINT", default=None
)
ADMIN_OIDC_USERNAME_CLAIM = config("ADMIN_OIDC_USERNAME_CLAIM", default=None)
ADMIN_OIDC_GROUPS_CLAIM = config("ADMIN_OIDC_GROUPS_CLAIM", default=None)
# XXX: this needs to be provided as a Mapping[str, list[str]] now instead of Mapping[str, str]!
ADMIN_OIDC_CLAIM_MAPPING = config("ADMIN_OIDC_CLAIM_MAPPING", default=None)
ADMIN_OIDC_SYNC_GROUPS = config("ADMIN_OIDC_SYNC_GROUPS", default=None)
ADMIN_OIDC_SYNC_GROUPS_GLOB_PATTERN = config(
    "ADMIN_OIDC_SYNC_GROUPS_GLOB_PATTERN", default=None
)
ADMIN_OIDC_DEFAULT_GROUPS = config("ADMIN_OIDC_DEFAULT_GROUPS", default=None)
ADMIN_OIDC_MAKE_USERS_STAFF = config("ADMIN_OIDC_MAKE_USERS_STAFF", default=None)
ADMIN_OIDC_SUPERUSER_GROUP_NAMES = config(
    "ADMIN_OIDC_SUPERUSER_GROUP_NAMES", default=None
)
ADMIN_OIDC_OIDC_USE_NONCE = config("ADMIN_OIDC_OIDC_USE_NONCE", default=None)
ADMIN_OIDC_OIDC_NONCE_SIZE = config("ADMIN_OIDC_OIDC_NONCE_SIZE", default=None)
ADMIN_OIDC_OIDC_STATE_SIZE = config("ADMIN_OIDC_OIDC_STATE_SIZE", default=None)
ADMIN_OIDC_USERINFO_CLAIMS_SOURCE = config(
    "ADMIN_OIDC_USERINFO_CLAIMS_SOURCE", default=None
)

#
# DigiD SAML
#
DIGID_SAML_CONFIG_ENABLE = config("DIGID_SAML_SAML_CONFIG_ENABLE", default=False)
DIGID_SAML_CERTIFICATE_LABEL = config("DIGID_SAML_CERTIFICATE_LABEL", default=None)
DIGID_SAML_CERTIFICATE_TYPE = config("DIGID_SAML_CERTIFICATE_TYPE", default=None)
DIGID_SAML_CERTIFICATE_PUBLIC_CERTIFICATE = config(
    "DIGID_SAML_CERTIFICATE_PUBLIC_CERTIFICATE", default=None
)
DIGID_SAML_CERTIFICATE_PRIVATE_KEY = config(
    "DIGID_SAML_CERTIFICATE_PRIVATE_KEY", default=None
)
DIGID_SAML_METADATA_FILE_SOURCE = config(
    "DIGID_SAML_METADATA_FILE_SOURCE", default=None
)
DIGID_SAML_WANT_ASSERTIONS_SIGNED = config(
    "DIGID_SAML_WANT_ASSERTIONS_SIGNED", default=None
)
DIGID_SAML_WANT_ASSERTIONS_ENCRYPTED = config(
    "DIGID_SAML_WANT_ASSERTIONS_ENCRYPTED", default=None
)
DIGID_SAML_ARTIFACT_RESOLVE_CONTENT_TYPE = config(
    "DIGID_SAML_ARTIFACT_RESOLVE_CONTENT_TYPE", default=None
)
DIGID_SAML_KEY_PASSPHRASE = config("DIGID_SAML_KEY_PASSPHRASE", default=None)
DIGID_SAML_SIGNATURE_ALGORITHM = config("DIGID_SAML_SIGNATURE_ALGORITHM", default=None)
DIGID_SAML_DIGEST_ALGORITHM = config("DIGID_SAML_DIGEST_ALGORITHM", default=None)
DIGID_SAML_ENTITY_ID = config("DIGID_SAML_ENTITY_ID", default=None)
DIGID_SAML_BASE_URL = config("DIGID_SAML_BASE_URL", default=None)
DIGID_SAML_SERVICE_NAME = config("DIGID_SAML_SERVICE_NAME", default=None)
DIGID_SAML_SERVICE_DESCRIPTION = config("DIGID_SAML_SERVICE_DESCRIPTION", default=None)
DIGID_SAML_TECHNICAL_CONTACT_PERSON_TELEPHONE = config(
    "DIGID_SAML_TECHNICAL_CONTACT_PERSON_TELEPHONE", default=None
)
DIGID_SAML_TECHNICAL_CONTACT_PERSON_EMAIL = config(
    "DIGID_SAML_TECHNICAL_CONTACT_PERSON_EMAIL", default=None
)
DIGID_SAML_ORGANIZATION_URL = config("DIGID_SAML_ORGANIZATION_URL", default=None)
DIGID_SAML_ORGANIZATION_NAME = config("DIGID_SAML_ORGANIZATION_NAME", default=None)
DIGID_SAML_ATTRIBUTE_CONSUMING_SERVICE_INDEX = config(
    "DIGID_SAML_ATTRIBUTE_CONSUMING_SERVICE_INDEX", default=None
)
DIGID_SAML_REQUESTED_ATTRIBUTES = config(
    "DIGID_SAML_REQUESTED_ATTRIBUTES", default=None
)
DIGID_SAML_SLO = config("DIGID_SAML_SLO", default=None)

#
# Eherkenning SAML
#
EHERKENNING_SAML_CONFIG_ENABLE = config("EHERKENNING_SAML_CONFIG_ENABLE", default=False)
EHERKENNING_SAML_CERTIFICATE_LABEL = config(
    "EHERKENNING_SAML_CERTIFICATE_LABEL", default=None
)
EHERKENNING_SAML_CERTIFICATE_TYPE = config(
    "EHERKENNING_SAML_CERTIFICATE_TYPE", default=None
)
EHERKENNING_SAML_CERTIFICATE_PUBLIC_CERTIFICATE = config(
    "EHERKENNING_SAML_CERTIFICATE_PUBLIC_CERTIFICATE", default=None
)
EHERKENNING_SAML_CERTIFICATE_PRIVATE_KEY = config(
    "EHERKENNING_SAML_CERTIFICATE_PRIVATE_KEY", default=None
)
EHERKENNING_SAML_METADATA_FILE_SOURCE = config(
    "EHERKENNING_SAML_METADATA_FILE_SOURCE", default=None
)
EHERKENNING_SAML_WANT_ASSERTIONS_SIGNED = config(
    "EHERKENNING_SAML_WANT_ASSERTIONS_SIGNED", default=None
)
EHERKENNING_SAML_WANT_ASSERTIONS_ENCRYPTED = config(
    "EHERKENNING_SAML_WANT_ASSERTIONS_ENCRYPTED", default=None
)
EHERKENNING_SAML_ARTIFACT_RESOLVE_CONTENT_TYPE = config(
    "EHERKENNING_SAML_ARTIFACT_RESOLVE_CONTENT_TYPE", default=None
)
EHERKENNING_SAML_KEY_PASSPHRASE = config(
    "EHERKENNING_SAML_KEY_PASSPHRASE", default=None
)
EHERKENNING_SAML_SIGNATURE_ALGORITHM = config(
    "EHERKENNING_SAML_SIGNATURE_ALGORITHM", default=None
)
EHERKENNING_SAML_DIGEST_ALGORITHM = config(
    "EHERKENNING_SAML_DIGEST_ALGORITHM", default=None
)
EHERKENNING_SAML_ENTITY_ID = config("EHERKENNING_SAML_ENTITY_ID", default=None)
EHERKENNING_SAML_BASE_URL = config("EHERKENNING_SAML_BASE_URL", default=None)
EHERKENNING_SAML_SERVICE_NAME = config("EHERKENNING_SAML_SERVICE_NAME", default=None)
EHERKENNING_SAML_SERVICE_DESCRIPTION = config(
    "EHERKENNING_SAML_SERVICE_DESCRIPTION", default=None
)
EHERKENNING_SAML_TECHNICAL_CONTACT_PERSON_TELEPHONE = config(
    "EHERKENNING_SAML_TECHNICAL_CONTACT_PERSON_TELEPHONE", default=None
)
EHERKENNING_SAML_TECHNICAL_CONTACT_PERSON_EMAIL = config(
    "EHERKENNING_SAML_TECHNICAL_CONTACT_PERSON_EMAIL", default=None
)
EHERKENNING_SAML_ORGANIZATION_URL = config(
    "EHERKENNING_SAML_ORGANIZATION_URL", default=None
)
EHERKENNING_SAML_ORGANIZATION_NAME = config(
    "EHERKENNING_SAML_ORGANIZATION_NAME", default=None
)
EHERKENNING_SAML_EH_LOA = config("EHERKENNING_SAML_EH_LOA", default=None)
EHERKENNING_SAML_EH_ATTRIBUTE_CONSUMING_SERVICE_INDEX = config(
    "EHERKENNING_SAML_EH_ATTRIBUTE_CONSUMING_SERVICE_INDEX", default=None
)
EHERKENNING_SAML_EH_REQUESTED_ATTRIBUTES = config(
    "EHERKENNING_SAML_EH_REQUESTED_ATTRIBUTES", default=None
)
EHERKENNING_SAML_EH_SERVICE_UUID = config(
    "EHERKENNING_SAML_EH_SERVICE_UUID", default=None
)
EHERKENNING_SAML_EH_SERVICE_INSTANCE_UUID = config(
    "EHERKENNING_SAML_EH_SERVICE_INSTANCE_UUID", default=None
)
EHERKENNING_SAML_EIDAS_LOA = config("EHERKENNING_SAML_EIDAS_LOA", default=None)
EHERKENNING_SAML_EIDAS_ATTRIBUTE_CONSUMING_SERVICE_INDEX = config(
    "EHERKENNING_SAML_EIDAS_ATTRIBUTE_CONSUMING_SERVICE_INDEX", default=None
)
EHERKENNING_SAML_EIDAS_REQUESTED_ATTRIBUTES = config(
    "EHERKENNING_SAML_EIDAS_REQUESTED_ATTRIBUTES", default=None
)
EHERKENNING_SAML_EIDAS_SERVICE_UUID = config(
    "EHERKENNING_SAML_EIDAS_SERVICE_UUID", default=None
)
EHERKENNING_SAML_EIDAS_SERVICE_INSTANCE_UUID = config(
    "EHERKENNING_SAML_EIDAS_SERVICE_INSTANCE_UUID", default=None
)
EHERKENNING_SAML_OIN = config("EHERKENNING_SAML_OIN", default=None)
EHERKENNING_SAML_NO_EIDAS = config("EHERKENNING_SAML_NO_EIDAS", default=None)
EHERKENNING_SAML_PRIVACY_POLICY = config(
    "EHERKENNING_SAML_PRIVACY_POLICY", default=None
)
EHERKENNING_SAML_MAKELAAR_ID = config("EHERKENNING_SAML_MAKELAAR_ID", default=None)
EHERKENNING_SAML_SERVICE_LANGUAGE = config(
    "EHERKENNING_SAML_SERVICE_LANGUAGE", default=None
)

#
# CMS configuration variables
#

# benefits (ssd)
CMS_CONFIG_SSD_ENABLE = config("CMS_CONFIG_SSD_ENABLE", default=False)
# common extension
CMS_SSD_REQUIRES_AUTH = config("CMS_SSD_REQUIRES_AUTH", default=None)
CMS_SSD_REQUIRES_AUTH_BSN_OR_KVK = config(
    "CMS_SSD_REQUIRES_AUTH_BSN_OR_KVK", default=None
)
CMS_SSD_MENU_INDICATOR = config("CMS_SSD_MENU_INDICATOR", default=None)
CMS_SSD_MENU_ICON = config("CMS_SSD_MENU_ICON", default=None)

# cases
CMS_CONFIG_CASES_ENABLE = config("CMS_CONFIG_CASES_ENABLE", default=False)
# common extension
CMS_CASES_REQUIRES_AUTH = config("CMS_CASES_REQUIRES_AUTH", default=None)
CMS_CASES_REQUIRES_AUTH_BSN_OR_KVK = config(
    "CMS_CASES_REQUIRES_AUTH_BSN_OR_KVK", default=None
)
CMS_CASES_MENU_INDICATOR = config("CMS_CASES_MENU_INDICATOR", default=None)
CMS_CASES_MENU_ICON = config("CMS_CASES_MENU_ICON", default=None)

# collaborations
CMS_CONFIG_COLLABORATE_ENABLE = config("CMS_CONFIG_COLLABORATE_ENABLE", default=False)
# common extension
CMS_COLLABORATE_REQUIRES_AUTH = config("CMS_COLLABORATE_REQUIRES_AUTH", default=None)
CMS_COLLABORATE_REQUIRES_AUTH_BSN_OR_KVK = config(
    "CMS_COLLABORATE_REQUIRES_AUTH_BSN_OR_KVK", default=None
)
CMS_COLLABORATE_MENU_INDICATOR = config("CMS_COLLABORATE_MENU_INDICATOR", default=None)
CMS_COLLABORATE_MENU_ICON = config("CMS_COLLABORATE_MENU_ICON", default=None)

# inbox
CMS_CONFIG_INBOX_ENABLE = config("CMS_CONFIG_INBOX_ENABLE", default=False)
# common extension
CMS_INBOX_REQUIRES_AUTH = config("CMS_INBOX_REQUIRES_AUTH", default=None)
CMS_INBOX_REQUIRES_AUTH_BSN_OR_KVK = config(
    "CMS_INBOX_REQUIRES_AUTH_BSN_OR_KVK", default=None
)
CMS_INBOX_MENU_INDICATOR = config("CMS_INBOX_MENU_INDICATOR", default=None)
CMS_INBOX_MENU_ICON = config("CMS_INBOX_MENU_ICON", default=None)

# products
CMS_CONFIG_PRODUCTS_ENABLE = config("CMS_CONFIG_PRODUCTS_ENABLE", default=False)
# common extension
CMS_PRODUCTS_REQUIRES_AUTH = config("CMS_PRODUCTS_REQUIRES_AUTH", default=None)
CMS_PRODUCTS_REQUIRES_AUTH_BSN_OR_KVK = config(
    "CMS_PRODUCTS_REQUIRES_AUTH_BSN_OR_KVK", default=None
)
CMS_PRODUCTS_MENU_INDICATOR = config("CMS_PRODUCTS_MENU_INDICATOR", default=None)
CMS_PRODUCTS_MENU_ICON = config("CMS_PRODUCTS_MENU_ICON", default=None)

# profile app enable
CMS_CONFIG_PROFILE_ENABLE = config("CMS_CONFIG_PROFILE_ENABLE", default=False)
# procile config
CMS_PROFILE_MY_DATA = config("CMS_PROFILE_MY_DATA", default=None)
CMS_PROFILE_SELECTED_CATEGORIES = config(
    "CMS_PROFILE_SELECTED_CATEGORIES", default=None
)
CMS_PROFILE_MENTORS = config("CMS_PROFILE_MENTORS", default=None)
CMS_PROFILE_MY_CONTACTS = config("CMS_PROFILE_MY_CONTACTS", default=None)
CMS_PROFILE_SELFDIAGNOSE = config("CMS_PROFILE_SELFDIAGNOSE", default=None)
CMS_PROFILE_ACTIONS = config("CMS_PROFILE_ACTIONS", default=None)
CMS_PROFILE_NOTIFICATIONS = config("CMS_PROFILE_NOTIFICATIONS", default=None)
CMS_PROFILE_QUESTIONS = config("CMS_PROFILE_QUESTIONS", default=None)
CMS_PROFILE_SSD = config("CMS_PROFILE_SSD", default=None)
CMS_PROFILE_NEWSLETTERS = config("CMS_PROFILE_NEWSLETTERS", default=None)
CMS_PROFILE_APPOINTMENTS = config("CMS_PROFILE_APPOINTMENTS", default=None)
# profile common extension
CMS_PROFILE_REQUIRES_AUTH = config("CMS_PROFILE_REQUIRES_AUTH", default=None)
CMS_PROFILE_REQUIRES_AUTH_BSN_OR_KVK = config(
    "CMS_PROFILE_REQUIRES_AUTH_BSN_OR_KVK", default=None
)
CMS_PROFILE_MENU_INDICATOR = config("CMS_PROFILE_MENU_INDICATOR", default=None)
CMS_PROFILE_MENU_ICON = config("CMS_PROFILE_MENU_ICON", default=None)
