# Generated by Django 3.2.15 on 2023-05-08 14:16

import app_data.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="Type")),
                (
                    "namespace",
                    models.CharField(
                        default=None,
                        max_length=100,
                        unique=True,
                        verbose_name="Instance namespace",
                    ),
                ),
                (
                    "app_data",
                    app_data.fields.AppDataField(default="{}", editable=False),
                ),
                (
                    "my_data",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether 'My data' section is rendered or not (Only for digid users).",
                        verbose_name="Mijn gegevens",
                    ),
                ),
                (
                    "selected_categories",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether 'selected categories' section is rendered or not.",
                        verbose_name="Interessegebieden",
                    ),
                ),
                (
                    "mentors",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether 'mentors' section is rendered or not.",
                        verbose_name="Begeleiders",
                    ),
                ),
                (
                    "my_contacts",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether 'contacts' section is rendered or not.",
                        verbose_name="Mijn netwerkcontacten",
                    ),
                ),
                (
                    "selfdiagnose",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether 'self diagnose' section is rendered or not.",
                        verbose_name="Zelfdiagnose",
                    ),
                ),
                (
                    "actions",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether 'actions' section is rendered or not.If this is disabled, plans (page and menu) should be disabled as well.",
                        verbose_name="Acties",
                    ),
                ),
                (
                    "notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether 'notifications' section is rendered or not.",
                        verbose_name="Communicatievoorkeuren",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apphook config",
                "verbose_name_plural": "Apphook configs",
                "abstract": False,
                "unique_together": {("type", "namespace")},
            },
        ),
    ]
