# Generated by Django 3.2.15 on 2023-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_profileconfig_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileconfig",
            name="ssd",
            field=models.BooleanField(default=True, verbose_name="Mijn uitkeringen"),
        ),
    ]
