# Generated by Django 3.2.20 on 2023-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_profileconfig_ssd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileconfig",
            name="notifications",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether 'notifications' section is rendered or not.",
                verbose_name="Mijn meldingen",
            ),
        ),
        migrations.AlterField(
            model_name="profileconfig",
            name="selected_categories",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether 'selected categories' section is rendered or not.",
                verbose_name="Gekozen onderwerpen",
            ),
        ),
    ]
