# Generated by Django 3.2.20 on 2023-11-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_profile_texts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileconfig",
            name="selected_categories",
        ),
    ]
