# Generated by Django 3.2.23 on 2024-02-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_alter_profileconfig_ssd"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileconfig",
            name="selected_categories",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether 'selected categories' section is rendered or not.",
                verbose_name="Gekozen onderwerpen",
            ),
        ),
    ]
