# Generated by Django 4.2.10 on 2024-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_profileconfig_selected_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileconfig",
            name="newsletters",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether 'Nieuwsbrieven' section is rendered or not.",
                verbose_name="Nieuwsbrieven",
            ),
        ),
    ]
