# Generated by Django 4.2.10 on 2024-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0008_profileconfig_newsletters"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileconfig",
            name="appointments",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether 'Mijn afspraken' section is rendered or not.",
                verbose_name="Mijn afspraken",
            ),
        ),
    ]
