# Generated by Django 4.2.18 on 2025-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0009_profileconfig_appointments"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileconfig",
            name="documents",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether 'Mijn documenten' section is rendered or not.",
                verbose_name="Mijn documenten",
            ),
        ),
    ]
