# Generated by Django 4.2.29 on 2026-03-24 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0010_remove_aldryn_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profileconfig",
            options={},
        ),
    ]
