# Generated by Django 3.2.15 on 2022-11-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0015_auto_20220307_1522"),
        ("openzaak", "0002_auto_20220128_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="document_service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Documents API",
            ),
        ),
    ]
