# Generated by Django 3.2.15 on 2022-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0004_openzaakconfig_document_max_confidentiality"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="zaak_max_confidentiality",
            field=models.CharField(
                choices=[
                    ("openbaar", "Openbaar"),
                    ("beperkt_openbaar", "Beperkt openbaar"),
                    ("intern", "Intern"),
                    ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                    ("vertrouwelijk", "Vertrouwelijk"),
                    ("confidentieel", "Confidentieel"),
                    ("geheim", "Geheim"),
                    ("zeer_geheim", "Zeer geheim"),
                ],
                default="openbaar",
                help_text="Select maximum confidentiality level of cases",
                max_length=32,
                verbose_name="Case confidentiality",
            ),
        ),
    ]
