# Generated by Django 3.2.15 on 2023-01-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0005_openzaakconfig_zaak_max_confidentiality"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogusConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="Catalogus URL")),
                ("domein", models.CharField(max_length=5, verbose_name="Domein")),
                ("rsin", models.CharField(max_length=9, verbose_name="RSIN")),
            ],
            options={
                "ordering": ("domein", "rsin"),
            },
        ),
        migrations.CreateModel(
            name="ZaakTypeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        max_length=50, verbose_name="Zaaktype identificatie"
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Zaaktype omschrijving"
                    ),
                ),
                ("notify_status_changes", models.BooleanField(default=False)),
                (
                    "catalogus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openzaak.catalogusconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaaktype Configuration",
            },
        ),
        migrations.AddConstraint(
            model_name="zaaktypeconfig",
            constraint=models.UniqueConstraint(
                fields=("catalogus", "identificatie"),
                name="unique_catalogus_identificatie",
            ),
        ),
    ]
