# Generated by Django 3.2.15 on 2023-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0006_auto_20230123_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="skip_notication_statustype_informeren",
            field=models.BooleanField(
                default=False,
                help_text="Enable when StatusType.informeren is not supported by the ZGW backend. This requires ZaakTypeConfig's to be configured to determine on which changes to notify.",
                verbose_name="Use StatusType.informeren workaround",
            ),
        ),
    ]
