# Generated by Django 3.2.15 on 2023-01-26 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openzaak", "0007_alter_openzaakconfig_allowed_file_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogusConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="Catalogus URL")),
                ("domein", models.CharField(max_length=5, verbose_name="Domein")),
                ("rsin", models.CharField(max_length=9, verbose_name="RSIN")),
            ],
            options={
                "ordering": ("domein", "rsin"),
            },
        ),
        migrations.AddField(
            model_name="openzaakconfig",
            name="skip_notification_statustype_informeren",
            field=models.BooleanField(
                default=False,
                help_text="Enable when StatusType.informeren is not supported by the ZGW backend. This requires ZaakTypeConfig's to be configured to determine on which changes to notify.",
                verbose_name="Use StatusType.informeren workaround",
            ),
        ),
        migrations.CreateModel(
            name="ZaakTypeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        max_length=50, verbose_name="Zaaktype identificatie"
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Zaaktype omschrijving"
                    ),
                ),
                ("notify_status_changes", models.BooleanField(default=False)),
                (
                    "catalogus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openzaak.catalogusconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaaktype Configuration",
            },
        ),
        migrations.CreateModel(
            name="UserCaseStatusNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_uuid", models.UUIDField(verbose_name="Zaak UUID")),
                ("status_uuid", models.UUIDField(verbose_name="Status UUID")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Zaak notification user inform record",
            },
        ),
        migrations.AddConstraint(
            model_name="zaaktypeconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("catalogus__isnull", False)),
                fields=("catalogus", "identificatie"),
                name="unique_identificatie_in_catalogus",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaaktypeconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("catalogus__isnull", True)),
                fields=("identificatie",),
                name="unique_identificatie_without_catalogus",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercasestatusnotification",
            constraint=models.UniqueConstraint(
                fields=("user", "case_uuid", "status_uuid"),
                name="unique_user_case_status",
            ),
        ),
    ]
