# Generated by Django 3.2.15 on 2023-01-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0006_auto_20230123_1619"),
        ("openzaak", "0007_openzaakconfig_skip_notication_statustype_informeren"),
    ]

    operations = []
