# Generated by Django 3.2.15 on 2023-01-24 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openzaak", "0008_merge_20230124_1455"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCaseStatusNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_uuid", models.UUIDField(verbose_name="Zaak UUID")),
                ("status_uuid", models.UUIDField(verbose_name="Status UUID")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Zaak notification user inform record",
            },
        ),
        migrations.AddConstraint(
            model_name="usercasestatusnotification",
            constraint=models.UniqueConstraint(
                fields=("user", "case_uuid", "status_uuid"),
                name="unique_user_case_status",
            ),
        ),
    ]
