# Generated by Django 3.2.15 on 2023-01-31 11:53

import django.db.models.deletion
from django.db import migrations, models

import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0008_auto_20230126_1034"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypeconfig",
            name="document_upload_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Enable document upload"
            ),
        ),
        migrations.AddField(
            model_name="zaaktypeconfig",
            name="external_document_upload_url",
            field=models.URLField(blank=True, verbose_name="Document upload URL"),
        ),
        migrations.CreateModel(
            name="ZaakTypeInformatieObjectTypeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "informatieobjecttype_url",
                    models.URLField(
                        max_length=1000, verbose_name="Information object URL"
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(max_length=80, verbose_name="Omschrijving"),
                ),
                (
                    "zaaktype_uuids",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.UUIDField(verbose_name="Zaaktype UUID"),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "document_upload_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Enable document upload"
                    ),
                ),
                (
                    "zaaktype_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openzaak.zaaktypeconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaaktype Information Object Configuration",
            },
        ),
        migrations.AddConstraint(
            model_name="zaaktypeinformatieobjecttypeconfig",
            constraint=models.UniqueConstraint(
                fields=("zaaktype_config", "informatieobjecttype_url"),
                name="unique_zaaktype_config_informatieobjecttype_url",
            ),
        ),
    ]
