# Generated by Django 3.2.15 on 2023-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0009_auto_20230131_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="reformat_esuite_zaak_identificatie",
            field=models.BooleanField(
                default=False,
                help_text="Enable to reformat user-facing Zaak.identificatie numbers from internal eSuite format (ex: '0014ESUITE66392022') to user friendly format ('6639-2022').",
                verbose_name="Reformat eSuite Zaak.identificatie",
            ),
        ),
    ]
