# Generated by Django 3.2.15 on 2023-02-07 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openzaak", "0010_openzaakconfig_reformat_esuite_zaak_identificatie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercasestatusnotification",
            options={"verbose_name": "Open Zaak status notification record"},
        ),
        migrations.CreateModel(
            name="UserCaseInfoObjectNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_uuid", models.UUIDField(verbose_name="Zaak UUID")),
                (
                    "zaak_info_object_uuid",
                    models.UUIDField(verbose_name="InformatieObject UUID"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Zaak info object notification record",
            },
        ),
        migrations.AddConstraint(
            model_name="usercaseinfoobjectnotification",
            constraint=models.UniqueConstraint(
                fields=("user", "case_uuid", "zaak_info_object_uuid"),
                name="unique_user_case_info_object",
            ),
        ),
    ]
