# Generated by Django 3.2.15 on 2023-02-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "openzaak",
            "0012_zaaktypeinformatieobjecttypeconfig_document_notification_enabled",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercaseinfoobjectnotification",
            old_name="created",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="usercasestatusnotification",
            old_name="created",
            new_name="created_on",
        ),
    ]
