# Generated by Django 3.2.15 on 2023-02-09 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0013_auto_20230209_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercaseinfoobjectnotification",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created on"
            ),
        ),
        migrations.AlterField(
            model_name="usercasestatusnotification",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created on"
            ),
        ),
    ]
