# Generated by Django 3.2.15 on 2023-03-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0015_openzaakconfig_form_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktypeconfig",
            name="document_upload_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Enable document upload via URL"
            ),
        ),
    ]
