# Generated by Django 3.2.15 on 2023-03-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
        ("openzaak", "0016_alter_zaaktypeconfig_document_upload_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openzaakconfig",
            name="catalogi_service",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"api_type": "ztc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Catalogi API",
            ),
        ),
        migrations.AlterField(
            model_name="openzaakconfig",
            name="document_service",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Documents API",
            ),
        ),
        migrations.AlterField(
            model_name="openzaakconfig",
            name="form_service",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Form API",
            ),
        ),
        migrations.AlterField(
            model_name="openzaakconfig",
            name="zaak_service",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"api_type": "zrc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Open Zaak API",
            ),
        ),
    ]
