# Generated by Django 3.2.20 on 2023-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "openzaak",
            "0020_rename_contact_moments_enabled_zaaktypeconfig_contact_form_enabled",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usercaseinfoobjectnotification",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Is sent"),
        ),
        migrations.AddField(
            model_name="usercasestatusnotification",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Is sent"),
        ),
    ]
