# Generated by Django 3.2.20 on 2023-08-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "openzaak",
            "0020_rename_contact_moments_enabled_zaaktypeconfig_contact_form_enabled",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Status tekst"
                    ),
                ),
                (
                    "translation",
                    models.CharField(max_length=255, verbose_name="Vertaling"),
                ),
            ],
            options={
                "verbose_name": "Status vertaling",
                "verbose_name_plural": "Status vertalingen",
            },
        ),
    ]
