# Generated by Django 3.2.20 on 2023-08-31 12:14

from django.db import migrations


def mark_as_is_sent(apps, schema_editor):
    """
    the new field is_sent needs default=False, but existing records are all considered is_sent=True
    """
    CaseInfo = apps.get_model("openzaak", "UserCaseInfoObjectNotification")
    CaseInfo.objects.update(is_sent=True)

    CaseStatus = apps.get_model("openzaak", "UserCaseStatusNotification")
    CaseStatus.objects.update(is_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0021_add_is_sent_to_notification_records"),
    ]

    operations = [
        migrations.RunPython(mark_as_is_sent, migrations.RunPython.noop),
    ]
