# Generated by Django 3.2.20 on 2023-09-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0021_statustranslation"),
        ("openzaak", "0022_mark_as_is_sent"),
    ]

    operations = []
