# Generated by Django 3.2.20 on 2023-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0023_merge_0021_statustranslation_0022_mark_as_is_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypeconfig",
            name="contact_subject_code",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="e-Suite 'onderwerp' code"
            ),
        ),
    ]
