# Generated by Django 3.2.20 on 2023-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0024_zaaktypeconfig_contact_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="title_text",
            field=models.TextField(
                default="Hier vindt u een overzicht van al uw lopende en afgeronde aanvragen.",
                help_text="The title/introductory text shown on the list view of 'Mijn aanvragen'.",
                verbose_name="Title text",
            ),
        ),
    ]
