# Generated by Django 3.2.20 on 2023-10-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0025_auto_20231016_0957"),
        ("openzaak", "0025_openzaakconfig_title_text"),
    ]

    operations = []
