# Generated by Django 3.2.20 on 2023-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0027_zaaktype_resultaattype_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="call_to_action_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The text displayed on the call-to-action button",
                max_length=48,
                verbose_name="Call to action text",
            ),
        ),
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="call_to_action_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="The url the user will be sent to by clicking on the call-to-action button",
                verbose_name="Call to action url",
            ),
        ),
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="show_document_uploads",
            field=models.BooleanField(
                default=True,
                help_text="Wheter document uploads are to be shown",
                verbose_name="Show document uploads",
            ),
        ),
    ]
