# Generated by Django 3.2.20 on 2023-11-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0027_auto_20231101_1641"),
        ("openzaak", "0027_zaaktype_resultaattype_config"),
    ]

    operations = []
