# Generated by Django 3.2.20 on 2023-11-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0028_merge_20231101_1705"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The text displayed in the case detail page for the status with this statustype",
                verbose_name="Frontend description",
            ),
        ),
    ]
