# Generated by Django 3.2.20 on 2023-11-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0028_merge_20231101_1705"),
        ("openzaak", "0028_zaaktype_statustype_button"),
    ]

    operations = []
