# Generated by Django 3.2.20 on 2023-11-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0029_auto_20231113_1459"),
        ("openzaak", "0029_zaaktypestatustypeconfig_description"),
    ]

    operations = []
