# Generated by Django 3.2.20 on 2023-11-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0029_merge_20231107_1355"),
        ("openzaak", "0030_merge_20231113_1518"),
    ]

    operations = []
