# Generated by Django 3.2.20 on 2023-11-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0031_merge_20231114_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktypestatustypeconfig",
            name="show_document_uploads",
            field=models.BooleanField(
                default=True,
                help_text="Whether document uploads are to be shown",
                verbose_name="Show document uploads",
            ),
        ),
    ]
