# Generated by Django 3.2.20 on 2023-11-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0032_alter_zaaktypestatustypeconfig_show_document_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="enable_categories_filtering_with_zaken",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the highlighted categories list on the homepage will consist of categories that are linked to ZaakTypen for which the DigiD authenticated user has at least one Zaak.",
                verbose_name="Enable category filtering based on zaken",
            ),
        ),
    ]
