# Generated by Django 3.2.20 on 2023-11-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0037_openzaakconfig_fetch_eherkenning_zaken_with_rsin"),
    ]

    # Cleared this data migration because it caused problems with later migrations and wasn't needed anymore.
    operations = []
