# Generated by Django 3.2.20 on 2023-11-20 10:07

from django.db import migrations
from django.db import transaction
from open_inwoner.openzaak.zgw_imports import get_configurable_zaaktypes
from django.core.exceptions import ObjectDoesNotExist


def populate_zaaktype_config_urls(apps, schema_editor):
    """
    Go through configurable zaaktypen and populate the new URL field where needed
    """
    ZaakTypeConfig = apps.get_model("openzaak", "ZaakTypeConfig")
    CatalogusConfig = apps.get_model("openzaak", "CatalogusConfig")
    catalog_lookup = {c.url: c for c in CatalogusConfig.objects.all()}

    zaaktypes = get_configurable_zaaktypes()
    if not zaaktypes:
        return []

    with transaction.atomic():
        for zaaktype in zaaktypes:
            catalog = catalog_lookup.get(zaaktype.catalogus)
            if not catalog:
                continue

            try:
                config = ZaakTypeConfig.objects.get(
                    catalogus=catalog, identificatie=zaaktype.identificatie
                )
                if zaaktype.url not in config.urls:
                    config.urls = config.urls + [zaaktype.url]
                    config.save()
            except ObjectDoesNotExist:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0034_zaaktypeconfig_urls"),
    ]

    operations = [
        migrations.RunPython(populate_zaaktype_config_urls, migrations.RunPython.noop),
    ]
