# Generated by Django 3.2.20 on 2023-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0035_populate_zaaktypeconfig_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypeconfig",
            name="relevante_zaakperiode",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Aantal maanden dat teruggekeken moet worden naar Zaken van deze zaaktypes.",
                null=True,
                verbose_name="Relevante zaakperiode",
            ),
        ),
    ]
