# Generated by Django 3.2.20 on 2023-11-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0035_populate_zaaktypeconfig_urls"),
        ("openzaak", "0037_result_description"),
    ]

    operations = []
