# Generated by Django 3.2.20 on 2023-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0037_result_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zaaktypestatustypeconfig",
            name="show_document_uploads",
        ),
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="document_upload_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable document uploads for this statustype (override setting for case type)",
                verbose_name="Document uploads",
            ),
        ),
    ]
