# Generated by Django 3.2.20 on 2023-11-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0037_openzaakconfig_fetch_eherkenning_zaken_with_rsin"),
        ("openzaak", "0038_merge_20231130_1232"),
    ]

    operations = []
