# Generated by Django 3.2.20 on 2023-11-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0038_auto_20231129_1212"),
        ("openzaak", "0039_merge_20231130_1523"),
    ]

    operations = []
