# Generated by Django 3.2.23 on 2024-01-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0040_merge_20231130_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="case_link_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The text that will be shown in the button that links to a case's detail page",
                max_length=40,
                verbose_name="Case link text",
            ),
        ),
    ]
