# Generated by Django 3.2.23 on 2024-01-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0042_case_notification_mail_template_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="action_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether the status change notification should indicate that an action is required",
                verbose_name="Action required",
            ),
        ),
    ]
