# Generated by Django 3.2.23 on 2024-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0043_zaaktypestatustypeconfig_action_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="action_required_deadline_days",
            field=models.IntegerField(
                default=15,
                help_text="Aantal dagen voor gebruiker om actie te ondernemen.",
                verbose_name="Standaard actie deadline termijn in dagen",
            ),
        ),
    ]
