# Generated by Django 4.2.10 on 2024-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0044_openzaakconfig_action_required_deadline_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercaseinfoobjectnotification",
            name="collision_key",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Collision key"
            ),
        ),
        migrations.AddField(
            model_name="usercasestatusnotification",
            name="collision_key",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Collision key"
            ),
        ),
    ]
