# Generated by Django 4.2.11 on 2024-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0045_usercaseinfoobjectnotification_collision_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openzaakconfig",
            name="fetch_eherkenning_zaken_with_rsin",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, Zaken for eHerkenning users are fetched using the company RSIN (Open Zaak). If not enabled, Zaken are fetched using the KvK number (eSuite).",
                verbose_name="Fetch Zaken for users authenticated with eHerkenning using RSIN",
            ),
        ),
    ]
