# Generated by Django 4.2.11 on 2024-05-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0046_alter_openzaakconfig_fetch_eherkenning_zaken_with_rsin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktyperesultaattypeconfig",
            name="omschrijving",
            field=models.CharField(max_length=200, verbose_name="Omschrijving"),
        ),
    ]
