# Generated by Django 4.2.15 on 2024-09-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0054_zgw_api_group_requires_most_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="zaken_filter_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Give users the option to filter zaken by status",
                verbose_name="Enable zaken filter",
            ),
        ),
    ]
