# Generated by Django 4.2.16 on 2024-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0055_openzaakconfig_zaken_filter_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="order_statusses_by_date_set",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, order the statusses of a case based on 'datum_status_gezet'. If not enabled, we show the statusses in the reverse order they are returned via the API, this because the eSuite does not return the timestamps of the statusses (eSuite, but also works for Open Zaak).",
                verbose_name="On the detail page of the case, order the statusses on the date they have been set",
            ),
        ),
    ]
