# Generated by Django 4.2.16 on 2024-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0055_openzaakconfig_zaken_filter_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="use_zaak_omschrijving_as_title",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, we use zaak.omschrijving for the title of the cases, and use zaaktype.omschrijving as a fallback in case it is not filled in. If not enabled, we ignore zaak.omschrijving and always use zaaktype.omschrijving.",
                verbose_name="Make use of zaak.omschrijving for the title of the cases instead of zaaktype.omschrijving (eSuite)",
            ),
        ),
    ]
