# Generated by Django 4.2.16 on 2024-11-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0055_openzaakconfig_zaken_filter_enabled"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zaaktypeconfig",
            name="unique_identificatie_in_catalogus",
        ),
        migrations.RemoveConstraint(
            model_name="zaaktypeinformatieobjecttypeconfig",
            name="unique_zaaktype_config_informatieobjecttype_url",
        ),
        migrations.RemoveConstraint(
            model_name="zaaktyperesultaattypeconfig",
            name="unique_zaaktype_config_resultaattype_url",
        ),
        migrations.RemoveConstraint(
            model_name="zaaktypestatustypeconfig",
            name="unique_zaaktype_config_statustype_url",
        ),
    ]
