# Generated by Django 4.2.16 on 2024-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0056_openzaakconfig_use_zaak_omschrijving_as_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="order_statuses_by_date_set",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the statuses of a case are ordered based on 'datum_status_gezet'. If not enabled, we show the statuses in the reverse order they are returned via the API, this because the eSuite does not return the timestamps of the statuses (eSuite, but also works for Open Zaak).",
                verbose_name="On the detail page of the case, order the statuses based on the date they have been set",
            ),
        ),
    ]
