# Generated by Django 4.2.16 on 2024-10-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0056_openzaakconfig_order_statusses_by_date_set"),
        ("openzaak", "0056_openzaakconfig_use_zaak_omschrijving_as_title"),
    ]

    operations = []
