# Generated by Django 4.2.16 on 2025-01-23 11:13

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def migrate_fetch_eherkenning_zaken_with_rsin(apps, _):
    OpenZaakConfig = apps.get_model("openzaak", "OpenZaakConfig")
    ZGWApiGroupConfig = apps.get_model("openzaak", "ZGWApiGroupConfig")

    zaak_config = OpenZaakConfig.objects.first()

    for config in ZGWApiGroupConfig.objects.all():
        config.fetch_eherkenning_zaken_with_rsin = (
            zaak_config.fetch_eherkenning_zaken_with_rsin
        )
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0059_openzaakconfig_show_cases_without_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="fetch_eherkenning_zaken_with_rsin",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, Zaken for eHerkenning users are fetched using the company RSIN (Open Zaak). If not enabled, Zaken are fetched using the KvK number (eSuite).",
                verbose_name="Fetch Zaken for users authenticated with eHerkenning using RSIN",
            ),
        ),
        migrations.RunPython(
            code=migrate_fetch_eherkenning_zaken_with_rsin,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="openzaakconfig",
            name="fetch_eherkenning_zaken_with_rsin",
        ),
    ]
