# Generated by Django 4.2.20 on 2025-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0059_openzaakconfig_show_cases_without_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="limit_user_visible_cases_to_role",
            field=models.CharField(
                blank=True,
                choices=[("initiator", "Initiator")],
                help_text="Show only cases in which the user has the relevant role. Leave empty to show cases irrespective of role.",
                verbose_name="Limit cases to role",
            ),
        ),
    ]
