# Generated by Django 4.2.16 on 2025-01-24 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "openzaak",
            "0060_remove_openzaakconfig_use_zaak_omschrijving_as_title_and_more",
        ),
        ("openzaak", "0060_zgwapigroupconfig_fetch_eherkenning_zaken_with_rsin"),
    ]

    operations = []
