# Generated by Django 4.2.18 on 2025-01-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "openzaak",
            "0061_merge_20250124_1149",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="enable_eherkenning_for_eenmanszaak",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, eenmanszaken may authenticate using eHerkenning and subsequently their kvk nummer will be used to interface with the zaken and klanten backends). If not, an eenmanszaak will be forced to use DigiD,  and the user's BSN will be used instead.",
                verbose_name="Allow eenmanszaken to authenticate using eHerkenning",
            ),
        ),
    ]
