# Generated by Django 4.2.18 on 2025-01-28 16:08

from django.db import migrations, models

import open_inwoner.openklant.models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0061_openzaakconfig_enable_eherkenning_for_eenmanszaak"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="klant_backend",
            field=models.CharField(
                choices=[("esuite", "ESUITE"), ("openklant2", "OPENKLANT2")],
                default="esuite",
                null=True,
                blank=True,
                help_text="Choose the API backend for retrieving klanten data.",
                max_length=10,
                validators=[open_inwoner.openklant.models.validate_backend_choice],
                verbose_name="Klant API backend",
            ),
        ),
    ]
