# Generated by Django 4.2.18 on 2025-02-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0063_alter_openzaakconfig_show_cases_without_status"),
        ("configurations", "0075_siteconfiguration_enable_eherkenning_for_eenmanszaak"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openzaakconfig",
            name="enable_eherkenning_for_eenmanszaak",
        ),
    ]
