# Generated by Django 4.2.20 on 2025-03-25 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0060_openzaakconfig_limit_user_visible_cases_to_role"),
        ("openzaak", "0066_replace_aanvragen_zaken"),
    ]

    operations = []
