# Generated by Django 4.2.20 on 2025-04-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0067_forwardport_0060_limit_user_visible_cases_to_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="derive_zaak_titel_from",
            field=models.CharField(
                choices=[
                    (
                        "zaak_omschrijving",
                        "The description of the case (`zaak.omschrijving`)",
                    ),
                    (
                        "zaaktype_omschrijving",
                        "The description of the case's type (`zaaktype.omschrijving`)",
                    ),
                    (
                        "zaaktype_onderwerp",
                        "The subject of the case's type (`zaaktype.onderwerp`)",
                    ),
                ],
                default="zaaktype_omschrijving",
                help_text="Which field from the underlying zaaksysteem to use to display the title  for a zaak (e.g. on the Mijn Zaken page).",
                verbose_name="Derive the case title from",
            ),
        ),
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="order_statuses_by_date_set",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the statuses of a case are ordered based on 'datum_status_gezet'. If not enabled, we show the statuses in the reverse order they are returned via the API, this because the eSuite does not return the timestamps of the statuses (eSuite, but also works for Open Zaak).",
                verbose_name="On the detail page of the case, order the statuses based on the date they have been set",
            ),
        ),
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="reformat_esuite_zaak_identificatie",
            field=models.BooleanField(
                default=False,
                help_text="Enable to reformat user-facing Zaak.identificatie numbers from internal eSuite format (ex: '0014ESUITE66392022') to user friendly format ('6639-2022').",
                verbose_name="Reformat eSuite Zaak.identificatie",
            ),
        ),
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="skip_notification_statustype_informeren",
            field=models.BooleanField(
                default=False,
                help_text="Enable when StatusType.informeren is not supported by the ZGW backend. This requires ZaakTypeConfig's to be configured to determine on which changes to notify.",
                verbose_name="Use StatusType.informeren workaround",
            ),
        ),
    ]
