# Generated by Django 4.2.24 on 2025-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "openzaak",
            "0068_zgwapigroupconfig_fetch_eherkenning_zaken_with_openzaak_120_params",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="zgwapigroupconfig",
            name="fetch_eherkenning_zaken_with_openzaak_120_params",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, Zaken for eHerkenning users are fetched using the rol__betrokkeneIdentificatie__nietNatuurlijkPersoon__kvkNummer and rol__betrokkeneIdentificatie__nietNatuurlijkPersoon__vestigingsNummer query parameters, rather than the rol__betrokkeneIdentificatie__vestiging__vestigingsNummer and rol__betrokkeneIdentificatie__nietNatuurlijkPersoon__innNnpId query parameters. This feature is available only in OpenZaak from version 1.20 and higher.",
                verbose_name="Fetch Zaken for users authenticated with eHerkenning using OpenZaak 1.20 query parameters",
            ),
        ),
    ]
