# Generated by Django 4.2.20 on 2025-04-23 10:54

from django.db import migrations


def migrate_zgw_backend_flags(apps, _):
    OpenZaakConfig = apps.get_model("openzaak", "OpenZaakConfig")
    ZGWApiGroupConfig = apps.get_model("openzaak", "ZGWApiGroupConfig")

    zaak_config = OpenZaakConfig.objects.first()

    # We migrate from global to backend-specific flags, hence we store the value of the
    # global setting on all backends to start with
    for zgw_group in ZGWApiGroupConfig.objects.all():
        zgw_group.skip_notification_statustype_informeren = (
            zaak_config.skip_notification_statustype_informeren
        )
        zgw_group.reformat_esuite_zaak_identificatie = (
            zaak_config.reformat_esuite_zaak_identificatie
        )
        zgw_group.derive_zaak_titel_from = zaak_config.derive_zaak_titel_from
        zgw_group.order_statuses_by_date_set = zaak_config.order_statuses_by_date_set
        zgw_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0068_zgwapigroupconfig_derive_zaak_titel_from_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_zgw_backend_flags,
            reverse_code=migrations.RunPython.noop,
        )
    ]
