# Generated by Django 4.2.20 on 2025-04-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0069_auto_20250423_1254"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openzaakconfig",
            name="derive_zaak_titel_from",
        ),
        migrations.RemoveField(
            model_name="openzaakconfig",
            name="order_statuses_by_date_set",
        ),
        migrations.RemoveField(
            model_name="openzaakconfig",
            name="reformat_esuite_zaak_identificatie",
        ),
        migrations.RemoveField(
            model_name="openzaakconfig",
            name="skip_notification_statustype_informeren",
        ),
    ]
