# Generated by Django 4.2.25 on 2025-10-06 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0071_zaaktypestatustypeconfig_description_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zaaktypestatustypeconfig",
            name="description_tmp",
        ),
    ]
