# Generated by Django 4.2.25 on 2025-10-06 10:32

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0072_zaaktypestatustypeconfig_description_schema_2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zaaktypestatustypeconfig",
            old_name="document_upload_description",
            new_name="document_upload_description_tmp",
        ),
        migrations.AddField(
            model_name="zaaktypestatustypeconfig",
            name="document_upload_description",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                ],
                blank=True,
                default=None,
                help_text="Description that will be shown above the document upload widget in a case detail page",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Document upload description",
            ),
        ),
    ]
