# Generated by Django 4.2.25 on 2025-10-06 10:32

import logging  # noqa: TID251 - keep for old migrations

from django.db import migrations

import markdown
from django_prosemirror.config import ProsemirrorConfig
from django_prosemirror.schema import MarkType, NodeType
from django_prosemirror.serde import html_to_doc

logger = logging.getLogger(__name__)


def migrate_statustype_doc_upload_descriptions(apps, schema_editor):
    ZaakTypeStatusTypeConfig = apps.get_model("openzaak", "ZaakTypeStatusTypeConfig")

    config = ProsemirrorConfig(
        allowed_node_types=[NodeType.PARAGRAPH],
        allowed_mark_types=[
            MarkType.STRONG,
            MarkType.ITALIC,
            MarkType.LINK,
            MarkType.UNDERLINE,
        ],
    )

    for row in ZaakTypeStatusTypeConfig.objects.values(
        "pk", "document_upload_description_tmp"
    ):
        content = row["document_upload_description_tmp"]

        if not content or not content.strip():
            continue

        content = content.strip('"')
        html_content = markdown.markdown(content, extensions=["extra"])

        if not html_content.startswith("<p>"):
            html_content = f"<p>{html_content}</p>"

        try:
            doc = html_to_doc(html_content, schema=config.schema)
        except (IndexError, ValueError):
            logger.exception(
                "Warning: Could not convert doc_upload_description for statustype_config pk=%s",
                row["pk"],
            )
            continue

        ZaakTypeStatusTypeConfig.objects.filter(pk=row["pk"]).update(
            document_upload_description=doc
        )


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0073_zaaktypestatustypeconfig_doc_upload_description_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_statustype_doc_upload_descriptions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
