# Generated by Django 4.2.25 on 2025-10-06 10:32

import logging  # noqa: TID251 - keep for old migrations

from django.db import migrations

import markdown
from django_prosemirror.config import ProsemirrorConfig
from django_prosemirror.schema import MarkType, NodeType
from django_prosemirror.serde import html_to_doc

logger = logging.getLogger(__name__)


def markdown_to_html(text):
    return markdown.markdown(text, extensions=["extra"])


def migrate_statustype_doc_upload_descriptions(apps, _):
    ZaakTypeStatusTypeConfig = apps.get_model("openzaak", "ZaakTypeStatusTypeConfig")

    statustype_configs = ZaakTypeStatusTypeConfig.objects.all()

    config = ProsemirrorConfig(
        allowed_node_types=[NodeType.PARAGRAPH],
        allowed_mark_types=[
            MarkType.STRONG,
            MarkType.ITALIC,
            MarkType.LINK,
            MarkType.UNDERLINE,
        ],
    )

    for statustype_config in statustype_configs:
        markdown_content = statustype_config.document_upload_description_tmp

        if not markdown_content or not markdown_content.strip():
            statustype_config.document_upload_description = None
            statustype_config.save()
            continue

        markdown_content = markdown_content.strip('"')

        html_content = markdown_to_html(markdown_content)

        if not html_content.startswith("<p>"):
            html_content = f"<p>{html_content}</p>"

        try:
            doc = html_to_doc(html_content, schema=config.schema)
            statustype_config.document_upload_description = doc
        except (IndexError, ValueError):
            logger.exception(
                "Warning: Could not convert description for statustype_config: %s",
                statustype_config,
            )
            statustype_config.document_upload_description = None

        statustype_config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0073_zaaktypestatustypeconfig_doc_upload_description_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_statustype_doc_upload_descriptions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
