# Generated by Django 4.2.28 on 2026-02-17 07:48

from django.db import migrations

import structlog

logger = structlog.stdlib.get_logger(__name__)


def fix_empty_string_prosemirror_fields(apps, schema_editor):  # noqa: ARG001
    """
    Fix ProseMirror fields that contain empty string literals '""'.

    This issue occurs when configs are exported/imported via the ZGW import/export
    functionality. The export code converts empty ProseMirror fields to the string '""'
    which then gets imported back into the database as JSON string value.

    ProseMirrorModelField is a JSONField that wraps values in ProsemirrorFieldDocument.
    When "" is stored, accessing the field gives us a wrapper with raw_data="".
    We need to check the raw_data attribute and set the field to None if it's "".

    This migration fixes existing instances by:
    1. Finding all fields where raw_data is the string "" (not dict/object/None)
    2. Setting them to None instead
    """
    ZaakTypeStatusTypeConfig = apps.get_model("openzaak", "ZaakTypeStatusTypeConfig")

    # Track statistics
    fixed_count = 0

    # Define models and their fields to fix
    # Note: ZaakTypeResultaatTypeConfig.description is a TextField, not ProsemirrorModelField
    # It doesn't have the "" issue from import/export, so we skip it
    # Note: ZaakTypeInformatieObjectTypeConfig has no ProsemirrorModelField fields
    models_to_fix = [
        (
            ZaakTypeStatusTypeConfig,
            ["description", "document_upload_description"],
        ),
    ]

    for model, field_names in models_to_fix:
        for config in model.objects.all():
            changed = False

            for field_name in field_names:
                # Check if field exists and is not None
                if not hasattr(config, field_name):
                    continue

                field_value = getattr(config, field_name)
                if field_value is None:
                    continue

                # In migrations, we might not have the wrapper, just the raw value
                raw_value = getattr(field_value, "raw_data", field_value)

                if raw_value == "":
                    logger.info(
                        "Fixing empty string literal in ProseMirror field",
                        model=model.__name__,
                        field=field_name,
                        config_id=config.pk,
                        omschrijving=config.omschrijving,
                    )
                    setattr(config, field_name, None)
                    changed = True

            if changed:
                config.save()
                fixed_count += 1

    logger.info(
        "Completed fixing empty string ProseMirror fields",
        total_fixed_count=fixed_count,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0077_catalogusconfig_found_in_api_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=fix_empty_string_prosemirror_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
