# Generated by Django 4.2.28 on 2026-02-17 07:48

from django.db import migrations

import structlog

logger = structlog.stdlib.get_logger(__name__)


def fix_empty_string_prosemirror_fields(apps, schema_editor):
    """
    Fix ProseMirror fields that contain empty string literals '""'.

    This issue occurs when configs are exported/imported via the ZGW import/export
    functionality. The export code converts empty ProseMirror fields to the string '""'
    which then gets imported back into the database as JSON string value.

    This migration fixes existing instances by:
    1. Finding all fields where the JSONB value is the JSON string "" (not a dict)
    2. Setting them to NULL instead
    """
    ZaakTypeStatusTypeConfig = apps.get_model("openzaak", "ZaakTypeStatusTypeConfig")

    # Note: ZaakTypeResultaatTypeConfig.description is a TextField, not ProsemirrorModelField
    # Note: ZaakTypeInformatieObjectTypeConfig has no ProsemirrorModelField fields
    field_names = ["description", "document_upload_description"]

    fixed_count = 0

    for field_name in field_names:
        for row in ZaakTypeStatusTypeConfig.objects.values(
            "pk", "omschrijving", field_name
        ):
            if row[field_name] != "":
                continue
            logger.info(
                "Fixing empty string literal in ProseMirror field",
                model="ZaakTypeStatusTypeConfig",
                field=field_name,
                config_id=row["pk"],
                omschrijving=row["omschrijving"],
            )
            ZaakTypeStatusTypeConfig.objects.filter(pk=row["pk"]).update(
                **{field_name: None}
            )
            fixed_count += 1

    logger.info(
        "Completed fixing empty string ProseMirror fields",
        total_fixed_count=fixed_count,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0077_catalogusconfig_found_in_api_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=fix_empty_string_prosemirror_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
