# Generated by Django 4.2.28 on 2026-03-02 12:43

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0078_fix_empty_string_prosemirror_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaaktypestatustypeconfig",
            name="description",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                blank=True,
                default=None,
                help_text="The text displayed in the case detail page for the status with this statustype",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Frontend description",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktypestatustypeconfig",
            name="document_upload_description",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                blank=True,
                default=None,
                help_text="Description that will be shown above the document upload widget in a case detail page",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Document upload description",
            ),
        ),
    ]
