# Generated by Django 5.2.13 on 2026-05-27 13:33

import django.utils.translation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0079_alter_zaaktypestatustypeconfig_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="zaak_end_date_label",
            field=models.CharField(
                default=django.utils.translation.gettext_lazy("Besluit genomen op"),
                help_text="Label shown when the case has a final decision date (einddatum is set).",
                max_length=100,
                verbose_name="Label: besluit genomen op",
            ),
        ),
        migrations.AddField(
            model_name="openzaakconfig",
            name="zaak_expected_end_date_label",
            field=models.CharField(
                default=django.utils.translation.gettext_lazy(
                    "U ontvangt een besluit vóór"
                ),
                help_text="Label shown when no final decision date is known yet; displays the legal or planned deadline.",
                max_length=100,
                verbose_name="Label: verwachte einddatum",
            ),
        ),
        migrations.AddField(
            model_name="openzaakconfig",
            name="zaak_identificatie_label",
            field=models.CharField(
                default=django.utils.translation.gettext_lazy("Zaaknummer"),
                help_text="Label shown next to the case identification number on the case detail page.",
                max_length=100,
                verbose_name="Label: zaaknummer",
            ),
        ),
        migrations.AddField(
            model_name="openzaakconfig",
            name="zaak_start_date_label",
            field=models.CharField(
                default=django.utils.translation.gettext_lazy("Zaak ingediend op"),
                help_text="Label shown next to the case submission date on the case detail page.",
                max_length=100,
                verbose_name="Label: zaak ingediend op",
            ),
        ),
    ]
