# Generated by Django 5.2.14 on 2026-06-02 10:48

from django.db import migrations, models

import django_jsonform.models.fields

import open_inwoner.openzaak.models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0080_openzaakconfig_zaak_end_date_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="document_visible_statuses",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("in_bewerking", "In bewerking"),
                        ("ter_vaststelling", "Ter vaststelling"),
                        ("definitief", "Definitief"),
                        ("gearchiveerd", "Gearchiveerd"),
                    ],
                    max_length=32,
                ),
                default=open_inwoner.openzaak.models.default_document_visible_statuses,
                help_text="Select which document statuses are visible to users. Documents with other statuses will be hidden. Warning: selecting no statuses means documents with any status will be visible.",
                size=None,
                verbose_name="Visible document statuses",
            ),
        ),
    ]
