# Generated by Django 5.2.14 on 2026-06-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0081_openzaakconfig_document_visible_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="case_list_fetch_timeout",
            field=models.PositiveIntegerField(
                default=25,
                help_text="Total time budget in seconds for fetching and resolving the case list. Divided proportionally across pipeline stages. Set slightly below the overall HTTP response timeout of the server.",
                verbose_name="Case list fetch timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="openzaakconfig",
            name="case_list_num_workers",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Maximum number of worker threads used to fetch and resolve cases in parallel on the case list page. Leave empty to use the library default (based on CPU count).",
                null=True,
                verbose_name="Case list worker threads",
            ),
        ),
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="cache_catalogi_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                default=86400,
                help_text="How long (in seconds) Catalogi API responses are cached. Leave empty to disable caching for this group.",
                null=True,
                verbose_name="Catalogi cache timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="cache_zaken_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                default=300,
                help_text="How long (in seconds) Zaken API responses are cached. Leave empty to disable caching for this group.",
                null=True,
                verbose_name="Zaken cache timeout (seconds)",
            ),
        ),
    ]
