# Generated by Django 5.2.14 on 2026-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0083_zgw_connect_params_defaults_from_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="openzaakconfig",
            name="notification_frequency_limit",
            field=models.PositiveIntegerField(
                default=900,
                help_text="Minimum time in seconds between notification emails sent to a user for the same case. Prevents email spam when multiple status changes occur in quick succession. Default is 900 seconds (15 minutes).",
                verbose_name="Notification frequency limit (seconds)",
            ),
        ),
    ]
