# Generated by Django 5.2.16 on 2026-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0084_openzaakconfig_notification_frequency_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktypeconfig",
            name="zaken_visible_from",
            field=models.DateField(
                blank=True,
                help_text="Only cases of this zaaktype with a startdatum on or after this date are shown to users. Leave empty to show all cases.",
                null=True,
                verbose_name="Show cases from date",
            ),
        ),
    ]
