# Generated by Django 5.2.17 on 2026-08-13 11:53

from django.db import migrations, models

import django_jsonform.models.fields

import open_inwoner.openzaak.models


class Migration(migrations.Migration):
    dependencies = [
        ("openzaak", "0085_zaaktypeconfig_zaken_visible_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openzaakconfig",
            name="document_visible_statuses",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("in_bewerking", "In bewerking"),
                        ("ter_vaststelling", "Ter vaststelling"),
                        ("definitief", "Definitief"),
                        ("gearchiveerd", "Gearchiveerd"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=open_inwoner.openzaak.models.default_document_visible_statuses,
                help_text="Select which document statuses are visible to users. Documents with other statuses will be hidden. Warning: selecting no statuses means documents with any status will be visible.",
                size=None,
                verbose_name="Visible document statuses",
            ),
        ),
    ]
