# Generated by Django 4.2.27 on 2026-01-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("zgw_consumers", "0025_service_jwt_valid_for"),
    ]

    operations = [
        migrations.CreateModel(
            name="MijnAfvalConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openafval_service",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.service",
                        verbose_name="OpenAfval API service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuratie Mijn Afval",
            },
        ),
    ]
