# Generated by Django 5.2.17

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_yubin", "0011_message_bcc_address_message_cc_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[],
            options={
                "proxy": True,
                "verbose_name": "e-mail verzendlog",
                "verbose_name_plural": "e-mail verzendlogs",
                "indexes": [],
                "constraints": [],
            },
            bases=("django_yubin.log",),
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[],
            options={
                "proxy": True,
                "verbose_name": "verzonden e-mail",
                "verbose_name_plural": "verzonden e-mails",
                "indexes": [],
                "constraints": [],
            },
            bases=("django_yubin.message",),
        ),
    ]
