# Generated by Django 3.2.20 on 2023-09-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoPlayer",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="plugins_videoplayer",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        help_text="The video from the catalog.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="media.video",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
