# Generated by Django 4.2.10 on 2024-03-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("plugins", "0004_alter_userfeed_cmsplugin_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAppointments",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Geplande balie-afspraken",
                        help_text="The title of the plugin block",
                        max_length=250,
                        verbose_name="Title",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
