# Generated by Django 4.2.16 on 2024-10-06 13:07

import django.db.models.deletion
from django.db import migrations, models

import objectsapiclient.models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("plugins", "0005_userappointments"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasksConfig",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Mijn Taken",
                        help_text="The title of the tasks block",
                        max_length=250,
                        verbose_name="Title",
                    ),
                ),
                (
                    "object_type",
                    objectsapiclient.models.ObjectTypeField(
                        db_index=False, max_length=100
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
