# Generated by Django 4.2.22 on 2025-08-18 14:39

from django.db import migrations

import objectsapiclient.models


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0006_tasksconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasksconfig",
            name="object_type",
        ),
        migrations.AddField(
            model_name="tasksconfig",
            name="object_type_dimpact",
            field=objectsapiclient.models.ObjectTypeField(
                blank=True,
                db_index=False,
                max_length=100,
                null=True,
                verbose_name="Object Type (Extern Formulier Taak)",
            ),
        ),
        migrations.AddField(
            model_name="tasksconfig",
            name="object_type_generieke_dienstverlening",
            field=objectsapiclient.models.ObjectTypeField(
                blank=True,
                db_index=False,
                max_length=100,
                null=True,
                verbose_name="Object Type (Url Taak)",
            ),
        ),
    ]
