# Generated by Django 4.2.25 on 2025-10-28 12:39

import django.db.models.deletion
from django.db import migrations, models

import django_prosemirror.fields
import django_prosemirror.schema.types
import djangocms_attributes_field.fields
import djangocms_link.validators
import filer.fields.file


class Migration(migrations.Migration):
    dependencies = [
        ("filer", "0017_image__transparent"),
        ("cms", "0022_auto_20180620_1551"),
        ("plugins", "0008_add_text_plugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSLinkPluginConfig",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Ga naar",
                        help_text="The title of the plugin block",
                        max_length=128,
                        verbose_name="Title",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="ExtendedCMSLink",
            fields=[
                (
                    "template",
                    models.CharField(
                        choices=[("default", "Default"), ("arrow", "Arrow")],
                        default="default",
                        max_length=255,
                        verbose_name="Template",
                    ),
                ),
                (
                    "external_link",
                    models.CharField(
                        blank=True,
                        help_text="Provide a link to an external source.",
                        max_length=2040,
                        validators=[
                            djangocms_link.validators.IntranetURLValidator(
                                intranet_host_re=None
                            )
                        ],
                        verbose_name="External link",
                    ),
                ),
                (
                    "anchor",
                    models.CharField(
                        blank=True,
                        help_text='Appends the value only after the internal or external link. Do <em>not</em> include a preceding "#" symbol.',
                        max_length=255,
                        verbose_name="Anchor",
                    ),
                ),
                (
                    "mailto",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="Email address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=255, verbose_name="Phone"),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("_blank", "Open in new window"),
                            ("_self", "Open in same window"),
                            ("_parent", "Delegate to parent"),
                            ("_top", "Delegate to top"),
                        ],
                        max_length=255,
                        verbose_name="Target",
                    ),
                ),
                (
                    "attributes",
                    djangocms_attributes_field.fields.AttributesField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "name",
                    django_prosemirror.fields.ProsemirrorModelField(
                        allowed_mark_types=[
                            django_prosemirror.schema.types.MarkType["STRONG"],
                            django_prosemirror.schema.types.MarkType["ITALIC"],
                            django_prosemirror.schema.types.MarkType["UNDERLINE"],
                        ],
                        allowed_node_types=[
                            django_prosemirror.schema.types.NodeType["PARAGRAPH"]
                        ],
                        default=None,
                        help_text="The text displayed for the link",
                        history=True,
                        tag_to_classes={},
                        verbose_name="Name",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="east",
                        help_text="Material icon name (e.g., 'east', 'arrow_forward', 'check', 'home'). See https://fonts.google.com/icons for available icons.",
                        max_length=96,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "file_link",
                    filer.fields.file.FilerFileField(
                        blank=True,
                        help_text="If provided links a file from the filer app.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="filer.file",
                        verbose_name="File link",
                    ),
                ),
                (
                    "internal_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="If provided, overrides the external link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cms.page",
                        verbose_name="Internal link",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
