# Generated by Django 4.2.25 on 2025-11-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("plugins", "0009_cmslinkpluginconfig_extendedcmslink"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSZakenPluginConfig",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Mijn Zaken",
                        help_text="The title of the zaken plugin block",
                        max_length=250,
                        verbose_name="Title",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
