# Generated by Django 4.2.27 on 2025-12-03 09:38

from django.db import migrations

import objectsapiclient.models


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0010_cmszakenpluginconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksconfig",
            name="object_type_dimpact",
            field=objectsapiclient.models.LazyObjectTypeField(
                blank=True,
                db_index=False,
                max_length=100,
                null=True,
                verbose_name="Object Type (Extern Formulier Taak)",
            ),
        ),
        migrations.AlterField(
            model_name="tasksconfig",
            name="object_type_generieke_dienstverlening",
            field=objectsapiclient.models.LazyObjectTypeField(
                blank=True,
                db_index=False,
                max_length=100,
                null=True,
                verbose_name="Object Type (Url Taak)",
            ),
        ),
    ]
