# Generated by Django 4.2.28 on 2026-02-17 12:30

import json

from django.db import connection, migrations, transaction

import structlog
from django_prosemirror.config import ProsemirrorConfig
from django_prosemirror.constants import get_empty_doc
from django_prosemirror.schema import MarkType, NodeType
from django_prosemirror.serde import html_to_doc

from open_inwoner.utils.migration_operations import (
    create_text_fallback_prosemirror_doc,
)

logger = structlog.stdlib.get_logger(__name__)


def migrate_ckeditor_text_plugins_to_new_text_plugin(apps, schema_editor):
    """
    Migrate old djangocms-text-ckeditor TextPlugin instances to new plugins.Text instances.

    This migration:
    1. Finds all old CKEditor TextPlugin instances (in djangocms_text_ckeditor_text table)
    2. For each one, creates a new plugins.Text instance with the same content
    3. Updates the plugin to use the new Text model instead of old CKEditor
    4. Preserves all relationships: parent, placeholder, position, language, etc.
    5. Converts HTML content to ProseMirror format
    6. Deletes the old djangocms_text_ckeditor_text records after migration
    7. Drops the djangocms_text_ckeditor_text table

    This replaces the old approach of just deleting the plugins (which would lose content).
    """
    CMSPlugin = apps.get_model("cms", "CMSPlugin")

    # Check if the old table exists
    if "djangocms_text_ckeditor_text" not in connection.introspection.table_names():
        logger.info(
            "Table djangocms_text_ckeditor_text does not exist, skipping migration"
        )
        return

    # Get all old CKEditor text plugin data
    # Raw SQL since this table has no Django model in our app
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT cmsplugin_ptr_id, body
            FROM djangocms_text_ckeditor_text
        """)
        old_text_plugins = cursor.fetchall()

    if not old_text_plugins:
        logger.info("No djangocms-text-ckeditor text plugin instances to migrate")
        # Drop the empty table
        with connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS djangocms_text_ckeditor_text CASCADE")
        logger.info("Dropped empty djangocms_text_ckeditor_text table")
        return

    logger.info(
        "Found %d djangocms-text-ckeditor text plugin instances to migrate",
        len(old_text_plugins),
    )
    logger.info("=" * 80)

    # Create Prosemirror config matching the Text model schema
    config = ProsemirrorConfig(
        allowed_node_types=[
            NodeType.PARAGRAPH,
            NodeType.BLOCKQUOTE,
            NodeType.HORIZONTAL_RULE,
            NodeType.HEADING,
            NodeType.HARD_BREAK,
            NodeType.CODE_BLOCK,
            NodeType.BULLET_LIST,
            NodeType.ORDERED_LIST,
            NodeType.LIST_ITEM,
            NodeType.TABLE,
            NodeType.TABLE_ROW,
            NodeType.TABLE_CELL,
            NodeType.TABLE_HEADER,
        ],
        allowed_mark_types=[
            MarkType.STRONG,
            MarkType.ITALIC,
            MarkType.LINK,
            MarkType.CODE,
            MarkType.UNDERLINE,
            MarkType.STRIKETHROUGH,
        ],
    )

    migrated_count = 0
    skipped_count = 0
    error_count = 0
    successfully_migrated_ids = []

    # Migrate each plugin in its own savepoint to isolate errors
    for plugin_id, html_body in old_text_plugins:
        try:
            with transaction.atomic():
                # Get the CMSPlugin instance
                try:
                    cms_plugin = CMSPlugin.objects.get(pk=plugin_id)
                except CMSPlugin.DoesNotExist:
                    logger.warning(
                        "CMSPlugin %d not found (orphaned), skipping", plugin_id
                    )
                    skipped_count += 1
                    continue

                # Log plugin info for audit trail
                if cms_plugin.placeholder:
                    if (
                        hasattr(cms_plugin.placeholder, "page")
                        and cms_plugin.placeholder.page
                    ):
                        try:
                            location = (
                                f"Page: {cms_plugin.placeholder.page.get_title()}"
                            )
                        except Exception:
                            location = f"Page ID: {cms_plugin.placeholder.page_id}"
                    elif cms_plugin.placeholder.slot:
                        location = f"Static placeholder: {cms_plugin.placeholder.slot}"
                    else:
                        location = "Unknown placeholder"
                else:
                    location = "No placeholder"

                logger.info(
                    "Migrating plugin %d (pos=%s, lang=%s, location=%s)",
                    plugin_id,
                    cms_plugin.position,
                    cms_plugin.language,
                    location,
                )

                # Convert HTML to ProseMirror format
                prosemirror_doc = None
                if html_body and html_body.strip():
                    try:
                        prosemirror_doc = html_to_doc(html_body, schema=config.schema)
                    except Exception as e:
                        # Conversion failed - try fallback strategies to preserve content
                        logger.warning(
                            "Failed to convert HTML to ProseMirror for plugin %d: %s. Trying fallback strategies...",
                            plugin_id,
                            e,
                        )

                        try:
                            # Fallback: Extract text content and wrap in paragraphs
                            prosemirror_doc = create_text_fallback_prosemirror_doc(
                                html_body
                            )
                            logger.info(
                                "Successfully created fallback ProseMirror content for plugin %d (text-only)",
                                plugin_id,
                            )
                        except Exception as fallback_error:
                            logger.error(
                                "Fallback conversion also failed for plugin %d: %s. Using empty content.",
                                plugin_id,
                                fallback_error,
                            )
                            prosemirror_doc = None
                else:
                    # Empty or whitespace-only content
                    # Create an empty ProseMirror document (single empty paragraph)
                    # This ensures the plugin always has valid content structure

                    prosemirror_doc = get_empty_doc()
                    logger.info(
                        "Plugin %d has empty/whitespace content, using empty ProseMirror document",
                        plugin_id,
                    )

                # Serialize ProseMirror document to JSON
                body_json = json.dumps(prosemirror_doc) if prosemirror_doc else None

                # Insert directly into plugins_text table using raw SQL
                # This avoids Django ORM trying to update the parent cms_cmsplugin record
                # which would set NULL values for tree fields (depth, numchild, path)
                with connection.cursor() as cursor:
                    cursor.execute(
                        "INSERT INTO plugins_text (cmsplugin_ptr_id, body) VALUES (%s, %s)",
                        (plugin_id, body_json),
                    )

                # Track successful migration
                successfully_migrated_ids.append(plugin_id)
                migrated_count += 1

        except Exception as e:
            logger.error(
                "Error migrating plugin %d: %s",
                plugin_id,
                e,
                exc_info=True,
            )
            error_count += 1
            # Continue with other plugins even if one fails

    # After migration, delete old records and drop table
    # Use a single transaction for cleanup
    logger.info("Cleaning up old djangocms_text_ckeditor_text data...")

    with transaction.atomic():
        with connection.cursor() as cursor:
            if successfully_migrated_ids:
                # Delete only successfully migrated records
                cursor.execute(
                    "DELETE FROM djangocms_text_ckeditor_text WHERE cmsplugin_ptr_id = ANY(%s)",
                    (successfully_migrated_ids,),
                )
                deleted_records = cursor.rowcount
                logger.info(
                    "Deleted %d records from djangocms_text_ckeditor_text",
                    deleted_records,
                )
            else:
                logger.info("No records to delete from djangocms_text_ckeditor_text")

            # Check if table is now empty
            cursor.execute("SELECT COUNT(*) FROM djangocms_text_ckeditor_text")
            result = cursor.fetchone()
            remaining_count = result[0] if result else 0

            if remaining_count == 0:
                # Drop the old table only if empty
                cursor.execute(
                    "DROP TABLE IF EXISTS djangocms_text_ckeditor_text CASCADE"
                )
                logger.info("Dropped djangocms_text_ckeditor_text table")
            else:
                logger.warning(
                    "Not dropping djangocms_text_ckeditor_text table: %d records remain (migration errors)",
                    remaining_count,
                )

    logger.info("Migration complete:")
    logger.info("  - Successfully migrated: %d plugins", migrated_count)
    logger.info("  - Skipped (orphaned): %d plugins", skipped_count)
    logger.info("  - Errors: %d plugins", error_count)

    if error_count > 0:
        logger.warning(
            "Some plugins failed to migrate. Review errors above and fix manually if needed."
        )


def reverse_migration(apps, schema_editor):
    """
    This migration cannot be meaningfully reversed automatically.

    The forward migration:
    - Converted djangocms-text-ckeditor TextPlugin instances to plugins.Text instances
    - Dropped the djangocms_text_ckeditor_text table

    Reversal would require:
    - Recreating the djangocms_text_ckeditor_text table structure
    - Converting ProseMirror content back to HTML
    - Deleting the new Text plugin instances

    This is complex and risky. If you need to restore, use a database backup.
    """
    logger.warning(
        "Reversing migration 0012_remove_djangocms_text_ckeditor: "
        "This is a no-op. The migration cannot be automatically reversed. "
        "If you need to restore data, use a database backup taken before this migration."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0011_alter_tasksconfig_object_type_dimpact_and_more"),
        ("cms", "0022_auto_20180620_1551"),  # Ensure CMS tables exist
    ]

    operations = [
        migrations.RunPython(
            code=migrate_ckeditor_text_plugins_to_new_text_plugin,
            reverse_code=reverse_migration,
        ),
    ]
