# Generated by Django 4.2.28 on 2026-02-16 10:53

from django.db import connection, migrations

import structlog

logger = structlog.stdlib.get_logger(__name__)


def remove_djangocms_text_ckeditor_instances(apps, schema_editor):
    """
    Remove all djangocms-text-ckeditor TextPlugin instances and drop the table.

    This cleans up legacy data from the old djangocms-text-ckeditor plugin
    that was replaced with a custom ProsemirrorModelField-based TextPlugin.

    Note: Raw SQL is used to query djangocms_text_ckeditor_text because this
    table was created by the external djangocms-text-ckeditor package and
    never had a Django model in our migration history. We cannot use the CMSPlugin
    manager to filter by 'plugin_type' since our new TextPlugin has the same
    'plugin_type' name.
    """
    CMSPlugin = apps.get_model("cms", "CMSPlugin")

    # Check if the old table exists
    if "djangocms_text_ckeditor_text" not in connection.introspection.table_names():
        logger.info(
            "Table djangocms_text_ckeditor_text does not exist, skipping cleanup"
        )
        return

    # Query the old table to get plugin IDs
    # Raw SQL since this table has no Django model in our app
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT cmsplugin_ptr_id
            FROM djangocms_text_ckeditor_text
        """)
        text_plugin_ids = [row[0] for row in cursor.fetchall()]

    if text_plugin_ids:
        logger.info(
            "Found %d djangocms-text-ckeditor text plugin instances",
            len(text_plugin_ids),
        )

        # Delete using Django ORM for proper cascade and signal handling
        deleted_count, _ = CMSPlugin.objects.filter(id__in=text_plugin_ids).delete()
        logger.info("Deleted %d cms_cmsplugin records via ORM", deleted_count)
    else:
        logger.info("No djangocms-text-ckeditor text plugin instances found")


def reverse_migration(apps, schema_editor):
    raise NotImplementedError(
        "This migration cannot be reversed as it permanently deletes data. "
        "If you need to restore the djangocms-text-ckeditor plugin, "
        "you must restore from a database backup."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0011_alter_tasksconfig_object_type_dimpact_and_more"),
        ("cms", "0022_auto_20180620_1551"),  # Ensure CMS tables exist
    ]

    operations = [
        migrations.RunPython(
            code=remove_djangocms_text_ckeditor_instances,
            reverse_code=reverse_migration,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS djangocms_text_ckeditor_text CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
