# Generated by Django 4.2.27 on 2026-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filer", "0017_image__transparent"),
        ("media", "0002_alter_video_link_id"),
        ("cms", "0022_auto_20180620_1551"),
        ("plugins", "0011_alter_tasksconfig_object_type_dimpact_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtendedCMSLink",
            new_name="LinkConfig",
        ),
        migrations.RenameModel(
            old_name="CMSLinkPluginConfig",
            new_name="LinkPluginConfig",
        ),
        migrations.RenameModel(
            old_name="TasksConfig",
            new_name="TakenPluginConfig",
        ),
        migrations.RenameModel(
            old_name="Text",
            new_name="TextPluginConfig",
        ),
        migrations.RenameModel(
            old_name="UserFeed",
            new_name="UserFeedPluginConfig",
        ),
        migrations.RenameModel(
            old_name="VideoPlayer",
            new_name="VideoPlayerPluginConfig",
        ),
        migrations.RenameModel(
            old_name="CMSZakenPluginConfig",
            new_name="ZakenPluginConfig",
        ),
        migrations.AlterModelTable(
            name="linkconfig",
            table="plugins_extendedcmslink",
        ),
        migrations.AlterModelTable(
            name="linkpluginconfig",
            table="plugins_cmslinkpluginconfig",
        ),
        migrations.AlterModelTable(
            name="takenpluginconfig",
            table="plugins_tasksconfig",
        ),
        migrations.AlterModelTable(
            name="textpluginconfig",
            table="plugins_text",
        ),
        migrations.AlterModelTable(
            name="userappointments",
            table="plugins_userappointments",
        ),
        migrations.AlterModelTable(
            name="userfeedpluginconfig",
            table="plugins_userfeed",
        ),
        migrations.AlterModelTable(
            name="videoplayerpluginconfig",
            table="plugins_videoplayer",
        ),
        migrations.AlterModelTable(
            name="zakenpluginconfig",
            table="plugins_cmszakenpluginconfig",
        ),
    ]
