# Generated by Django 5.2.11 on 2026-02-07
# Data migration for ExtendedCMSLink model - consolidates link fields into single JSON field

from django.db import migrations

import djangocms_link.fields


def migrate_link_data_forward(apps, schema_editor):
    """
    Migrate data from individual link fields to the new consolidated link JSON field.

    The new LinkField format stores links as:
    - {"external_link": "https://..."} for external URLs
    - {"internal_link": "cms.page:123"} for internal page links
    - {"internal_link": "cms.page:123", "anchor": "#section"} for internal links with anchors
    - {"file_link": 456} for file links
    """
    ExtendedCMSLink = apps.get_model("plugins", "ExtendedCMSLink")

    for link in ExtendedCMSLink.objects.all():
        link_data = {}

        # Priority order: internal_link > file_link > external_link > mailto > phone
        if link.internal_link_id:
            # Format: "app.model:pk"
            link_data["internal_link"] = f"cms.page:{link.internal_link_id}"
            if link.anchor:
                link_data["anchor"] = (
                    f"#{link.anchor}"
                    if not link.anchor.startswith("#")
                    else link.anchor
                )
        elif link.file_link_id:
            link_data["file_link"] = link.file_link_id
        elif link.external_link:
            # External link may include mailto: or tel: schemes, or be a URL
            link_data["external_link"] = link.external_link
            if link.anchor:
                # Append anchor to external link if present
                anchor = (
                    f"#{link.anchor}"
                    if not link.anchor.startswith("#")
                    else link.anchor
                )
                if "#" not in link.external_link:
                    link_data["external_link"] = f"{link.external_link}{anchor}"
        elif link.mailto:
            link_data["external_link"] = f"mailto:{link.mailto}"
        elif link.phone:
            link_data["external_link"] = f"tel:{link.phone}"

        link.link = link_data
        link.save(update_fields=["link"])


def migrate_link_data_backward(apps, schema_editor):
    """
    Migrate data back from the consolidated link field to individual fields.
    """
    ExtendedCMSLink = apps.get_model("plugins", "ExtendedCMSLink")

    for link in ExtendedCMSLink.objects.all():
        link_data = link.link or {}

        if "internal_link" in link_data:
            # Parse "cms.page:123" format
            try:
                _, pk = link_data["internal_link"].split(":", 1)
                link.internal_link_id = int(pk)
            except (ValueError, AttributeError):
                pass
            if "anchor" in link_data:
                anchor = link_data["anchor"]
                link.anchor = anchor.lstrip("#") if anchor else ""
        elif "file_link" in link_data:
            link.file_link_id = link_data["file_link"]
        elif "external_link" in link_data:
            external = link_data["external_link"]
            if external.startswith("mailto:"):
                link.mailto = external[7:]
            elif external.startswith("tel:"):
                link.phone = external[4:]
            else:
                # Check for anchor in URL
                if "#" in external:
                    url, anchor = external.rsplit("#", 1)
                    link.external_link = url
                    link.anchor = anchor
                else:
                    link.external_link = external

        link.save(
            update_fields=[
                "internal_link_id",
                "file_link_id",
                "external_link",
                "mailto",
                "phone",
                "anchor",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0011_alter_tasksconfig_object_type_dimpact_and_more"),
    ]

    operations = [
        # Step 1: Add the new link field
        migrations.AddField(
            model_name="extendedcmslink",
            name="link",
            field=djangocms_link.fields.LinkField(
                default=dict, help_text="-", verbose_name="Link"
            ),
        ),
        # Step 2: Migrate data from old fields to new field
        migrations.RunPython(
            migrate_link_data_forward,
            migrate_link_data_backward,
        ),
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="anchor",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="external_link",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="file_link",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="internal_link",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="mailto",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="phone",
        ),
    ]
