# Generated by Django 4.2.28 on 2026-02-26 11:47

from django.db import migrations

import structlog

logger = structlog.stdlib.get_logger(__name__)


def swap_object_type_fields(apps, schema_editor):
    """
    Swap the values of object_type_dimpact and object_type_generieke_dienstverlening.

    Background:
    The factory mapping in tasks.py was updated to correctly associate:
    - object_type_dimpact → ExternFormulierTaakObject
    - object_type_generieke_dienstverlening → UrlTaakObject

    This data migration swaps existing field values to maintain compatibility with
    existing configurations.
    """
    TasksConfig = apps.get_model("plugins", "TasksConfig")

    tasks_configs = TasksConfig.objects.all()
    swapped_count = 0

    for config in tasks_configs:
        # Store the original values
        original_dimpact = config.object_type_dimpact
        original_generieke = config.object_type_generieke_dienstverlening

        # Only swap if at least one field has a value
        if original_dimpact or original_generieke:
            # Swap the values
            config.object_type_dimpact = original_generieke
            config.object_type_generieke_dienstverlening = original_dimpact
            config.save()
            swapped_count += 1

            logger.info(
                "Swapped TasksConfig fields",
                config_id=config.pk,
                old_dimpact=original_dimpact,
                old_generieke=original_generieke,
                new_dimpact=config.object_type_dimpact,
                new_generieke=config.object_type_generieke_dienstverlening,
            )

    logger.info(
        "Completed swapping object type fields",
        total_configs=tasks_configs.count(),
        swapped_count=swapped_count,
    )


def reverse_swap_object_type_fields(apps, schema_editor):
    """
    Reverse the swap by swapping the fields back.
    """
    TasksConfig = apps.get_model("plugins", "TasksConfig")

    tasks_configs = TasksConfig.objects.all()
    swapped_count = 0

    for config in tasks_configs:
        # Store the original values
        original_dimpact = config.object_type_dimpact
        original_generieke = config.object_type_generieke_dienstverlening

        # Only swap if at least one field has a value
        if original_dimpact or original_generieke:
            # Swap the values back
            config.object_type_dimpact = original_generieke
            config.object_type_generieke_dienstverlening = original_dimpact
            config.save()
            swapped_count += 1

            logger.info(
                "Reversed TasksConfig fields swap",
                config_id=config.pk,
                restored_dimpact=config.object_type_dimpact,
                restored_generieke=config.object_type_generieke_dienstverlening,
            )

    logger.info(
        "Completed reversing object type fields swap",
        total_configs=tasks_configs.count(),
        swapped_count=swapped_count,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0012_remove_djangocms_text_ckeditor"),
    ]

    operations = [
        migrations.RunPython(
            code=swap_object_type_fields,
            reverse_code=reverse_swap_object_type_fields,
        ),
    ]
