# Generated by Django 4.2.28 on 2026-03-02 12:43

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0013_swap_tasks_object_type_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedcmslink",
            name="name",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                ],
                default=None,
                help_text="The text displayed for the link",
                history=True,
                tag_to_classes={},
                verbose_name="Name",
            ),
        ),
    ]
