# Generated by Django 4.2.29 on 2026-03-30 14:43

from django.db import migrations

import djangocms_link.fields


def migrate_links_forward(apps, schema_editor):
    ExtendedCMSLink = apps.get_model("plugins", "ExtendedCMSLink")
    for obj in ExtendedCMSLink.objects.exclude(external_link=""):
        obj.link = {"external_link": obj.external_link}
        obj.save(update_fields=["link"])


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0014_alter_extendedcmslink_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedcmslink",
            name="link",
            field=djangocms_link.fields.LinkField(
                default=dict, help_text="-", verbose_name="Link"
            ),
        ),
        migrations.RunPython(
            code=migrate_links_forward, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="external_link",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="anchor",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="file_link",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="internal_link",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="mailto",
        ),
        migrations.RemoveField(
            model_name="extendedcmslink",
            name="phone",
        ),
    ]
