# Generated by Django 4.2.30 on 2026-05-04 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0015_fix_legacy_text_plugin_body"),
        ("plugins", "0015_remove_extendedcmslink_anchor_and_more"),
    ]

    operations = []
