# Generated by Django 4.2.10 on 2024-03-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qmatic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qmaticconfig",
            name="booking_base_url",
            field=models.URLField(
                blank=True,
                help_text="The base URL where the user can reschedule or delete their appointment",
                max_length=1000,
                verbose_name="Booking base URL",
            ),
        ),
    ]
