# Generated by Django 4.2.11 on 2024-06-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
        ("qmatic", "0003_alter_qmaticconfig_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qmaticconfig",
            name="service",
            field=models.OneToOneField(
                help_text="The Qmatic Orchestra Calendar Public Appointment API service. Example: https://example.com:8443/rest/",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Calendar API",
            ),
        ),
    ]
