# Generated by Django 3.2.7 on 2021-10-18 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("pdc", "0002_auto_20211013_1214"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the tag type",
                        max_length=100,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag type",
                "verbose_name_plural": "tag types",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the tag",
                        max_length=100,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "icon",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        help_text="Icon of the tag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tag_icons",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products which the tag is applied to",
                        related_name="tags",
                        to="pdc.Product",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The related tag type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="pdc.tagtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tag",
            },
        ),
    ]
