# Generated by Django 3.2.7 on 2021-10-27 15:19

from django.db import migrations

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0005_auto_20211025_1803"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                help_text="Slug of the category",
                max_length=100,
                populate_from="name",
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                help_text="Slug of the category",
                max_length=100,
                populate_from="name",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
