# Generated by Django 3.2.7 on 2021-10-27 15:20

from django.db import migrations


def save_slug(apps, schemas):
    Product = apps.get_model("pdc.Product")

    for product in Product.objects.all():
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0006_auto_20211027_1719"),
    ]

    operations = [migrations.RunPython(save_slug)]
