# Generated by Django 3.2.7 on 2021-11-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0009_auto_20211027_1732"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Slug of the organization",
                max_length=100,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Slug of the tag",
                max_length=100,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the product",
                max_length=100,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Name of the tag", max_length=100, verbose_name="name"
            ),
        ),
    ]
