# Generated by Django 3.2.7 on 2021-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0009_auto_20211027_1732"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlocation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Location name",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the product",
                max_length=100,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
