# Generated by Django 3.2.7 on 2021-11-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0010_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description of the category",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Action link to request the product",
                verbose_name="link",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short description of the product",
                verbose_name="summary",
            ),
        ),
    ]
