# Generated by Django 3.2.7 on 2021-11-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("pdc", "0010_auto_20211119_1346"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_files",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Related product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="pdc.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product file",
                "verbose_name_plural": "product files",
            },
        ),
    ]
