# Generated by Django 3.2.7 on 2021-11-22 14:56

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ("filer", "0012_file_mime_type"),
        ("pdc", "0011_productfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=filer.fields.file.FilerFileField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_files",
                to="filer.file",
            ),
        ),
    ]
