# Generated by Django 3.2.7 on 2021-11-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0011_auto_20211119_1025"),
        ("pdc", "0012_alter_productfile_file"),
    ]

    operations = []
