# Generated by Django 3.2.7 on 2021-11-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0013_merge_0011_auto_20211119_1025_0012_auto_20211119_1645"),
        ("pdc", "0013_merge_20211122_1701"),
    ]

    operations = []
