# Generated by Django 3.2.7 on 2021-11-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0014_merge_20211123_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlocation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Location name",
                max_length=100,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
