# Generated by Django 3.2.7 on 2021-12-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0014_merge_20211123_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                help_text="Categories which the product relates to",
                related_name="products",
                to="pdc.Category",
            ),
        ),
        migrations.AlterField(
            model_name="productlocation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Location name",
                max_length=100,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
