# Generated by Django 3.2.7 on 2021-11-24 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0014_merge_20211123_1220"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                default=list,
                help_text="List of keywords for search",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="productlocation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Location name",
                max_length=100,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
