# Generated by Django 3.2.7 on 2021-12-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0015_alter_productlocation_name"),
        ("pdc", "0015_auto_20211206_1033"),
    ]

    operations = []
