# Generated by Django 3.2.7 on 2021-12-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0015_auto_20211124_1546"),
        ("pdc", "0016_merge_20211206_1627"),
    ]

    operations = []
