# Generated by Django 3.2.7 on 2021-12-20 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0017_merge_20211209_1213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                default=list,
                help_text="List of keywords for search",
                size=None,
            ),
        ),
    ]
