# Generated by Django 3.2.7 on 2021-12-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0018_alter_product_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="uniforme_productnaam",
            field=models.CharField(
                blank=True,
                help_text="Attribute to sync data from PDC's (like SDG)",
                max_length=250,
                verbose_name="uniforme productnaam",
            ),
        ),
    ]
