# Generated by Django 3.2.7 on 2022-02-02 17:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("pdc", "0019_product_uniforme_productnaam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Icon of the category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_icons",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="icon",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Image of the category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_images",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="neighbourhood",
            field=models.ForeignKey(
                blank=True,
                help_text="The neighbourhood of the organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization",
                to="pdc.neighbourhood",
                verbose_name="neighbourhood",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                help_text="Categories which the product relates to",
                related_name="products",
                to="pdc.Category",
                verbose_name="categories",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                default=list,
                help_text="List of keywords for search",
                size=None,
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organizations which provides this product",
                related_name="products",
                to="pdc.Organization",
                verbose_name="organizations",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related products to this product",
                to="pdc.Product",
                verbose_name="related products",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags which the product is linked to",
                related_name="products",
                to="pdc.Tag",
                verbose_name="tags",
            ),
        ),
        migrations.AlterField(
            model_name="productcontact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization of the product contact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_contacts",
                to="pdc.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="icon",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Icon of the tag",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tag_icons",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="icon",
            ),
        ),
    ]
