# Generated by Django 3.2.7 on 2022-01-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0019_product_uniforme_productnaam"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcontact",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="The role/function of the product contact",
                max_length=100,
                verbose_name="Rol",
            ),
        ),
    ]
