# Generated by Django 3.2.7 on 2022-02-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0020_auto_20220202_1835"),
        ("pdc", "0020_productcontact_role"),
    ]

    operations = []
