# Generated by Django 3.2.12 on 2022-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0022_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCondition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name of the condition",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Question used in the question-answer game",
                        verbose_name="Question",
                    ),
                ),
                (
                    "positive_text",
                    models.TextField(
                        help_text="Description how to meet the condition",
                        verbose_name="Positive text",
                    ),
                ),
                (
                    "negative_text",
                    models.TextField(
                        help_text="Description how not to meet the condition",
                        verbose_name="Negative text",
                    ),
                ),
                (
                    "rule",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Rule for the automated check",
                        verbose_name="Rule",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="Products for which the condition is applicable",
                        related_name="conditions",
                        to="pdc.Product",
                        verbose_name="Products",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condition",
                "verbose_name_plural": "Conditions",
            },
        ),
    ]
