# Generated by Django 3.2.12 on 2022-02-18 12:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ("filer", "0012_file_mime_type"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("pdc", "0022_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="neighbourhood",
            options={
                "verbose_name": "Neighbourhood",
                "verbose_name_plural": "Neighbourhoods",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationtype",
            options={
                "verbose_name": "Organization type",
                "verbose_name_plural": "Organization types",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productcontact",
            options={
                "verbose_name": "Product contact",
                "verbose_name_plural": "Product contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="productfile",
            options={
                "verbose_name": "Product file",
                "verbose_name_plural": "Product files",
            },
        ),
        migrations.AlterModelOptions(
            name="productlink",
            options={
                "verbose_name": "Product link",
                "verbose_name_plural": "Product links",
            },
        ),
        migrations.AlterModelOptions(
            name="productlocation",
            options={
                "verbose_name": "Product location",
                "verbose_name_plural": "Product locations",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.AlterModelOptions(
            name="tagtype",
            options={"verbose_name": "Tag type", "verbose_name_plural": "Tag types"},
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description of the category",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Icon of the category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_icons",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Image of the category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_images",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Name of the category", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the category",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="neighbourhood",
            name="name",
            field=models.CharField(
                help_text="Neighbourhood name",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Logo of the orgaization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_logos",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="Name of the organization",
                max_length=250,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="neighbourhood",
            field=models.ForeignKey(
                blank=True,
                help_text="The neighbourhood of the organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization",
                to="pdc.neighbourhood",
                verbose_name="Neighbourhood",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the organization",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.ForeignKey(
                help_text="Organization type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="pdc.organizationtype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="organizationtype",
            name="name",
            field=models.CharField(
                help_text="Organization type",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                help_text="Categories which the product relates to",
                related_name="products",
                to="pdc.Category",
                verbose_name="Categories",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="content",
            field=models.TextField(
                help_text="Product content with build-in WYSIWYG editor",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost of the product in EUR",
                max_digits=8,
                verbose_name="Costs",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                default=list,
                help_text="List of keywords for search",
                size=None,
                verbose_name="Keywords",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Action link to request the product",
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Name of the product", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organizations which provides this product",
                related_name="products",
                to="pdc.Organization",
                verbose_name="Organizations",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related products to this product",
                to="pdc.Product",
                verbose_name="Related products",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the product",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short description of the product",
                verbose_name="Summary",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags which the product is linked to",
                related_name="products",
                to="pdc.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uniforme_productnaam",
            field=models.CharField(
                blank=True,
                help_text="Attribute to sync data from PDC's (like SDG)",
                max_length=250,
                verbose_name="Uniforme productnaam",
            ),
        ),
        migrations.AlterField(
            model_name="productcontact",
            name="first_name",
            field=models.CharField(
                help_text="First name of the product contact",
                max_length=255,
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="productcontact",
            name="last_name",
            field=models.CharField(
                help_text="Last name of the product contact",
                max_length=255,
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="productcontact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization of the product contact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_contacts",
                to="pdc.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="productcontact",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_contacts",
                to="pdc.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=filer.fields.file.FilerFileField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_files",
                to="filer.file",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="pdc.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productlink",
            name="name",
            field=models.CharField(
                help_text="Name for the link", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="productlink",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="pdc.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productlink",
            name="url",
            field=models.URLField(help_text="Url of the link", verbose_name="Url"),
        ),
        migrations.AlterField(
            model_name="productlocation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Location name",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="productlocation",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="pdc.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pdc.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="icon",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Icon of the tag",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tag_icons",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Name of the tag", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the tag",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="The related tag type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="pdc.tagtype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="tagtype",
            name="name",
            field=models.CharField(
                help_text="Name of the tag type",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
