# Generated by Django 3.2.12 on 2022-02-14 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ("filer", "0012_file_mime_type"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("pdc", "0022_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "tag", "verbose_name_plural": "tags"},
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Logo of the orgaization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_logos",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="logo",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.ForeignKey(
                help_text="Organization type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="pdc.organizationtype",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="productcontact",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_contacts",
                to="pdc.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=filer.fields.file.FilerFileField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_files",
                to="filer.file",
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="pdc.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productlink",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="pdc.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productlocation",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="pdc.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pdc.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="The related tag type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="pdc.tagtype",
                verbose_name="type",
            ),
        ),
    ]
