# Generated by Django 3.2.12 on 2022-02-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0023_auto_20220218_1359"),
        ("pdc", "0023_productcondition"),
    ]

    operations = []
