# Generated by Django 3.2.12 on 2022-02-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0024_merge_0023_auto_20220218_1359_0023_productcondition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcondition",
            name="products",
        ),
        migrations.AddField(
            model_name="product",
            name="conditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditions applicable for the product",
                related_name="products",
                to="pdc.ProductCondition",
                verbose_name="Conditions",
            ),
        ),
    ]
