# Generated by Django 3.2.12 on 2022-03-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0025_auto_20220223_1153"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contacts responsible for the product",
                related_name="products",
                to="pdc.ProductContact",
                verbose_name="Product contacts",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Locations where the product is available at.",
                related_name="products",
                to="pdc.ProductLocation",
                verbose_name="Product locations",
            ),
        ),
        migrations.AlterField(
            model_name="productlocation",
            name="product",
            field=models.ForeignKey(
                help_text="Related product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_locations",
                to="pdc.product",
                verbose_name="Product",
            ),
        ),
    ]
