# Generated by Django 3.2.12 on 2022-03-12 09:56

from django.db import migrations


def combine_contacts(apps, schema_editor):
    Product = apps.get_model("pdc", "Product")
    for product in Product.objects.all():
        for contact in product.product_contacts.all():
            product.contacts.add(contact)
        product.save()


def combine_locations(apps, schema_editor):
    Product = apps.get_model("pdc", "Product")
    for product in Product.objects.all():
        for location in product.product_locations.all():
            product.locations.add(location)
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0026_auto_20220312_1054"),
    ]

    operations = [
        migrations.RunPython(combine_contacts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(combine_locations, reverse_code=migrations.RunPython.noop),
    ]
