# Generated by Django 3.2.12 on 2022-03-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0027_auto_20220312_1056"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcontact",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productlocation",
            name="product",
        ),
    ]
