# Generated by Django 3.2.12 on 2022-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0028_auto_20220312_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcondition",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
