# Generated by Django 3.2.12 on 2022-03-25 12:08

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0028_auto_20220312_1107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                help_text="The phone number of the organization",
                max_length=15,
                validators=[open_inwoner.utils.validators.validate_phone_number],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AlterField(
            model_name="productcontact",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                help_text="The phone number of the product contact",
                max_length=15,
                validators=[open_inwoner.utils.validators.validate_phone_number],
                verbose_name="Phonenumber",
            ),
        ),
    ]
