# Generated by Django 3.2.12 on 2022-03-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0029_auto_20220325_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pdc.category",
                verbose_name="Category",
            ),
        ),
    ]
