# Generated by Django 3.2.12 on 2022-03-22 14:20

from django.db import migrations


def set_order(apps, schemas):
    ProductCondition = apps.get_model("pdc.ProductCondition")

    for index, condition in enumerate(ProductCondition.objects.all()):
        condition.order = index
        condition.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0029_productcondition_order"),
    ]

    operations = [
        migrations.RunPython(set_order, reverse_code=migrations.RunPython.noop)
    ]
