# Generated by Django 3.2.12 on 2022-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0029_auto_20220325_1308"),
        ("pdc", "0030_auto_20220322_1520"),
    ]

    operations = []
