# Generated by Django 3.2.12 on 2022-03-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0031_merge_0029_auto_20220325_1308_0030_auto_20220322_1520"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcondition",
            options={
                "ordering": ("order",),
                "verbose_name": "Condition",
                "verbose_name_plural": "Conditions",
            },
        ),
    ]
