# Generated by Django 3.2.12 on 2022-03-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0030_alter_question_category"),
        ("pdc", "0032_alter_productcondition_options"),
    ]

    operations = []
