# Generated by Django 3.2.12 on 2022-04-11 10:59

from django.db import migrations


def remove_orphan_files(apps, schema_editor):
    """
    An admin user may have 'orphan files' in the database.
    This appears in Product when we clear a file from ProductFile inline without actually deleting it.
    Below we delete these instances.
    """
    ProductFile = apps.get_model("pdc", "ProductFile")
    for product_file in ProductFile.objects.all():
        if product_file.file_id is None:
            product_file.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0033_merge_20220329_1630"),
    ]

    operations = [
        migrations.RunPython(
            remove_orphan_files, reverse_code=migrations.RunPython.noop
        ),
    ]
