# Generated by Django 3.2.12 on 2022-04-11 11:40

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('pdc', '0034_auto_20220411_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=filer.fields.file.FilerFileField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_files', to='filer.file', verbose_name='File'),
        ),
    ]
