# Generated by Django 3.2.12 on 2022-04-11 11:41

import django.db.models.deletion
from django.db import migrations

import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ("filer", "0012_file_mime_type"),
        ("pdc", "0035_alter_productfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=filer.fields.file.FilerFileField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_files",
                to="filer.file",
                verbose_name="File",
            ),
        ),
    ]
