# Generated by Django 3.2.13 on 2022-05-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0036_alter_productfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="highlighted",
            field=models.BooleanField(
                default=False,
                help_text="Wether the category should be highlighted or not",
                verbose_name="Highlighted",
            ),
        ),
    ]
