# Generated by Django 3.2.13 on 2022-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0036_alter_productfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="form_snippet",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Code snippet for open-forms sdk integration",
                verbose_name="Form snippet",
            ),
        ),
    ]
