# Generated by Django 3.2.13 on 2022-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0038_auto_20220601_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="highlighted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the category should be highlighted or not",
                verbose_name="Highlighted",
            ),
        ),
    ]
