# Generated by Django 3.2.13 on 2022-06-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0039_alter_category_highlighted"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Whether the category should be published or not.",
                verbose_name="Published",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Whether the product should be published or not.",
                verbose_name="Published",
            ),
        ),
    ]
