# Generated by Django 3.2.13 on 2022-06-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdc', '0037_product_form_snippet'),
        ('pdc', '0039_alter_category_highlighted'),
    ]

    operations = [
    ]
