# Generated by Django 3.2.13 on 2022-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0040_auto_20220616_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the category should be published or not.",
                verbose_name="Published",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the product should be published or not.",
                verbose_name="Published",
            ),
        ),
    ]
