# Generated by Django 3.2.15 on 2022-09-29 15:26

from django.db import migrations, models
import openformsclient.models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0041_auto_20220724_1357"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="form",
            field=openformsclient.models.OpenFormsSlugField(
                blank=True,
                help_text="Select a form to show this form on the product page. If a form is selected, the link will not be shown.",
                verbose_name="Request form",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Action link to request the product.",
                verbose_name="Link",
            ),
        ),
    ]
