# Generated by Django 3.2.15 on 2022-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0043_question_product"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("category__isnull", True),
                    ("product__isnull", True),
                    _connector="OR",
                ),
                name="category_or_product_null",
            ),
        ),
    ]
