# Generated by Django 3.2.15 on 2023-02-20 15:28

from django.db import migrations


def truncate_product_summary(apps, schema_editor):
    MyModel = apps.get_model("pdc", "Product")
    for product in MyModel.objects.all():
        if len(product.summary) > 300:
            product.summary = product.summary[:300]
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0044_question_category_or_product_null"),
    ]

    operations = [
        migrations.RunPython(
            truncate_product_summary, reverse_code=migrations.RunPython.noop
        ),
    ]
