# Generated by Django 3.2.15 on 2023-02-21 08:54

import uuid

from django.db import migrations


def gen_uuid_product_location(apps, schema_editor):
    MyModel = apps.get_model("pdc", "ProductLocation")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0045_auto_20230221_0954"),
    ]

    operations = [
        migrations.RunPython(
            gen_uuid_product_location, reverse_code=migrations.RunPython.noop
        ),
    ]
