# Generated by Django 3.2.15 on 2023-02-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0045_auto_20230220_1628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short description of the product",
                max_length=300,
                verbose_name="Summary",
            ),
        ),
    ]
