# Generated by Django 3.2.15 on 2023-02-21 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0046_auto_20230221_0954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlocation",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
    ]
