# Generated by Django 3.2.15 on 2023-02-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0046_alter_product_summary"),
        ("pdc", "0047_alter_productlocation_uuid"),
    ]

    operations = []
