# Generated by Django 3.2.15 on 2023-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0047_alter_productlocation_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short description of the product, limited to 300 characters.",
                verbose_name="Summary",
            ),
        ),
    ]
