# Generated by Django 3.2.15 on 2023-02-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0048_alter_product_summary"),
        ("pdc", "0048_merge_20230221_1229"),
    ]

    operations = []
