# Generated by Django 3.2.15 on 2023-02-21 14:18

from django.db import migrations, models


def set_order_fields(apps, schema_editor):
    Category = apps.get_model("pdc", "Category")
    CategoryProduct = apps.get_model("pdc", "CategoryProduct")
    for category in Category.objects.all():
        qs = CategoryProduct.objects.filter(category=category).order_by("product__name")
        for i, prod_cat in enumerate(qs):
            prod_cat.order = i
            prod_cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0051_auto_20230220_1702"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="CategoryProduct",
            options={"ordering": ("category", "product")},
        ),
        migrations.AddField(
            model_name="CategoryProduct",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_order_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
