# Generated by Django 3.2.15 on 2023-03-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0053_alter_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content",
            field=models.TextField(
                help_text="Product content with build-in WYSIWYG editor. By adding '[CTABUTTON]' you can embed a cta-button for linking to the defined form or link",
                verbose_name="Content",
            ),
        ),
    ]
