# Generated by Django 3.2.15 on 2023-03-17 10:44

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("pdc", "0053_alter_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Logo of the organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_logos",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Logo",
            ),
        ),
    ]
