# Generated by Django 3.2.15 on 2023-06-23 13:23

from django.db import migrations, models

import open_inwoner.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0056_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                help_text="The phone number of the organization",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AlterField(
            model_name="productcontact",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                help_text="The phone number of the product contact",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Phonenumber",
            ),
        ),
        migrations.AlterField(
            model_name="productlocation",
            name="phonenumber",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The phonenumber of the current location",
                max_length=15,
                validators=[open_inwoner.utils.validators.DutchPhoneNumberValidator()],
                verbose_name="Phonenumber",
            ),
        ),
    ]
