# Generated by Django 3.2.15 on 2023-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0057_auto_20230623_1523"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="button_text",
            field=models.CharField(
                blank=True,
                default="Aanvraag starten",
                help_text="The text displayed on the button.",
                max_length=64,
                verbose_name="CTA Button text",
            ),
        ),
    ]
