# Generated by Django 3.2.20 on 2023-09-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("pdc", "0058_product_button_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.ForeignKey(
                blank=True,
                help_text="Video to show after the intro",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="media.video",
                verbose_name="Video",
            ),
        ),
    ]
