# Generated by Django 3.2.20 on 2023-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0059_product_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content_is_collapsable",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user can expand and collapse the product content.",
                verbose_name="Make product content collapsable",
            ),
        ),
    ]
