# Generated by Django 3.2.20 on 2023-11-06 11:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0060_content_collapsable"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="relevante_zaakperiode",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Aantal maanden dat teruggekeken moet worden naar Zaken van deze zaaktypes.",
                null=True,
                verbose_name="Relevante zaakperiode",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="visible_for_anonymous",
            field=models.BooleanField(
                default=True,
                help_text="Of het onderwerp zichtbaar moet zijn op het anonieme deel (zonder inloggen).",
                verbose_name="Anonieme deel",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="visible_for_authenticated",
            field=models.BooleanField(
                default=True,
                help_text="Of het onderwerp zichtbaar moet zijn op het beveiligde deel (achter inloggen).",
                verbose_name="Beveiligde deel",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="visible_for_citizens",
            field=models.BooleanField(
                default=True,
                help_text="Of het onderwerp zichtbaar moet zijn wanneer iemand aangeeft een inwoner te zijn (of is ingelogd met BSN).",
                verbose_name="Inwoner content",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="visible_for_companies",
            field=models.BooleanField(
                default=True,
                help_text="Of het onderwerp zichtbaar moet zijn wanneer iemand aangeeft een bedrijf te zijn (of is ingelogd met KvK).",
                verbose_name="Bedrijven content",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="zaaktypen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1000),
                blank=True,
                default=list,
                help_text="Zaaktypen waarvoor bij aanwezigheid dit onderwerp getoond moet worden.",
                size=None,
                verbose_name="Zaaktypen",
            ),
        ),
    ]
