# Generated by Django 3.2.20 on 2023-11-13 10:55

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0061_auto_20231106_1207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="zaaktypen",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1000),
                blank=True,
                default=list,
                help_text="Zaaktypen waarvoor bij aanwezigheid dit onderwerp getoond moet worden.",
                size=None,
                verbose_name="Zaaktypen",
            ),
        ),
    ]
