# Generated by Django 3.2.20 on 2023-11-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0062_alter_category_zaaktypen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="relevante_zaakperiode",
        ),
    ]
