# Generated by Django 3.2.23 on 2023-12-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0063_remove_category_relevante_zaakperiode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="visible_for_authenticated",
        ),
    ]
