# Generated by Django 3.2.23 on 2024-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0064_remove_category_visible_for_authenticated"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="auto_redirect_to_link",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user should be automatically redirect to the product link when the user visits the product page.",
                verbose_name="Automatically redirect to link",
            ),
        ),
    ]
