# Generated by Django 3.2.23 on 2024-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0064_remove_category_visible_for_authenticated"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="auto_redirect_to_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="If configured, the user will be automatically redirected to this link when accessing the category detail page.",
                max_length=1000,
                verbose_name="Automatically redirect to link",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="auto_redirect_to_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="If configured, the user will be automatically redirected to this link when accessing the product detail page.",
                max_length=1000,
                verbose_name="Automatically redirect to link",
            ),
        ),
    ]
