# Generated by Django 3.2.23 on 2024-01-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pdc", "0065_auto_20240112_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="access_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="If set, only users belonging to this group can edit this category and its products",
                related_name="managed_categories",
                to="auth.Group",
                verbose_name="Restrict to admin groups",
            ),
        ),
    ]
