# Generated by Django 4.2.20 on 2025-06-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0066_category_access_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="button_text",
            field=models.CharField(
                blank=True,
                default="Aanvraag starten",
                help_text="The text displayed on the button inside the content of the product.",
                max_length=64,
                verbose_name="CTA Button text",
            ),
        ),
    ]
