# Generated by Django 4.2.25 on 2025-10-07 09:32

import logging

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types
import markdown
from django_prosemirror.config import ProsemirrorConfig
from django_prosemirror.schema import MarkType, NodeType
from django_prosemirror.serde import html_to_doc

logger = logging.getLogger(__name__)


def migrate_answer_texts(apps, _):
    Question = apps.get_model("pdc", "Question")

    questions = Question.objects.all()

    config = ProsemirrorConfig(
        allowed_node_types=[NodeType.PARAGRAPH],
        allowed_mark_types=[
            MarkType.STRONG,
            MarkType.ITALIC,
            MarkType.LINK,
            MarkType.UNDERLINE,
        ],
    )

    for question in questions:
        content = question.answer_tmp

        # Skip empty or whitespace-only content
        if not content or not content.strip():
            question.answer = None
            question.save()
            continue

        content = content.strip('"')

        html_content = markdown.markdown(content, extensions=["extra"])

        if not html_content.startswith("<p>"):
            html_content = f"<p>{html_content}</p>"

        # Convert the HTML to a proper ProseMirror document
        try:
            doc = html_to_doc(html_content, schema=config.schema)
            question.answer = doc
        except (IndexError, ValueError):
            logger.exception(
                "Warning: Could not convert answer for question: %s",
                question,
            )
            question.answer = None

        question.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0066_category_access_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="answer",
            new_name="answer_tmp",
        ),
        migrations.AddField(
            model_name="question",
            name="answer",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                    django_prosemirror.schema.types.NodeType["BLOCKQUOTE"],
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Antwoord",
            ),
        ),
        migrations.RunPython(
            code=migrate_answer_texts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="question",
            name="answer_tmp",
        ),
    ]
