# Generated by Django 4.2.16 on 2024-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0066_category_access_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productcondition",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productcontact",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productfile",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productlink",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="question",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tagtype",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
