# Generated by Django 4.2.11 on 2024-04-29 10:17

from django.db import migrations

import openformsclient.models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0066_category_access_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="form",
            field=openformsclient.models.OpenFormsSlugField(
                blank=True,
                choices=[],
                db_index=False,
                help_text="Select a form to show this form on the product page. If a form is selected, the link will not be shown.",
                max_length=100,
                verbose_name="Request form",
            ),
        ),
    ]
