# Generated by Django 4.2.25 on 2025-10-07 11:30

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0067_question_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="description",
            new_name="description_tmp",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                    django_prosemirror.schema.types.NodeType["FILER_IMAGE"],
                ],
                blank=True,
                default=None,
                help_text="Description of the category",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Description",
            ),
        ),
    ]
