# Generated by Django 4.2.16 on 2024-10-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdc", "0067_category_open_producten_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighbourhood",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="organizationtype",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productlocation",
            name="open_producten_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
