# Generated by Django 4.2.25 on 2025-10-07 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0069_category_description_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description_tmp",
        ),
    ]
