# Generated by Django 4.2.25 on 2025-10-07 14:42

from functools import partial

from django.db import migrations

from django_prosemirror.schema import NodeType

from open_inwoner.utils.migration_operations import migrate_to_prosemirror_field

migrate_product_content = partial(
    migrate_to_prosemirror_field,
    app_label="pdc",
    model_name="Product",
    field_name="content",
    allowed_node_types=[
        NodeType.PARAGRAPH,
        NodeType.HEADING,
        NodeType.FILER_IMAGE,
        NodeType.TABLE,
        NodeType.TABLE_ROW,
        NodeType.TABLE_CELL,
        NodeType.TABLE_HEADER,
    ],
    use_singleton=False,
    convert_markdown=True,
    process_images=True,
)


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0071_product_content_schema_1"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_product_content,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
