# Generated by Django 4.2.27 on 2026-01-26 11:06

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0073_product_content_schema_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                    django_prosemirror.schema.types.NodeType["HEADING"],
                    django_prosemirror.schema.types.NodeType["FILER_IMAGE"],
                    django_prosemirror.schema.types.NodeType["BULLET_LIST"],
                    django_prosemirror.schema.types.NodeType["ORDERED_LIST"],
                    django_prosemirror.schema.types.NodeType["LIST_ITEM"],
                    django_prosemirror.schema.types.NodeType["TABLE"],
                    django_prosemirror.schema.types.NodeType["TABLE_ROW"],
                    django_prosemirror.schema.types.NodeType["TABLE_CELL"],
                    django_prosemirror.schema.types.NodeType["TABLE_HEADER"],
                ],
                blank=True,
                default=None,
                help_text="Product content with build-in WYSIWYG editor. By adding '[CTABUTTON]' you can embed a cta-button for linking to the defined form or link",
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Content",
            ),
        ),
    ]
