# Generated by Django 4.2.28 on 2026-03-02 12:58

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0074_alter_product_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                    django_prosemirror.schema.types.NodeType["HEADING"],
                    django_prosemirror.schema.types.NodeType["BLOCKQUOTE"],
                    django_prosemirror.schema.types.NodeType["TABLE"],
                    django_prosemirror.schema.types.NodeType["TABLE_CELL"],
                    django_prosemirror.schema.types.NodeType["TABLE_HEADER"],
                    django_prosemirror.schema.types.NodeType["TABLE_ROW"],
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Antwoord",
            ),
        ),
    ]
