# Generated by Django 4.2.30 on 2026-05-04 15:30

from django.db import migrations

import django_prosemirror.fields
import django_prosemirror.schema.types


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0076_alter_category_description_alter_product_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=django_prosemirror.fields.ProsemirrorModelField(
                allowed_mark_types=[
                    django_prosemirror.schema.types.MarkType["STRONG"],
                    django_prosemirror.schema.types.MarkType["ITALIC"],
                    django_prosemirror.schema.types.MarkType["UNDERLINE"],
                    django_prosemirror.schema.types.MarkType["LINK"],
                ],
                allowed_node_types=[
                    django_prosemirror.schema.types.NodeType["HARD_BREAK"],
                    django_prosemirror.schema.types.NodeType["PARAGRAPH"],
                    django_prosemirror.schema.types.NodeType["HEADING"],
                    django_prosemirror.schema.types.NodeType["BLOCKQUOTE"],
                    django_prosemirror.schema.types.NodeType["TABLE"],
                    django_prosemirror.schema.types.NodeType["TABLE_CELL"],
                    django_prosemirror.schema.types.NodeType["TABLE_HEADER"],
                    django_prosemirror.schema.types.NodeType["TABLE_ROW"],
                    django_prosemirror.schema.types.NodeType["BULLET_LIST"],
                    django_prosemirror.schema.types.NodeType["ORDERED_LIST"],
                    django_prosemirror.schema.types.NodeType["LIST_ITEM"],
                ],
                blank=True,
                default=None,
                history=True,
                null=True,
                tag_to_classes={},
                verbose_name="Antwoord",
            ),
        ),
    ]
