# Generated by Django 5.2.17 on 2026-09-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdc", "0078_sanitize_prosemirror_link_hrefs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="button_text",
            field=models.CharField(
                blank=True,
                default="Aanvraag starten",
                help_text="The text displayed on the button inside the content of the product.",
                max_length=64,
                verbose_name="CTA Button text",
            ),
        ),
    ]
