# Generated by Django 3.2.20 on 2023-09-25 10:01

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="link_id",
            field=models.CharField(
                help_text="https://vimeo.com/[Video ID] | https://www.youtube.com/watch?v=[Video ID]",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "[a-z0-9_-]", flags=re.RegexFlag["IGNORECASE"]
                    )
                ],
                verbose_name="video ID",
            ),
        ),
    ]
