from django.contrib.gis.geos import Point
from django.utils.text import slugify

import factory.fuzzy
import markdown
from django_prosemirror.config import ProsemirrorConfig
from django_prosemirror.fields import ProsemirrorFieldDocument
from django_prosemirror.schema import MarkType, NodeType
from django_prosemirror.serde import html_to_doc

from open_inwoner.pdc.models import (
    Category,
    Organization,
    OrganizationType,
    Product,
    ProductCondition,
    ProductContact,
    ProductLocation,
    Question,
    Tag,
)


class ProductFactory(factory.django.DjangoModelFactory):
    name = factory.Sequence(lambda n: f"product {n}")
    slug = factory.LazyAttribute(lambda a: slugify(a.name))
    summary = factory.Faker("sentence")
    content = factory.Faker("paragraph")
    published = True

    class Meta:
        model = Product

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        """Convert string content to ProseMirror document if needed."""
        content = kwargs.get("content")

        # If content is provided as string, convert it to a ProseMirror document
        if content and isinstance(content, str):
            config = ProsemirrorConfig(
                allowed_node_types=[
                    NodeType.HARD_BREAK,
                    NodeType.PARAGRAPH,
                    NodeType.HEADING,
                    NodeType.FILER_IMAGE,
                ],
                allowed_mark_types=[
                    MarkType.STRONG,
                    MarkType.ITALIC,
                    MarkType.LINK,
                    MarkType.UNDERLINE,
                ],
            )
            try:
                # Remove weird undocumented \\< escape/prefix generated by CKeditor
                content = content.replace("\\<", "<")
                html_content = markdown.markdown(content, extensions=["extra"])

                # Wrap content in paragraph if needed (only for inline content, not block elements)
                if not html_content.strip().startswith(
                    ("<p", "<h", "<ul", "<ol", "<blockquote")
                ):
                    html_content = f"<p>{html_content}</p>"

                # Convert HTML to ProseMirror document
                kwargs["content"] = html_to_doc(html_content, schema=config.schema)
            except (IndexError, ValueError, Exception):
                # If conversion fails, set content to None (like the migration does)
                kwargs["content"] = None

        return super()._create(model_class, *args, **kwargs)

    @factory.post_generation
    def categories(self, create, extracted, **kwargs):
        if not create:
            return

        if extracted:
            for category in extracted:
                self.categories.add(category)

    @factory.post_generation
    def locations(self, create, extracted, **kwargs):
        if not create:
            return

        if extracted:
            for location in extracted:
                self.locations.add(location)

    @factory.post_generation
    def related_products(self, create, extracted, **kwargs):
        if not create:
            return

        if extracted:
            for related_product in extracted:
                self.related_products.add(related_product)


class CategoryFactory(factory.django.DjangoModelFactory):
    name = factory.Sequence(lambda n: f"category {n}")
    slug = factory.LazyAttribute(lambda a: slugify(a.name))
    description = factory.Faker("sentence")
    published = True

    class Meta:
        model = Category

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        """For now factory creates only root categories"""
        description = kwargs.pop("description", None)

        # Create the category without description first
        obj = Category.add_root(**kwargs)

        # If description is provided as string, convert it to a ProseMirror document
        if description and isinstance(description, str):
            config = ProsemirrorConfig(
                allowed_node_types=[
                    NodeType.HARD_BREAK,
                    NodeType.PARAGRAPH,
                    NodeType.FILER_IMAGE,
                ],
                allowed_mark_types=[
                    MarkType.STRONG,
                    MarkType.ITALIC,
                    MarkType.LINK,
                    MarkType.UNDERLINE,
                ],
            )
            # Convert markdown to HTML first (like the migration does)
            html_content = markdown.markdown(description, extensions=["extra"])

            # Wrap content in paragraph if needed
            if not html_content.strip().startswith("<p"):
                html_content = f"<p>{html_content}</p>"

            # Convert HTML to ProseMirror document and assign to object
            doc_dict = html_to_doc(html_content, schema=config.schema)
            obj.description = ProsemirrorFieldDocument(doc_dict, schema=config.schema)
            obj.save()

        return obj


class TagFactory(factory.django.DjangoModelFactory):
    name = factory.Sequence(lambda n: f"tag {n}")
    slug = factory.LazyAttribute(lambda a: slugify(a.name))

    class Meta:
        model = Tag


class OrganizationTypeFactory(factory.django.DjangoModelFactory):
    name = factory.Faker("word")

    class Meta:
        model = OrganizationType


class OrganizationFactory(factory.django.DjangoModelFactory):
    name = factory.Sequence(lambda n: f"organization {n}")
    slug = factory.LazyAttribute(lambda a: slugify(a.name))
    type = factory.SubFactory(OrganizationTypeFactory)
    street = factory.Faker("street_name", locale="nl_NL")
    postcode = factory.Faker("postcode", locale="nl_NL")
    geometry = Point(5, 52)

    class Meta:
        model = Organization


class ProductContactFactory(factory.django.DjangoModelFactory):
    organization = factory.SubFactory(OrganizationFactory)
    first_name = factory.Faker("first_name")
    last_name = factory.Faker("last_name")
    email = factory.Faker("email")
    phonenumber = "0612345678"

    class Meta:
        model = ProductContact


class ProductLocationFactory(factory.django.DjangoModelFactory):
    name = factory.Faker("word")
    street = factory.Faker("street_name", locale="nl_NL")
    postcode = factory.Faker("postcode", locale="nl_NL")
    geometry = Point(5, 52)

    class Meta:
        model = ProductLocation


class ProductConditionFactory(factory.django.DjangoModelFactory):
    name = factory.Faker("word")
    question = factory.Faker("word")
    positive_text = factory.Faker("word")
    negative_text = factory.Faker("word")
    rule = factory.Faker("word")

    class Meta:
        model = ProductCondition


class QuestionFactory(factory.django.DjangoModelFactory):
    question = factory.Faker("sentence")
    answer = factory.Faker("text")

    class Meta:
        model = Question

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        """Convert string answer to ProseMirror document if needed."""
        answer = kwargs.pop("answer", None)

        # Create the object without answer first
        obj = super()._create(model_class, *args, **kwargs)

        # If answer was provided and is a string, convert it to a ProseMirror document
        if answer and isinstance(answer, str):
            config = ProsemirrorConfig(
                allowed_node_types=[
                    NodeType.HARD_BREAK,
                    NodeType.PARAGRAPH,
                    NodeType.FILER_IMAGE,
                ],
                allowed_mark_types=[
                    MarkType.STRONG,
                    MarkType.ITALIC,
                    MarkType.LINK,
                    MarkType.UNDERLINE,
                ],
            )
            # Convert markdown to HTML first (like the migration does)
            html_content = markdown.markdown(answer, extensions=["extra"])

            # Wrap content in paragraph if needed
            if not html_content.strip().startswith("<p"):
                html_content = f"<p>{html_content}</p>"

            # Convert HTML to ProseMirror document and assign to object
            doc_dict = html_to_doc(html_content, schema=config.schema)
            obj.answer = ProsemirrorFieldDocument(doc_dict, schema=config.schema)
            obj.save()

        return obj
