# Generated by Django 4.2.20 on 2025-06-09 17:49

import django.db.models.deletion
from django.db import migrations, models

import cms.models.fields


class Migration(migrations.Migration):
    replaces = [
        ("themes", "0001_initial"),
        ("themes", "0002_theme_caption_theme_required_actions_and_more"),
        ("themes", "0003_theme_slug"),
        ("themes", "0004_theme_theme_page"),
        ("themes", "0005_alter_theme_theme_page"),
        ("themes", "0006_remove_theme_slug"),
    ]

    initial = True

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeList",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of this theme list.", verbose_name="Title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of this theme.", verbose_name="Title"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption under the title",
                        null=True,
                        verbose_name="Caption",
                    ),
                ),
                (
                    "required_actions",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the widget should display a 'actions required' indicator.",
                        verbose_name="Required actions",
                    ),
                ),
                (
                    "theme_page",
                    cms.models.fields.PageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cms.page",
                        verbose_name="Theme Page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
