# Generated by Django 4.2.22 on 2025-06-11 12:36

import django.db.models.deletion
from django.db import migrations

import cms.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("themes", "0001_squashed_0006_remove_theme_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="theme_page",
            field=cms.models.fields.PageField(
                blank=True,
                help_text="The page containing the ProductList that this theme should point to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cms.page",
                verbose_name="Theme Page",
            ),
        ),
    ]
