# Generated by Django 4.2.20 on 2025-06-19 08:58

from django.db import migrations
from django.utils.text import slugify

from cms.api import add_plugin, create_page

from open_inwoner.core.cms.cms_plugins.footer.cms_plugins import CMSFlatPagePlugin


def create_cms_pages(apps, schema_editor):
    FlatPage = apps.get_model("flatpages", "FlatPage")

    language = "nl"

    for flatpage in FlatPage.objects.all():
        title = flatpage.title
        slug = flatpage.url.strip("/")
        if not slug:
            slug = slugify(flatpage.title)

        page = create_page(
            title=title,
            template="core/cms/footer/cms_flatpage_template.html",
            language=language,
            slug=slug,
            published=True,
            in_navigation=True,
        )

        placeholder = page.placeholders.get(slot="content")

        add_plugin(
            placeholder=placeholder,
            plugin_type=CMSFlatPagePlugin,
            language=language,
            title=flatpage.title,
            content=flatpage.content,
        )


def link_cms_pages_with_siteconfig(apps, schema_editor):
    SiteConfiguration = apps.get_model("configurations", "SiteConfiguration")
    SiteConfigurationPage = apps.get_model("configurations", "SiteConfigurationPage")

    Page = apps.get_model("cms", "Page")
    CMSFlatPageModel = apps.get_model("footer", "CMSFlatPageModel")

    # remove existing pages for clean slate
    SiteConfigurationPage.objects.all().delete()

    site_config = SiteConfiguration.objects.first()

    for order, cms_model in enumerate(CMSFlatPageModel.objects.all()):
        placeholder = cms_model.placeholder
        cms_page = Page.objects.filter(placeholders=placeholder).first()

        SiteConfigurationPage.objects.create(
            configuration=site_config,
            cms_page=cms_page,
            order=order,
        )


def delete_flatpages(apps, schema_editor):
    FlatPage = apps.get_model("flatpages", "FlatPage")

    FlatPage.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=create_cms_pages,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=link_cms_pages_with_siteconfig,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=delete_flatpages,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
