name: code-quality

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  migrations:
    name: Check for model changes not present in the migrations
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install system packages
        run: |
          sudo apt-get update \
          && sudo apt-get install -y --no-install-recommends \
            libgdal-dev \
            gdal-bin \
            libxml2-dev \
            libxmlsec1-dev \
            libxmlsec1-openssl
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -r requirements/dev.txt --system
      - name: Run manage.py makemigrations --check --dry-run
        run: |
          src/manage.py makemigrations --check --dry-run
        env:
          DJANGO_SETTINGS_MODULE: open_inwoner.conf.dev
          SECRET_KEY: dummy
          DB_USER: postgres
          DB_PASSWORD: ''

  prettier:
    name: Check code formatting with prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Run Prettier
        run: |
          npm run check-linting

  ruff-check:
    name: Lint code with ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          grep ^ruff requirements/ci.txt | uv pip install --system -r /dev/stdin
      - name: Run ruff check on all files
        run: ruff check --output-format=github src

  ruff-format:
    name: Format code with ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          grep ^ruff requirements/ci.txt | uv pip install --system -r /dev/stdin
      - name: Run ruff format on all files
        run: ruff format --diff --target-version py311 src
