name: Resolve dependencies

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '**'
    paths:
      - 'bin/*'
      - 'requirements/*'
  pull_request:
    paths:
      - 'bin/*'
      - 'requirements/*'
  workflow_dispatch:

permissions: {}

jobs:
  compile_dependencies_linux:
    name: Run compile_dependencies on Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: false

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Make sure current directory can be detected a git repository
        run: git init

      - name: Run bin/compile_dependencies.sh
        run: ./bin/compile_dependencies.sh

  compile_dependencies_macos:
    name: Run compile_dependencies on MacOS
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: 'pyproject.toml'

      - name: Install OS-level deps
        run: brew install postgresql

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: false

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Make sure current directory can be detected a git repository
        run: git init

      - name: Install OS-level deps
        run: brew install postgresql

      - name: Run bin/compile_dependencies.sh
        run: ./bin/compile_dependencies.sh
