name: Frontend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set up test environment
        run: |
          npx playwright install --with-deps firefox webkit chromium
          npm run compilemessages

      - name: Run tests
        run: npm run test:vitest

      - name: Type check and build
        run: |
          npm run type-check
          npm run build

  interaction-tests:
    name: Run Storybook tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set up test environment
        run: |
          npx playwright install --with-deps firefox webkit chromium
          npm run compilemessages

      - name: Run Storybook tests
        run: npm run test:storybook

  storybook:
    name: Create storybook build
    runs-on: ubuntu-latest
    needs: [unit-tests, interaction-tests]

    steps:
      - uses: actions/checkout@v6
      - name: Build Storybook docs
        run: |
          npm ci
          npm run build-storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./storybook-static

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Allow one concurrent deployment
    concurrency:
      group: 'pages-${{ github.ref_name }}' # unique builds for branch/tag name
      cancel-in-progress: true

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push' # Exclude PRs
    needs: storybook
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
